src/NzbDrone.Common/Http/HttpClient.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowser.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserService.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserSettings.cs
src/NzbDrone.Core/Notifications/Xbmc/XbmcJsonApiProxy.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Rest/RestSharpExtensions.cs

@kayone @Taloth 
Converted it from RestSharp to our own HttpClient and since MediaBrowser actually supports library updates now we can actually release it.

New: MediaBrowser notifications

---

src/NzbDrone.Core/Datastore/ConnectionStringFactory.cs

fixed: changed Journaling for osx to prevent db corruption

---

src/NzbDrone.Core.Test/Datastore/Migration/074_disable_eztv.cs
src/NzbDrone.Core.Test/IndexerTests/EztvTests/EztvFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Datastore/Migration/074_disable_eztv.cs
src/NzbDrone.Core/Indexers/Eztv/EztvSettings.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

@kayone @Taloth I think this is the last thing we need to do before we merge.... finally.

Disable EZTV

---

src/UI/Cells/EpisodeFilePathCell.js
src/UI/Content/icons.less
src/UI/EpisodeFile/Editor/EmptyView.js
src/UI/EpisodeFile/Editor/EmptyViewTemplate.hbs
src/UI/EpisodeFile/Editor/EpisodeFileEditorLayout.js
src/UI/EpisodeFile/Editor/EpisodeFileEditorLayoutTemplate.hbs
src/UI/EpisodeFile/Editor/QualitySelectView.js
src/UI/EpisodeFile/Editor/QualitySelectViewTemplate.hbs
src/UI/Series/Details/SeasonLayout.js
src/UI/Series/Details/SeasonLayoutTemplate.hbs
src/UI/Series/Details/SeriesDetailsLayout.js
src/UI/Series/Details/SeriesDetailsTemplate.hbs
src/UI/Series/series.less

@kayone @Taloth 
Not sure about the icon (we need to update to Font Awesome 4 to get some nicer ones):
https://www.dropbox.com/s/zrgousjbd6n7q8s/shot_150219_221448.png
Pretty simple editor:
https://www.dropbox.com/s/31sgxyi3xeywhra/shot_150219_221805.png?dl=0
Delete has a confirm, changing the quality does not since its reversible (without setting the recycling bin first).

Episode file editor

---

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs

Established indexer. Been around for 2+ years.

Added NZBFinder.ws as optional Indexer

---

src/NzbDrone.Api/DownloadClient/DownloadClientModule.cs
src/NzbDrone.Api/Indexers/IndexerModule.cs
src/NzbDrone.Api/Metadata/MetadataModule.cs
src/NzbDrone.Api/Notifications/NotificationModule.cs
src/NzbDrone.Api/ProviderModuleBase.cs
src/NzbDrone.Core/Download/Clients/Deluge/DelugeSettings.cs
src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs
src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs
src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdSettings.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionSettings.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Validation/LanguageValidator.cs
src/NzbDrone.Core/Validation/NzbDroneValidationFailure.cs
src/NzbDrone.Core/Validation/NzbDroneValidationResult.cs
src/NzbDrone.Core/Validation/NzbDroneValidationState.cs
src/NzbDrone.Core/Validation/NzbDroneValidator.cs
src/NzbDrone.Core/Validation/RuleBuilderExtensions.cs
src/UI/Content/form.less
src/UI/jQuery/jquery.validation.js

Atm only for sabnzbd/nzbget coz most others need plugins or workarounds to have categories.
Fire away.

Validation warnings for missing Category in sabnzbd/nzbget

---

src/UI/Settings/DownloadClient/Edit/DownloadClientEditViewTemplate.hbs
src/UI/Settings/Metadata/MetadataEditViewTemplate.hbs
src/UI/Settings/Notifications/Edit/NotificationEditViewTemplate.hbs
src/UI/Settings/Profile/Edit/EditProfileViewTemplate.hbs

New look: https://i.imgur.com/svnWK1i.png

UI: Separate setting groups & clarify tooltips

---

src/NzbDrone.Core/Datastore/Migration/082_add_fanzub_settings.cs
src/NzbDrone.Core/Indexers/Fanzub/Fanzub.cs
src/NzbDrone.Core/Indexers/Fanzub/FanzubRequestGenerator.cs
src/NzbDrone.Core/Indexers/Fanzub/FanzubSettings.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

Running a bit ahead to the possibility that ppl will use the fanzub sources to setup alternative sites. This allows em to configure the url for Sonarr.

Fanzub url can now be modified [migration 82]

---

src/NzbDrone.Core/Datastore/ConnectionStringFactory.cs

 Changed sqlite to use full fsync on osx

---

src/NzbDrone.Api/Calendar/CalendarFeedModule.cs
src/NzbDrone.Api/Calendar/CalendarModule.cs
src/NzbDrone.Core.Test/TvTests/EpisodeRepositoryTests/EpisodesBetweenDatesFixture.cs
src/NzbDrone.Core/IndexerSearch/EpisodeSearchService.cs
src/NzbDrone.Core/Tv/EpisodeRepository.cs
src/NzbDrone.Core/Tv/EpisodeService.cs
src/UI/Calendar/CalendarCollection.js
src/UI/Calendar/CalendarLayout.js
src/UI/Calendar/CalendarLayoutTemplate.hbs
src/UI/Calendar/CalendarView.js
src/UI/Calendar/UpcomingCollectionView.js
src/UI/Calendar/calendar.less
src/UI/Handlebars/Helpers/Episode.js
src/UI/Shared/Toolbar/ToolbarLayout.js
src/UI/Shared/Toolbar/ToolbarLayoutTemplate.hbs

@Taloth @kayone 
Option to show all (including unmonitored) or just monitored episodes on the calendar. I also moved the ical link to make it more obvious to people (since I had to add the toolbar).
https://www.dropbox.com/s/j2qqixu78fcn6tm/shot_150328_091100.png?dl=0

New: Option to show unmonitored episodes on calendar

---

src/NzbDrone.Core/Instrumentation/DatabaseTarget.cs
src/NzbDrone.Core/ProgressMessaging/ProgressMessageTarget.cs

DB locking due to Progress Messaging

---

src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs

Set permissions on Sonarr.app (OS X)

---

src/NzbDrone.Core/Notifications/PushBullet/PushBulletSettings.cs

Fixed a small typo in a tooltip for the Pushbullet notification settings.

Fixed: Pushbullet settings typo

---

src/NzbDrone.Api/Config/UiConfigResource.cs
src/NzbDrone.Core/Configuration/ConfigService.cs
src/NzbDrone.Core/Configuration/IConfigService.cs
src/UI/Calendar/calendar.less
src/UI/Content/mixins.less
src/UI/Settings/UI/UiViewTemplate.hbs
src/UI/Shared/UiSettingsController.js
src/UI/main.js

Really not happy with the way the setting is initialized and updated in the UI. So could use some advice there.
We prolly should look at some other color coded items as well.

Added Color-Impaired mode to UI settings

---

src/NzbDrone.Core/Tv/SeriesTitleNormalizer.cs

Fix for #242

---

src/LogentriesNLog/packages.config
src/NzbDrone.App.Test/NzbDrone.Host.Test.csproj
src/NzbDrone.Host/NzbDrone.Host.csproj
src/NzbDrone.Integration.Test/NzbDrone.Integration.Test.csproj
src/NzbDrone/NzbDrone.csproj
src/ServiceHelpers/ServiceInstall/ServiceInstall.csproj
src/ServiceHelpers/ServiceUninstall/ServiceUninstall.csproj

Compilation: Misc changes to support XBuild

---

src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs

Yes, that easy.
Basically, with this change, we don't terminate the process on linux (linux doesn't lock open files like windows does).
- Then we perform the update.
- Afterwards we kill sonarr.
- Give upstart/systemd/custom 5 seconds to restart it.
- If didn't get restarted we then do it ourselves.

Hand-off update logic to handle upstart/systemd restarts

---

src/NzbDrone.Api/Qualities/QualityDefinitionResource.cs
src/NzbDrone.Core.Test/Datastore/Migration/084_update_quality_minmax_sizeFixture.cs
src/NzbDrone.Core.Test/DecisionEngineTests/AcceptableSizeSpecificationFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Datastore/Converters/DoubleConverter.cs
src/NzbDrone.Core/Datastore/Migration/084_update_quality_minmax_size.cs
src/NzbDrone.Core/Datastore/TableMapping.cs
src/NzbDrone.Core/DecisionEngine/Specifications/AcceptableSizeSpecification.cs
src/NzbDrone.Core/Fluent.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Qualities/Quality.cs
src/NzbDrone.Core/Qualities/QualityDefinition.cs
src/UI/Settings/Quality/Definition/QualityDefinitionCollectionTemplate.hbs
src/UI/Settings/Quality/Definition/QualityDefinitionItemView.js

Tiny changes, lots of code to make it happen cleanly.

Unlimited MaxSize and increased granularity.

---

src/NzbDrone.Common/Http/HttpRequest.cs
src/NzbDrone.Common/Http/UriExtensions.cs
src/NzbDrone.Core.Test/Files/Indexers/Rarbg/RecentFeed.json
src/NzbDrone.Core.Test/IndexerTests/RarbgTests/RarbgFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Indexers/Rarbg/Rarbg.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgParser.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgRequestGenerator.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgSettings.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgTokenProvider.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgTorrent.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

Fixes #555
Not sure yet if we should default to RankedOnly=true or false.

Added support for Rarbg as replacement for Eztv.

---

src/NzbDrone.Update/UpdateApp.cs

Fix spelling mistake in UpdateApp.cs

---

src/NzbDrone.Core/Notifications/Plex/PlexAuthenticationException.cs
src/NzbDrone.Core/Notifications/Plex/PlexServerProxy.cs
src/NzbDrone.Core/Notifications/Plex/PlexServerService.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/UI/Settings/Indexers/Edit/IndexerEditViewTemplate.hbs
src/UI/Settings/Notifications/Edit/NotificationEditViewTemplate.hbs

Fixes:
- Plex.tv password not taking effect immediately
- An incorrect plex.tv password won't lock out plex.tv account
@Sonarr/team-sonarr

Plex Server Authentication Improvements

---

src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentDirectoryValidator.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentProxy.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

@Sonarr/team-sonarr 
Closes #626

Choose download folder for rTorrent

---

src/UI/Activity/Queue/QueueCollection.js
src/UI/Mixins/AsPageableCollection.js

@Sonarr/team-sonarr Not a fan of editing the this external library, but neither am I with copying over the entire method.
Closes #670

Alter backbone.pageable to stay on same page during fetch

---

src/NzbDrone.Core/Notifications/Boxcar/Boxcar.cs
src/NzbDrone.Core/Notifications/Boxcar/BoxcarException.cs
src/NzbDrone.Core/Notifications/Boxcar/BoxcarProxy.cs
src/NzbDrone.Core/Notifications/Boxcar/BoxcarSettings.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Rest/RestSharpExtensions.cs

Hi,
I added boxcar.io support, related to #322 
I have duplicated PushBullet because it was matching the boxcar API.
With somes changes to fit the boxcar API.
I also added a new response status code to RestSharpExtension.
Because boxcar API send back a 201 Created.
Thank you for your code review ;)

Added Boxcar 2

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Parser/Language.cs
src/NzbDrone.Core/Parser/Parser.cs

Based on discussion https://forums.sonarr.tv/t/custom-quality-definition-for-filtering-possible/6552/4
Please note, I'm not a programmer and haven't tested the changes. Just did a search on Dutch and tried to add similar behaviour.

Add Hungarian Language

---

src/NzbDrone.Common.Test/ExtensionTests/Int64ExtensionFixture.cs
src/NzbDrone.Common/Extensions/Int64Extensions.cs
src/UI/Activity/Queue/TimeleftCell.js
src/UI/Settings/Quality/Definition/QualityDefinitionItemView.js
src/UI/Shared/FormatHelpers.js

as per this issue https://github.com/Sonarr/Sonarr/issues/709

change to using 1024 over 1000

---

src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentProxy.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs

Fixes https://forums.sonarr.tv/t/rtorrent-adding-new-download-sometimes-fails and #762. Also exposes the Url Base field in basic configuration mode, as it is often modified.

rTorrent fixes

---

src/UI/JsLibraries/jquery.js

Just a simple version bump to jQuery. Fixes an IOS bug in 8.2 and 8.3

UI: Update jQuery to 1.11.3

---

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs

Should be pretty straightforward, If I missed anything, please let me know.

Adding new newznab preset for NZBCat

---

src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
src/NzbDrone.Core.Test/ParserTests/ExtendedQualityParserRegex.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs
src/NzbDrone.Core/Parser/QualityParser.cs

Made it case sensitive to `REAL` only.
Closes #453

Support for REAL releases

---

src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/ImportDecisionMakerFixture.cs
src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Parser/QualityParser.cs
src/NzbDrone.Core/Qualities/QualityModel.cs
src/NzbDrone.Core/Qualities/QualitySource.cs

@Taloth 
Pretty minor, but wanted your thoughts on it, @kayone and I discussed it earlier and this seemed like the least impacting, but a reliable way to handle this issue.
Closes #603

Folder quality when file quality determined by its extension

---

src/NzbDrone.Core/NzbDrone.Core.csproj

Enables usage within MonoDevelop and Xamarin Studio including NUnit

Include mediainfo and sqlite3 libraries for Mac

---

src/UI/Handlebars/Helpers/Html.js

Provide 2x srcset for posters

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/TransmissionTests/TransmissionFixture.cs
src/NzbDrone.Core/Download/Clients/Transmission/Transmission.cs

Fixed: Paths with colons prevent Sonarr from communicating with Transmission

---

src/NzbDrone.Api/Calendar/CalendarFeedModule.cs

@kayone rather simple, but the parameter names could use some work, thoughts?
Closes #974

iCal parameters

---

src/NzbDrone.Common/Extensions/StringExtensions.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/NzbVortexTests/NzbVortexFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Download/Clients/NzbVortex/JsonConverters/NzbVortexLoginResultTypeConverter.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/JsonConverters/NzbVortexResultTypeConverter.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortex.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexAuthenticationException.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexFile.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexFiles.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexGroup.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexJsonError.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexLoginResultType.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexNotLoggedInException.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexPriority.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexProxy.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexQueue.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexQueueItem.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexResultType.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexSettings.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexStateType.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/Responses/NzbVortexAddResponse.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/Responses/NzbVortexApiVersionResponse.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/Responses/NzbVortexAuthNonceResponse.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/Responses/NzbVortexAuthResponse.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/Responses/NzbVortexGroupResponse.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/Responses/NzbVortexResponseBase.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/Responses/NzbVortexRetryResponse.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/Responses/NzbVortexVersionResponse.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

New: NZBVortex Download Client
Closes #360
@kayone @Taloth

NZBVortex Download Client

---

src/NzbDrone.Common.Test/Http/HttpUriFixture.cs
src/NzbDrone.Common.Test/NzbDrone.Common.Test.csproj
src/NzbDrone.Common/Http/HttpUri.cs

Cleanup HttpUri.PathCombine

---

src/NzbDrone.Core.Test/DecisionEngineTests/PrioritizeDownloadDecisionFixture.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionPriorizationService.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Parser/Model/TorrentInfo.cs

@Taloth @kayone 
Started on this a few months ago and finally got a chance to finish it off. One thing I'd like to do is move the scoring elsewhere so we can track the score on the decision and use it for ordering.

Release scoring

---

src/NzbDrone.Api/Indexers/ReleaseModule.cs
src/NzbDrone.Core.Test/DecisionEngineTests/RssSync/DelaySpecificationFixture.cs
src/NzbDrone.Core.Test/IndexerSearchTests/NzbSearchServiceFixture.cs
src/NzbDrone.Core.Test/IndexerSearchTests/SeriesSearchServiceFixture.cs
src/NzbDrone.Core/DecisionEngine/Specifications/RssSync/DelaySpecification.cs
src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs
src/NzbDrone.Core/IndexerSearch/EpisodeSearchService.cs
src/NzbDrone.Core/IndexerSearch/NzbSearchService.cs
src/NzbDrone.Core/IndexerSearch/SeasonSearchService.cs
src/NzbDrone.Core/IndexerSearch/SeriesSearchService.cs

Respect delays when searching after a failed DownloadRelease

---

src/NzbDrone.Core/Metadata/Consumers/Xbmc/XbmcMetadata.cs

XBMC NFO Stream Details

---

src/NzbDrone.Core/Download/Clients/qBittorrent/QBittorrentProxy.cs

Fix #1347 for the new (3.3.5) version of qBittorent for which the api for setting torrent labels has changed from setLabel to setCategory. Get torrent label still has the same api call as before, so doesn't need updating.

Fix adding label to Sonarr initiated torrents in qBittorrent 3.3.5

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

I fully expect that these require improvements, but wanted to get a PR out there before I forget again.

GHI and PR Templates

---

src/NzbDrone.Core/Datastore/ConnectionStringFactory.cs
src/NzbDrone.Core/Datastore/CorruptDatabaseException.cs
src/NzbDrone.Core/Datastore/DbFactory.cs
src/NzbDrone.Core/Datastore/Migration/Framework/MigrationController.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

Fixes: #1050 
Pretty simplistic approach, happy to discuss alternatives.

Recreate log database if migration fails

---

src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoModel.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/UpdateMediaInfoService.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

NO - might need one
New file naming tokens `MediaInfo VideoBitDepth` (10 Bit) and `MediaInfo AudioChannels` (5.1).

MediaInfo VideoBitDepth and AudioChannels

---

schemas/torznab.xsd

NO
Using the attributes it's possible to signal states like freeleech/neutral leech/double upload
none

add downloadvolumefactor and uploadvolumefactor torznab attributes

---

src/NzbDrone.Common/NzbDrone.Common.csproj
src/NzbDrone.Common/packages.config

NO
To fix issue #1554 
* #1554

Upgrade SocksWebProxy dependancy to fix #1554

---

.gitignore

Added Visual Studio folder (.vs) to the ignore file.

---

src/NzbDrone.Common.Test/Http/HttpHeaderFixture.cs
src/NzbDrone.Common.Test/NzbDrone.Common.Test.csproj
src/NzbDrone.Common/Http/HttpHeader.cs

NO
Workaround for charset being wrap in quotes. 
Issue #1586

workaround for faulty server sending wrong charset

---

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs

Use DOGnzb name as the default rather than the URL

---

src/NzbDrone.Core/Notifications/Pushover/PushoverPriority.cs

NO
Fixes incorrect value for silent priority. 
https://github.com/Sonarr/Sonarr/issues/1619
*

Pushover Priority Value Update

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/DownloadStationFixture.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/DownloadStation.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DSMInfoProxy.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DiskStationProxyBase.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationProxy.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/FileStationProxy.cs

NO
Throws a DownloadClientException with the message return by the Diskstation when the request was unsuccessful
#1671

Throw exception with error message return by diskstation

---

gulp/less.js
package.json

NO
Use a better css compressor. We save 3KB overall. CleanCSS performs well -> https://goalsmashers.github.io/css-minification-benchmark/

use cleancss for minification

---

src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/TitleTheFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs
src/NzbDrone.Core/Organizer/FileNameSampleService.cs
src/UI/Settings/MediaManagement/Naming/Partials/SeriesTitleNamingPartial.hbs

* Adds 'Series Title, The' filename option
* Updates the FileNameBuilder.SeriesTitleRegex to include new format
* Adds tests for this new format
NO
* 371

Add 'Series Title, The' filename option

---

src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs
src/NzbDrone.Core/IndexerSearch/NzbSearchService.cs

Avoid duplicate Scene/QueryTitles from appearing in SearchCriteriaBase

---

src/NzbDrone.Core/Indexers/HDBits/HDBitsSettings.cs

According to LSL1337 on Radarr Discord there's a new codec option HEVC with ID=5

Add new codec HEVC with ID=5 for HDBits

---

.github/ISSUE_TEMPLATE.md
.github/SUPPORT.md

NO
More Structure in `ISSUE_TEMPLATE.md` and a basic `SUPPORT.md`.

Updated ISSUE_TEMPLATE.md and added SUPPORT.md

---

.gitignore

NO
Adds `.DS_Store` to the `.gitignore` file.

Ignore macOS DS_Store files

---

src/NzbDrone.Api/Config/IndexerConfigModule.cs
src/NzbDrone.Api/Config/IndexerConfigResource.cs
src/NzbDrone.Core.Test/DecisionEngineTests/MaximumSizeSpecificationFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Configuration/ConfigService.cs
src/NzbDrone.Core/Configuration/IConfigService.cs
src/NzbDrone.Core/DecisionEngine/Specifications/MaximumSizeSpecification.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/UI/Settings/Indexers/Options/IndexerOptionsViewTemplate.hbs

NO
WIP for issue #1996. Not tested yet.

Maximum size for a release

---

src/NzbDrone.Common/Instrumentation/GlobalExceptionHandlers.cs

Fixed typo in log file

---

frontend/src/Components/Link/ClipboardButton.js
frontend/src/Components/Table/Cells/RelativeDateCell.js

NO
Filename normalization
* Allows correct compilation on OS's that use case-specific filenames

case-sensitive OS fix

---

.github/ISSUE_TEMPLATE.md

Fixed a grammer mistake

---

src/NzbDrone.Core/Configuration/SeedConfigProvider.cs
src/NzbDrone.Core/Download/Clients/Deluge/DelugeProxy.cs

NO
Fixes for indexer seed ratio `pr/n2272_beschoenen`
I made a little wiki page: https://github.com/Sonarr/Sonarr/wiki/Indexer-Seed-Ratio

N2272 fixes

---

src/NzbDrone.Api/Extensions/Pipelines/GZipPipeline.cs
src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs

The bug is registered upstream, but this commit works around the problem by doing the gzip decompression separately from the http stack.
Ref #2296

Mono bug causing memory leakage when http connections use gzip

---

src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowser.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserService.cs

Update emby api call for library update
#2662

Fix emby library update

---

frontend/src/InteractiveImport/Interactive/InteractiveImportModalContent.js

NO
Fixed a typo in the v3 manual import UI. `Select Qualty` -> `Select Quality`
*

Fixed quality typo.

---

src/Sonarr.Api.V3/History/HistoryModule.cs

NO
Add Ability to V3 history API to search by downloadId

Add Ability to search by downloadId

---

src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/Specifications/MatchesFolderSpecificationFixture.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/MatchesFolderSpecification.cs

Fix for season numbers mismatch not rejecting

---

README.md

NO
Small fix for markdown hyperlink formatting in the README

Fix README hyperlink formatting

---

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs

NO
Removed PFMonkey from presets as the indexer closed in 2018. Added x265 category to NZB Finder as it will recategorize those into a new separate category soon.

Update indexer presets

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

NO
Improve Chinese language detection
N/A

New: Improve Chinese language detection

---

frontend/src/Activity/Queue/RemoveQueueItemModal.js

It is implied Sonarr will not look for any release of this episode again.
NO
Fixing a typo in gui 
NA

Fix typo in remove queue item modal

---

frontend/src/System/Events/LogsTable.js

NO
Simple fix for the string that displays when clearing the event list.

Fixed: Empty list message for System: Events

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

NO
Added support for qBittorent forcedDL state.
* https://github.com/Sonarr/Sonarr/issues/3604

Fixed: Handle qBit ForcedDL State

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/DifferentQualitySpecification.cs

Add missing "does" to DifferentQualitySpec message

---

frontend/src/Settings/Indexers/Indexers/Indexer.js

Fixed: "Profile" to "Indexer" on Clone Button

---

frontend/src/Settings/General/BackupSettings.js

NO
Corrects a typo in the help text. 
* Provides clarity of the feature.

Fixed: Typo/unclear text in backup retention

---

src/NzbDrone.Core/Notifications/Telegram/TelegramService.cs
src/NzbDrone.Core/Notifications/Telegram/TelegramSettings.cs

NO
Added telegram setting option to enable the silent notification feature of telegram api. 
This was possible by adding the field "disable_notification=boolean" to the message method.
https://core.telegram.org/bots/api#sendmessage
https://github.com/Sonarr/Sonarr/issues/3867

New: Added silent notification option to telegram

---

frontend/src/Series/Editor/Organize/OrganizeSeriesModalContent.js

Fixed: Preview rename tip wording

---

frontend/src/Settings/MediaManagement/MediaManagement.js

NO
Changing 'Ignore Deleted Episodes' --> 'Unmonitor Deleted Episodes' for consistency with the helptext and for consistency with radarr menu.

Change 'Ignore Deleted Episodes' to 'Unmonitor Deleted Episodes' for consistency

---

src/NzbDrone.Core/Tv/AddSeriesService.cs

Co-Authored-By: Qstick <376117+Qstick(at)users.noreply.github.com>
NO
Title.
Fixes #4100

Fixed: List Import no longer fails due to duplicates

---

frontend/src/Series/Details/SeriesDetails.js
frontend/src/Series/MonitoringOptions/MonitoringOptionModalConnector.js
frontend/src/Series/MonitoringOptions/MonitoringOptionsModal.js
frontend/src/Series/MonitoringOptions/MonitoringOptionsModalContent.js
frontend/src/Series/MonitoringOptions/MonitoringOptionsModalContentConnector.js
frontend/src/Store/Actions/seriesActions.js

NO
Added Series monitoring toggle to Series detail similar to Season pass page and when adding a new season 
* #3991 
Update button is currently below the dropdown box in the footer, I cannot seem to see why though - picture below for reference. 
I would appreciate feedback on this if anything needs changing etc.

New: Added Series Monitoring Toggle to Series Details

---

frontend/src/AddSeries/AddNewSeries/AddNewSeries.js
frontend/src/Components/FileBrowser/FileBrowserModalContent.js
frontend/src/Settings/General/UpdateSettings.js
frontend/src/Settings/Indexers/Options/IndexerOptions.js
frontend/src/System/Status/MoreInfo/MoreInfo.js
frontend/src/login.html
src/NzbDrone.Api/ProviderModuleBase.cs
src/NzbDrone.Core.Test/HealthCheck/HealthCheckFixture.cs
src/NzbDrone.Core/Datastore/DbFactory.cs
src/NzbDrone.Core/HealthCheck/HealthCheck.cs
src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/Twitter/TwitterSettings.cs
src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
src/Sonarr.Api.V3/ProviderResource.cs

NO
Title.
-- [ ] Fix: src\NzbDrone.Core.Test\HealthCheck\HealthCheckFixture.cs

All Wiki links now use the consolidated Servarr wiki

---

src/NzbDrone.Core.Test/Datastore/Migration/148_mediainfo_channel_propertiesFixture.cs
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatAudioChannelsFixture.cs
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/VideoFileInfoReaderFixture.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
src/NzbDrone.Core/Datastore/Migration/148_mediainfo_channels.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoModel.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
src/NzbDrone.Core/Organizer/FileNameSampleService.cs

YES
This pulls Radarr changes: 
https://github.com/Radarr/Radarr/pull/5352 and https://github.com/Radarr/Radarr/issues/5404
*

Pull Radarr MediaInfo Updates/Fixes

---

frontend/src/AddSeries/ImportSeries/SelectFolder/ImportSeriesSelectFolder.js
frontend/src/Components/Page/Sidebar/PageSidebar.js

New: Rename Import to Library Import

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

NO
Almost no-one names their files "polish".
None

Fixed: Parsing Polish language

---

src/NzbDrone.Core.Test/ParserTests/HashedReleaseFixture.cs
src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs
src/NzbDrone.Core/Parser/QualityParser.cs

NO
Additional handling for various parser issues; see linked GHI
- Wiki Updates -N/A
* Fixes #4198
* Fixes #4199

Fixed: Parser Improvements

---

src/NzbDrone.Core/HealthCheck/Checks/DotnetVersionCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/DownloadClientCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/DownloadClientStatusCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/ImportListStatusCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/ImportMechanismCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/IndexerLongTermStatusCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/IndexerStatusCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/MonoVersionCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/MountCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/RemovedSeriesCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/RootFolderCheck.cs

NO
Self-Descriptive
* Fixes #4190

Update wiki link hints for health checks

---

src/NzbDrone.Core.Test/ParserTests/HashedReleaseFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
IYKYK
- [] Wiki Updates-Still not needed 
* Fixes #4198

Fix yet another obfuscation

---

src/NzbDrone.Core/Download/Clients/Flood/Flood.cs
src/NzbDrone.Core/Download/Clients/Flood/FloodProxy.cs
src/NzbDrone.Core/Download/Clients/Flood/FloodSettings.cs
src/NzbDrone.Core/Download/Clients/Flood/Models/AdditionalTags.cs
src/NzbDrone.Core/Download/Clients/Flood/Types/Torrent.cs
src/NzbDrone.Core/Download/Clients/Flood/Types/TorrentContent.cs
src/NzbDrone.Core/Download/Clients/Flood/Types/TorrentListSummary.cs

NO
Add support for [Flood](https://flood.js.org), a modern Web UI for various torrent clients.

New: Flood Download Client

---

.github/workflows/lock.yml

(github actions may need to be setup to finish this off)
GH

Lock closed issues after 90 days without activity

---

frontend/src/Settings/Notifications/Notifications/EditNotificationModalContent.js
frontend/src/Settings/Notifications/Notifications/Notification.js
frontend/src/Store/Actions/Settings/notifications.js
src/NzbDrone.Core.Test/NotificationTests/NotificationBaseFixture.cs
src/NzbDrone.Core/Datastore/Migration/153_add_on_episodefiledelete_for_upgrade.cs
src/NzbDrone.Core/Datastore/TableMapping.cs
src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/INotification.cs
src/NzbDrone.Core/Notifications/NotificationBase.cs
src/NzbDrone.Core/Notifications/NotificationDefinition.cs
src/NzbDrone.Core/Notifications/NotificationFactory.cs
src/NzbDrone.Core/Notifications/NotificationService.cs
src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookEpisodeDeletePayload.cs
src/Sonarr.Api.V3/Notifications/NotificationResource.cs

YES 153
To add an option for notifications on episode file delete for upgrades

New: On Episode File Delete For Upgrade notification option

---

src/NzbDrone.Core.Test/ParserTests/HashedReleaseFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
The wack-a-mole continues.
-  Wiki Updates-N/A
* Closes #4198

Fixed: Handle more obfuscated names

---

src/NzbDrone.Core/HealthCheck/Checks/RemovedSeriesCheck.cs

Fixed: Series Removed From TVDB wiki link

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Update feature request template

---

CONTRIBUTING.md

Update contributing.md Github docs URL

---

src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularListType.cs
src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularRequestGenerator.cs

NO
Adds recommended trakt lists for week/month/year/all, similar to top watched.
Are all four wanted in this list?
* #4167

New: Add Recommended to the List types for Trakt

---

src/NzbDrone.Common/Http/HttpResponse.cs

NO
Fixes leftover from d6cf370bc

Cleanup trailing space in HttpResponse

---

src/NzbDrone.Core/HealthCheck/Checks/PackageGlobalMessageCheck.cs

NO
Double blank and extra whitespace from 7da02c2

Cleanup formatting in PackageGlobalMessageCheck.cs

---

.github/ISSUE_TEMPLATE/bug_report.md

update bug template

---

frontend/src/Settings/MediaManagement/Naming/NamingModal.js

NO
Lower Case -> Lowercase
Upper Case -> Uppercase
- Tests-N/A
*

Fixed: Debatable typos in Naming Modal

---

src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserRequestGenerator.cs
src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserSettings.cs

NO
Actually, Trakt Import List feature only allows personal list from authenticated user. This new option allow the user to set any user to import his lists.

New: Add option to import from any user's personal list

---

src/NzbDrone.Core/Notifications/Xbmc/HttpApiProvider.cs
src/NzbDrone.Core/Notifications/Xbmc/XbmcJsonApiProxy.cs
src/NzbDrone.Core/Notifications/Xbmc/XbmcSettings.cs

NO
Adds support for SSL when connecting with Kodi. SSL support was added to Kodi in v18 Leia (https://github.com/xbmc/xbmc/pull/13165)
*

New: Adds SSL option to Kodi connections

---

src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs

NO
self explanatory
- Tests - n/a
-  Wiki Updates - n/a
*

Update indexer category help text

---

src/NzbDrone.Core/Notifications/Mailgun/Mailgun.cs

NO
Adds On Episode Delete and On Series Delete notifications to the new MailGun notifications

Add missing On Delete Notifications to Mailgun notifications

---

src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs

New: Date format in log files

---

src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs

NO
Copy / Paste typo fix from https://github.com/Sonarr/Sonarr/commit/85f4cbe94c6f00352e0d4a38f337fb9417d3032b

Fixed: NZBGet Settings reference Sabnzbd

---

frontend/src/Components/HeartRating.css
frontend/src/Components/HeartRating.js
frontend/src/Series/Details/SeriesDetails.js

NO
Shows what years the show ran between, this is useful when some shows have remakes etc. as you can easily see the start and finish dates when looking at your shows. 
Show that has ended: 
Show that is continuing: 
Show that is upcoming:

New: Added Running Years into the shows details

---

.github/ISSUE_TEMPLATE/bug_report.md

Add wiki link for logs in bug report template

---

frontend/src/Activity/Queue/QueueRow.js
frontend/src/Store/Actions/queueActions.js

NO
Adds a `Size` column to the activity queue
* Fixes #4527

New: Add Size column to Activity: Queue

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Languages/Language.cs
src/NzbDrone.Core/Parser/IsoLanguages.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

NO
This should catch the most common title names with Bulgarian audio
None

New: Bulgarian Language

---

src/NzbDrone.Core/Notifications/Join/JoinProxy.cs

NO
Fix logo links to use develop branch in case we ever clean up branches. Also fix Radarr reference, as much as I want to leave it ;)

Fix Phantom branch reference in Join proxy

---

src/NzbDrone.Core/Download/Clients/Aria2/Aria2.cs

NO
Cleanup numerous issues with Aria2 class formatting

Aria2 formatting cleanup

---

frontend/src/Settings/DownloadClients/DownloadClients/AddDownloadClientModalContent.js

NO
Changes as discussed in #4545 
* Fixes #4545

Fixed: Help message when adding download clients

---

src/NzbDrone.Core.Test/ParserTests/AbsoluteEpisodeNumberParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

https://github.com/Sonarr/Sonarr/issues/4330#issuecomment-848258429
NO
Fixes Erai-Raws Batches Detection. More info here https://github.com/Sonarr/Sonarr/issues/4330#issuecomment-848258429
https://github.com/Sonarr/Sonarr/issues/4330#issuecomment-848258429
*

Fixes Erai-Raws Batches Detection

---

src/NzbDrone.Core/Notifications/Prowl/Prowl.cs
src/NzbDrone.Core/Notifications/Prowl/ProwlProxy.cs

NO
Updates Prowl to more similarly mirror the implementation of other notifications. This should also fix the priority issue - I don't have Prowl to test to be sure though.
* Fixes: #4719

Fixed: Prowl notifications priority

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

NO
* adds more tests
* reworks logic that was causing downstream tests to fail

Add missing remux quality parsing tests

---

src/NzbDrone.Core/Notifications/Boxcar/BoxcarProxy.cs
src/NzbDrone.Core/Notifications/Discord/Discord.cs

Fixed: Images for Connections using old branch name

---

src/NzbDrone.Core/Notifications/DownloadMessage.cs
src/NzbDrone.Core/Notifications/NotificationRepository.cs
src/NzbDrone.Core/Notifications/Trakt/Resource/TraktAuthRefreshResource.cs
src/NzbDrone.Core/Notifications/Trakt/Resource/TraktCollectShowResource.cs
src/NzbDrone.Core/Notifications/Trakt/Resource/TraktCollectShowsResource.cs
src/NzbDrone.Core/Notifications/Trakt/Resource/TraktEpisodeResource.cs
src/NzbDrone.Core/Notifications/Trakt/Resource/TraktListResource.cs
src/NzbDrone.Core/Notifications/Trakt/Resource/TraktSeasonResource.cs
src/NzbDrone.Core/Notifications/Trakt/Resource/TraktShowIdsResource.cs
src/NzbDrone.Core/Notifications/Trakt/Resource/TraktShowResource.cs
src/NzbDrone.Core/Notifications/Trakt/Resource/TraktUserIdsResource.cs
src/NzbDrone.Core/Notifications/Trakt/Resource/TraktUserResource.cs
src/NzbDrone.Core/Notifications/Trakt/Resource/TraktUserSettingsResource.cs
src/NzbDrone.Core/Notifications/Trakt/Trakt.cs
src/NzbDrone.Core/Notifications/Trakt/TraktException.cs
src/NzbDrone.Core/Notifications/Trakt/TraktInterlacedTypes.cs
src/NzbDrone.Core/Notifications/Trakt/TraktProxy.cs
src/NzbDrone.Core/Notifications/Trakt/TraktService.cs
src/NzbDrone.Core/Notifications/Trakt/TraktSettings.cs

This is the port of a similar feature recently added to Radarr.
https://github.com/geogolem/Radarr/commit/00f631c623e08699ed1c8dbb7e5566a1ab5c4152
NO
Update Trakt Collection when item is added to Sonarr library
https://github.com/Sonarr/Sonarr/issues/3906
*

New: Trakt Connection

---

frontend/src/Store/Actions/queueActions.js

Fixes #4783
NO
title
- Tests
*

New: Display Unknown Items in Activity Queue by default

---

src/NzbDrone.Core/DataAugmentation/Xem/XemProxy.cs

NO
Thexem.info throws insecure connection warnings when using http schema
*

New: Use https for thexem.info

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

NO
title
* discord https://discord.com/channels/383686866005917708/383688189941907459/917825662075686932

Fixed: Improve WEBDL detection of Netflix Rips

---

src/NzbDrone.Core/HealthCheck/Checks/MonoVersionCheck.cs

Fixed: Bad wiki fragment for mono health check

---

build.sh

Use mono for MachOConverter in build.sh

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixed: Cleanse Notifiarr secret from URL in logs

---

frontend/src/Settings/MediaManagement/Naming/NamingModal.js

NO
Title
- Tests
* [comment](https://github.com/Sonarr/Sonarr/commit/7b694ea71d7f78bad5c03393c4cf6f7a28ada1cb#commitcomment-62519414)

Fixed: Add missing MediaInfo VideoDynamicRangeType token to help modal

---

src/NzbDrone.Core/Indexers/HttpIndexerBase.cs

NO
Title
QOL / Less confusion for users and improve the accuracy
- Tests
- Wiki Updates
*

Fixed: Improved Indexer test failure message when no results are returned

---

frontend/src/Settings/Profiles/Release/EditReleaseProfileModalContent.js

Fixed: Help text for Release Profile tags

---

frontend/src/System/Status/Health/Health.js
src/NzbDrone.Core.Test/HealthCheck/Checks/IndexerJackettAllCheckFixture.cs
src/NzbDrone.Core.Test/IndexerTests/TorznabTests/TorznabFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/IndexerJackettAllCheck.cs
src/NzbDrone.Core/Indexers/Torznab/Torznab.cs

NO
Jackett all is bad - ~~stopping~~ warning adding/editing indexers that have this and calls a health check for those that have the all endpoint configured! 
(cherry picked from commit 54c914d48fefa730728518d50fc9e49032d0947b)
* Closes #4437

New: End Jackett 'all' endpoint support

---

frontend/src/Settings/General/HostSettings.js

Fixed: IPv4 instead of IP4

---

frontend/src/System/Backup/BackupRow.js
frontend/src/System/Backup/Backups.js
src/NzbDrone.Core/Backup/Backup.cs
src/NzbDrone.Core/Backup/BackupService.cs
src/Sonarr.Api.V3/System/Backup/BackupModule.cs
src/Sonarr.Api.V3/System/Backup/BackupResource.cs

NO
Added backup size information the the frontend
* #4830

New: Add backup size information

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Adds a few more groups that do not follow the conventional -Group format
/
/

New: Add more groups that do not follow -Group format

---

frontend/src/Settings/General/SecuritySettings.js

Grammar - Literally added "v"
YES | NO
No
Added clarification + exceptionally helpful for Syno users due to SynoCommunity's...excellent maintaining of Mono. /s

New: Update Cert Validation Help Text

---

src/NzbDrone.Core/Download/Clients/DownloadStation/Responses/DiskStationError.cs

NO
Synology updated some docs after releasing DSM 7.0, so i'm updating the error to reflect that.
- [Login](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Os/DSM/All/enu/DSM_Login_Web_API_Guide_enu.pdf)
- [FileStation](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/FileStation/All/enu/Synology_File_Station_API_Guide.pdf)
*

Update Synology error codes

---

frontend/src/System/Status/MoreInfo/MoreInfo.js

NO
Change twitter url from sonarr website to sonarr twitter
*

Fixed: Twitter link

---

src/NzbDrone.Core.Test/Files/Indexers/Nyaa/Nyaa2021.xml
src/NzbDrone.Core.Test/IndexerTests/NyaaTests/NyaaFixture.cs
src/NzbDrone.Core/Indexers/EzrssTorrentRssParser.cs
src/NzbDrone.Core/Indexers/Nyaa/Nyaa.cs
src/NzbDrone.Core/Indexers/TorrentRssParser.cs

NO
- Added Nyaa's XML example to reflect their current, updated format
- Updated Nyaa parsing test
- Added to IndexerRSS
-  bool CalculatePeersAsSum
- InfoHashElementName
- PeersElementName
- SeedsElementName
- MagnetElementName
- N/A Wiki Updates
* Fixes #4614
https://nyaa.si/xmlns/nyaa

Fixed: Support for new Nyaa RSS Feed format

---

src/Sonarr.Http/ClientSchema/SchemaBuilder.cs

… Provider.Settings fields
(cherry picked from commit b2195148a2d6a08f9c779487223097c0715cfa0b)
NO
- Fixes v3.0.7 main breaking Prowlarr for some users
- Fixes nullref errors
- Tests
- Wiki Updates
* Relating to #4968

Fixed: API error when sending payload without optional parameters

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

NO
title
- Tests
- Wiki Updates
*

Fixed: Clarify Qbit Content Path Error

---

frontend/src/Components/Filter/Builder/DateFilterBuilderRowValue.js

Added the type "date" whenever the TextInput is a date, this will not
allow the user to input a incorrect date/format
NO
Added a datepicker so users can select a date from the picker instead of free typing it. This should provide better validation and  avoid users from inputing incorrect formats
- [ X] Tests
#4972 
*

feature request: #4972 Add date picker for custom filter window

---

src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs

(cherry picked from commit 3fcc39596438beaf5e38de3fde4a83397940f80e)
NO
* Fixes #4788

Fixed: Escape Characters as needed for *znab queries

---

frontend/src/Settings/Indexers/Indexers/AddIndexerModalContent.js

NO
There was a typo in the "Add Indexer" modal of the Web UI.

Fixed: Typo in AddIndexerModalContent.js

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

Fixed: Improved parsing WebDL Releases

---

src/NzbDrone.Core/ImportLists/Sonarr/SonarrImport.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrSettings.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrV3Proxy.cs

NO
Sync with Language Profile filters for Sonarr import list type
* Fixes #4892

New: Sonarr Sync on Language Profile

---

frontend/src/App/AppRoutes.js
frontend/src/Commands/commandNames.js
frontend/src/Components/SignalRConnector.js
frontend/src/Settings/Quality/Quality.js
frontend/src/Settings/Quality/QualityConnector.js
frontend/src/Settings/Quality/Reset/ResetQualityDefinitionsModal.js
frontend/src/Settings/Quality/Reset/ResetQualityDefinitionsModalContent.css
frontend/src/Settings/Quality/Reset/ResetQualityDefinitionsModalContent.js
frontend/src/Settings/Quality/Reset/ResetQualityDefinitionsModalContentConnector.js
src/NzbDrone.Core/Qualities/Commands/ResetQualityDefinitionsCommand.cs
src/NzbDrone.Core/Qualities/QualityDefinitionRepository.cs
src/NzbDrone.Core/Qualities/QualityDefinitionService.cs
src/Sonarr.Api.V3/Qualities/QualityDefinitionModule.cs

NO
Adds button to reset quality definitions (including option to reset names)
* Fixes #3390

New: Reset Quality Definitions to default

---

frontend/src/Store/Actions/releaseActions.js

NO
Releases size filter doesn’t take size input
*

Fixed: Releases Size filter has incorrect value type

---

src/NzbDrone.Common/Disk/DiskProviderBase.cs
src/NzbDrone.Common/Disk/FileAlreadyExistsException.cs
src/NzbDrone.Core/MediaFiles/RenameEpisodeFileService.cs

NO
This is a simpler mitigation for [this issue](https://github.com/Sonarr/Sonarr/pull/4160).

Fixed: Improve moving file to location where another one exists

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

NO
backport of various Radarr webdl/webrip parsing updates and sync the logic
- Wiki Updates
*

Fixed: Improve WebDL and WebRip Parsing

---

src/NzbDrone.Core/Parser/QualityParser.cs

NO
Fixes CF resolution specification to match correctly.

Fixed: CF Resolution Specification not matching correctly

---

frontend/src/Activity/Queue/RemoveQueueItemsModal.js

NO
referred to blocking an episode, when in fact it blocks a release
*

Update blocklist help text

---

src/NzbDrone.Core/Notifications/Ntfy/Ntfy.cs
src/NzbDrone.Core/Notifications/Ntfy/NtfyException.cs
src/NzbDrone.Core/Notifications/Ntfy/NtfyPriority.cs
src/NzbDrone.Core/Notifications/Ntfy/NtfyProxy.cs
src/NzbDrone.Core/Notifications/Ntfy/NtfySettings.cs

* Added: Ntfy provider for notifications.
* Changed: Clean up of validation and fields for ntfy
* Fixed: Unused title setting, and spelling issue.
(cherry picked from commit dca00db)
NO
This adds ntfy.sh as a notification provider.
It allows public server or private instance.
Cherry-picked via Radarr.
- [ X ] Tests

Added: Ntfy provider for notifications

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Languages/Language.cs
src/NzbDrone.Core/Parser/IsoLanguages.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

NO
Following my similar PR in Radarr which was merged recently, I decided to add Slovak language to Sonarr as well.

New: Add Slovak Language

---

src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularSettings.cs
src/NzbDrone.Core/ImportLists/Trakt/TraktSettingsBase.cs

Cherry pick of https://github.com/Radarr/Radarr/commit/5d8775ac96d4b7de1b4381c463e71cf035a3f942
NO
backport from Radarr reference https://github.com/Radarr/Radarr/issues/7464
*

Fixed: Remove non-functional filters for Trakt Lists

---

src/NzbDrone.Core.Test/DecisionEngineTests/RepackSpecificationFixture.cs
src/NzbDrone.Core/DecisionEngine/Specifications/RepackSpecification.cs

NO
fixes repack spec not using config repack/proper preference
- Wiki Updates
*

Fixed: Repack Preference Ignored

---

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs

NO
See Commits. Adds additional info to custom scripts
- Tests
- Wiki Updates
* towards #5166 - does not do webhook; however, previous comments indicated adding additional fields to the webhook should be trivial

Notification updates

---

frontend/src/Styles/Themes/light.js

NO
FIX light theme Text var calendarTextDimAlternate
- N/A
N/A

Fix light theme variable

---

frontend/src/AddSeries/ImportSeries/Import/SelectSeries/ImportSeriesSelectSeries.css
frontend/src/Components/SignalRConnector.js
frontend/src/Series/Index/Overview/Options/SeriesIndexOverviewOptionsModalContent.js
frontend/src/Series/Index/Posters/Options/SeriesIndexPosterOptionsModalContent.js
src/NzbDrone.Common.Test/Http/HttpClientFixture.cs
src/NzbDrone.Common/EnvironmentInfo/AppFolderFactory.cs
src/NzbDrone.Common/Extensions/StringExtensions.cs
src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs
src/NzbDrone.Common/OAuth/OAuthTools.cs
src/NzbDrone.Common/ServiceProvider.cs
src/NzbDrone.Core/Datastore/ExpressionVisitor.cs
src/NzbDrone.Core/Datastore/Migration/052_add_columns_for_anime.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionProxy.cs
src/NzbDrone.Core/Extras/Metadata/ExistingMetadataImporter.cs
src/NzbDrone.Core/HealthCheck/Checks/DownloadClientRootFolderCheck.cs
src/NzbDrone.Core/ImportLists/ImportListSyncService.cs
src/NzbDrone.Core/Notifications/Mailgun/Mailgun.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserSettings.cs
src/NzbDrone.Core/Notifications/Twitter/TwitterService.cs
src/NzbDrone.Core/Parser/Parser.cs
src/NzbDrone.Host/UtilityModeRouter.cs
src/NzbDrone.Mono.Test/Sonarr.Mono.Test.csproj
src/NzbDrone.Mono/Sonarr.Mono.csproj

Found via `codespell -q 3`  
Related: https://github.com/Lidarr/Lidarr/pull/3055

Fix various typos

---

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookEpisode.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookPayload.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookSeries.cs

Signed-off-by: Devin Buhl <devin@buhl.casa>
NO
Changes for customscript:
- Add `ApplicationUrl`, `InstanceName`, `TitleSlug` and Episode `Overview` to env
Changes to webhook:
- Add `ApplicationUrl`, `InstanceName` and `TitleSlug` to global payload
- Add `Overview` and `SeriesId` to episode payload
* https://github.com/Sonarr/Sonarr/issues/5059

New: Send additional information with Webhook and Custom Scripts

---

src/NzbDrone.Core/Notifications/Simplepush/Simplepush.cs
src/NzbDrone.Core/Notifications/Simplepush/SimplepushProxy.cs
src/NzbDrone.Core/Notifications/Simplepush/SimplepushSettings.cs

NO
Adds support for Simplepush Notifications
* Fixes #5108

New: Add support for Simplepush notifications

---

build.sh
src/Directory.Build.props
src/NzbDrone.Mono.Test/Sonarr.Mono.Test.csproj
src/NzbDrone.Mono/Sonarr.Mono.csproj

New: FreeBSB Support

---

frontend/src/Settings/General/HostSettings.js
src/NzbDrone.Common.Test/ExtensionTests/StringExtensionTests/IsValidIPAddressFixture.cs
src/NzbDrone.Common.Test/Http/HttpUriFixture.cs
src/NzbDrone.Common/Extensions/StringExtensions.cs
src/NzbDrone.Common/Http/HttpUri.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserSettings.cs
src/NzbDrone.Core/Notifications/Plex/Server/PlexServerProxy.cs
src/NzbDrone.Core/Notifications/Xbmc/XbmcSettings.cs
src/NzbDrone.Core/Validation/IpValidation.cs
src/NzbDrone.Core/Validation/RuleBuilderExtensions.cs
src/Sonarr.Api.V3/Config/HostConfigController.cs

YES | NO
Fixes BindAddress validation to support IPv6 and localhost (to match Kestrel) and adds IPv6 support for connections./download clients/indexers.
* Closes #622
* Closes #4149

IPv6 Improvements

---

src/NzbDrone.Common/Extensions/IpAddressExtensions.cs
src/Sonarr.Http/Extensions/RequestExtensions.cs

NO
Make IPAddress.IsLocal more robust. Cleanup handling for x-forwarded headers

Local IP handling improvements

---

frontend/src/Settings/Quality/Definition/QualityDefinition.css
frontend/src/Settings/Quality/Definition/QualityDefinition.js
frontend/src/Settings/Quality/Definition/QualityDefinitionConnector.js
src/NzbDrone.Core.Test/DecisionEngineTests/PrioritizeDownloadDecisionFixture.cs
src/NzbDrone.Core/Datastore/Migration/181_quality_definition_preferred_size.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionPriorizationService.cs
src/NzbDrone.Core/Qualities/Quality.cs
src/NzbDrone.Core/Qualities/QualityDefinition.cs
src/Sonarr.Api.V3/Qualities/QualityDefinitionResource.cs

YES - 181
Mostly a cherry pick from Radarr's commit
* Closes #724

New: Quality Preferred Setting

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/FreeboxDownloadTests/TorrentFreeboxDownloadFixture.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/FreeboxDownloadEncoding.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/FreeboxDownloadException.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/FreeboxDownloadPriority.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/FreeboxDownloadProxy.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/FreeboxDownloadSettings.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/Responses/FreeboxDownloadConfiguration.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/Responses/FreeboxDownloadTask.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/Responses/FreeboxLogin.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/Responses/FreeboxResponse.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/TorrentFreeboxDownload.cs

NO
Adds a new Download Client to support Freebox Download app.
Closes https://github.com/Sonarr/Sonarr/issues/5140

New: Add support for native Freebox Download Client

---

src/NzbDrone.Core/ImportLists/FetchAndParseImportListService.cs

NO
Don't check minimum when single list is fetched (provider updates and tests)

Fixed: Don't enforce minimum on single list fetch

---

src/NzbDrone.Core.Test/Languages/LanguageFixture.cs
src/NzbDrone.Core.Test/ParserTests/IsoLanguagesFixture.cs
src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Languages/Language.cs
src/NzbDrone.Core/Parser/IsoLanguages.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

NO
Adds Portuguese (Brazil) and Spanish (Latino) languages.
* Closes #5302

New: Portuguese (Brazil) and Spanish (Latino) languages

---

src/NzbDrone.Core/Parser/Parser.cs

small Fixup thanks to faxity on Discord

Fix comment

---

README.md

2023 readme fixes

---

src/NzbDrone.Core/ImportLists/FetchAndParseImportListService.cs
src/NzbDrone.Core/ImportLists/ImportListStatus.cs
src/NzbDrone.Core/ImportLists/ImportListStatusService.cs
src/NzbDrone.Core/ImportLists/ImportListType.cs
src/NzbDrone.Core/ImportLists/Simkl/SimklAPI.cs
src/NzbDrone.Core/ImportLists/Simkl/SimklImportBase.cs
src/NzbDrone.Core/ImportLists/Simkl/SimklParser.cs
src/NzbDrone.Core/ImportLists/Simkl/SimklSettingsBase.cs
src/NzbDrone.Core/ImportLists/Simkl/User/SimklUserImport.cs
src/NzbDrone.Core/ImportLists/Simkl/User/SimklUserListType.cs
src/NzbDrone.Core/ImportLists/Simkl/User/SimklUserRequestGenerator.cs
src/NzbDrone.Core/ImportLists/Simkl/User/SimklUserSettings.cs

NO
Adds support for Simkl User Watchlists (Watched/PlanToWatch/Hold/Completed/Dropped). OAuth app has been setup on https://auth.servarr.com similar to Trakt. 
* Fixes #5306

New: Simkl List Support

---

src/NzbDrone.Core/Download/CompletedDownloadService.cs

NO
Direct users to the troubleshooting docs for common user required interaction errors
Reduce the constant questions and posts of https://www.reddit.com/r/sonarr/comments/104zwpw/not_importing_random_episodes/
- Tests
- Wiki Updates
*

New: Improve messaging when imports are left in queue

---

frontend/src/Helpers/Props/filterBuilderTypes.js
frontend/src/Helpers/Props/filterTypePredicates.js
frontend/src/Helpers/Props/filterTypes.js

NO
Adds a few filter predicates for strings in custom filters in UI
- Starts With
- Does Not Start With
- Ends With
- Does Not End Wtih

New: Additional custom filter predicates for strings

---

src/NzbDrone.Core/ImportLists/Custom/CustomImportProxy.cs
src/NzbDrone.Core/ImportLists/HttpImportListBase.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrV3Proxy.cs
src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
src/NzbDrone.Core/Indexers/Newznab/Newznab.cs
src/NzbDrone.Core/Indexers/Torznab/Torznab.cs
src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrProxy.cs

NO
oops $
- Tests
- Wiki Updates
* Fixes #5461

Fixed: Regression in error message logging

---

frontend/src/Calendar/Agenda/AgendaEvent.css
frontend/src/Calendar/Agenda/AgendaEvent.css.d.ts

NO
correctly colours the items in Agenda view
* fixes #5477

Fixed: Color unaired items in agenda view

---

src/NzbDrone.Core.Test/HealthCheck/Checks/HealthCheckFixtureExtensions.cs
src/NzbDrone.Core.Test/HealthCheck/Checks/RemotePathMappingCheckFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/DownloadClientRootFolderCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/ImportListRootFolderCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/IndexerJackettAllCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/SystemTimeCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/UpdateCheck.cs

NO
- New: RemotePath HealthCheck
- misc healthcheck improvements to sync downstream with Radarr
- HealthCheckFixtureExtensions add wikiFragment check to ShouldBeError
*

New: Various HealthCheck Improvements

---

src/NzbDrone.Common/Sonarr.Common.csproj
src/NzbDrone.Core/MediaCover/ImageResizer.cs
src/NzbDrone.Core/Notifications/Email/Email.cs
src/NzbDrone.Core/Sonarr.Core.csproj
src/NzbDrone.Host/Sonarr.Host.csproj
src/NzbDrone.Update/Sonarr.Update.csproj
src/Sonarr.sln.DotSettings

NO
This PR updates a few packages: SixLabors.ImageSharp, MailKit, DryIoc and adds team-shared setting file. See my comments below

Update SixLabors.ImageSharp, MailKit, DryIoc libraries

---

src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs
src/NzbDrone.Core/Download/Clients/Deluge/DelugeLabel.cs
src/NzbDrone.Core/Download/Clients/Deluge/DelugeProxy.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs

(cherry picked from commit 4f281669fcd460efa4191590de31da12c7e4271d)
NO
- [] Tests
- [] Wiki Updates
* Fixes #5522

Fixed: Download Client HealthChecks fixes & Pathing improvements

---

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
src/NzbDrone.Host/Startup.cs

Fixed: Ensure default config file on starting app

---

src/NzbDrone.Common/Http/HttpRequestBuilder.cs
src/NzbDrone.Common/Http/TooManyRequestsException.cs
src/NzbDrone.Core.Test/IndexerTests/RarbgTests/RarbgFixture.cs
src/NzbDrone.Core/Indexers/Exceptions/RequestLimitReachedException.cs
src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
src/NzbDrone.Core/Indexers/Rarbg/Rarbg.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgParser.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgRequestGenerator.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgResponse.cs

NO
Updates Rarbg to handle additional rate limit cases.
* Closes #5206

New: Updated Rarbg request limits

---

src/NzbDrone.Common/Processes/ProcessProvider.cs

NO
Removes mono process detection. No longer applicable.

Remove mono process detection

---

src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookEpisodeDeletePayload.cs

NO
Return WebhookEpisodeFile for onEpisodeFileDelete events to match the type used in onDownload events.

Fixed: Return properly formatted episode file for deleted files Webhook

---

src/Sonarr.Http/Frontend/Mappers/StaticResourceMapperBase.cs

NO
Same fix as https://github.com/Prowlarr/Prowlarr/pull/1372

New: Serve log files as UTF-8

---

frontend/src/InteractiveSearch/InteractiveSearchRow.css

NO
enable hover color change on override download button
*

Fixed: Hover color on override download button

---

frontend/src/Components/Form/ProviderFieldFormGroup.js
src/NzbDrone.Core/Annotations/FieldDefinitionAttribute.cs
src/NzbDrone.Core/Notifications/Apprise/Apprise.cs
src/NzbDrone.Core/Notifications/Apprise/AppriseError.cs
src/NzbDrone.Core/Notifications/Apprise/AppriseException.cs
src/NzbDrone.Core/Notifications/Apprise/AppriseNotificationType.cs
src/NzbDrone.Core/Notifications/Apprise/ApprisePayload.cs
src/NzbDrone.Core/Notifications/Apprise/AppriseProxy.cs
src/NzbDrone.Core/Notifications/Apprise/AppriseSettings.cs
src/Sonarr.Http/ClientSchema/Field.cs
src/Sonarr.Http/ClientSchema/SchemaBuilder.cs

NO
[Apprise](https://github.com/caronc/apprise) is a self-hosted solution that supports a lot of [notifications providers](https://github.com/caronc/apprise#supported-notifications). It can be used as a [docker image from LS](https://github.com/linuxserver/docker-apprise-api#usage).

Add Apprise notifications

---

frontend/src/Calendar/Day/DayOfWeek.css
frontend/src/Styles/Themes/dark.js
frontend/src/Styles/Themes/light.js

Fix typo in calendarBackgroundColor CSS variable

---

gulpFile.js

NO
Looks like a leftover to me since gulp was no longer used and this requires another file that does not exist.

Remove unused gulpFile

---

package.json
yarn.lock

NO
Just updates to webpack and it's CLI, improves project build time by around 4 seconds.
```
OLD
webpack 5.72.1 compiled successfully in 22724 ms
Done in 30.78s.
NEW
webpack 5.81.0 compiled successfully in 17971 ms
Done in 26.28s.
webpack 5.81.0 compiled successfully in 17566 ms
Done in 25.76s.
```

Update webpack and webpack-cli

---

frontend/src/Settings/Profiles/Quality/EditQualityProfileModalContent.js

NO
There is a wrong spread operator that causes a syntax error when doing the rest operator in the called method.
* #5588

Fixed: Edit Quality Profile not opening

---

frontend/src/Components/DescriptionList/DescriptionListItem.js
frontend/src/Components/Link/IconButton.js
frontend/src/Components/Page/Header/PageHeader.js
frontend/src/Components/Page/Header/PageHeaderActionsMenu.js
frontend/src/Components/ProgressBar.js

NO
Fixes a few aria violations that I found when running lighthouse, the remaining one is in 3rd party code at https://github.com/moroshko/react-autosuggest/pull/830

Fixed some aria violations

---

src/NzbDrone.Core/MediaFiles/TorrentInfo/TorrentFileInfoReader.cs

NO
Useful for debugging download issues.

Log contents for invalid torrent files

---

src/NzbDrone.Core/Notifications/Ntfy/NtfyProxy.cs
src/NzbDrone.Core/Notifications/Ntfy/NtfySettings.cs

Add token authentication for ntfy.sh notifications

---

src/NzbDrone.Common/Processes/ProcessProvider.cs

NO
Fixing NullReferenceException in CustomScript, where for example Release is null in OnDownload for manual imports.
* Fixes #5617

Fix NullReferenceException for nullable environment variables

---

src/NzbDrone.Core/Indexers/EzrssTorrentRssParser.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabRssParser.cs
src/NzbDrone.Core/Indexers/Torznab/TorznabRssParser.cs

Check response status code in classes that extend RssParser

---

frontend/src/App/AppUpdatedModalContent.js
frontend/src/System/Updates/Updates.js

NO
title
- Tests
- Wiki Updates
*

New: Improved Maintenance Release Wording

---

src/NzbDrone.Core/ImportLists/Rss/Plex/PlexRssImport.cs
src/NzbDrone.Core/ImportLists/Rss/Plex/PlexRssImportParser.cs
src/NzbDrone.Core/ImportLists/Rss/Plex/PlexRssImportSettings.cs
src/NzbDrone.Core/ImportLists/Rss/RssImportBase.cs
src/NzbDrone.Core/ImportLists/Rss/RssImportBaseParser.cs
src/NzbDrone.Core/ImportLists/Rss/RssImportBaseSettings.cs

NO
Minor cleanup mostly to make it a little clear downstream. Mostly switching from nested ifs to a single one, and checking for the category before initializing the object.

Minor cleanup in RssImport

---

src/NzbDrone.Common.Test/Http/HttpClientFixture.cs
src/NzbDrone.Common/Http/HttpClient.cs
src/NzbDrone.Core.Test/Framework/CoreTest.cs

Remove unused field userAgentBuilder in HttpClient

---

.github/labeler.yml
.github/workflows/labeler.yml

NO
Use [actions/labeler](https://github.com/actions/labeler) for adding labels automatically based on paths.

Add Pull Request Labeler

---

.github/workflows/api_docs.yml
docs.sh
src/Sonarr.Api.V3/Episodes/EpisodeController.cs
src/Sonarr.Api.V3/Series/SeriesController.cs

NO
Going from https://github.com/Sonarr/Sonarr/pull/5600#issuecomment-1529155922, switched some params to native ASP.NET style to fix validation and to show up in swagger. 
I didn't use nullable bool since it skips the validation.
Before:
After:

Fix validation for boolean query parameters

---

frontend/src/Components/TagList.js
frontend/src/Series/Details/SeriesTagsConnector.js

(cherry picked from commit bb1ebda753157a96154095e0c1e32703f2a68d1a)
NO
Sort tags alphabetically and use the native `find` function.

Sort tags by label

---

src/NzbDrone.Core/Blocklisting/BlocklistService.cs

Fix checking for SameTorrent when the indexer is null

---

src/NzbDrone.Core/Notifications/Plex/Server/PlexServerService.cs
src/NzbDrone.Core/Notifications/Plex/Server/PlexServerSettings.cs

(cherry picked from commit 24206ad0a3095c4bf5c860af516d8543bd6525d6)
NO
Nice addition for partial scan when paths don't match.

 New: Add path mapping for partial library updates in Plex Server Notifications

---

frontend/src/Settings/AdvancedSettingsButton.js
frontend/src/Settings/Indexers/Indexers/EditIndexerModalContent.js
frontend/src/Settings/Indexers/Indexers/EditIndexerModalContentConnector.js
src/NzbDrone.Core/Localization/Core/en.json

(cherry picked from commit a570fd2a8f138fb89c5b0ae43ddb7919f6bf26e3)
NO

New: Advanced settings toggle in indexer edit/add modal

---

frontend/src/Settings/Notifications/Notifications/Notification.js
frontend/src/Settings/Notifications/Notifications/Notifications.js
frontend/src/Settings/Notifications/Notifications/NotificationsConnector.js

New: Show tags in Notifications index

---

src/NzbDrone.Core/Download/Aggregation/Aggregators/AggregateLanguages.cs
src/NzbDrone.Core/Indexers/IndexerBase.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabRssParser.cs
src/NzbDrone.Core/Indexers/Torznab/TorznabRssParser.cs

NO
Cleanup and fixing typos from 9c5a07f62a6e32832c10c80813cd3b98c5859989

Cleanup "Use languages from Torznab/Newznab attributes if given"

---

src/NzbDrone.Core/Notifications/Signal/InvalidResponseException.cs
src/NzbDrone.Core/Notifications/Signal/Signal.cs
src/NzbDrone.Core/Notifications/Signal/SignalError.cs
src/NzbDrone.Core/Notifications/Signal/SignalPayload.cs
src/NzbDrone.Core/Notifications/Signal/SignalProxy.cs
src/NzbDrone.Core/Notifications/Signal/SignalSettings.cs

As i did in radarr, here is a PR to support notifications via signal rest API.
Everything is mentionned in https://github.com/Radarr/Radarr/pull/8371

Initial Signal integration in sonarr

---

frontend/src/Components/Loading/LoadingMessage.js

just some trapped hamster's typos

Fixed: those stupid lines

---

src/NzbDrone.Core/Notifications/NotificationService.cs

NO
title
- [] Tests
- [] Wiki Updates
*

Fixed: Improve Webhook Notification Error Messaging

---

frontend/src/Components/Form/NumberInput.js
frontend/src/Settings/DownloadClients/DownloadClients/Manage/Edit/ManageDownloadClientsEditModalContent.tsx
frontend/src/Settings/DownloadClients/DownloadClients/Manage/ManageDownloadClientsModalRow.tsx
frontend/src/Settings/ImportLists/ImportLists/Manage/ManageImportListsModalRow.tsx
frontend/src/Settings/Indexers/Indexers/Manage/Edit/ManageIndexersEditModalContent.tsx
frontend/src/Settings/Indexers/Indexers/Manage/ManageIndexersModalRow.tsx
frontend/src/Store/Actions/Settings/downloadClients.js
frontend/src/Store/Actions/Settings/importLists.js
frontend/src/Store/Actions/Settings/indexers.js

NO
Avoid Manage Edit modal from crashing on click in and out of priority number input

Fix priority input for provider manage edit modal

---

src/NzbDrone.Common/Http/HttpResponse.cs
src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
src/NzbDrone.Core/Indexers/RssParser.cs

NO
- New: Improve Indexer Error Handling and Messaging
- Fixed: (Newznab Torznab) Better HTTP Error Handling
Catch the following expected HTTP responses and pass messaging indicating the indexer is down and try again later as bool IsServerNotAvailable for HTTP Response
HTTP 500 +
* Closes #5658
* Ref https://github.com/Prowlarr/Prowlarr/pull/1672

Indexer Messaging and Error Improvements

---

frontend/src/Components/Filter/Builder/SeriesStatusFilterBuilderRowValue.js

NO
Added `Deleted` to series status filter

Fixed: Filter series by Tvdb deleted status

---

frontend/src/System/Status/MoreInfo/MoreInfo.js

NO
Update MoreInfo.js with new discord link
*

Update MoreInfo.js with new discord link

---

frontend/src/Components/Form/ProviderFieldFormGroup.js
src/NzbDrone.Api.Test/ClientSchemaTests/SchemaBuilderFixture.cs
src/NzbDrone.Core/Annotations/FieldDefinitionAttribute.cs
src/Sonarr.Http/ClientSchema/Field.cs
src/Sonarr.Http/ClientSchema/SchemaBuilder.cs

NO
Sometimes it's useful to use `helpTextWarning` in the UI.

Add HelpTextWarning support in FieldDefinition

---

src/NzbDrone.Common/Http/HttpClient.cs

(cherry picked from commit ed7c5a937f4b50fcdf819e8fe347c8c0bc6bd2e7)
NO
Adhere to the 302/303 specifications.

Fixed: Correctly handle 302 and 303 redirects in HttpClient

---

src/NzbDrone.Core/ImportLists/Sonarr/SonarrImport.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrV3Proxy.cs

NO
Fix for silent errors with null results when redirects happen due to possible wrong URL base, making `GetSeries` successful in tests but not in real use.

Fixed: Treat redirects as errors in Sonarr Import List

---

frontend/src/Activity/Blocklist/Blocklist.js
frontend/src/Activity/History/History.js
frontend/src/Activity/Queue/Queue.js
frontend/src/AddSeries/ImportSeries/Import/ImportSeries.js
frontend/src/AddSeries/ImportSeries/SelectFolder/ImportSeriesSelectFolder.js
frontend/src/Calendar/Calendar.js
frontend/src/Components/Page/PageSectionContent.js
frontend/src/Episode/History/EpisodeHistory.js
frontend/src/InteractiveImport/Language/SelectLanguageModalContent.tsx
frontend/src/InteractiveImport/Quality/SelectQualityModalContent.tsx
frontend/src/InteractiveSearch/OverrideMatch/DownloadClient/SelectDownloadClientModalContent.tsx
frontend/src/RootFolder/RootFolders.js
frontend/src/Series/History/SeriesHistoryModalContent.js
frontend/src/Series/Index/SeriesIndex.tsx
frontend/src/Settings/DownloadClients/Options/DownloadClientOptions.js
frontend/src/Settings/General/GeneralSettings.js
frontend/src/Settings/Indexers/Options/IndexerOptions.js
frontend/src/Settings/MediaManagement/MediaManagement.js
frontend/src/Settings/MediaManagement/Naming/Naming.js
frontend/src/Settings/UI/UISettings.js
frontend/src/System/Backup/Backups.js

Show loading errors as Alerts

---

src/Sonarr.Api.V3/Queue/QueueController.cs

Fix sorting queue items by size

---

src/Sonarr.Api.V3/System/Backup/BackupController.cs

(cherry picked from commit 0ff0fe2e68f3abf7b8e4d6bf0c1e9dee4eb68227)
NO

Prevent NullRef when deleting missing backups

---

src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupAbsolutePathMetadataFiles.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupAdditionalNamingSpecs.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupAdditionalUsers.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupDownloadClientUnavailablePendingReleases.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupDuplicateMetadataFiles.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedBlocklist.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedDownloadClientStatus.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedEpisodeFiles.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedEpisodes.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedHistoryItems.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedImportListStatus.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedIndexerStatus.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedMetadataFiles.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedPendingReleases.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupUnusedTags.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/FixFutureRunScheduledTasks.cs

NO
Closing db connections in `Dispose()`.
[IDE0063](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0063) for second commit.

Close database connections in housekeeping tasks

---

frontend/src/Components/Page/Header/SeriesSearchInputConnector.js
frontend/src/Components/Page/Header/SeriesSearchResult.js
frontend/src/Components/Page/Header/fuse.worker.js

NO
This is more of a nice to have.

New: (UI) Search library by tvdbId, tvMazeId and imdbId

---

frontend/src/Settings/Tags/Tags.js
frontend/src/System/Events/LogsTable.js
frontend/src/System/Logs/Files/LogFiles.js
frontend/src/System/Updates/Updates.js
frontend/src/Wanted/CutoffUnmet/CutoffUnmet.js
frontend/src/Wanted/Missing/Missing.js

NO
- ~~Fix build by adding missing imports. `yarn build` doesn't complain about the missing imports for some reason.~~
- Add no items messages are info messages.

Show no items as Info Alerts

---

frontend/src/Components/Form/EnhancedSelectInput.js

Allow array of string as value in EnhancedSelectInput

---

src/NzbDrone.Core/Localization/Core/el.json

Translations update from [Servarr Weblate](https://translate.servarr.com) for [Servarr/Sonarr](https://translate.servarr.com/projects/servarr/sonarr/).
Current translation status:

Translations update from Servarr Weblate

---

frontend/src/Activity/Queue/QueueRow.css
frontend/src/Activity/Queue/QueueRow.css.d.ts
frontend/src/Activity/Queue/QueueRow.js
frontend/src/Store/Actions/queueActions.js
src/Sonarr.Api.V3/Queue/QueueResource.cs

NO
Add the ability to see the Custom Format Score as a column in the Activity Queue.
Closes #5780 
*

New: Add customFormatScore column to activity queue

---

src/NzbDrone.Core/MediaFiles/ScriptImportDecider.cs
src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs

NO
In the process of writing the script to actually use #5538 I found a few more environment variables that would be useful for that and also added those in the corresponding places in the custom scripts. Leaving this as a draft for now until I have finished said script and verified I didn't miss any others that might be useful.
---
---

New: More info for script import and custom script

---

src/NzbDrone.Core/Indexers/Nyaa/NyaaRequestGenerator.cs

NO
Seems like single episode search was missing.

Fixed: (Nyaa) Add single episode search for anime standard format

---

src/NzbDrone.Core/ImportLists/FetchAndParseImportListService.cs

NO
Import List Logging Improvements
- Tests
- Wiki Updates
*

New: Import List Logging Improvements

---

src/NzbDrone.Core/Notifications/Xbmc/XbmcService.cs

NO
clarify a bit
- Tests
- Wiki Updates
*

Fixed: Improve Kodi Library Update logging

---

src/Sonarr.Api.V3/Queue/QueueResource.cs

Fixed: (Queue) Prevent NullRef for format scoring when series isn't mapped

---

frontend/src/Parse/Parse.tsx
frontend/src/Parse/ParseModalContent.tsx
frontend/src/Store/Actions/parseActions.ts

NO
Fixes issues with item being reported as undefined here: https://github.com/Sonarr/Sonarr/blob/c9e3890f73296fd658536215c6e08030f873e170/frontend/src/Parse/ParseModalContent.tsx#L100
Also fixing the Loading Indicator.

Fix isFetching and onClearPress to reset state in Parse

---

src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetParser.cs

NO
Fix for a NullRef described in https://www.reddit.com/r/sonarr/comments/14v1neb/bug_report_nullreferenceexception_in/

Fixed: (BTN) Prevent NullRef when Result.Torrents is null

---

frontend/src/Activity/History/HistoryRow.js
frontend/src/Activity/Queue/QueueRow.js

New: Show tooltips with custom formats in History and Queue

---

.github/workflows/api_docs.yml

NO
To prevent stale PRs like  #5817 (f2c63b1d0312dabc5fa1bd777262751084d300c1)

Run API docs workflow on changes to Sonarr.Http

---

src/NzbDrone.Core/RemotePathMappings/RemotePathMappingService.cs

NO
Let's add some logging.
- [] Tests
- [] Wiki Updates
* Towards Downstream https://github.com/Radarr/Radarr/issues/8737

New: Remote Path Mapping Logging Improvements

---

frontend/src/Series/MonitoringOptions/MonitoringOptionsModalContent.js

NO
Changed to properly use the current props.

Fixed: Ensure Monitoring Options resets to No Change after a change

---

frontend/src/Settings/MediaManagement/Naming/NamingModal.js
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/CleanTitleFixture.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/CleanTitleWithoutYearFixture.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/CleanTitleYearFixture.cs
src/NzbDrone.Core/Organizer/FileNameSampleService.cs

NO
Brought naming modal examples in line with how Clean works in filename tokens
*

Naming modal update examples

---

src/Sonarr.Api.V3/CustomFormats/CustomFormatController.cs

Fixed: Ensure validation for Custom Format specifications

---

src/NzbDrone.Core.Test/HealthCheck/Checks/IndexerJackettAllCheckFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/IndexerJackettAllCheck.cs

Fixed: Check only enabled indexers in IndexerJackettAll health check

---

frontend/src/Components/Markdown/InlineMarkdown.js

Ensure original data is shown when no matches are made

---

frontend/src/App/State/AppState.ts
frontend/src/App/State/RootFolderAppState.ts
frontend/src/App/State/SettingsAppState.ts
frontend/src/Store/Selectors/createRootFoldersSelector.ts

NO
Not part of `state.settings.rootFolders` anymore.

Move RootFolderAppState to root AppState

---

frontend/src/Components/Page/Sidebar/PageSidebar.js
frontend/src/Components/Page/Sidebar/PageSidebarItem.js
frontend/src/RootFolder/RootFolders.tsx
frontend/src/Settings/DownloadClients/DownloadClients/Manage/ManageDownloadClientsModalContent.tsx
frontend/src/Settings/ImportLists/ImportLists/Manage/ManageImportListsModalContent.tsx
frontend/src/Settings/Indexers/Indexers/Manage/ManageIndexersModalContent.tsx
frontend/src/System/Backup/Backups.js
frontend/src/System/Logs/Files/LogFiles.js
frontend/src/System/Status/DiskSpace/DiskSpace.js
frontend/src/System/Status/Health/Health.js
frontend/src/System/Tasks/Queued/QueuedTasks.js
frontend/src/System/Tasks/Scheduled/ScheduledTasks.js

Simplify frontend translations

---

src/NzbDrone.Core/HealthCheck/Checks/IndexerDownloadClientCheck.cs
src/NzbDrone.Core/Localization/Core/en.json

New: Add health check for indexers with invalid download client setting

---

src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs

NO
Some more sentry filtering to clean things up

Filter user issues from Sentry

---

frontend/src/Settings/MediaManagement/Naming/Naming.js

Fix: Anime Episode Format translation

---

src/NzbDrone.Common/EnvironmentInfo/OsInfo.cs
src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs

Fixed: Detect Docker when using control group v2

---

frontend/src/Activity/Queue/RemoveQueueItemModal.js

Corrects the translation key used. Thanks to Qsuicide for pointing it out

Fix Remove from queue modal translation

---

src/NzbDrone.Core.Test/Housekeeping/Housekeepers/DeleteBadMediaCovers.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/DeleteBadMediaCovers.cs
src/NzbDrone.Core/Tv/AddSeriesService.cs

NO
A couple performance improvements in when adding multiple series and performing housekeeping by avoiding calling for all series and instead only calling for data needed.

AllSeries performance tweaks

---

frontend/src/Settings/General/UpdateSettings.js
frontend/src/System/Updates/Updates.js
src/NzbDrone.Common/Extensions/PathExtensions.cs
src/NzbDrone.Core/Localization/Core/en.json
src/Sonarr.Api.V3/Config/HostConfigController.cs

NO
Also
- Prevent NullRef in IsPathValid for null paths
- Replace legacy master branch with main

Show warning when using the docker update mechanism

---

frontend/src/System/Status/Health/Health.js
src/NzbDrone.Core.Test/HealthCheck/Checks/NotificationStatusCheckFixture.cs
src/NzbDrone.Core.Test/Housekeeping/Housekeepers/CleanupOrphanedNotificationStatusFixture.cs
src/NzbDrone.Core.Test/NotificationTests/NotificationStatusServiceFixture.cs
src/NzbDrone.Core/Datastore/Migration/194_add_notification_status.cs
src/NzbDrone.Core/Datastore/TableMapping.cs
src/NzbDrone.Core/Download/DownloadClientFactory.cs
src/NzbDrone.Core/HealthCheck/Checks/NotificationStatusCheck.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedDownloadClientStatus.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedNotificationStatus.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/FixFutureImportListStatusTimes.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/FixFutureNotificationStatusTimes.cs
src/NzbDrone.Core/Notifications/NotificationFactory.cs
src/NzbDrone.Core/Notifications/NotificationService.cs
src/NzbDrone.Core/Notifications/NotificationStatus.cs
src/NzbDrone.Core/Notifications/NotificationStatusRepository.cs
src/NzbDrone.Core/Notifications/NotificationStatusService.cs

YES (194 NotificationStatus Table)
Adds status tracking for Noticiations/Connections as well as health messages
* Fixes #4408

New: Notifications (Connect) Status

---

frontend/src/Quality/Quality.ts

NO
Fix Typo in QualitySource Enum
*

Fix Typo in QualitySource Enum

---

frontend/src/Settings/DownloadClients/RemotePathMappings/RemotePathMappings.js
src/NzbDrone.Core/Localization/Core/en.json

NO
Add info box to Remote Path Mappings that they are rarely required
*

Add info box to Remote Path Mappings Settings

---

frontend/src/InteractiveSearch/InteractiveSearchRow.tsx

Fix download tooltip in interactive search

---

src/Sonarr.Api.V3/Series/SeriesController.cs
src/Sonarr.Api.V3/openapi.json

Add `includeSeasonImages` parameter to get single series endpoint

---

frontend/src/FirstRun/AuthenticationRequiredModalContent.js

Fix user check in Authentication Required for newer installs

---

.github/ISSUE_TEMPLATE/bug_report.yml

NO
With Postgres support merged, add `Database` to the bug report template. Also added trailing spaces to the rest of the environment items for easier/more consistent entry.
*

Add Database to Bug Report template

---

src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs

NO
Add SeriesStatusType to Kodi .nfo
* #5980

Add SeriesStatusType to Kodi .nfo

---

src/NzbDrone.Common/Http/HttpClient.cs

NO
A workaround for slower connections.

Increase request timeout in Download File for slower connections

---

frontend/src/Components/Form/EnhancedSelectInputOption.css

NO
It's very confusing when the disabled option is using the default pointer.

Display a not allowed cursor for disabled select options

---

frontend/src/Episode/Summary/EpisodeAiring.js

NO
fixes networkLabel for TBA episodes
*

Fix Episode Airing networkLabel for TBA

---

frontend/src/App/AppUpdatedModalContent.js
frontend/src/App/State/InteractiveImportAppState.ts
frontend/src/Calendar/Events/CalendarEventGroup.js
frontend/src/Components/FileBrowser/FileBrowserModalContent.js
frontend/src/Episode/Summary/EpisodeAiring.js
frontend/src/Settings/CustomFormats/CustomFormats/Specifications/EditSpecificationModalContent.js
frontend/src/Settings/MediaManagement/Naming/NamingModal.js
frontend/src/Settings/MetadataSource/TheTvdb.js
frontend/src/Settings/Profiles/Quality/QualityProfileFormatItems.js
frontend/src/System/Logs/Files/LogFiles.js

move some imports from relative to folder to relative to frontend src root
*

Fix relative imports for Components and Utilities

---

src/NzbDrone.Mono.Test/EnvironmentInfo/VersionAdapters/MacOsVersionAdapterFixture.cs
src/NzbDrone.Mono/EnvironmentInfo/VersionAdapters/MacOsVersionAdapter.cs

Fixed detection of newer versions of macOS

---

src/NzbDrone.Core/Notifications/Pushcut/Pushcut.cs
src/NzbDrone.Core/Notifications/Pushcut/PushcutException.cs
src/NzbDrone.Core/Notifications/Pushcut/PushcutPayload.cs
src/NzbDrone.Core/Notifications/Pushcut/PushcutProxy.cs
src/NzbDrone.Core/Notifications/Pushcut/PushcutResponse.cs
src/NzbDrone.Core/Notifications/Pushcut/PushcutSettings.cs
src/Sonarr.sln.DotSettings

NO
Add support for notification via Pushcut.
N/A

New: Add support for Pushcut notifications

---

src/NzbDrone.Core.Test/HealthCheck/HealthCheckServiceFixture.cs

Add missing using directive in HealthCheckServiceFixture

---

src/NzbDrone.Mono/Disk/DiskProvider.cs

NO
https://github.com/Radarr/Radarr/issues/9176

Fixed: Ignore invalid mount points

---

src/NzbDrone.Core/MediaCover/MediaCoverProxy.cs
src/Sonarr.Http/Frontend/Mappers/IMapHttpRequestsToDisk.cs
src/Sonarr.Http/Frontend/Mappers/MediaCoverProxyMapper.cs
src/Sonarr.Http/Frontend/Mappers/StaticResourceMapperBase.cs
src/Sonarr.Http/Frontend/StaticResourceController.cs

Use async requests for media cover proxy

---

src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs

Use await on reading the response content

---

src/NzbDrone.Core/ImportLists/Custom/CustomImport.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrImport.cs

NO
Looks like that CustomImport and SonarrImport don't show or log any HTTP exception that might occur.

Log exceptions for failed fetches in Custom and Sonarr import lists

---

frontend/src/Series/SeriesImage.js
package.json
yarn.lock

Preserve the protocol in Series Image

---

frontend/src/Series/Details/SeriesDetails.js

Preserve the protocol for fanart images

---

src/NzbDrone.Common/Extensions/PathExtensions.cs
src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
src/NzbDrone.Core/Parser/QualityParser.cs

Fixed: Skip parsing releases without title

---

src/NzbDrone.Core/Parser/LanguageParser.cs

Fix typo for Romanian regex group

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/SabnzbdTests/SabnzbdFixture.cs
src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs

NO
Fixes #6044 
allows for retention of at least 14 days also
*

Fix SabNZBd history retention to allow at least 14 days

---

README.md

NO
Add Translated + Sponsor Badges to README.md

Add Translated + Sponsor Badges to README.md

---

frontend/src/System/Status/Health/Health.js

Add status test all button for IndexerLongTermStatusCheck

---

frontend/src/Components/Modal/ModalContent.js
frontend/src/Components/Page/Header/PageHeader.js
frontend/src/Components/Page/Header/PageHeaderActionsMenu.js
frontend/src/Episode/EpisodeSearchCell.js
frontend/src/Helpers/Props/icons.js

New: Additional tooltips

---

frontend/src/Components/Form/ProviderFieldFormGroup.js
src/NzbDrone.Core/Annotations/FieldDefinitionAttribute.cs
src/NzbDrone.Core/AutoTagging/Specifications/QualityProfileSpecification.cs

NO
One use case would be to used with delay profiles.

New: Auto tag based on series quality profile

---

src/NzbDrone.Core/RemotePathMappings/RemotePathMappingService.cs

NO
Lowering the noise from 360d989cb047d0f752dd71b806aa0a746e3b5f3d
- Fixes #6073

Fixed: Avoid logging evaluations when not using any Remote Path Mappings

---

src/NzbDrone.Core/HealthCheck/Checks/RemovedSeriesCheck.cs

NO
dont require check health to be re-ran....just run on series deletes
- Tests
- Wiki Updates
* UX

Fixed: Refresh Removed Series Healthcheck on All Series Deletes

---

src/NzbDrone.Core/ImportLists/Rss/Plex/PlexRssImportParser.cs

Fixed: Add support for IMDb in Plex Watchlist RSS

---

src/NzbDrone.Core.Test/Localization/LocalizationServiceFixture.cs

NO
Fix Localization test after b5e2b32
*

Fix Localization test after b5e2b32

---

src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/Specifications/AlreadyImportedSpecificationFixture.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/AlreadyImportedSpecification.cs

Fixed: Avoid import loop for already imported episodes part of season packs

---

src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs

Sort Custom Formats by name

---

frontend/src/Activity/Queue/Queue.js
frontend/src/Activity/Queue/QueueDetails.js
frontend/src/Activity/Queue/QueueStatusCell.js
frontend/src/Activity/Queue/TimeleftCell.js
frontend/src/Components/Filter/Builder/HistoryEventTypeFilterBuilderRowValue.tsx
frontend/src/Components/Filter/Builder/SeriesFilterBuilderRowValue.tsx
frontend/src/Store/Actions/historyActions.js
frontend/src/Store/Actions/queueActions.js
src/Sonarr.Api.V3/History/HistoryController.cs

Add translations to history and queue custom filters

---

frontend/src/Series/Index/Overview/SeriesIndexOverviewInfo.tsx

Use the correct property for quality profile on overview

---

src/NzbDrone.Core/HealthCheck/Checks/UpdateCheck.cs

NO
fix incorrect translation token used in HC
*

Fix Update health check translation token

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
adds SEV release group to the list that like to do things differently.
* Closes #6118

New: add [SEV] to ExceptionReleaseGroupRegex

---

src/NzbDrone.Core.Test/DecisionEngineTests/RawDiskSpecificationFixture.cs
src/NzbDrone.Core/DecisionEngine/Specifications/RawDiskSpecification.cs

Fixed: Don't reject DVDRip/DVDRemux as full DVD disk releases

---

src/NzbDrone.Core/DecisionEngine/Specifications/RawDiskSpecification.cs

Fix full disk releases regex for DVDs at the end of the title

---

frontend/src/AddSeries/ImportSeries/SelectFolder/ImportSeriesSelectFolderConnector.js
frontend/src/Components/Form/RootFolderSelectInputConnector.js

NO
For those with too many root folders.

Sort root folders by path in UI

---

src/NzbDrone.Core/Notifications/NotificationFactory.cs

NO
Had an issue with one connection and now it's stuck on failed.

Fixed: Record status for notifications on tests

---

src/NzbDrone.Core/Sonarr.Core.csproj

NO
Bump to latest patch version of 5.1 LTS

Bump ffprobe to 5.1.4

---

frontend/src/Settings/CustomFormats/CustomFormats/CustomFormat.js

NO
fixes incorrectly named translation token.
* closes #6172

fixes DeleteCustomFormatMessageText token

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/DetectSample.cs

fix hardcoded logging value of 90s
NO
title
-  Tests
-  Wiki Updates
* ref #6180

Improve Sample Detection Logging

---

src/NzbDrone.Core/HealthCheck/Checks/ApiKeyValidationCheck.cs
src/NzbDrone.Core/Localization/Core/en.json

NO
fix translation key in ApiKeyValidationCheck and UpdateStartupTranslocationHealthCheckMessage
*

fix translation keys

---

frontend/src/Activity/Blocklist/Blocklist.js
src/NzbDrone.Core/Localization/Core/en.json

New: Confirmation before clearing blocklist

---

src/NzbDrone.Core/Localization/Core/fr.json
src/NzbDrone.Core/Localization/Core/pt_BR.json
src/NzbDrone.Core/Localization/Core/ru.json

NO
I missed a couple of renames in the foreign json files. Weblate now troes to remove them in #6195 
Not sure if you can fix them with this PR and close the automatic weblate one?
*

fix missed translation renames

---

src/NzbDrone.Core/AutoTagging/Specifications/GenreSpecification.cs

Fixed: Case insensitive matching autotagging genres

---

frontend/src/Components/DescriptionList/DescriptionListItemDescription.css

Wrap long lines in description lists

---

frontend/src/Store/Actions/seriesActions.js
src/NzbDrone.Core/Localization/Core/en.json

Fix filter type for series' network

---

frontend/src/Series/Details/SeriesDetails.js

NO
Lets not show the 0% rating if it doesn't exist. Quite a few questions about it recently
*

Hide ratings on series page if non existent

---

src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNet.cs
src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetParser.cs
src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetRequestGenerator.cs
src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetSettings.cs
src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetTorrent.cs
src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetTorrentQuery.cs
src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetTorrents.cs

Fixed: Handle query limit error and add rate limit for BroadcastheNet

---

src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatVideoDynamicRangeTypeFixture.cs
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/VideoFileInfoReaderFixture.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/HdrFormat.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs

New: Support for DV HDR10Plus 

---

frontend/src/Content/Images/Icons/manifest.json

To enforce browser nav buttons
NO
This makes navigation easier in PWAs on desktops.
*

Enable browser nav buttons for PWA

---

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs

NZB Finder will consolidate WEBDL & X265 into SD,HD,UHD so removed 5010 and 5090 categories.
OZnzb is dead so removed it from the presets list.

Updated NZB Finder categories and removed OZnzb

---

frontend/src/Series/Details/SeriesDetails.js
frontend/src/Series/Index/Posters/SeriesIndexPoster.tsx
frontend/src/Series/Index/Table/SeriesIndexRow.css

Fixed: Undefined statistics and season folder column width on series index

---

src/NzbDrone.Core/DecisionEngine/Specifications/UpgradableSpecification.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/UpgradeSpecification.cs

NO
title
- radarr downstream: https://github.com/Radarr/Radarr/commit/4bcde25e2916ef7727a2f2d7e481501653acc856
- radarr downstream: https://github.com/Radarr/Radarr/pull/9501
- Tests
- Wiki Updates
*

Improve Custom Format compare logging

---

distribution/debian/install.sh

the yes/no check to continue was causing problems for some users. removed it here.

install.sh - remove yes/no check 

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentContentLayout.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs
src/NzbDrone.Core/Localization/Core/en.json


NO
Content Layout option for qBit used when adding torrents.
* Closes #6213

New: Add qBittorrent option for Content Layout

---

frontend/src/Episode/EpisodeQuality.js
frontend/src/InteractiveSearch/InteractiveSearchRow.css
frontend/src/InteractiveSearch/InteractiveSearchRow.tsx

NO
Show a P or R tag for proper or repack in the interactive search results, with possibility to expand to other places quality label is shown.
*

New: Show Proper or Repack tag in interactive search

---

src/NzbDrone.Core/Notifications/Discord/Discord.cs
src/NzbDrone.Core/Notifications/Discord/DiscordSettings.cs

New: Improve fields selection for Discord connection

---

frontend/src/Settings/DownloadClients/DownloadClients/Manage/ManageDownloadClientsModalContent.tsx
frontend/src/Settings/Indexers/Indexers/Manage/ManageIndexersModalContent.tsx
frontend/src/Store/Actions/Settings/downloadClients.js
frontend/src/Store/Actions/Settings/indexers.js

NO
adds sorting to the modals for manage indexers and manage dl clients
* closes #6246

New: add sorting to manage indexer and dl client modals

---

src/NzbDrone.Core/Notifications/Trakt/Resource/TraktEpisodeResource.cs
src/NzbDrone.Core/Notifications/Trakt/Trakt.cs
src/NzbDrone.Core/Notifications/Trakt/TraktInterlacedTypes.cs
src/NzbDrone.Core/Notifications/Trakt/TraktProxy.cs

NO
`DolbyVisionHdr10Plus` depends on #6226

HDR metadata and rate limiting for Trakt connection

---

src/NzbDrone.Core/Download/Clients/Flood/Flood.cs

NO
Avoid sending null or empty values as tags to Flood as seen in https://github.com/Radarr/Radarr/issues/8145

Fixed: Ignore empty tags when adding items to Flood

---

src/NzbDrone.Core/Download/DownloadClientBase.cs
src/NzbDrone.Core/Download/TorrentClientBase.cs
src/NzbDrone.Core/Download/UsenetClientBase.cs
src/NzbDrone.Core/Sonarr.Core.csproj

NO
A fix for flakey trackers throw server errors randomly.

New: Retry on failed downloads of torrent and nzb files

---

distribution/debian/install.sh

NO
fix debian install.sh - Remove UTF8-BOM

fix debian install.sh - Remove UTF8-BOM

---

src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserImport.cs
src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserListType.cs
src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserRequestGenerator.cs
src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserSettings.cs
src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserWatchedListType.cs

NO
Adding sorting for user watch list type and rate limit to avoid some of the 429s.
https://github.com/Radarr/Radarr/issues/7002

New: Watch list sorting and rate limit for Trakt Import Lists

---

distribution/macOS/Sonarr.app/Contents/Info.plist
package.json

NO
update MacOS Major Version
* Fixes #6294

Bump MacOS Major Version

---

frontend/src/Episode/History/EpisodeHistory.js
frontend/src/Episode/History/EpisodeHistoryRow.css
frontend/src/Episode/History/EpisodeHistoryRow.css.d.ts
frontend/src/Episode/History/EpisodeHistoryRow.js
frontend/src/Series/History/SeriesHistoryModal.js
frontend/src/Series/History/SeriesHistoryModalContent.js
frontend/src/Series/History/SeriesHistoryRow.css
frontend/src/Series/History/SeriesHistoryRow.css.d.ts
frontend/src/Series/History/SeriesHistoryRow.js

New: Custom formats in episode history

---

src/NzbDrone.Core/Localization/Core/en.json
src/NzbDrone.Core/Notifications/Apprise/AppriseSettings.cs
src/NzbDrone.Core/Notifications/Gotify/GotifySettings.cs
src/NzbDrone.Core/Notifications/Ntfy/NtfySettings.cs
src/NzbDrone.Core/Notifications/Pushcut/PushcutSettings.cs

NO
Fix Missing HelpText Translation Keys
*

Fix Missing HelpText Translation Keys

---

frontend/src/Series/Details/SeriesDetails.js

NO
Fix end date 2024-01-01 for those with negative TZ.

Fixed: Series end date in UTC

---

src/NzbDrone.Core/Indexers/Torznab/Torznab.cs
src/NzbDrone.Core/Indexers/Torznab/TorznabSettings.cs

NO
Remove dead Torznab presets - HD4Free.xyz and Nyaa Pantsu.
Again, tidy/change whatever.
*

Fixed: Remove dead Torznab presets

---

src/NzbDrone.Core/Download/Pending/PendingReleaseService.cs

Fixed: Persist release source for pending releases

---

src/Sonarr.Api.V3/Indexers/ReleasePushController.cs

Fixed: Release source for release/push

---

.github/actions/test/action.yml
.github/workflows/publish-test-results.yml

Test reporting working during builds and post-build.

Fix post-build test reporting and report summary

---

frontend/src/App/State/AppState.ts
frontend/src/Series/Index/Posters/SeriesIndexPosters.tsx
frontend/src/Store/Selectors/createDimensionsSelector.ts

Don't re-render series posters when width changes as scroll bar shows/hides rapidly when height is just right.
* Closes #6311

Fixed: Series posters flickering when width changes repeatedly

---

src/NzbDrone.Common/Http/XmlRpcRequestBuilder.cs
src/NzbDrone.Core/Download/Clients/Aria2/Aria2Proxy.cs
src/NzbDrone.Core/Download/Clients/Aria2/Aria2Settings.cs
src/NzbDrone.Core/Localization/Core/en.json

Adds a `Directory` setting for Aria2.
* Closes #6343

New: Optional directory setting for Aria2

---

src/NzbDrone.Core/MediaFiles/EpisodeFileMovingService.cs

Clarify EpisodeFileMovingService hardlinking is not definite

---

src/NzbDrone.Core/Download/TorrentClientBase.cs

NO
https://github.com/Radarr/Radarr/issues/9125

Throw download as failed for invalid magnet links

---

src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetSettings.cs
src/NzbDrone.Core/Indexers/FileList/FileListSettings.cs
src/NzbDrone.Core/Indexers/HDBits/HDBitsSettings.cs
src/NzbDrone.Core/Indexers/IPTorrents/IPTorrentsSettings.cs
src/NzbDrone.Core/Indexers/Nyaa/NyaaSettings.cs
src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssIndexerSettings.cs
src/NzbDrone.Core/Indexers/Torrentleech/TorrentleechSettings.cs
src/NzbDrone.Core/Indexers/Torznab/TorznabSettings.cs
src/NzbDrone.Core/Localization/Core/en.json

NO
Adds translations for the new settings introduced in 3541cd7ba877fb785c7f97123745abf51162eb8e

add missing translation keys from Indexer Settings

---

frontend/src/Components/Filter/CustomFilters/CustomFiltersModalContent.js
frontend/src/Components/Menu/FilterMenuContent.js

NO
Sorts custom filters alphabetically
* closes #6334

Sort Custom Filters

---

.github/workflows/build.yml

Re-enabling after further build testing.

Re-enable Deploy

---

distribution/debian/install.sh

Script will exit without input if a prereq package is missing

Update install.sh to not prompt for package installation

---

src/NzbDrone.Core.Test/IndexerTests/FileListTests/FileListFixture.cs
src/NzbDrone.Core/Indexers/FileList/FileListParser.cs

Avoiding deserialize for invalid content type.

Check Content-Type in FileList parser

---

src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs

log which title is being used for trace for custom format debugging & future improvements
Towards https://github.com/Sonarr/Sonarr/pull/5575
Ref https://github.com/Sonarr/Sonarr/issues/5598

Improve Release Title Custom Format debugging

---

frontend/babel.config.js

Needed due to the recent usage of logical assignment operators.
https://github.com/Sonarr/Sonarr/blob/d336aaf3f04136471970155b5a7cc876770c64ff/frontend/src/InteractiveImport/Interactive/InteractiveImportModalContent.tsx#L301-L302

Transpile logical assignment operators with babel

---

src/NzbDrone.Core.Test/Datastore/Migration/201_email_encryptionFixture.cs
src/NzbDrone.Core/Datastore/Migration/201_email_encryption.cs

[Issue on discord](https://discord.com/channels/383686866005917708/383688189941907459/1198616918656037004)

Fix possible NullRef in Email Encryption migration

---

src/NzbDrone.Core/History/HistoryService.cs

Adds size to most history events
* Closes #6234

New: Add size to more history events

---

src/NzbDrone.Core.Test/HealthCheck/Checks/RemotePathMappingCheckFixture.cs
src/NzbDrone.Core.Test/HistoryTests/HistoryServiceFixture.cs
src/NzbDrone.Core.Test/NotificationTests/SynologyIndexerFixture.cs
src/NzbDrone.Core.Test/NotificationTests/Xbmc/OnDownloadFixture.cs
src/NzbDrone.Core/MediaFiles/DeletedEpisodeFile.cs
src/NzbDrone.Core/MediaFiles/EpisodeFileMoveResult.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs
src/NzbDrone.Core/MediaFiles/Events/EpisodeImportedEvent.cs
src/NzbDrone.Core/MediaFiles/RecycleBinProvider.cs
src/NzbDrone.Core/MediaFiles/ScriptImportDecider.cs
src/NzbDrone.Core/MediaFiles/UpgradeMediaFileService.cs
src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/DownloadMessage.cs
src/NzbDrone.Core/Notifications/Synology/SynologyIndexer.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookEpisodeFile.cs
src/NzbDrone.Core/Parser/Model/LocalEpisode.cs

Adds the Recycle Bin Path for deleted files to Custom Script and Webhook events
* Closes #6114

New: Add recycle bin path for deleted episodes to webhook/custom script

---

src/NzbDrone.Core/Download/Pending/PendingReleaseService.cs

Utilizes the download client column for items that are waiting for a specific download client. For items that are waiting a download client of a certain type the download client name is not specified because it is not known.
* Closes #6274

New: Add download client name to pending items waiting for a specific client

---

frontend/src/Settings/CustomFormats/CustomFormats/Specifications/EditSpecificationModalContent.js
src/NzbDrone.Core/Localization/Core/en.json

fix translation in CF Spec

---

src/NzbDrone.Core/Notifications/NotificationDefinition.cs

To prevent testing for disabled notifications on save.

Fixed: Testing for disabled Notifications

---

frontend/src/InteractiveImport/Interactive/InteractiveImportModalContent.tsx

Just a bug because JS is fun.
* Closes #6429

Fixed: Specials not allowing multi-episode select in Manual Import

---

src/NzbDrone.Core/Download/ProcessDownloadDecisions.cs

Improve Release Grabbing & Failure Logging

---

frontend/src/Settings/Notifications/Notifications/Notification.js

Avoid `On Series Add` and `Disabled` in the same time.

Avoid disabled label for notifications with only On Series Add enabled

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Add RZeroX to release group parsing exceptions
Sorry for the messy commit history, I attempted to do all the changes using the github UI lol

Add RZeroX to release group parsing exceptions

---

src/NzbDrone.Core.Test/CustomFormats/Specifications/LanguageSpecification/MultiLanguageFixture.cs
src/NzbDrone.Core.Test/CustomFormats/Specifications/LanguageSpecification/OriginalLanguageFixture.cs
src/NzbDrone.Core.Test/CustomFormats/Specifications/LanguageSpecification/SingleLanguageFixture.cs
src/NzbDrone.Core/CustomFormats/Specifications/CustomFormatSpecificationBase.cs
src/NzbDrone.Core/CustomFormats/Specifications/LanguageSpecification.cs

Adds some words explaining how matches for languages work, didn't want to get too verbose.
* Closes #6408

New: Improve multi-language negate Custom Format

---

frontend/src/Settings/MediaManagement/Naming/NamingOption.css

Fix: Wrapping of naming tokens with alternate separators

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/UpgradeSpecification.cs

Title. This will put the reject reason directly in the UI instead of only debug logs

Improve Custom Format Reject Reason Messaging

---

src/NzbDrone.Core.Test/ParserTests/SingleEpisodeParserFixture.cs
src/NzbDrone.Core/DecisionEngine/Specifications/SplitEpisodeSpecification.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/SplitEpisodeSpecification.cs
src/NzbDrone.Core/Parser/Model/ParsedEpisodeInfo.cs
src/NzbDrone.Core/Parser/Parser.cs

Attempt to parse and then later reject split episodes.
* Closes #6471

New: Parse and reject split episode releases and files

---

src/NzbDrone.Core.Test/ImportListTests/ImportListSyncServiceFixture.cs
src/NzbDrone.Core/ImportLists/ImportListSyncService.cs

Skip import list items with only a title, title only is too inaccurate.
* Closes #6474

Fixed: Don't attempt to import from list with title only

---

.github/workflows/build.yml

Avoid builds on translations and API docs changes only.

Prevent useless builds

---

frontend/src/Settings/Tags/TagsConnector.js

Fixed: Refresh tags state to clear removed tags by housekeeping

---

frontend/src/Components/Form/DownloadClientSelectInputConnector.js
src/NzbDrone.Core/Download/DownloadClientProvider.cs

For those cases when it's so hard to debug which indexer has the issue and why.

Improve messaging on indexer specified download client is not available

---

frontend/src/Store/Actions/calendarActions.js

Correctly persist calendar custom filter selection

Fixed: Correctly persist calendar custom filter selection

---

frontend/src/Settings/UI/UISettings.js

Making the format a little more clearer as hints.

Hints for week column and short dates in UI settings

---

src/NzbDrone.Core/DecisionEngine/Specifications/UpgradableSpecification.cs

A check if existing quality meets the custom formats cutoff, since it's possible that an intermediary quality to bypass the custom formats cutoff. 
Seems reasonable?

Fixed: Avoid upgrades for custom formats cut-off already met

---

src/NzbDrone.Core.Test/ParserTests/SingleEpisodeParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Kept this pretty strict to not interfere with parsing dates or similarly named files.
* Closes #6492

New: Parse releases with season and episode numbers separated by a period

---

src/NzbDrone.Core/Parser/ParsingService.cs

Fix typo in log message matching by TVRage ID

---

.github/workflows/build.yml

Bump version to 4.0.2

---

src/NzbDrone.Core/ImportLists/ImportListSyncService.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrAPIResource.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrImport.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrSettings.cs
src/NzbDrone.Core/Localization/Core/en.json
src/NzbDrone.Core/Parser/Model/ImportListItemInfo.cs
src/NzbDrone.Core/Tv/EpisodeMonitoredService.cs
src/NzbDrone.Core/Tv/MonitoringOptions.cs

Option to sync season monitoring from source Sonarr instance.
* Closes #6542

New: Option to sync season monitoring state when importing from another Sonarr instance

---

frontend/src/Wanted/CutoffUnmet/CutoffUnmet.js
frontend/src/Wanted/Missing/Missing.js
yarn.lock

Needed to be able to change page size.

New: Options button for Missing/Cutoff Unmet

---

src/NzbDrone.Core/Localization/Core/en.json
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserService.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserSettings.cs
src/NzbDrone.Core/Notifications/Plex/Server/PlexServerProxy.cs
src/NzbDrone.Core/Notifications/Plex/Server/PlexServerSettings.cs
src/NzbDrone.Core/Notifications/Xbmc/XbmcSettings.cs

Adds URL base setting to Plex, Emby/Jellyfin and Kodi connections.
* Closes #4416

New: URL Base setting for Media Server connections

---

src/Sonarr.Api.V3/Commands/CommandController.cs

Queue manual import commands at high priority so they don't get stuck behind other manually triggered commands.

Queue Manual Import commands at high priority

---

src/NzbDrone.Core/CustomFormats/Specifications/ReleaseTypeSpecification.cs
src/NzbDrone.Core/Datastore/Migration/205_rename_season_pack_spec.cs

A quick rename and a migration to make sure the DB is updated too.
YES - 205

Renamed SeasonPackSpecification to ReleaseTypeSpecification

---

src/NzbDrone.Core/Extras/Subtitles/ExistingSubtitleImporter.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Aggregation/Aggregators/AggregateSubtitleInfo.cs

Just an error that was reported on [Discord](https://discord.com/channels/383686866005917708/383688189941907459/1213643675175747694)

Fixed: Issue extracting subtitle information for unknown episodes

---

src/NzbDrone.Core.Test/TvTests/EpisodeServiceTests/HandleEpisodeFileDeletedFixture.cs
src/NzbDrone.Core/Tv/EpisodeService.cs

Keeps a cache of removed episodes and only unmonitors them after the series is rescanned.
* Closes #6584

New: Do not automatically unmonitor episodes renamed outside of Sonarr

---

frontend/src/Settings/MetadataSource/TheTvdb.js
frontend/src/Store/Actions/Settings/importListExclusions.js
frontend/src/Store/Actions/settingsActions.js
src/NzbDrone.Core/Notifications/Xbmc/XbmcJsonApiProxy.cs
src/NzbDrone.Core/Notifications/Xbmc/XbmcSettings.cs

Update Address for Kodi after 9fd193d2a82d5c2cdc0f36c1f984e4b6b68aaa8d

Fixed: URL Base setting for Kodi connections

---

frontend/src/Store/Actions/settingsActions.js

Persist page size for Import List Exclusions

---

src/NzbDrone.Core/Organizer/FileNameBuilder.cs

Follow up to #6606 to land ASAP.

Prevent NullRef in naming when truncating a null Release Group

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/FullSeasonSpecification.cs

-  improve UX
- Current messaging is unclear and vague
- support example: https://forums.sonarr.tv/t/files-stuck-on-downloaded-waiting-to-import-in-activity/33545

Fixed: Improve Single File Full Season Messaging

---

src/NzbDrone.Core/HealthCheck/Checks/DownloadClientRootFolderCheck.cs
src/NzbDrone.Core/Localization/Core/en.json
src/NzbDrone.Core/Localization/Core/es.json
src/NzbDrone.Core/Localization/Core/fi.json
src/NzbDrone.Core/Localization/Core/fr.json
src/NzbDrone.Core/Localization/Core/hu.json
src/NzbDrone.Core/Localization/Core/pt_BR.json
src/NzbDrone.Core/Localization/Core/zh_CN.json

Also removes stale translations
* Ref #6609 - may help clarify the issue to users

Update release profile download client warning

---

src/NzbDrone.Core.Test/ParserTests/AbsoluteEpisodeNumberParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

One rather horribly named Spanish release and a French one that was over parsed.
https://forums.sonarr.tv/t/cant-download-dragon-ball-z-permanent-unkown-series/33563

Fixed: Parsing of some French and Spanish anime releases

---

.github/workflows/build.yml
frontend/src/Settings/MediaManagement/Naming/NamingOption.css
package.json

Notifications when develop/main builds succeed/fail.

Add notification for build success/failures

---

frontend/src/Components/Form/EnhancedSelectInput.css
frontend/src/System/Tasks/Queued/QueuedTaskRowNameCell.tsx

- Sort series by title in task name
- Ensure not-allowed is shown for disabled selects

Sort series by title in task name

---

src/Sonarr.Http/Ping/PingController.cs

New: Allow HEAD requests to ping endpoint

---

.github/workflows/build.yml

Bump version to 4.0.3

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Cleanse BHD RSS keys from log files.
* Closes #6666

Fixed: Cleanse BHD RSS key in log files

---

src/NzbDrone.Core/Tv/MoveSeriesService.cs

Fixed: Skip move when source and destination are the same

---

src/NzbDrone.Core/ImportLists/AniList/List/AniListImport.cs

Testing of AniList will return a warning if all results are filtered out by 'Media' filters, this will now query additional pages to find at least one valid result before returning that warning.

Fixed: Improve AniList testing with Media filters

---

src/NzbDrone.Mono/Disk/FindDriveType.cs

`fuse.shfs` is a mergerfs-like union filesystem being used by Unraid.

New: Detect shfs mounts in disk space

---

src/NzbDrone.Core.Test/ParserTests/AbsoluteEpisodeNumberParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Adds support for the glorious format that AniLibriaTV decided to use.
* Closes #6694

New: Parse absolute episode numbers within square brackets

---

.github/workflows/build.yml

Bumping to 4.0.4 for main release.

Bump version to 4.0.4

---

.devcontainer/Sonarr.code-workspace

Allows the linting and style settings for the frontend to be applied even when you load the main repo as a workspace

Add dev container workspace

---

src/NzbDrone.Core.Test/IndexerTests/TestIndexerSettings.cs
src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetSettings.cs
src/NzbDrone.Core/Indexers/Fanzub/FanzubSettings.cs
src/NzbDrone.Core/Indexers/FileList/FileListSettings.cs
src/NzbDrone.Core/Indexers/HDBits/HDBitsSettings.cs
src/NzbDrone.Core/Indexers/IIndexerSettings.cs
src/NzbDrone.Core/Indexers/IPTorrents/IPTorrentsSettings.cs
src/NzbDrone.Core/Indexers/IndexerBase.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs
src/NzbDrone.Core/Indexers/Nyaa/NyaaSettings.cs
src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssIndexerSettings.cs
src/NzbDrone.Core/Indexers/Torrentleech/TorrentleechSettings.cs
src/NzbDrone.Core/Indexers/Torznab/TorznabSettings.cs
src/NzbDrone.Core/Languages/RealLanguageFieldConverter.cs
src/NzbDrone.Core/Localization/Core/en.json

Choose what language a Multi release should be treated as.
Backport from this commit of Radarr : https://github.com/Radarr/Radarr/commit/efd4abfa3eaab0b476ff8d69a7ef4fc98ae1fd7d
NO
* Closes #2854

Default/multi Language selection per indexer

---

.github/workflows/build.yml
.github/workflows/labeler.yml
.github/workflows/lock.yml

Update CI dependencies and arguments in consequences

Update CI dependencies

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

Parsed releases with multiple Ukranian audio tracks in the name.
* Closes #6714

New: Parse releases with multiple Ukranian audio tracks

---

.github/labeler.yml
.github/workflows/conflict_labeler.yml

Make the merge conflict labeler work correctly

Fix merge conflict labeling

---

src/NzbDrone.Core/Sonarr.Core.csproj

https://github.com/advisories/GHSA-g85r-6x2q-45w7
https://github.com/advisories/GHSA-5x7m-6737-26cr

Bump SixLabors.ImageSharp to 3.1.4

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Adding exceptions for 2 release groups who are fairly known. BluDragon seems to be focusing on anime.

New: Add KRaLiMaRKo and BluDragon to release group parsing exceptions

---

src/NzbDrone.Host/Startup.cs

Include `X-Forwarded-Host` header in forwarded headers.
* Closes #6764

Forward X-Forwarded-Host header

---

src/Sonarr.Api.V3/AutoTagging/AutoTaggingController.cs
src/Sonarr.Api.V3/Commands/CommandController.cs
src/Sonarr.Api.V3/Config/ConfigController.cs
src/Sonarr.Api.V3/Config/HostConfigController.cs
src/Sonarr.Api.V3/Config/NamingConfigController.cs
src/Sonarr.Api.V3/Config/UiConfigController.cs
src/Sonarr.Api.V3/CustomFilters/CustomFilterController.cs
src/Sonarr.Api.V3/CustomFormats/CustomFormatController.cs
src/Sonarr.Api.V3/EpisodeFiles/EpisodeFileController.cs
src/Sonarr.Api.V3/ImportLists/ImportListExclusionController.cs
src/Sonarr.Api.V3/Indexers/ReleaseController.cs
src/Sonarr.Api.V3/Indexers/ReleasePushController.cs
src/Sonarr.Api.V3/Profiles/Delay/DelayProfileController.cs
src/Sonarr.Api.V3/Profiles/Languages/LanguageProfileController.cs
src/Sonarr.Api.V3/Profiles/Quality/QualityProfileController.cs
src/Sonarr.Api.V3/Profiles/Release/ReleaseProfileController.cs
src/Sonarr.Api.V3/ProviderControllerBase.cs
src/Sonarr.Api.V3/Qualities/QualityDefinitionController.cs
src/Sonarr.Api.V3/Queue/QueueActionController.cs
src/Sonarr.Api.V3/RemotePathMappings/RemotePathMappingController.cs
src/Sonarr.Api.V3/RootFolders/RootFolderController.cs
src/Sonarr.Api.V3/SeasonPass/SeasonPassController.cs
src/Sonarr.Api.V3/Series/SeriesController.cs
src/Sonarr.Api.V3/System/Backup/BackupController.cs
src/Sonarr.Api.V3/Tags/TagController.cs

.NET 8.0 needs parameter binding for resources in POST/PUT bodies, so preparing for it.

Parameter binding for API requests

---

src/NzbDrone.Core/Localization/Core/en.json

fixes a missing translation key for qbittorrent status

fix missing translation key

---

frontend/src/Series/History/SeriesHistoryRow.js

Guard against missing episodes preventing other items from loading.
* Closes #6782

Fixed: History with unknown episode

---

src/NzbDrone.Core.Test/ParserTests/SeasonParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Treats S1E1-8 of 8 as a full season release.
* Closes #6757

New: Treat batch releases with total episode count as full season release

---

src/NzbDrone.Core/Download/Clients/Transmission/TransmissionTorrent.cs

https://github.com/Radarr/Radarr/issues/9987

Fixed: Parsing long downloading/seeding values from Transmission

---

src/NzbDrone.Core/Indexers/SeedCriteriaSettings.cs
src/Sonarr.Http/ClientSchema/SchemaBuilder.cs

Minor change to set `isFloat` for nullable double.

Use number input for seed ratio

---

frontend/src/Episode/Summary/EpisodeFileRow.css
frontend/src/Episode/Summary/EpisodeFileRow.css.d.ts
frontend/src/Episode/Summary/EpisodeFileRow.js
frontend/src/Episode/Summary/EpisodeSummary.js
frontend/src/Episode/Summary/EpisodeSummaryConnector.js

Because @fryfrog asked on Discord and it should absolutely be there.

New: Add Custom Format Score to file in Episode Details

---

src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/Notifiarr/Notifiarr.cs
src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookSeries.cs
src/NzbDrone.Core/Tags/TagRepository.cs

Adds tags under series for applicable Webhook and Notifiarr events.

New: Add series tags to Webhook and Notifiarr events

---

src/NzbDrone.Core.Test/ParserTests/DailyEpisodeParserFixture.cs
src/NzbDrone.Core.Test/ParserTests/SeasonParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Fixes issues with some partial season packs and ambiguous air dates (parse them so we can detect and throw an error).
* Closes #6799

Partial Season Packs and Ambiguous Air Dates

---

frontend/src/login.html

Using the light and dark theme colors for textColor to fix the color for the inputs on the login page.

Fixed: Text color for inputs on login page

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

Parse some more garbage release names to something more accurate/useful useful.
* Closes #6801

New: Parse 480i Bluray/Remux as Bluray 480p

---

src/NzbDrone.Core/Validation/Paths/RootFolderExistsValidator.cs
src/Sonarr.Api.V3/ImportLists/ImportListController.cs

Adding new validator for optional root folder existence.

New: Root folder exists validation for import lists

---

src/NzbDrone.Core/Sonarr.Core.csproj

Security update. https://github.com/npgsql/npgsql/releases/tag/v7.0.7

Bump Npgsql to 7.0.7

---

frontend/src/Components/SignalRConnector.js
src/Sonarr.Api.V3/Episodes/EpisodeResource.cs

Fixing the wanted section to match `wantedActions` and https://github.com/Sonarr/Sonarr/blob/627b2a4289ecdd5558d37940624289708e01e10a/frontend/src/Episode/episodeEntities.js#L4-L5

Update the wanted section for missing and cutoff unmet

---

.github/workflows/build.yml

Bump version to 4.0.5

---

src/NzbDrone.Core/Notifications/Notifiarr/Notifiarr.cs
src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookImage.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookSeries.cs

Adds in the additional fields.
* Closes #6822

New: Genres and Images for Webhooks and Notifiarr

---

src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs

This should basically trigger a reimport if you decide to add back a series that exists in the cached queue without needing a restart to do the same thing.
Added same filtering by TvdbId in deleted series event.

New: Refresh cache for tracked queue on series add

---

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs

Improve the messaging a bit to tell the user their config file is invalid.
* Closes #6860

Fixed: Improve error messaging if config file isn't formatted correctly

---

frontend/src/Components/Page/Header/SeriesSearchInputConnector.js
frontend/src/Components/Page/Header/SeriesSearchResult.js
frontend/src/Components/Page/Header/fuse.worker.js
frontend/src/Series/Details/SeriesDetails.js
frontend/src/Series/Details/SeriesDetailsLinks.js
frontend/src/Series/Series.ts
frontend/src/Settings/MediaManagement/Naming/NamingModal.js
src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/IdFixture.cs
src/NzbDrone.Core.Test/TvTests/RefreshSeriesServiceFixture.cs
src/NzbDrone.Core/Datastore/Migration/206_add_tmdbid.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/KodiEpisodeGuide.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
src/NzbDrone.Core/MediaFiles/ScriptImportDecider.cs
src/NzbDrone.Core/MetadataSource/SkyHook/Resource/ShowResource.cs
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserItems.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookSeries.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs
src/NzbDrone.Core/Organizer/FileNameSampleService.cs
src/NzbDrone.Core/Tv/RefreshSeriesService.cs
src/NzbDrone.Core/Tv/Series.cs
src/Sonarr.Api.V3/Series/SeriesResource.cs
src/Sonarr.Api.V3/openapi.json

Adds support for tmdb ids in renaming and searching in newznab.
YES - 206
* Closes #6866

New: Add TMDB id support

---

src/NzbDrone.Core/Download/Aggregation/RemoteEpisodeAggregationService.cs
src/NzbDrone.Core/Tv/SeriesScannedHandler.cs

Found these minor issues while adding series with unknown items in the queue.

Fixed: Adding series with unknown items in queue

---

src/NzbDrone.Core/ImportLists/Imdb/ImdbListParser.cs

A few people have had issues with lists, turns out IMDb lists were never returning the series' title so they'd get a SQL exception.

Fixed: Importing from IMDb list

---

frontend/src/Components/Form/EnhancedSelectInput.js
frontend/src/Components/Form/EnhancedSelectInputConnector.js
frontend/src/Settings/Notifications/Notifications/EditNotificationModalContentConnector.js
frontend/src/Store/Actions/Creators/Reducers/createSetProviderFieldValuesReducer.js
frontend/src/Store/Actions/Settings/notifications.js
src/NzbDrone.Core/Annotations/FieldDefinitionAttribute.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabCategoryFieldOptionsConverter.cs
src/NzbDrone.Core/Localization/Core/en.json
src/NzbDrone.Core/Notifications/Plex/PlexTv/PlexTvProxy.cs
src/NzbDrone.Core/Notifications/Plex/PlexTv/PlexTvResource.cs
src/NzbDrone.Core/Notifications/Plex/PlexTv/PlexTvService.cs
src/NzbDrone.Core/Notifications/Plex/Server/PlexServer.cs
src/NzbDrone.Core/Notifications/Plex/Server/PlexServerSettings.cs

Use's plex.tv's resources after authenticating you can lookup you servers and select on the connections, includes server name, hostname / IP, local / remote and whether it's secure. Selecting an option overrides the Host, Port and Use SSL options with values for that connection.
* Closes #6887

New: Ability to select Plex Media Server from plex.tv

---

src/Sonarr.Api.V3/Episodes/EpisodeResource.cs
src/Sonarr.Api.V3/openapi.json

Removed in v3, just left in the resource by mistake.
* Closes #6841

Remove seriesTitle from EpisodeResource

---

src/NzbDrone.Core/Housekeeping/Housekeepers/TrimLogDatabase.cs

Disable trim log database housekeeping task

---

.github/workflows/build.yml

Bump version to 4.0.6

---

frontend/src/Activity/History/HistoryRow.js

Bad things happen when you remove a series in another tab.

Fixed: History with unknown series

---

src/NzbDrone.Core.Test/ParserTests/SeasonParserFixture.cs
src/NzbDrone.Core.Test/ParserTests/SingleEpisodeParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Fixes a regression in https://github.com/Sonarr/Sonarr/commit/63bed3e670edbbc58cb165d1b856e9070ffc98a4
* Closes #6925

Fixed: Parsing of anime releases using standard numbering

---

src/NzbDrone.Core/ImportLists/Custom/CustomAPIResource.cs
src/NzbDrone.Core/ImportLists/Custom/CustomImport.cs

Prevents some errors and allows Custom Import Lists to return a title that is used.

Custom Import List improvements

---

frontend/src/Components/Label.css
frontend/src/Components/Label.css.d.ts
frontend/src/Series/Details/SeasonProgressLabel.tsx
frontend/src/Series/Details/SeriesDetailsSeason.js

New: Queued episode count for seasons in series details

---

frontend/src/Activity/Queue/RemoveQueueItemModal.tsx
src/Sonarr.Api.V3/Queue/QueueController.cs

Respect blocklist argument for pending releases removal.

Fixed: Removing pending release without blocklisting

---

.github/workflows/build.yml

Bump version to 4.0.7

---

.github/workflows/build.yml

Bump version to 4.0.8

---

src/NzbDrone.Core/Parser/Parser.cs

Removed unnecessary tabs to improve code style.

fix: Remove unnecessary tabs in RemoveFileExtension method

---

src/NzbDrone.Core.Test/ParserTests/AbsoluteEpisodeNumberParserFixture.cs
src/NzbDrone.Core.Test/ParserTests/UnicodeReleaseParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

More parsing fixes for anime releases.

More Anime Formats More Parsing Problems

---

frontend/src/Settings/Profiles/Quality/QualityProfileFormatItems.js

Fixing regression introduced with 1a1c8e6c08a6db5fcd2b5d17e65fa1f943d2e746.

Fix custom formats sorting for quality profiles

---

frontend/src/AddSeries/AddNewSeries/AddNewSeriesSearchResult.css
frontend/src/AddSeries/AddNewSeries/AddNewSeriesSearchResult.css.d.ts
frontend/src/AddSeries/AddNewSeries/AddNewSeriesSearchResult.js
frontend/src/Helpers/Props/icons.js
frontend/src/Series/Details/SeriesDetails.css
frontend/src/Series/Details/SeriesDetails.css.d.ts
frontend/src/Series/Details/SeriesDetails.js

New: Display original language on series details and search results page

---

src/NzbDrone.Core/Tv/ShouldRefreshSeries.cs

Initially was thinking of adding the same command as a schedule task, but seems like I can't add it with custom attributes. So I took this approach instead for `ShouldRefresh` to give a little chance for TBA episodes if possible.

Refresh series with recently aired episodes with TBA titles

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

More restrictive on what French releases are.
* Closes #6995

Fixed: Don't treat SubFrench as French audio language

---

src/NzbDrone.Core/MediaFiles/RenameEpisodeFileService.cs

Would be useful to see how many files really changed.

Improve messaging for renamed episode files progress info

---

src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs

New: Add TVMaze and TMDB IDs to Kodi .nfo

---

src/NzbDrone.Core/HealthCheck/Checks/UpdateCheck.cs
src/NzbDrone.Core/Localization/Core/en.json

Include available version in update health check

---

frontend/src/Store/Actions/seriesActions.js

New: Title filter for Series Index

---

frontend/.eslintrc.js
frontend/src/Activity/Blocklist/Blocklist.tsx
frontend/src/Activity/History/History.tsx
frontend/src/Activity/Queue/Queue.tsx
frontend/src/Activity/Queue/QueueOptions.tsx
frontend/src/App/AppRoutes.tsx
frontend/src/Components/Error/ErrorBoundaryError.tsx
frontend/src/Episode/EpisodeNumber.tsx
frontend/src/Helpers/Hooks/useModalOpenState.ts
frontend/src/InteractiveImport/Interactive/InteractiveImportModalContent.tsx
frontend/src/InteractiveImport/Language/SelectLanguageModal.tsx
frontend/src/InteractiveImport/Series/SelectSeriesModalContent.tsx
frontend/src/InteractiveSearch/OverrideMatch/DownloadClient/SelectDownloadClientModal.tsx
frontend/src/Parse/ParseToolbarButton.tsx
frontend/src/Series/Index/Overview/SeriesIndexOverviews.tsx
frontend/src/Series/Index/Posters/SeriesIndexPosters.tsx
frontend/src/Series/Index/Table/SeriesIndexTable.tsx
frontend/src/Series/Index/Table/SeriesIndexTableOptions.tsx
frontend/src/Settings/CustomFormats/CustomFormatSettingsPage.tsx
frontend/src/Settings/DownloadClients/DownloadClients/Manage/ManageDownloadClientsModalContent.tsx
frontend/src/Settings/ImportLists/ImportLists/Manage/ManageImportListsModalContent.tsx
frontend/src/Settings/Indexers/Indexers/Manage/ManageIndexersModalContent.tsx
frontend/src/System/Status/About/About.tsx
frontend/src/System/Updates/Updates.tsx

Re-adds the missing page size option and unknown series for Queue.
* Closes #7035

Fixed: Setting page size in Queue, History and Blocklist

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs

Ref https://github.com/Radarr/Radarr/issues/10237
FYI for `ProcessFolder` it's important to note that if you have other files not part off the download, they'll get the same indexer flags as well. This should not happen, but it's good to keep in mind that with some weird download clients like FreeBox who don't have support for single files as output paths (like qbit has since 813f8869202b54048db8d792ee6c3f0d060dbd72), it will process the full downloads folder not just the file in question.

Fixed: Persist indexer flags when manual importing failed imports from queue

---

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs

@fryfrog brought it up before on Discord, but finally remembered to do it.

New: Default log level changed to debug

---

src/NzbDrone.Core/Indexers/HDBits/HDBitsParser.cs

Minor change for those who use the native indexer to profit from match by series id.

Parse TvdbId for releases from HDBits

---

src/Sonarr.Api.V3/Series/SeriesEditorController.cs
src/Sonarr.Api.V3/Series/SeriesEditorValidator.cs

As discussed a while ago on discord, adding validation on the series editor endpoint for quality profiles and root folders.

New: Validation for bulk series editor

---

distribution/debian/install.sh
frontend/src/Activity/Queue/QueueRow.css
src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs
src/NzbDrone.Test.Common/AutoMoq/AutoMoqer.cs

Aligns the actions to the right so remove is always on the right in the same spot.

Align queue action buttons on right

---

frontend/src/Settings/ImportLists/ImportListExclusions/EditImportListExclusionModal.tsx

To clear pending changes to avoid use of not actual values when you open a fresh edit modal.

Fixed: Clearing pending changes for edit import list exclusions on modal close

---

src/NzbDrone.Core.Test/ParserTests/DailyEpisodeParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

From Discord: https://discord.com/channels/383686866005917708/649018968559845376/1271837895103221832
Just some poorly named wrestling releases. Parsing them as daily because it's less of a collision with mini-series parsing that this collides with.

New: Support for releases with absolute episode number and air date

---

src/Sonarr.Api.V3/ImportLists/ImportListExclusionController.cs
src/Sonarr.Api.V3/ImportLists/ImportListExclusionExistsValidator.cs

Prevent `This exclusion has already been added` errors when editing an existing exclusion.

Fixed: Updating existing import list exclusions

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Another release group trying to be unique.
* Closes #7083

New: Parse DarQ release group

---

frontend/src/Series/Details/SeriesDetails.css
frontend/src/Series/Details/SeriesDetails.css.d.ts
frontend/src/Series/Details/SeriesDetails.js
frontend/src/Series/Index/Overview/SeriesIndexOverview.css
frontend/src/Series/Index/Overview/SeriesIndexOverview.css.d.ts
frontend/src/Series/Index/Overview/SeriesIndexOverview.tsx
frontend/src/Series/Index/Posters/SeriesIndexPoster.css
frontend/src/Series/Index/Posters/SeriesIndexPoster.css.d.ts
frontend/src/Series/Index/Posters/SeriesIndexPoster.tsx
frontend/src/Series/Index/ProgressBar/SeriesIndexProgressBar.tsx
frontend/src/Series/Index/Table/SeriesStatusCell.tsx
frontend/src/Series/Series.ts
frontend/src/Series/SeriesStatus.ts
frontend/src/Utilities/Series/getProgressBarKind.ts

Improve UX a little for deleted series for posters, overviews and details page.

Fixed: Improve status labels for deleted series

---

src/NzbDrone.Core.Test/Extras/Metadata/Consumers/Kometa/FindMetadataFileFixture.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Kometa/KometaMetadata.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Kometa/KometaMetadataSettings.cs

allow creation of metadata images in Kometa naming format
* Closes #6851

Add Kometa metadata image creation

---

src/NzbDrone.Core/Notifications/Discord/Discord.cs
src/NzbDrone.Core/Notifications/Discord/DiscordFieldType.cs

Similar to `On Grab`, but per-file, does not apply to `On Import Complete` notifications

New: Optionally include Custom Format Score for Discord On File Import notifications

---

src/NzbDrone.Core.Test/ParserTests/MultiEpisodeParserFixture.cs
src/NzbDrone.Core.Test/ParserTests/SingleEpisodeParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

More Spanish release name shenanagins.

New: Parse spanish multi-episode releases

---

src/Sonarr.Http/Authentication/AuthenticationController.cs

Only allows redirects to paths within Sonarr.

Fixed: Limit redirects after login to local paths

---

.github/workflows/build.yml

Bump version to 4.0.9

---

frontend/src/Components/Link/Link.tsx

Polymorphic TS refactoring of the `Link` component
Allows the component to be statically typed given the component passed
No behavior changes expected
Before:
After:

Refactoring: Link polymorphic static typing

---

frontend/.vscode/settings.json

Updates VSCode code action syntax
https://code.visualstudio.com/updates/v1_83#_code-actions-on-save-and-auto-save

Tech: VSCode updated code action format

---

frontend/src/Components/MonitorToggleButton.css

Minor change to show cursor not allowed.

Fix disabled style for monitor toggle button

---

src/NzbDrone.Common/Sonarr.Common.csproj
src/NzbDrone.Core.Test/Http/HttpProxySettingsProviderFixture.cs
src/NzbDrone.Core/Http/HttpProxySettingsProvider.cs

Adding support for IP address ranges to be bypassed in proxy use.
* Closes https://github.com/Prowlarr/Prowlarr/issues/2203

New: Bypass IP addresses ranges in proxies

---

frontend/src/Components/Form/TextTagInputConnector.js
src/Sonarr.Api.V3/Profiles/Release/ReleaseProfileController.cs
src/Sonarr.Api.V3/Profiles/Release/ReleaseProfileResource.cs

4 years later, but a fix for https://forums.sonarr.tv/t/releases-being-rejected-clarification-on-why/25191/3 😄

Fixed: Forbid empty spaces in Must Contain/Must Not Contain for Release Profiles

---

frontend/src/Series/Details/SeriesDetailsLinks.tsx
frontend/src/Series/Series.ts

Converted to TS and added the MDBList link and converted all links to https.
* Closes #7162

New: Add MDBList link to series details

---

frontend/src/Settings/MediaManagement/MediaManagement.js
src/NzbDrone.Core.Test/DecisionEngineTests/FreeSpaceSpecificationFixture.cs
src/NzbDrone.Core/Configuration/ConfigService.cs
src/NzbDrone.Core/DecisionEngine/Specifications/FreeSpaceSpecification.cs
src/NzbDrone.Core/Localization/Core/en.json

Checks for free space before grabbing, doesn't consider existing files as that space may not be reclaimed before importing if they are seeding torrents that are hardlinked.
* Closes #7177

New: Check for available space before grabbing

---

src/NzbDrone.Core.Test/Datastore/Migration/214_add_bluray576p_in_profileFixture.cs
src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Datastore/Migration/214_add_blurary576p_quality_in_profiles.cs
src/NzbDrone.Core/Parser/QualityParser.cs
src/NzbDrone.Core/Profiles/Qualities/QualityProfileService.cs
src/NzbDrone.Core/Qualities/Quality.cs

Adds Bluray 576p, enabled in profiles that have Bluray 480p enabled.
YES - 214
* Closes #6203

New: Add Bluray 576p quality

---

src/Sonarr.Http/Authentication/AuthenticationBuilderExtensions.cs

Uses `AddOptions` so we can inject `IConfigFileProvider` when creating the auth cookie name.
* Closes #7199

New: Use instance name in forms authentication cookie name

---

src/Sonarr.Api.V3/Config/CertificateValidator.cs
src/Sonarr.Api.V3/Config/HostConfigController.cs

Adds the exception message + logs the full exception when SSL certificate validation fails.
* Closes #7198

New: Add exception to SSL Certificate validation message

---

src/NzbDrone.Core/Notifications/Gotify/Gotify.cs

Fixes the transposition of Trakt and TVMaze.

Fixed: Links for Trakt and TVMaze in Gotify notifications

---

src/Sonarr.Api.V3/Episodes/EpisodeController.cs

Adds includeSeries and includeEpisodeFile to /episode endpoint; both false by default

Adds includeSeries and includeEpisodeFile to episode endpoint (default = false)

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs

With the changes to detecting samples wee need to make sure we include media info when reprocessing, which is done via augmenting instead of just assigning so any other augmenting can be done as well.
* Closes #7221

Fixed: Reprocessing manual import items unable to detect sample

---

frontend/src/Store/Actions/episodeSelectionActions.js

Persists to local storage and doesn't reset
* Closes #7233

New: Persist sort in Select Episodes modal

---

src/Sonarr.Api.V3/Blocklist/BlocklistController.cs
src/Sonarr.Api.V3/History/HistoryController.cs
src/Sonarr.Api.V3/ImportLists/ImportListExclusionController.cs
src/Sonarr.Api.V3/Queue/QueueController.cs
src/Sonarr.Api.V3/Wanted/CutoffController.cs
src/Sonarr.Api.V3/Wanted/MissingController.cs

Adding list of allowed sorting keys  for queue since fca8c36156da1d9591483a08beddd115c3cb2c31 made the allowed list mandatory.

Fixed: Sorting queue by columns

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixes the telegram API key in the log file. 
YES - No
* See https://github.com/Radarr/Radarr/pull/10477

Fixed: Telegram Log Message

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Parse `BEN THE MAN` as a release group with his special release group name.
* Closes #7255

New: Parse 'BEN THE MAN' release group

---

src/NzbDrone.Core/Indexers/FileList/FileListSettings.cs

They added a new category for encodes that have native dubs (aren't the main language).

Add new category for FL

---

src/NzbDrone.Core.Test/DecisionEngineTests/FreeSpaceSpecificationFixture.cs
src/NzbDrone.Core/DecisionEngine/Specifications/FreeSpaceSpecification.cs

This was throwing, but not being caught.
* Closes #7273

Fixed: Ignore free space check before grabbing if directory is missing

---

.github/workflows/build.yml

Bump version to 4.0.10

---

src/NzbDrone.Core/IndexerSearch/ReleaseSearchService.cs

Fixed: Dedupe releases for single daily and anime episode searches

---

frontend/src/AddSeries/AddNewSeries/AddNewSeries.js
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs

Should make it easier for users to identify their issue by returning the exception message in error.

Include exception message in SkyHook failure message

---

frontend/src/Settings/ImportLists/ImportLists/ImportList.js
frontend/src/Settings/ImportLists/ImportLists/ImportLists.js
frontend/src/Settings/ImportLists/ImportLists/ImportListsConnector.js

New: Display items tags on import lists index

---

frontend/src/Components/SignalRConnector.js
src/Sonarr.Api.V3/DownloadClient/DownloadClientController.cs
src/Sonarr.Api.V3/ImportLists/ImportListController.cs
src/Sonarr.Api.V3/Indexers/IndexerController.cs
src/Sonarr.Api.V3/Metadata/MetadataController.cs
src/Sonarr.Api.V3/Notifications/NotificationController.cs
src/Sonarr.Api.V3/ProviderControllerBase.cs

Updating the UI in real time for provider changes made by other apps, for example Prowlarr or Buildarr.

New: Sync updates to UI for providers

---

frontend/src/Settings/Tags/TagsConnector.js

Continuation of #6962.
* Closes #7295

Natural sorting for tags list in the UI

---

src/NzbDrone.Core.Test/Download/DownloadClientProviderFixture.cs
src/NzbDrone.Core/Download/DownloadClientProvider.cs

For the users using tags on everything returning the actual reason why there's no download client available.

Improve message for grab errors due to no matching tags

---

src/NzbDrone.Core/Instrumentation/DatabaseTarget.cs

Cleasing the exception messages that were appended to an already cleansed message, and also the full exception.

Cleanse exceptions in event logs

---

src/NzbDrone.Core.Test/ParserTests/AbsoluteEpisodeNumberParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Parse standard numbering from some specific release names.
* Closes #7246

New: Improve parsing absolute followed by standard numbering

---

frontend/src/Components/Link/ClipboardButton.tsx
src/NzbDrone.Core/Extras/ExtraService.cs
src/NzbDrone.Core/Extras/Files/ExtraFileManager.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Kometa/KometaMetadata.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Plex/PlexMetadata.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Plex/PlexMetadataSettings.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Roksbox/RoksboxMetadata.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Wdtv/WdtvMetadata.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
src/NzbDrone.Core/Extras/Metadata/IMetadata.cs
src/NzbDrone.Core/Extras/Metadata/MetadataBase.cs
src/NzbDrone.Core/Extras/Metadata/MetadataService.cs
src/NzbDrone.Core/Extras/Others/OtherExtraService.cs
src/NzbDrone.Core/Extras/Subtitles/SubtitleService.cs
src/NzbDrone.Core/Localization/Core/en.json

For the people that want to fill their `.plexmatch` file with every episode.
* Closes #5784

New: Episode mappings in .plexmatch metadata files

---

src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookEpisodeFile.cs

Adds `SourcePath` to the episode file for import events.

New: Include source path with Webhook import event episode file

---

src/NzbDrone.Core/HealthCheck/Checks/ImportListRootFolderCheck.cs

Fixing an issue where the heath check isn't triggered if the old root folder still exists on the storage.

Fixed: Root folder existence for import lists health check

---

src/NzbDrone.Common.Test/TPLTests/DebouncerFixture.cs
src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/Specifications/HasAudioTrackSpecificationFixture.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/HasAudioTrackSpecification.cs

Reject any files during import that don't have any audio tracks.
* Closes #7298

New: Reject files during import that have no audio tracks

---

frontend/src/Store/Middleware/createPersistState.js

Use the instance name (replacing spaces with `_` and all lower case), migrates from` sonarr` when it already exists.
* Closes #7368

New: Improve stored UI settings for multiple instances under the same host

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

New: Replace 'Ben the Man' release group parsing with 'Ben the Men'

---

frontend/src/AddSeries/ImportSeries/Import/ImportSeriesFooter.css
frontend/src/Components/Form/FormInputGroup.tsx
frontend/src/Components/Form/Select/EnhancedSelectInput.tsx
frontend/src/Components/Form/Select/LanguageSelectInput.tsx
frontend/src/Settings/UI/UISettings.js
frontend/src/Store/Selectors/createFilteredLanguagesSelector.ts

- Improves `LanguageSelectInput` to select languages.
- Fixes `EnhancedSelectInput` so clicking outside works correctly
- Fixes styling on Library Import

Improve LanguageSelectInput and fix EnhancedSelectInput

---

.github/workflows/build.yml

Bump version to 4.0.11

---

src/NzbDrone.Core.Test/TvTests/RefreshEpisodeServiceFixture.cs
src/NzbDrone.Core/Tv/RefreshEpisodeService.cs

Looks like a left over check from before we made it Monitor New Seasons.
* Closes #7401

Fixed: New episodes in season follow season's monitored status

---

src/NzbDrone.Core/Notifications/Webhook/WebhookEpisodeFile.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookRelease.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookSeries.cs

Adds OriginalLanguage to the series object, and Languages string to the episode file and release objects
* Closes #7421

New: Additional language fields in webhook notification

---

src/NzbDrone.Core/Download/DownloadClientProvider.cs

A small regression, although the original implementation wasn't 100% correct either. Regardless of tags being provided when getting a download client it will filter based on those tags or fall back to download clients without tags.
* Closes #7474

Fixed: Series without tags bypassing tags on Download Client

---

src/Sonarr.Api.V3/System/Backup/BackupController.cs

Reference: https://github.com/Prowlarr/Prowlarr/issues/2300

Fixed: Refresh backup list on deletion

---

src/NzbDrone.Core/Download/Clients/Transmission/TransmissionProxy.cs

Suggest adding the source IP to RPC whitelist on `403` since some consider it to be an issue with the arrs and not Transmission.

Suggest adding IP to RPC whitelist for on failed Transmission auth

---

.github/workflows/build.yml

Bumping to 4.0.12 for main release

Bump version to 4.0.12

---

frontend/src/Components/Form/FormInputGroup.tsx

Fixes a regression from https://github.com/Sonarr/Sonarr/commit/682d2b4e1b8acb74ab6e75b85e2a73aa431b5332

Fixed: Tooltips for detailed error messages

---

src/NzbDrone.Core/DecisionEngine/Specifications/RssSync/DelaySpecification.cs

Add a couple of extra log lines to clarify when delay profiles are being assessed.
* Closes #7558

Additional logging for delay profile decisions

---

README.md

update translation widget

---

src/NzbDrone.Core.Test/ParserTests/SeasonParserFixture.cs
src/NzbDrone.Core.Test/ParserTests/SingleEpisodeParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Parses single episode releases (possible some multi-episode releases) in this amazing format.
* Closes #7559

New: Parse releases with year and season number in brackets

---

frontend/src/Activity/History/Details/HistoryDetails.tsx
src/NzbDrone.Core/DecisionEngine/Specifications/CustomFormatAllowedByProfileSpecification.cs

Just a minor typo in translation token.

Fix translation key for RSS in History Details

---

src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Adding support for dual titles using `AKA`. 
* Closes #7576

Fixed: Parsing of AKA release titles

---

src/NzbDrone.Core.Test/Download/Aggregation/Aggregators/AggregateLanguagesFixture.cs
src/NzbDrone.Core/Download/Aggregation/Aggregators/AggregateLanguages.cs

Reference https://github.com/Radarr/Radarr/pull/10842

Fixed: Augmenting languages for releases with MULTI and other languages

---

src/NzbDrone.Core/MediaFiles/FileExtensions.cs

add .scr to dangerousExtensions
* Closes #7588

add .scr to dangerousExtensions

---

frontend/src/InteractiveSearch/InteractiveSearch.tsx
frontend/src/InteractiveSearch/InteractiveSearchPayload.ts
frontend/src/InteractiveSearch/InteractiveSearchRow.tsx

Minor addition of typing for search payload.

Typing for Interactive Search payload

---

.github/workflows/api_docs.yml
.github/workflows/build.yml
.github/workflows/conflict_labeler.yml
CONTRIBUTING.md
docs.sh
frontend/src/Settings/DownloadClients/DownloadClients/EditDownloadClientModal.tsx
frontend/src/Settings/DownloadClients/DownloadClients/Manage/ManageDownloadClientsModalRow.tsx
frontend/src/Settings/ImportLists/ImportLists/Manage/ManageImportListsModalRow.tsx
frontend/src/Settings/Indexers/Indexers/Manage/ManageIndexersModalRow.tsx
src/NzbDrone.Host/Startup.cs
src/Sonarr.Api.V3/Qualities/QualityDefinitionResource.cs
src/Sonarr.Api.V3/openapi.json
src/Sonarr.Api.V5/openapi.json
src/Sonarr.Http/VersionedApiControllerAttribute.cs
src/Sonarr.Http/VersionedFeedControllerAttribute.cs

v5 API docs

---

.github/workflows/api_docs.yml
docs.sh
src/Sonarr.sln

v5 API wasn't included in the release build 🙈

Fix builds with v5 API

---

src/NzbDrone.Common/Disk/FileSystemLookupService.cs
src/NzbDrone.Common/Disk/SpecialFolders.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/Blackhole/ScanWatchFolderFixture.cs
src/NzbDrone.Core/Download/Clients/Blackhole/ScanWatchFolder.cs

Follow up to https://github.com/Sonarr/Sonarr/pull/7591 and doing the check on the folder name directly since we don't want to exclude files with leading spaces.

Fixed: Ignore special folders inside Blackhole watch folders

---

src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs

Refresh queue items after series updates to reflect changes like path to prevent imports to old paths.

New: Refresh cache for tracked queue on series update

---

src/NzbDrone.Core.Test/ParserTests/DailyEpisodeParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Try DMY if the day and month are ambiguous.

Fixed: Parsing of daily some episodes using DMY

---

src/NzbDrone.Core/Download/FailedDownloadService.cs

enhance failed download warning for items not grabbed by sonarr

enhance failed download warning for items not grabbed by sonarr

---

src/NzbDrone.Core/Sonarr.Core.csproj

Upgrade Microsoft.Data.SqlClient to 6.0.1

Upgrade Microsoft.Data.SqlClient to 6.0.1

---

src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs
src/NzbDrone.Core/Localization/Core/en.json

Recommend against using uTorrent

---

src/NzbDrone.Core/Download/RejectedImportService.cs

The check of a LocalEpisode == null sometimes fails depending on if this is a single file or a nested file in a folder. The check isn't really essential to the logic of whether to further fail or warn on the download so removed.
Added some minor logging also

Fix: Improve rejected download handling

---

frontend/src/Episode/Summary/EpisodeSummary.tsx
frontend/src/Series/Details/SeriesDetails.tsx

Fixing a minor typo since it's not a Connector anymore.

Fix import typo for QualityProfileName

---

frontend/src/Series/Details/SeriesDetails.css
frontend/src/Series/Details/SeriesDetails.tsx

This PR addresses issues with long texts in the series title and synopsis being cutoff.
The series overview page was making use of rigid layout patterns that prevented containers from flowing to fit their content. Most notably, it was making use of JavaScript based text truncation, a technique typically used to achieve multi-line ellipses that often leads to bizarre UI behaviour (often a result of height calculations being off), slower UI responsiveness, and poorer accessibility (particularly for screen readers).
For standard prose (such as synopsis), text truncation should be considered as a last resort. It's often better to re-think how you should present such information (e.g. you could make the container scrollable or use a pop-up modal).
Rather than making that choice as part of this …

fix: prevent series synopsis from being cutoff

---

frontend/src/Helpers/Hooks/useTheme.ts

Switch style theme instantly when system changes instead of waiting for browser refresh
* Closes #8068

Switch theme automatically when system changes

---

src/NzbDrone.Core.Test/ParserTests/AbsoluteEpisodeNumberParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Avoids reparsing OVAs and other anime specials with the folder name.
* Closes #8083

New: Don't reparse OVA with folder name
