Sonarr/Sonarr

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

The lookarounds on the anime regex were inverted so fixed that too.

No longer reports SxxExx as releasegroup if original title uses - separator

---

src/NzbDrone.Api/Queue/QueueActionModule.cs
src/NzbDrone.Api/Queue/QueueResource.cs
src/NzbDrone.Core.Test/MediaFiles/DownloadedEpisodesCommandServiceFixture.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownload.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs
src/NzbDrone.Core/MediaFiles/Commands/DownloadedEpisodesScanCommand.cs
src/NzbDrone.Core/MediaFiles/DownloadedEpisodesCommandService.cs
src/NzbDrone.Core/Queue/Queue.cs
src/NzbDrone.Core/Queue/QueueService.cs

@markus101 @kayone Haven't yet tested it in intergrated environment so it can't be merged but all tests pass.
I also changed the trackedDownloadService again from TrackingId to DownloadId hopefully not overlooking a  ```Find``` call. Using the TrackingId was to make items, but in the db the DownloadId has to be unique anyway to be effective so it was giving more headaches than it solved.
I basically took the old implementation and refactored it to ```ProcessPath```.

Fix extern import

---

src/NzbDrone.Api/Frontend/Mappers/MediaCoverMapper.cs
src/NzbDrone.Api/MediaCovers/MediaCoverModule.cs
src/NzbDrone.Common/Crypto/HashProvider.cs
src/NzbDrone.Common/Disk/DiskProviderBase.cs
src/NzbDrone.Common/Disk/IDiskProvider.cs
src/NzbDrone.Common/Extensions/StreamExtensions.cs
src/NzbDrone.Core.Test/HealthCheck/Checks/DeleteBadMediaCovers.cs
src/NzbDrone.Core.Test/MediaCoverTests/ImageResizerFixture.cs
src/NzbDrone.Core.Test/MediaCoverTests/MediaCoverServiceFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Housekeeping/Housekeepers/DeleteBadMediaCovers.cs
src/NzbDrone.Core/MediaCover/ImageResizer.cs
src/NzbDrone.Core/MediaCover/MediaCoverService.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Update/UpdateVerification.cs
src/NzbDrone.Core/packages.config
src/NzbDrone.sln
src/UI/Handlebars/Helpers/Html.js
src/UI/Handlebars/Helpers/Series.js

Didn't do caching, but the thirdparty app should do that anyway. Using the ImageResizer library to do the heavy lifting.
You can specify ```&width=``` and/or ```&height=``` if you do both it you can additionally specify ```&mode=Max|Pad|Crop|Carve|Stretch``` (defaults to Crop).
I would recommend Max or Crop, which preserve aspect ratio.

Added support to the api mediacover endpoint to resize the image

---

src/UI/Activity/Queue/TimeleftCell.js
src/UI/AddSeries/SearchResultViewTemplate.hbs
src/UI/Calendar/CalendarFeedViewTemplate.hbs
src/UI/Shared/Toolbar/Radio/RadioButtonView.js
src/UI/Shared/Tooltip.js
src/UI/System/SystemLayoutTemplate.hbs

To avoid the button distortions we usually bind to body, but that messes up tooltips visible in dynamic (signalr) rows. coz they get stuck.
This offers best of both worlds, we automatically find the btn-group, input-group and attach as sibling there.
We do this by overriding the getOptions of the Tooltip object to determine the correct container. If we don't find a btn group we don't change the container, thus the tooltip gets added near the element.
Also removed the localized fixes.
Also had to remove the tooltip from Copy clipboard in the ical modal coz that gets copied to the zeroclipboard and gets stuck when the model closes.

Modify Tooltip mixin to deal with the btn-group distortions

---

src/NzbDrone.Api/Series/SeriesModule.cs
src/NzbDrone.Api/Tags/TagModule.cs
src/NzbDrone.Core.Test/Datastore/Migration/079_dedupe_tagsFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Datastore/Migration/066_add_tags.cs
src/NzbDrone.Core/Datastore/Migration/079_dedupe_tags.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Tags/TagService.cs
src/NzbDrone.Core/Tags/TagsUpdatedEvent.cs
src/UI/Tags/TagCollection.js

@kayone @Taloth 
Currently there are a number of users with duplicate tags (different tags with the same label), this will clean those up (and fix things that are referencing deleted tags) as well as prevent it from reoccurring.

Dedupe tags

---

src/NzbDrone.Core.Test/Datastore/Migration/081_move_dot_prefix_to_transmission_categoryFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/TransmissionTests/TransmissionFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Datastore/Migration/081_move_dot_prefix_to_transmission_category.cs
src/NzbDrone.Core/Download/Clients/Transmission/Transmission.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

With migration to add the dot to existing configured Transmission Settings so we don't break existing users.

Removed hardcoded dot prefix from the transmission category [migration 81]

---

src/UI/Cells/SelectAllCell.js
src/UI/Series/Editor/SeriesEditorLayout.js

@markus101
A hack imo.
Problem is that this.model.collection points to the original unsorted collection and thus messes up the indexes.
Strangely enough I couldn't find a collection property on the cell, so this hack piggybacks it via column.
Any suggestions are welcome.

selecting range with shift-key in Series Editor should now work

---

src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetPriority.cs

*follow up to #223*
The force priority allows NZBs to be downloaded even if the general queue is in a paused state. The use case here is setting recently released items to be downloaded even if the queue is paused. This is a quite common pattern on ISPs that have download quotas (e.g.: most in Australia) where downloading huge archives may need to be paced but shows being currently aired should be fetched for viewing as soon as they are available.
The existence of this priority is buried in their API [docs](http://nzbget.net/RPC_API_reference#Method_.22append.22) and in forum [posts](http://nzbget.net/forum/viewtopic.php?f=3&t=1177) but has been supported for a while (as of r1000). It also shows up [in the NZBGet UI](http://take.ms/gTojP). On older clients, the NZBGet UI will just show …

New: "Force" priority for NZBGet

---

osx/Sonarr

Fixed EXE_PATH to match NzbDrone.exe’s capitalisation, so that on mac case sensitive systems, Sonarr boot up without modifications.

Allow startup on case sensitive file systems

---

src/UI/Content/theme.less

FPS boost when scrolling on Chrome, Safari, and Opera.
**Problem:**
CSS attribute `position:fixed` on background logo: `UI/Content/Images/background/logo.png` causes scroll lag on Webkit browsers.
**Changes:**
1. Separating background-color from background image increased scroll responsiveness on Safari.
2. Temporary workaround:  `-webkit-transform: translatez(0);` is required to force Chrome and Opera to GPU accelerate scrolling on `position:fixed` background.
**References:**
[Opera & Chrome background-attachement: fixed bug](https://petersproblems.wordpress.com/2014/12/06/background-attachment-fixed-causing-lag-when-scrolling/).

Fixed scrolling performance issues on Webkit based browsers.

---

src/NzbDrone.Api/Blacklist/BlacklistResource.cs
src/NzbDrone.Api/History/HistoryResource.cs
src/NzbDrone.Core.Test/Blacklisting/BlacklistRepositoryFixture.cs
src/NzbDrone.Core.Test/Blacklisting/BlacklistServiceFixture.cs
src/NzbDrone.Core/Blacklisting/Blacklist.cs
src/NzbDrone.Core/Blacklisting/BlacklistRepository.cs
src/NzbDrone.Core/Blacklisting/BlacklistService.cs
src/NzbDrone.Core/Datastore/Migration/083_additonal_blacklist_columns.cs
src/NzbDrone.Core/DecisionEngine/Specifications/BlacklistSpecification.cs
src/NzbDrone.Core/History/HistoryService.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/UI/Activity/Blacklist/BlacklistActionsCell.js
src/UI/Activity/Blacklist/Details/BlacklistDetailsLayout.js
src/UI/Activity/Blacklist/Details/BlacklistDetailsLayoutTemplate.hbs
src/UI/Activity/Blacklist/Details/BlacklistDetailsView.js
src/UI/Activity/Blacklist/Details/BlacklistDetailsViewTemplate.hbs
src/UI/Cells/cells.less

@Taloth @kayone 
- Blacklisting of torrents (manual only until stalled detection is a thing)
- Uses more information about the release to determine if it should be blacklisted (size and indexer in addition to date and name)
- Shows details in the UI as to why it was blacklisted (instead of having to look in history)

Improved Blacklisting

---

src/NzbDrone.App.Test/ContainerFixture.cs
src/NzbDrone.Common.Test/TPLTests/DebouncerFixture.cs
src/NzbDrone.Common/Composition/Container.cs
src/NzbDrone.Common/TPL/Debouncer.cs
src/NzbDrone.Core/Download/TrackedDownloads/DownloadMonitoringService.cs

@markus101 
Should fix the problem, but I didn't test it in integration environment.
Also changed IHandleAsync to IHandle, seemed to make sense to do it sync now.

Prevent the premature deletion of a download when slowly importing season pack

---

build.ps1
src/MediaInfoDotNet.dll.config
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/VideoFileInfoReaderFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/MediaInfoDllCheck.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoLib.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/NzbDrone.Core.dll.config
src/NzbDrone.Core/packages.config

The original fix was a hack, trying to trick the system in accepting UTF-8 but that doesn't work on all systems.
In this revision I integrate the MediaInfo wrapper and properly handle the unicode pinvokes by auto-detecting the wchar size (linux wchar = 4 bytes).
That worked, but it would still fail while running via upstart (no clue why).
So I now took the final step, and use the Buffer api to send the file blocks to MediaInfo instead of filenames. (just the blocks mediainfo requests, not the whole file).
This means that the filename is no longer relevant, it's never sent to MediaInfo anymore.
It also means the unicode changes aren't important anymore, coz all stuff we want from MediaInfo is Ascii, but I left it in for completeness.

Integrated MediaInfo wrapper to be able to properly handle Unicode

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/RTorrentTests/RTorrentFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentPriority.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentProxy.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentTorrent.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/packages.config

The client must be accessible via HTTP, usually via a scgi proxy such as Nginx. For more info, see https://github.com/rakshasa/rtorrent/wiki/RPC-Setup-XMLRPC.
- Can be improved
- Magnets must currently be resolved before adding priority / label (however: whether the torrent get resolved is often indicative of swarm health)
- Absolute download path must be specified for post-processing to work

Download clients: New client rTorrent

---

src/NzbDrone.Core/Validation/IpValidation.cs
src/UI/Settings/General/GeneralViewTemplate.hbs

Alternatives:
- Allow empty value (parse as wildcard)
- Before POST, replace empty value with "*"

Settings: Remove misleading placeholder, fix error-message

---

src/NzbDrone.Core.Test/MediaFiles/EpisodeFileMovingServiceTests/MoveEpisodeFileFixture.cs
src/NzbDrone.Core/MediaFiles/EpisodeFileMovingService.cs
src/NzbDrone.Core/MediaFiles/Events/EpisodeFolderCreatedEvent.cs
src/NzbDrone.Core/Metadata/MetadataService.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

Fixes #545
@markus101 Just a quick look for sign-off.
The idea is that on folder creation an event is raised. Atm only used to update metadata.
That should only happen when the series/season folders didn't exist yet.

Series/season metadata also created on episode import.

---

src/NzbDrone.Common.Test/DiskTests/DiskProviderFixtureBase.cs
src/NzbDrone.Common.Test/DiskTests/DiskTransferServiceFixture.cs
src/NzbDrone.Common.Test/NzbDrone.Common.Test.csproj
src/NzbDrone.Common/Disk/DiskProviderBase.cs
src/NzbDrone.Common/Disk/DiskTransferService.cs
src/NzbDrone.Common/Disk/IDiskProvider.cs
src/NzbDrone.Common/NzbDrone.Common.csproj
src/NzbDrone.Core.Test/ProviderTests/RecycleBinProviderTests/DeleteDirectoryFixture.cs
src/NzbDrone.Core.Test/ProviderTests/RecycleBinProviderTests/DeleteFileFixture.cs
src/NzbDrone.Core.Test/TvTests/MoveSeriesServiceFixture.cs
src/NzbDrone.Core.Test/UpdateTests/UpdateServiceFixture.cs
src/NzbDrone.Core/Backup/BackupService.cs
src/NzbDrone.Core/MediaFiles/EpisodeFileMovingService.cs
src/NzbDrone.Core/MediaFiles/RecycleBinProvider.cs
src/NzbDrone.Core/Metadata/MetadataService.cs
src/NzbDrone.Core/Tv/MoveSeriesService.cs
src/NzbDrone.Core/Update/InstallUpdateService.cs
src/NzbDrone.Update/UpdateEngine/BackupAndRestore.cs
src/NzbDrone.Update/UpdateEngine/BackupAppData.cs
src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs

Episode moves now include filesize checks.
Basically the procedure is as follows:
- If a hardlink was requested, try the hardlink first revert to copy if that fails. (this is what was done already)
- If a copy, do the copy and compare the filesizes, retry 2 times if wrong, throws IOException if it still fails.
- If a move a couple of steps:
1. make a hardlink to '{filename}.movebackup' in same directory. If fails, skip to 3.
2. Move that backup file to the destination and compare the filesizes. If succeeds, delete original and exit.
3. Delete backup file if created. Then do a Copy like before, 2 retries at the most.
4. Delete original if succeeded, throw IOException if failed.
The goal of this procedure is to detect CIFS errors. Another method would be to revert to read and write the file …

Verified file transfer

---

.gitmodules
build.ps1
src/NzbDrone.Common.Test/Http/HttpClientFixture.cs
src/NzbDrone.Common/CurlSharp.dll.config
src/NzbDrone.Common/Http/CurlHttpClient.cs
src/NzbDrone.Common/Http/HttpClient.cs
src/NzbDrone.Common/NzbDrone.Common.csproj
src/NzbDrone.sln

@markus101 Request for comments.
Basically, when there's a tls error, I try performing the https request via libcurl.
Obviously this is only done on mono + https.
The wrapper isn't perfect, I believe there are plenty of scenarios which won't be handle properly. That's why I always try the WebClient implementation first, if that fails I mark the domain as such and subsequently try curl.

Curl fallback

---

src/NzbDrone.Api/Queue/QueueActionModule.cs
src/NzbDrone.Core.Test/Download/Pending/PendingReleaseServiceTests/RemovePendingFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Download/Pending/PendingReleaseService.cs

Right now, we only delete the current release being shown, which is annoying. lets say 2x720p releases and 2x1080p releases have been tracked by sonarr, and I have a delay for the episode. I decide that I'm behind on the show and I just don't want it to download that episode, I would have to remove it from the queue four times. it could also cause the user to think the remove button is broken since the episode they deleted keeps reappearing, not knowing that each time they are deleting the next release.

Fix: When removing pending items from the queue remove all releases for that episode

---

src/NzbDrone.Core.Test/Download/CompletedDownloadServiceFixture.cs
src/NzbDrone.Core.Test/Download/TrackedDownloads/TrackedDownloadServiceFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Download/CompletedDownloadService.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs

I am working getting an anime indexer working and it has the issue that the torrent name isn't in a format that Sonarr supports so it doesn't track when added to the download client.  
I changed it so that if its unable to match using the download name then it looks up the history item using the download id and uses the source title which works as the name supplied by the indexer rather than inside the torrent file is in the correct format.

Allow downloads to be tracked by the source name in addition to the download name

---

src/NzbDrone.Api/Episodes/EpisodeResource.cs
src/NzbDrone.Core.Test/DataAugmentation/SceneNumbering/XemServiceFixture.cs
src/NzbDrone.Core/DataAugmentation/Xem/XemService.cs
src/NzbDrone.Core/Datastore/Migration/092_add_unverifiedscenenumbering.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/UnverifiedSceneNumberingSpecification.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Tv/Episode.cs
src/UI/Series/Details/EpisodeWarningCell.js

Work in progress.
I ran into the problem that thexem had mappings for early episodes in a season, where tvdb had higher numbers. A new episode got released and overwrote one of the older ones coz Sonarr blindly assumed those newer episodes were mapped 1 to 1.
As discussed there are two options: We can extrapolate numbering ourselves, or prevent import.
This PR fills in numbering for old (unmapped) seasons, as well as future seasons. Unless there's a season number mismatch.
The idea was to create a ImportSpec that would block the import if series.(UseSeasonNumbering = true and episode.SceneEpisodeNumber = null.) But after thinking about it a bit more it seems ugly to do it that way.
So instead I think we should add an extra field to Episode. 'UnknownSceneNumbering' = true.
We could set …

Extrapolate scene numbering but won't auto import

---

src/NzbDrone.Api/Indexers/ReleaseModule.cs
src/NzbDrone.Api/Indexers/ReleaseModuleBase.cs
src/NzbDrone.Api/Indexers/ReleasePushModule.cs
src/NzbDrone.Api/NzbDrone.Api.csproj
src/NzbDrone.Core/Download/ProcessDownloadDecisions.cs

A new PR to finish off the changes from https://github.com/Sonarr/Sonarr/pull/631
I extracted ReleaseModule to a base class so I could use MapDecisions in both modules (instead of making an almost identical resource to map a DownloadDecision to a resource).
@Taloth @kayone Please take a quick look so we can close this one up.

Release pushing

---

src/NzbDrone.Common/EnvironmentInfo/StartupContext.cs
src/NzbDrone.Core/Update/InstallUpdateService.cs
src/NzbDrone.Host/SpinService.cs

@kayone @Taloth 
Same as during an update we will preserve the arguments passed in when Sonarr was opened.
Closes #325

Preserve startup arguments during restart

---

src/NzbDrone.Core.Test/DecisionEngineTests/HistorySpecificationFixture.cs
src/NzbDrone.Core/DecisionEngine/Specifications/RssSync/HistorySpecification.cs

Prevents grabbing if recent grab is less than an hour old and fixes a bug with invalid season passes and SAB.
Closes #837
Fixes #625

Improvements to History Specification

---

build.ps1
build.sh
integration_mono.sh
src/NzbDrone.Common.Test/Http/HttpClientFixture.cs
src/NzbDrone.Common.Test/NzbDrone.Common.Test.csproj
src/NzbDrone.Common/Http/CurlHttpClient.cs
src/NzbDrone.Common/Http/HttpClient.cs
src/NzbDrone.Common/Http/HttpHeader.cs

This updates HttpTestFixture.cs so that all the tests are run in the normal way and using curl.
I've added a couple of tests (for https and malformed cookie expiry dates) and made a few fixes so that all the tests pass.

Add tests for CurlHttpClient and fix some bugs they uncovered

---

src/UI/Content/theme.less

Near the bottom of the page, there's a small area where the scroll to top button can no longer hover. This is because part of the footer has a "higher" z-index.
Confirmed in Chrome and Firefox. IE doesn't appear to be affected. Here's some screenshots with an added black bar to explain the overlay issue.
Before:
After:
Just an FYI, I tried to sign the CLA but was met with a server error.

Fix z-index on scroll to top button

---

src/UI/Series/series.less

This fixes #875. Tested at various resolutions on Chrome, Firefox and IE. It coincidentally also fixes a bug where the label might overflow out of its parent column as seen in the Large Before screenshot below.
Before (Large):
Before (Small):
After (Large):
After (Small):
After (Bonus - path with no spaces):

Add wrapping to fix long paths in labels. Fixes #875

---

src/UI/Calendar/CalendarView.js

This fixes #857 by making the tooltip's container slightly broader.

Alter calendar tooltip container. Fixes #857

---

src/UI/Calendar/calendar.less

`.legend-labels` has set widths of 500px and 400px depending on the breakpoint. This adds a max-width of 100% so that it won't be larger than the container on screens smaller than 400px wide.
(On a side, completely unrelated note, I majorly screwed up some rebasing earlier... my git skills could be better.)

Give calendar legend ul max width of 100%. Fixes #922

---

src/NzbDrone.Core/Indexers/IndexerFactory.cs

The message is wrong for ~96% of the world.

Changing Indexer failure log message to local from UTC.

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Download/Clients/qBittorrent/DigestAuthenticator.cs
src/NzbDrone.Core/Download/Clients/qBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/qBittorrent/QBittorrentPriority.cs
src/NzbDrone.Core/Download/Clients/qBittorrent/QBittorrentProxy.cs
src/NzbDrone.Core/Download/Clients/qBittorrent/QBittorrentSettings.cs
src/NzbDrone.Core/Download/Clients/qBittorrent/QBittorrentTorrent.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

I had experimented with a qBittorrent plugin a few months ago, but I wasn't able to get it working well because their Web UI API (https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation) didn't have a way to set labels. I've been tracking their "[Web UI] Labels implementation" pull request at https://github.com/qbittorrent/qBittorrent/pull/3444, and it looks like it may merge in the near future.
I updated my prototype to make use of the setLabel command it introduces, so I wanted to share it with you ahead of time for feedback.

Download client for qBittorrent

---

src/NzbDrone.Core/Notifications/PushBullet/PushBulletProxy.cs
src/NzbDrone.Core/Notifications/PushBullet/PushBulletSettings.cs

Pushbullet allows you to create a new device via the API. This new field allows the user to specify an ID of a device to send from. Similar to #641, but instead of public channels, you get a private device to organise pushes from Sonarr.

Pushbullet: Source device support

---

build.sh

Passing the /m parameter to xbuild causes an error.  See:
http://stackoverflow.com/questions/32220678/xbuild-reporting-too-many-project-files-but-works-with-msbuild

Fix: xbuild doesn't support /m parameter

---

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs

Nzbplanet.net recently updated their API URL from `https://nzbplanet.net` to `https://api.nzbplanet.net`. This pull request simply updates the default value suggested when creating a nzbplanet.net Indexer.
Here is a snippet from their news page:
```
The new Api server is now up and synced, To use the new Api server you will need to
change your Api to https or http://api.nzbplanet.net.
```

updating nzbplanet.net api url to reflect recent change

---

src/NzbDrone.Api/Calendar/CalendarFeedModule.cs
src/NzbDrone.Api/Calendar/CalendarModule.cs
src/NzbDrone.Api/Episodes/EpisodeModuleWithSignalR.cs
src/NzbDrone.Common.Test/CacheTests/CachedDictionaryFixture.cs
src/NzbDrone.Common.Test/NzbDrone.Common.Test.csproj
src/NzbDrone.Common/Cache/CacheManager.cs
src/NzbDrone.Common/Cache/CachedDictionary.cs
src/NzbDrone.Common/Cache/ICachedDictionary.cs
src/NzbDrone.Common/Http/HttpClient.cs
src/NzbDrone.Common/NzbDrone.Common.csproj
src/NzbDrone.Core.Test/DataAugmentation/SceneNumbering/XemServiceFixture.cs
src/NzbDrone.Core/DataAugmentation/Scene/SceneMappingService.cs
src/NzbDrone.Core/DataAugmentation/Xem/XemService.cs
src/NzbDrone.Core/Tv/Events/SeriesRefreshStartingEvent.cs
src/NzbDrone.Core/Tv/RefreshSeriesService.cs
src/UI/Calendar/CalendarView.js
src/UI/JsLibraries/fullcalendar.js

Added CachedDictionary that's basically an auto-refreshing cache. Used in both places now.
I haven't tested it thoroughly.
One concern I already noticed is that the SceneMappings are used in the API to add alternativetitles, meaning the api call may wait for an external timeout. Not that bad though, coz in the past we used to do SceneMapping refresh on Appstart event.

Revised caching mechanism in XemService and SceneMappingService

---

src/NzbDrone.Common/Crypto/HashConverter.cs
src/NzbDrone.Common/Extensions/StringExtensions.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/Blackhole/ScanWatchFolderFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/Blackhole/TorrentBlackholeFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/Blackhole/UsenetBlackholeFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadClientFixtureBase.cs
src/NzbDrone.Core.Test/IndexerTests/TorrentRssIndexerTests/TorrentRssIndexerFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Download/Clients/Blackhole/ScanWatchFolder.cs
src/NzbDrone.Core/Download/Clients/Blackhole/TorrentBlackhole.cs
src/NzbDrone.Core/Download/Clients/Blackhole/TorrentBlackholeSettings.cs
src/NzbDrone.Core/Download/Clients/Blackhole/UsenetBlackhole.cs
src/NzbDrone.Core/Download/Clients/Blackhole/UsenetBlackholeSettings.cs
src/NzbDrone.Core/Download/Clients/Blackhole/WatchFolderItem.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Test.Common/AutoMoq/AutoMoqer.cs

Basically creates a hash of the files name+date+sizes involved (not their actual contents, obviously).
And uses that to determine if the download changed.
The graceperiod is currently hardcoded to 30sec, which is fairly arbitrary since CDH is on a 1min cycle.
Effectively it means that all blackhole downloads are delayed for 1min.
@markus101 please note this PR includes the migration-test commit. Just look over that commit separately.

Delaying Blackhole imports while they're still being updated

---

src/NzbDrone.Core/Validation/RuleBuilderExtensions.cs

This is particularly useful on FreeNAS.  It uses underscores in the hostnames when creating plugin jails.

Fixed: Allow underscore when validating hostnames

---

src/NzbDrone.Api/Series/AlternateTitleResource.cs
src/NzbDrone.Core.Test/DataAugmentation/Scene/SceneMappingServiceFixture.cs
src/NzbDrone.Core.Test/IndexerSearchTests/NzbSearchServiceFixture.cs
src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/GetEpisodesFixture.cs
src/NzbDrone.Core/DataAugmentation/Scene/SceneMapping.cs
src/NzbDrone.Core/DataAugmentation/Scene/SceneMappingService.cs
src/NzbDrone.Core/DataAugmentation/Xem/XemProxy.cs
src/NzbDrone.Core/Datastore/Migration/100_add_scene_season_number.cs
src/NzbDrone.Core/IndexerSearch/EpisodeSearchService.cs
src/NzbDrone.Core/IndexerSearch/NzbSearchService.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Parser/ParsingService.cs
src/UI/Series/Details/EpisodeNumberCell.js
src/UI/Series/Details/InfoViewTemplate.hbs
src/UI/Series/Details/SeriesDetailsLayout.js
src/UI/reqres.js

This fixes parsing, searching and UI display of aliases that should only apply to scene season numbers, not TVDB season numbers. This will treat anything from TheXEM as a scene season number and anything from Sonarr's services as a season number.
Closes #1140

Treat XEM aliases as SceneSeasonNumber

---

package.json

The `readme.md` specifies that the license for the project is GPLv3, but the value contained in the `package.json` license field was `BSD`. I have changed it to the `GPL-3.0` SPDX license string both so npm doesn't throw any warnings about license string validity and to better reflect the license of the project.

Update package.json license expression

---

src/NzbDrone.Core/Notifications/Synology/SynologyIndexer.cs

AfterRename/OnRename was implemented a year ago already when it was
disabled in 0f2bba061537e2de72f560b8c474f366201a2ab0, I assume it was
by mistake.
Right now it's super annoying, as I have to update the synoindex library manually after every single renaming done in Sonarr.

Reenabled calling synoindex after renaming

---

src/UI/Mixins/AsFilteredCollection.js
src/UI/Series/Index/SeriesIndexLayout.js
src/UI/Series/SeriesCollection.js

This pull request implements a new Series filtering option to the main "Series" index page. When selected, it lists only those series that have missing episodes (i.e. percentOfEpisodes < 100).
Since I had to implement the 'lt' filter operator for this, I went ahead and created 'gt', 'le', 'ge' and 'ne' as well, just for completeness sake.
I just used the "wrench" icon for the button, I figured I'd let someone else who has better design skills pick something more appropriate.

'missing' series episodes patch

---

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs

www.nzbfinder.ws redirects to https://nzbfinder.ws so changed that.

Updated NZBFinder URL

---

src/NzbDrone.Core.Test/DataAugmentation/Scene/SceneMappingServiceFixture.cs
src/NzbDrone.Core.Test/IndexerSearchTests/NzbSearchServiceFixture.cs
src/NzbDrone.Core/DataAugmentation/Scene/SceneMappingService.cs
src/NzbDrone.Core/IndexerSearch/NzbSearchService.cs
src/UI/Series/Details/EpisodeNumberCell.js
src/UI/Series/Details/SeriesDetailsLayout.js
src/UI/reqres.js

Xem scene naming exceptions are stored in the db as seasonNumber: null sceneSeasonNumber: x.
But for episodes without mapping Sonarr doesn't have a SceneSeasonNumber specified for the episode, so wouldn't use the naming exception.
This commit basically uses episode.SeasonNumber as episode.SceneSeasonNumber if none was specified.
I included several tests to check the specific behavior, in the hopes of not breaking it in the future.
I also adjusted the UI to show the alt title on the episode scene popout.

Fixed: XEM series with only alternate season titles.

---

src/NzbDrone.Core/Organizer/FileNameSampleService.cs

NO
Adds sample mediaInfo values for `VideoBitDepth` `AudioChannels` to be shown in the "Settings > Media Management" page.

Add VideoBitDepth & AudioChannels to mediaInfo sample.

---

src/NzbDrone.Console/ConsoleApp.cs

Minor fix to match input request in NzbDrone.Console/ConsoleApp.cs
Changed "Press any key to exit..." prompt to "Press enter to exit..."

Changed exit statement to "Press enter to exit..." to match use of ReadLine()

---

src/NzbDrone.Common/NzbDrone.Common.csproj
src/NzbDrone.Common/Security/SecurityProtocolPolicy.cs
src/NzbDrone.Core/Indexers/Newznab/Newznab.cs
src/NzbDrone.Host/Bootstrap.cs
src/NzbDrone.Host/Owin/OwinHostController.cs
src/NzbDrone.Update/UpdateApp.cs

NO
Support for TLS 1.1 and TLS 1.2 when making HTTP requests. SSL3 and TLS are also still supported, SSL3 should be dropped for security reasons, but left a note to do that in v3.

New: Support for TLS 1.1 and 1.2 connections when .net 4.5 is installed

---

src/LogentriesNLog/fastJSON/JSON.cs
src/LogentriesNLog/fastJSON/JsonSerializer.cs
src/NzbDrone.Common.Test/DiskTests/DiskTransferServiceFixture.cs
src/NzbDrone.Common/Disk/DiskTransferService.cs
src/NzbDrone.Update/NzbDrone.Update.csproj
src/NzbDrone.Update/UpdateApp.cs
src/NzbDrone.Update/UpdateEngine/BackupAndRestore.cs
src/NzbDrone.Update/UpdateEngine/BackupAppData.cs
src/NzbDrone.Update/UpdateEngine/DetectExistingVersion.cs
src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs

When emptying the install dir fails, due to permission issues, the rollback logic kicks in. But instead of just restoring the missing files, it rewrites everything and pukes over the same permission issue.
Usually this doesn't corrupt the install (coz it follows the same sequence), but it logs a Fatal twice.
So I changed it to a MirrorFolder function that compares source and target folders and files and applies only the changes required.
Also added the current version to the logging, so we know what the original version was and which version is being installed.
I didn't test it yet.

Updater fixes and logging

---

src/NzbDrone.Api/Calendar/CalendarFeedModule.cs
src/NzbDrone.Core.Test/Housekeeping/Housekeepers/CleanupUnusedTagsFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupUnusedTags.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Tags/TagRepository.cs
src/NzbDrone.Core/Tags/TagService.cs
src/UI/Calendar/CalendarFeedView.js
src/UI/Calendar/CalendarFeedViewTemplate.hbs
src/UI/Mixins/TagInput.js

Filter ical feed by tags. The UI uses the tag input, without the ability to add new tags.
It adds it as integers to the query params.
The feed endpoint supports both integers and tag labels.
Also added housekeeping logic to cleanup unused tags.

Filter iCal feed by tags

---

.gitignore
src/NzbDrone.Core.Test/Download/DownloadClientTests/UTorrentTests/UTorrentFixture.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentProxy.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentResponse.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentTorrentCache.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

Basically gets differential updates from the webui, without it utorrent api implementation gets serious performance hits when ppl have several hundred of torrents.

uTorrent differential api support

---

src/NzbDrone.Core.Test/HealthCheck/Checks/MonoVersionCheckFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/MonoVersionCheck.cs

NO
Health check warning if the user is running under 3.10 since that is our recommended minimum (as lower versions had various issues) and an error if running 4.4.x because it has a bug that breaks connecting to indexers/download clients

Upgraded mono version check (3.10 minimum and 4.4.x)

---

src/NzbDrone.Core/Notifications/Boxcar/BoxcarProxy.cs

NO
Now there is a small Sonarr icon next to the Boxcar notification.

Added Sonarr-icon to Boxcar notification

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core/Download/Clients/qBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/qBittorrent/QBittorrentPreferences.cs
src/NzbDrone.Core/Download/Clients/qBittorrent/QBittorrentProxy.cs
src/NzbDrone.Core/Download/Clients/qBittorrent/QBittorrentTorrent.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

NO
Track QBittorrent's configured `max_ratio`, and compare that against each torrent's `share_ratio` to determine whether the torrent has finished seeding. If it has, allow Sonarr to remove and delete the completed torrent.
* https://github.com/Sonarr/Sonarr/issues/1316

qbittorrent: allow removal of torrents that reached the configured max ratio

---

src/NzbDrone.Core.Test/Download/CompletedDownloadServiceFixture.cs
src/NzbDrone.Core.Test/MediaFiles/DownloadedEpisodesCommandServiceFixture.cs
src/NzbDrone.Core.Test/MediaFiles/DownloadedEpisodesImportServiceFixture.cs
src/NzbDrone.Core.Test/MediaFiles/ImportApprovedEpisodesFixture.cs
src/NzbDrone.Core/Download/CompletedDownloadService.cs
src/NzbDrone.Core/MediaFiles/Commands/DownloadedEpisodesScanCommand.cs
src/NzbDrone.Core/MediaFiles/DownloadedEpisodesCommandService.cs
src/NzbDrone.Core/MediaFiles/DownloadedEpisodesImportService.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportMode.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportCommand.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/UI/ManualImport/ManualImportLayout.js
src/UI/ManualImport/ManualImportLayoutTemplate.hbs

NO
- DownloadedEpisodesScan command now has an importMode=['Move','Copy'] property to override default behavior. It defaults to whatever CDH is saying about the downloadId. If no downloadId is supplied, 'Move' is used as default.
- Manual Import UI now has a dropdown to change the mode. Defaults to 'Move'.
- Activity->Queue->Force Import sets the initial value of the dropdown to whatever CDH is saying about the download (so effectively, seeding torrent defaults to 'Copy')
- https://github.com/Sonarr/Sonarr/issues/606

Added support to override Copy vs Move import logic for Manual Import

---

src/NzbDrone.Core/Organizer/FileNameBuilder.cs

NO
This shortens the  'MPEG-2 Video' to 'MPEG2' so when using the renamer, files look like;
`Land Girls - S01E01 - Childhood's End [DVD MPEG2 AC3 2.0].mkv`
vs.
`Land Girls - S01E01 - Childhood's End [DVD MPEG-2 Video AC3 2.0].mkv`

Shorten 'MPEG-2 Video' codec name to 'MPEG2' when renaming files.

---

src/NzbDrone.Core.Test/NotificationTests/NotificationBaseFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Notifications/Boxcar/Boxcar.cs
src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/Email/Email.cs
src/NzbDrone.Core/Notifications/Growl/Growl.cs
src/NzbDrone.Core/Notifications/Join/Join.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowser.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserService.cs
src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserSettings.cs
src/NzbDrone.Core/Notifications/NotificationBase.cs
src/NzbDrone.Core/Notifications/NotifyMyAndroid/NotifyMyAndroid.cs
src/NzbDrone.Core/Notifications/Plex/PlexClient.cs
src/NzbDrone.Core/Notifications/Plex/PlexHomeTheater.cs
src/NzbDrone.Core/Notifications/Plex/PlexServer.cs
src/NzbDrone.Core/Notifications/Prowl/Prowl.cs
src/NzbDrone.Core/Notifications/PushBullet/PushBullet.cs
src/NzbDrone.Core/Notifications/Pushalot/Pushalot.cs
src/NzbDrone.Core/Notifications/Pushover/Pushover.cs
src/NzbDrone.Core/Notifications/Slack/Slack.cs
src/NzbDrone.Core/Notifications/Synology/SynologyIndexer.cs
src/NzbDrone.Core/Notifications/Telegram/Telegram.cs
src/NzbDrone.Core/Notifications/Twitter/Twitter.cs

NO
Cleaned up some of the API making them less boiler platy!
Two main parts:
-  `SupportsOnGrab` `SupportsOnDownload` etc, is no longer needed in the implementation, it's dynamically determined at runtime based on whether the implementation has overridden the matching method.  🎩 
- We had 20 different version of `Sonarr - Grabbed` text all over the place, now it all comes from base class, there is still room to make it even more DRY, but requires digging into the proxies etc.

Notification API Cleanup

---

src/NzbDrone.Api/Calendar/CalendarFeedModule.cs
src/UI/Calendar/CalendarFeedView.js
src/UI/Calendar/CalendarFeedViewTemplate.hbs

NO
As a European watching mostly American shows, the iCal feed events all take place around midnight, which (in my case) is collapsed by default. Since I don't really care for the exact air time of each episode (it takes a while before they are available anyway), I would prefer the ability of having all-day events for each episode. 
The following toggle enables this feature.
* None. This was just a random idea that came up. Since it's not that intrusive, I thought I'd just propose it anyway.

Option to convert ical feed items to all-day events

---

src/NzbDrone.Core/Download/Clients/DownloadStation/DownloadStation.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationProxy.cs

NO
DS doesn't support deleting files when removing the torrent after it has finished seeding.
#1676

Delete data manually after finished seeding

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/TorrentDownloadStationFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/UsenetDownloadStationFixture.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/DownloadStationTask.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationProxy.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Responses/DiskStationError.cs

NO
Returns a generic error message if error-code is not in the dictionary.
#1700

Diskstation: Fix for key not found, returning a generic error instead

---

src/NzbDrone.Core.Test/Files/Indexers/TorrentRss/AlphaRatio.xml
src/NzbDrone.Core.Test/IndexerTests/TorrentRssIndexerTests/TorrentRssIndexerFixture.cs
src/NzbDrone.Core.Test/IndexerTests/TorrentRssIndexerTests/TorrentRssSettingsDetectorFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Indexers/RssParser.cs
src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssSettingsDetector.cs
src/NzbDrone.Core/Indexers/XmlCleaner.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

NO
I started this a couple weeks ago, but found a way around the RSS feed that was throwing the issues when checking for the appropriate feed. This furthers the cleanup of invalid characters for even shittier RSS feeds (look at that AlphaRatio mess of a feed), but could be useful on a feed that isn't a complete mess. I've added an AlphaRatio test that include unicode characters that will be stripped out, even though it has an abomination of a title.
* #1518

Clean RSS feed before detecting type

---

src/NzbDrone.Api/Series/SeasonResource.cs
src/NzbDrone.Api/Series/SeriesModule.cs
src/NzbDrone.Api/Series/SeriesResource.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core.Test/TvTests/AddSeriesFixture.cs
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Tv/AddSeriesService.cs
src/NzbDrone.Core/Tv/AddSeriesValidator.cs
src/NzbDrone.Core/Tv/Series.cs
src/NzbDrone.Core/Tv/SeriesService.cs
src/NzbDrone.Core/Tv/SeriesTitleSlugValidator.cs

NO
Removes the requirement to send the full JSON body (from `/series/lookup`) when adding a new series and requires only the basic information (so Sonarr knows where to put it and what quality to get it in).
Fixes #1403

Fixed: Reduce parameters required to add a new series

---

src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DiskStationProxyBase.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs

NO
User must set download station default destination up before trying to add the client to sonarr.
Fixed an infinite loop when handling authorization error.
And do not retry if user has not permission to use download station
#1720

Download Station - Added default destination test when adding client

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Extras/ExtraService.cs
src/NzbDrone.Core/Extras/Files/ExtraFileManager.cs
src/NzbDrone.Core/Extras/Metadata/MetadataService.cs
src/NzbDrone.Core/Extras/Others/OtherExtraService.cs
src/NzbDrone.Core/Extras/Subtitles/SubtitleService.cs
src/NzbDrone.Core/Parser/LanguageParser.cs
src/UI/Settings/MediaManagement/Sorting/SortingViewTemplate.hbs

NO
Importing of extra files (new option in the UI) and renaming them when the episode file is renamed.
Closes #459

Import and Rename Extra files

---

src/NzbDrone.Api/Frontend/Mappers/StaticResourceMapperBase.cs

NO
Wraps responses for static resources in [MaterialisingResponse](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Responses/MaterialisingResponse.cs) so the response is properly calculated before returning to the client and the logs should the correct response (and `OnError` handling works in the pipeline).
PRed such a simple change because there is a warning on `MaterialisingResponse` and while our responses aren't for giant files I wanted to play it safe.

Use MaterialisingResponse for static resource responses

---

src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DiskStationProxyBase.cs

NO
As it seems guid is causing some troubles i think we should get back to "DownloadStation" for the session name. Just tried here with filestation api and it's working fine.
* #1786, #1784

DownloadStation - Revert Session name

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/DelugeTests/DelugeFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/TorrentDownloadStationFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/UsenetDownloadStationFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/TransmissionTests/TransmissionFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/UTorrentTests/UTorrentFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/VuzeTests/VuzeFixture.cs
src/NzbDrone.Core.Test/HistoryTests/HistoryServiceFixture.cs
src/NzbDrone.Core.Test/MediaFiles/ImportApprovedEpisodesFixture.cs
src/NzbDrone.Core/Download/Clients/Blackhole/TorrentBlackhole.cs
src/NzbDrone.Core/Download/Clients/Blackhole/UsenetBlackhole.cs
src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs
src/NzbDrone.Core/Download/Clients/Hadouken/Hadouken.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortex.cs
src/NzbDrone.Core/Download/Clients/Nzbget/Nzbget.cs
src/NzbDrone.Core/Download/Clients/Pneumatic/Pneumatic.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs
src/NzbDrone.Core/Download/DownloadClientItem.cs
src/NzbDrone.Core/Download/DownloadEventHub.cs
src/NzbDrone.Core/Download/TrackedDownloads/DownloadMonitoringService.cs
src/NzbDrone.Core/MediaFiles/DownloadedEpisodesImportService.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs
src/NzbDrone.Core/MediaFiles/Events/EpisodeImportedEvent.cs

NO
This PR is to separate the logic behind IsReadOnly. This flag is used to indicate when the item can be imported and when can it be removed from the client. It a WIP, so i'm open to suggestions...
* #1764

 Split isReadOnly up into CanBeRemoved and CanMoveFiles in DownloadClientItem 

---

src/NzbDrone.Common/NzbDrone.Common.csproj
src/NzbDrone.Common/packages.config

NO
Updating SocksWebProxy to version 1.3.4 to fix the issues discovered in #1641 
None
* #1641

Update SocksWebProxy to fix #1641

---

src/UI/index.html
src/UI/login.html

NO
Since we already use the recommended way of sending down the `X-UA-Compatible` http header we don't need the meta tag as well.

remove redundant IE meta tag as we use http header instead

---

src/NzbDrone.Core.Test/DataAugmentation/Scene/SceneMappingServiceFixture.cs
src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/GetEpisodesFixture.cs
src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/MapFixture.cs
src/NzbDrone.Core/DataAugmentation/Scene/InvalidSceneMappingException.cs
src/NzbDrone.Core/DataAugmentation/Scene/SceneMapping.cs
src/NzbDrone.Core/DataAugmentation/Scene/SceneMappingService.cs
src/NzbDrone.Core/Datastore/Migration/112_added_regex_to_scenemapping.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Parser/Model/ParsedEpisodeInfo.cs
src/NzbDrone.Core/Parser/Parser.cs
src/NzbDrone.Core/Parser/ParsingService.cs
src/NzbDrone.Core/Tv/SeriesService.cs

YES: 112
- First is adding a FilterRegex field to SceneMapping. If it's not-null then the regex is used against the releaseTitle. In order to make that happen I needed to make sure the releaseTitle was passed through from the various places.
Along the way did some cleanup (SeriesService no longer has a ref to SceneMapping, ParsingService does that.)
- Second is dealing with potential duplicates. Atm I throw if there are conflicting scenemappings. Although one with regex will never conflict with one without regex.
The idea is that if you add a mapping to services that for example maps a scene name without year to a tvdb name with year, that you'll ALSO add the original non-year tvdb series 'mapping' unless the original has no scene releases. That way Sonarr is aware that there's a dupe. …

Added ability to filter scene mappings by regex via services.

---

src/NzbDrone.Common/Disk/DriveInfoMount.cs
src/NzbDrone.Common/Disk/IMount.cs
src/NzbDrone.Common/Disk/MountOptions.cs
src/NzbDrone.Common/NzbDrone.Common.csproj
src/NzbDrone.Core/HealthCheck/Checks/MountCheck.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Mono/Disk/DiskProvider.cs
src/NzbDrone.Mono/Disk/ProcMount.cs
src/NzbDrone.Mono/Disk/ProcMountProvider.cs

NO
Adds a health check to determine if any series targets a mount that is currently read-only.
* #1867

Health Check - Mount Read-Only

---

src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatAudioChannelsFixture.cs
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatAudioCodecFixture.cs
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatVideoCodecFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoModel.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

Fixed: Stream details for MP3 and EAC3 in Kodi metadata
Closes #1534
NO
This will allow us to consistently format MediaInfo in various locations as well as expose in on the API with the same consistency. There is a bit of duplication everywhere this is used right now, we could either add additional properties to the `MediaInfoModel` and always format them when returning them or only do that in the API module and leave the rest as-is. Even if we did it when returning the `EpisodeFile`s we'd still need to handle the case when importing a new episode file. Thoughts?
* #1534

Consistent formatting for MediaInfo in various locations

---

src/NzbDrone.Api/EpisodeFiles/EpisodeFileModule.cs
src/NzbDrone.Core.Test/MediaFiles/MediaFileDeletionService/DeleteEpisodeFileFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/MediaFiles/MediaFileDeletionService.cs
src/NzbDrone.Core/MediaFiles/RecycleBinProvider.cs
src/NzbDrone.Core/NzbDrone.Core.csproj
src/UI/Cells/DeleteEpisodeFileCell.js
src/UI/EpisodeFile/Editor/EpisodeFileEditorLayout.js

NO
This improves the deleting of episode files and a small refactor to deleting episode files after a series is deleted.
There are a few rules (consistent with rescanning a series folder):
- If the root folder for a series is missing or empty the file will not be deleted from the DB
- If only the series folder or the episode file is missing the file will be deleted from the DB
- If the file exists on disk we'll delete it from disk and then the DB
* #1782

Deleting Episode Files that no longer exist on disk

---

src/UI/EpisodeFile/Editor/EpisodeFileEditorLayoutTemplate.hbs

NO
Move the delete button on the Episode File Editor to the left. The button being on the right, next to the close button makes it seem like it is a 'continue' or 'apply changes' button.

EpisodeFileEditorLayoutTemplate - Move Delete button to the left

---

src/NzbDrone.Api/Extensions/Pipelines/UrlBasePipeline.cs
src/NzbDrone.Api/Frontend/StaticResourceModule.cs
src/NzbDrone.Api/NzbDrone.Api.csproj

NO
Currently if a user has set a URL Base of `/sonarr` and then hits `localhost:8989` they're redirected to the login page at `localhost:8989/sonarr/login?returnUrl=/` and when they login they get redirected back to the login page because the cookie is stored on `/sonarr` not `/`. This hook needs to execute before the forms auth login hook.

Redirect calls missing URL Base

---

src/NzbDrone.Core.Test/MediaFiles/DownloadedEpisodesImportServiceFixture.cs
src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/DetectSampleFixture.cs
src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/ImportDecisionMakerFixture.cs
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/VideoFileInfoReaderFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/MediaFiles/DownloadedEpisodesImportService.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/DetectSample.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/DetectSampleResult.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/NotSampleSpecification.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

NO
Turns out we haven't fallen back to file size to determine if a file is a sample for a long time (years maybe?), so I've fixed the glitch and also improved what Sonarr logs/reports when getting the mediainfo fails completely.
* #1967

Better handling when MediaInfo is not available

---

src/NzbDrone.Mono/Disk/DiskProvider.cs

NO
Removes the handling of `InvalidOperationException`s in Mono `DiskProvider`. This way suppress warnings actually works when Sonarr doesn't have access.
* #1993

Fixed: Logging error when accessing mount point

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxy.cs

NO
I noticed that the naming of "qBittorrent" in exception/log messages is a little inconsistent. This updates all the references to the correct name of the application.

Fix inconsistent naming of qBittorrent

---

src/UI/Settings/UI/UiViewTemplate.hbs

NO
Since the day and month numbers were both lower than 12 you couldn't tell which was which.  
I changed the day number to 25 because it very obviously couldn't be a month number and has the added bonus of actually being a tuesday (that was actually a coincidence :D).

Made date format options more descriptive

---

src/NzbDrone.Api/Calendar/CalendarFeedModule.cs

NO
Provides a default name for the Sonarr.ics when added as its own calendar to an application that supports iCal. I thought this would be better than using the long URL path which is currently used because nothing else is set.
It appears both the `NAME` and `X-WR-CALNAME` are used for this purpose, they are however both non-standard and not in the RFC, which is why they have to be added as properties.

Add default calendar name for iCal

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs

NO
Changes the default port set when setting up uTorrent or qBittorrent as a download client.
* uTorrent sets `8080` as the alternative port WebUI port by default.
* qBittorrent uses `8080` as the default port.

Change default port of uTorrent and qBittorrent

---

src/NzbDrone.Core/Notifications/Telegram/TelegramService.cs

Fixes #2249
Switched parse_mode to html and used html encoding. But someone needs to test if the `<b>abc</b><br/>message` syntax works. I'm mostly concerned about the `<br/>` since there are different conventions for that one.

Telegram notification with underscore and other special characters

---

src/NzbDrone.Common/Disk/DiskProviderBase.cs
src/NzbDrone.Mono.Test/DiskProviderTests/DiskProviderFixture.cs
src/NzbDrone.Mono/Disk/DiskProvider.cs

Based on the IRC chat with Ingram.
Mono doesn't properly move/copy symlinks if they're not on the same filesystem. And instead copies the content.
This PR patches that logic in the DiskProvider. It should also properly handle relative symlinks.
I've also added a check in TryCreateHardlink so that it doesn't try hardlink a symlink, I don't think that would actually ever hardlink but better safe than sorry.
This should make some scenarios work better for the Move/hardlink/symlink issue that's been lingering.

Mono internals does not properly copy/move symlinks

---

src/NzbDrone.Core.Test/Download/TrackedDownloads/TrackedDownloadServiceFixture.cs
src/NzbDrone.Core.Test/ParserTests/IsPossibleSpecialEpisodeFixture.cs
src/NzbDrone.Core.Test/TvTests/EpisodeServiceTests/FindEpisodeByTitleFixture.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs
src/NzbDrone.Core/Parser/Model/ParsedEpisodeInfo.cs
src/NzbDrone.Core/Parser/Parser.cs
src/NzbDrone.Core/Parser/ParsingService.cs
src/NzbDrone.Core/Tv/EpisodeService.cs

Pretty old issue about E00 actually being Specials.
@markus101  I'm not sure if there could be bad consequences of this change. So a PR first.
The Sense8 edge-case with episode shift seems to work because it doesn't actually manage to work out which special it is and thus fall back to the normal logic.
Issue https://github.com/Sonarr/Sonarr/issues/1872

Consider all scene SxxE00 releases Specials as well.

---

src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs

NO
Add missing error check when adding a magnet link to deluge. The same error check is already present for adding from a file, just not a magnet.

Add missing error check when adding a magnet link to deluge

---

src/NzbDrone.Core/Download/Clients/DownloadStation/Responses/DiskStationError.cs

NO
If the user account used to access to DSM doesn't have privileges to use FileStation we get 160 as errorcode. This adds the description to let the user know what is happening
#1758 1758

Added errorcode 160 - Permission denied on FileStation

---

src/NzbDrone.Core.Test/ParserTests/AbsoluteEpisodeNumberParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
This commit fixes wrongly parsed episodes that have a # in from of their absolute number
```
[Shark-Raws] Crayon Shin-chan #957 (NBN 1280x720 x264 AAC).mp4
```
Previously parsed to:
Crayon Shin-chan S9E57 (Abs somewhere in the 3xx)
Now parses to:
Crayon Shin-chan S27E07 (Abs 957)

Add fix for # in front of absolute numbers

---

src/NzbDrone.Core.Test/TvTests/SeriesTitleNormalizerFixture.cs
src/NzbDrone.Core/Tv/SeriesTitleNormalizer.cs

https://forums.sonarr.tv/t/a-p-bio-sorting-under-p/17959
- Added sorting for "A.P. Bio"
- Added unit test
- Removed name normalization for series which was deleted on thetvdb

Fixed: sorting for series "A.P. Bio"

---

src/NzbDrone.Core.Test/Extras/Metadata/Consumers/Roksbox/FindMetadataFileFixture.cs
src/NzbDrone.Core.Test/Extras/Metadata/Consumers/Wdtv/FindMetadataFileFixture.cs
src/NzbDrone.Core.Test/Extras/Metadata/Consumers/Xbmc/FindMetadataFileFixture.cs
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core/Extras/ExtraService.cs
src/NzbDrone.Core/Extras/Files/ExtraFileService.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcNfoDetector.cs
src/NzbDrone.Core/Extras/Metadata/Files/MetadataFileService.cs
src/NzbDrone.Core/Extras/Metadata/MetadataService.cs
src/NzbDrone.Core/Extras/Others/OtherExtraFileRenamer.cs
src/NzbDrone.Core/Extras/Others/OtherExtraService.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

NO
- Recycle Metadata files on episode removal, instead of permanently deleting them.
- Import nfo 'other' files as 'nfo' instead of 'nfo-orig'.
- On import existing the Kodi metadata provider will check if the .nfo is xml, and only mark if as EpisodeMetadata if that's the case. (leaving it to OtherFiles to pick up the scene nfo)
- On Kodi metadata generation, the existing .nfo OtherFile will be renamed to .nfo-orig.
- Bonus: Kodi metadata generation refresh will preserve 'watched' flag if possible, but not on episode upgrades.
The end result is that if kodi metadata is disabled, scene .nfo files will be treated as scene nfo and kept intact.
* closes #2398
* closes #932
* ref #991

Improve Kodi Metadata provider handling of scene nfo files

---

src/UI/AddSeries/AddSeriesView.js

Searching for a movie by name copy-pasted from somewhere looks like common scenario, and search is not triggered when text got pasted into input.
'Input' event works better then 'keyup' as it got triggered upon _any_ change of input's value (keypress, paste, text drag-n-drop).

changed: which event handler triggers movie search

---

src/NzbDrone.Api/Commands/CommandModule.cs
src/NzbDrone.Common/Extensions/IEnumerableExtensions.cs
src/NzbDrone.Core.Test/Download/DownloadApprovedReportsTests/DownloadApprovedFixture.cs
src/NzbDrone.Core.Test/IndexerSearchTests/NzbSearchServiceFixture.cs
src/NzbDrone.Core/Datastore/DbFactory.cs
src/NzbDrone.Core/Datastore/Migration/120_update_series_episodes_history_indexes.cs
src/NzbDrone.Core/DecisionEngine/Specifications/AcceptableSizeSpecification.cs
src/NzbDrone.Core/Download/Pending/PendingReleaseService.cs
src/NzbDrone.Core/Download/ProcessDownloadDecisions.cs
src/NzbDrone.Core/IndexerSearch/Definitions/DailySeasonSearchCriteria.cs
src/NzbDrone.Core/IndexerSearch/NzbSearchService.cs
src/NzbDrone.Core/Indexers/BitMeTv/BitMeTvRequestGenerator.cs
src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetRequestGenerator.cs
src/NzbDrone.Core/Indexers/Fanzub/FanzubRequestGenerator.cs
src/NzbDrone.Core/Indexers/HDBits/HDBitsRequestGenerator.cs
src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
src/NzbDrone.Core/Indexers/IIndexer.cs
src/NzbDrone.Core/Indexers/IIndexerRequestGenerator.cs
src/NzbDrone.Core/Indexers/IPTorrents/IPTorrentsRequestGenerator.cs
src/NzbDrone.Core/Indexers/IndexerBase.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
src/NzbDrone.Core/Indexers/Nyaa/NyaaRequestGenerator.cs
src/NzbDrone.Core/Indexers/Omgwtfnzbs/OmgwtfnzbsRequestGenerator.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgRequestGenerator.cs
src/NzbDrone.Core/Indexers/RssIndexerRequestGenerator.cs
src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssIndexerRequestGenerator.cs
src/NzbDrone.Core/Indexers/Torrentleech/TorrentleechRequestGenerator.cs
src/NzbDrone.Core/Messaging/Events/EventAggregator.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

**YES** 120 - Replace/add db indexes
A season search for a daily show used to simply do a 'standard' season search, which only works if the show uses years as seasons.
This change adds a DailySeasonSearchCriteria that groups by the year in the airdate and performs searches for those.
Possible side-effect I just realised is that Jackett might not handle the format.
This PR also includes half a dozen performance improvements:
Test method: With no download client I queried 1 daily show season that caused 1416 releases to be added to the pending queue.Subsequently all indexers were disabled, which causes the RssSync to only evaluate the pending releases.
The following measurements of cumulative improvements. The biggest improvement by far is sqlite initialization env vars.
Original: 47.5 sec …

Daily season search

---

src/NzbDrone.Core/Download/Clients/Transmission/TransmissionProxy.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionTorrent.cs
src/NzbDrone.Core/Download/Clients/Vuze/Vuze.cs

NO
Better handling of multi-file torrents in Vuze where the folder doesn't match the name.
* #2571

Fixed: Multi-file torrents in Vuze with different folder and file names

---

osx/Sonarr

NO
By default, Homebrew installs mono to `/usr/local/bin`. However, when starting Sonarr, it does not appear to have this path as part of its `$PATH`, which results in Sonarr prompting the user to, incorrectly, install Mono via the “official” installer, even though it’s already installed.
Adding this check ensures that the right `$PATH` additions are made for a Homebrew-installed copy of mono.
* None

Add compatibility w/ Hombrew-installed mono

---

src/NzbDrone.Core/Notifications/Join/JoinPriority.cs
src/NzbDrone.Core/Notifications/Join/JoinProxy.cs
src/NzbDrone.Core/Notifications/Join/JoinSettings.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

NO
A small change to the Join notification service to allow for various priority levels to be selected. This way you can send join notifications to your phone without it vibrating every time. This functions similarly to the pushover notification service's priority levels. 
None

New: Added priority levels to Join Notifications

---

package.json

NO
gulp-livereload 4.0.0 transitively depends on a range of versions of flatmap-stream some of which are known to be vulnerable. See https://github.com/dominictarr/event-stream/issues/116. While the malicious code doesn't appear to target software like sonarr, particularly in dev it would be nice not to depend on known malicious code (if already cached) or a package that no longer exists (flatmap-stream is now unpublished).
N/A
< none >

Prevent flatmap vulnerability

---

src/NzbDrone.Common/Extensions/StringExtensions.cs
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatAudioCodecFixture.cs
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/VideoFileInfoReaderFixture.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoModel.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs

NO
After discussions in the original issue that started all this, I decided to start a new branch and bring in the changes for media info from radarr first.
This pull request is for that work. I've updated `MediaInfoModel` to include the additional properties and `MediaInfoFormatter` to match the code in Radarr with the additional audio codec formatting.
I also added tests for the audio codec formatting to cover the additional audio features.  Where possible I took the values from media files that I found that were all tv episodes, rather than movies
*

Update media info from Radarr

---

src/NzbDrone.App.Test/NzbDrone.Host.Test.csproj
src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core.Test/ParserTests/UnicodeReleaseParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs
src/NzbDrone.Integration.Test/NzbDrone.Integration.Test.csproj

NO
Follow up https://github.com/Sonarr/Sonarr/pull/2904#issuecomment-459064953
+ Replace black lenticular brackets to square brackets
+ Remove `END` postfix after anime's absolute episode number
+ Remove separators before English title
*  #2898

Support anime release with title and episode number in brackets

---

.npmrc
.yarnrc
yarn.lock

NO
event-stream@3.3.6 has backdoor in it: 
https://snyk.io/blog/a-post-mortem-of-the-malicious-event-stream-backdoor/
https://github.com/dominictarr/event-stream/issues/115
https://github.com/dominictarr/event-stream/issues/116
Since npm has already unpublished event-stream@3.3.6 and flatmap-stream, running `yarn` on a fresh copy of Sonarr would result in 404 error.
Removed `.npmrc` file because (AFAIK) the current workflow uses yarn
*

Downgrade event-stream

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Removes 'WhiteRev' and 'BUYMORE' suffixes from release group names. These type of release names exist in multiple usenet indexers. 
Examples:
- `Deadly.Class.S01E10.Sink.With.California.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG-WhiteRev`
-  `The.Walking.Dead.S09E12.Guardians.REPACK.1080p.AMZN.WEB-DL.DD.5.1.H.264-CasStudio-BUYMORE`
Tested these on a local build.
* n/a

Parser: Remove 'WhiteRev'/'BUYMORE' suffixes from release group names.

---

src/NzbDrone.Core/Extras/Metadata/Consumers/Roksbox/RoksboxMetadata.cs

NO
When Series has no images, Roksbox series images handling will return null instead of a blank list, this results in NullRef at `MetadataService.cs` Line 290. Return empty list instead of null like other consumers.

Fixed: Roksbox no Series images can lead to NullRef

---

src/NzbDrone.Mono/Disk/FindDriveType.cs

NO
Currently mergerfs filesystems are not shown on the system page. This pull request adds support for it via the drive FindDriveType exception list (only a guess maybe it's not that) because it does not show up in `/proc/filesystems`.

Add support to detect mergerfs mounts

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Remove 'AsRequested' suffix from release group names.
Various indexers have a ton of these releases that end with `-AsRequested` and it get's chosen as the release group during import.
Examples:
- `2.Broke.Girls.S02E24.1080p.AMZN.WEBRip.DD5.1.x264-CasStudio-AsRequested.mkv`
-  ` Love.Death.and.Robots.S01E12.Fish.Night.720p.NF.WEB-DL.DDP5.1.x264-NTG-AsRequested.mkv`
N/A

Remove 'AsRequested' suffix from release group names.

---

src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs
src/NzbDrone.Core/Download/Clients/Deluge/DelugeProxy.cs
src/NzbDrone.Core/Download/Clients/Deluge/DelugeSettings.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentLabel.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV1.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentProxy.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentProxy.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs
src/NzbDrone.Core/Download/CompletedDownloadService.cs
src/NzbDrone.Core/Download/DownloadClientBase.cs
src/NzbDrone.Core/Download/DownloadEventHub.cs
src/NzbDrone.Core/Download/IDownloadClient.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

NO (not sure if anything needs to be done with the database tbh)
Allows download clients to set a label after a successful import provided that the SetLabel method is overridden (currently only done for Deluge).
* #2469 (kind-of... only implemented for deluge currently. Not sure what other download clients have the current supporting code). 
Right now it's only setting the label after a successful auto import post-download. I'm not sure how things work if Sonarr fails to import the release automatically, and the user later manually has to import the donwload or where in the code this happens.

Set post-import label for deluge

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/TransmissionTests/TransmissionFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/TransmissionTests/TransmissionFixtureBase.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/VuzeTests/VuzeFixture.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionConfig.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionProxy.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionTorrent.cs
src/NzbDrone.Core/NzbDrone.Core.csproj

NO
Revises the Transmission Seed Criteria detection.
The torrent will be eligible for removal if:
- If a per-torrent or global ratio is set and reached. And the Torrent status is 'Stopped'.
- If a per-torrent idle-limit is set, and seed time (not idle-time) is larger than that. Torrent status must be 'Stopped' or 'Seeding'.
- If a per-torrent idle-limit is not set, but a global one is. Then if torrent status is 'Stopped'.
The is largely a workaround to transmission not providing the idle-limit and/or not having a seed time limit.
The per-torrent idle-limit is likely set _by_ sonarr and treated as a seed time limit. The global idle limit is not set by sonarr and treated as idle limit, but since it cannot be verified the only criteria is that it must be Stopped.
Fixes #2807

Transmission Seed Idle Limit handling

---

frontend/src/Components/Form/EnhancedSelectInput.js
frontend/src/Components/Form/EnhancedSelectInputOption.css
frontend/src/Components/Form/FormInputGroup.css
frontend/src/Components/Form/FormInputGroup.js
frontend/src/Components/Form/HintedSelectInputOption.css
frontend/src/Components/Form/HintedSelectInputOption.js
frontend/src/Components/Form/HintedSelectInputSelectedValue.css
frontend/src/Components/Form/HintedSelectInputSelectedValue.js
frontend/src/Settings/DownloadClients/RemotePathMappings/EditRemotePathMappingModalContent.js
frontend/src/Settings/DownloadClients/RemotePathMappings/EditRemotePathMappingModalContentConnector.js
frontend/src/Settings/MediaManagement/Naming/Naming.js

For Remote Path Mappings i wanted to show which download clients a particular host was used for. Instead of a simply auto-complete or dropdown.
Most select inputs use the SelectInput browser control, rather than the more stylish EnhancedSelectInput.
There are some reasons to prefer SelectInput, mostly the visualisation on mobile, but I felt that switching to Enhanced globally looks good.
Before and after on desktop:
After for mobile:
Some fixes along the way:
- On Chrome you had to click twice on a option for it to be selected. (not on firefox)
- Tap outside of the modal content on mobile didn't cancel it
- hover color overrode the selected color which looked weird
- overflow wasn't handled properly in nested flex components (fix is min-width: 0)

Hinted EnhancedSelectInput instead of SelectInput and Remote Path Mapping Host

---

src/NzbDrone.Core.Test/NzbDrone.Core.Test.csproj
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/TruncatedEpisodeTitlesFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

NO
Limits file name sections to 255 characters (accounting for season or episode folders being part of the episode naming format). 
- If the title is acceptable it is returned as-is
- If there are more than 2 episode titles, attempt to return the first and last titles with an ellipsis between them
- Otherwise try to return the first title
- Finally return a partial title
There is an edge case where only an ellipsis could be returned, but the odds of that seem pretty low.
* #2699

New: Limit filenames to a maximum of 255 characters

---

src/NzbDrone.Core.Test/ParserTests/UnicodeReleaseParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Lilith-Raws is a new Chinese anime release group, and they don't use brackets for series name.
*

New: Add support for Lilith-Raws release group

---

frontend/src/Settings/MediaManagement/MediaManagement.js
src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/Specifications/FreeSpaceSpecificationFixture.cs
src/NzbDrone.Core/Configuration/ConfigService.cs
src/NzbDrone.Core/Configuration/IConfigService.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/FreeSpaceSpecification.cs
src/Sonarr.Api.V3/Config/MediaManagementConfigModule.cs
src/Sonarr.Api.V3/Config/MediaManagementConfigResource.cs

NO
Allow user to configure the minimum amount of disk space available after import instead of using a fixed 100 megabyte value.
#3233

User configurable minimum free disk space

---

src/NzbDrone.Core/Download/Clients/Deluge/DelugeSettings.cs

NO
Deluge's Label plugin allows digits, but the client's category fields in Sonarr do not.

Allow digits in Deluge categories

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

NO
The state 'moving' wasn't being recording in Radarr, so it would show up as a warning.

Added qBittorent state 'moving'

---

src/NzbDrone.Core.Test/Datastore/Migration/128_rename_quality_profiles_add_upgrade_allowedFixture.cs
src/NzbDrone.Core/Datastore/Migration/128_rename_quality_profiles_add_upgrade_allowed.cs

Workaround in migration 128 that detects if early Radarr version hijacked the 111 migration, if so then the 111 migration is reapplied.

Fixed: Rare scenario where early Radarr version messes up Sonarr database

---

src/NzbDrone.Common.Test/OsPathFixture.cs
src/NzbDrone.Common/Disk/OsPath.cs

NO
Fixes the problem with double / characters not parsing correctly.
#3470

Fixed: Replace duplicate slashes from file names when importing

---

build.sh

NO
I tried to build on Linux and ran into this error:
> The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format. 
This was fixed by replacing the deprecated xbuild with msbuild.
fixes issue #2553
*

Use msbuild, xbuild is deprecated and does not work anymore

---

src/NzbDrone.Common/Http/Proxy/IHttpProxySettingsProvider.cs
src/NzbDrone.Core/Http/HttpProxySettingsProvider.cs
src/NzbDrone.Core/Notifications/Boxcar/BoxcarProxy.cs
src/NzbDrone.Core/Notifications/Gotify/GotifyProxy.cs
src/NzbDrone.Core/Notifications/Join/JoinProxy.cs
src/NzbDrone.Core/Notifications/PushBullet/PushBulletProxy.cs
src/NzbDrone.Core/Notifications/Pushover/PushoverProxy.cs
src/NzbDrone.Core/Notifications/Telegram/TelegramService.cs
src/NzbDrone.Core/Notifications/Xbmc/XbmcJsonApiProxy.cs
src/NzbDrone.Core/Rest/IRestClientFactory.cs
src/NzbDrone.Core/Rest/RestClientFactory.cs

NO
Telegram is blocked in Russian Federation, but it works using proxy server. But `TelegramProxy` wasn't using global proxy settings.
Test that connection goes through proxy server.
* https://github.com/Sonarr/Sonarr/issues/3521

Fixed: RestClient does not use global proxy settings

---

src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNet.cs

No
This changes ``BroadcastheNet`` to ``BroadcasTheNet``, per site.

BTN: Fix name

---

frontend/src/Helpers/Props/icons.js
frontend/src/Settings/MediaManagement/Naming/NamingModal.css
frontend/src/Settings/MediaManagement/Naming/NamingModal.js
frontend/src/Settings/MediaManagement/Naming/NamingOption.css
frontend/src/Settings/MediaManagement/Naming/NamingOption.js
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs
src/NzbDrone.Core/Parser/IsoLanguages.cs

NO
Definitely a 1% feature.
@markus101 We talked about this and I think it would still be better to filter by language profile or something, but I feel like there's more edgecases there and harder to implement.
Allow `{MediaInfo SubtitleLanguages:EN+DE}` custom format to influence formatter:
- `:EN+DE` filters out all except EN and DE (the order here determines the output order too)
- `:-DE-NO` filters out DE and NO
- `:EN+DE+` (trailing + ) will replace any unlisted languages with `--`, so a file with `EN+NL+NO` would become `[EN+--]` (not sure about this one)
Formats work for AudioLanguages, AudioLanguagesAll and even Full. For Full it'll eliminates any possible future formatting for the codec/etc stuff that's in Full, but that's not a big issue imo.
Finally I'm also not sure about how …

Add ability to filter languages in MediaInfo formatter

---

src/NzbDrone.Core/Notifications/MediaBrowser/MediaBrowserSettings.cs
src/NzbDrone.Core/Notifications/Plex/HomeTheater/PlexHomeTheaterSettings.cs
src/NzbDrone.Core/Notifications/Xbmc/XbmcSettings.cs

NO
The help text in some Connections dialogs was changed in v3 from "On Download" to a more accurate "On Import", but the associated "Update Library" text was not changed so it is inconsistent.
*

Update help text in Connections from Download to Import

---

distribution/debian/control
distribution/debian/postinst
distribution/debian/rules
distribution/docker-build/Dockerfile
docker/tests/mono/sonarr/Dockerfile
docker/tests/run-all.sh
setup/sonarr.iss
src/NzbDrone.Core.Test/HealthCheck/Checks/DotnetVersionCheckFixture.cs
src/NzbDrone.Core.Test/HealthCheck/Checks/MonoVersionCheckFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/DotnetVersionCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/MonoVersionCheck.cs
src/NzbDrone.Core/Lifecycle/ApplicationStartingEvent.cs
src/NzbDrone.Core/Update/InstallUpdateService.cs
src/NzbDrone.Host/ApplicationServer.cs
src/NzbDrone.Mono/Disk/DiskProvider.cs

NO
- Mono 6 workaround for the copy/filesystem issue. untested
- Copied over the framework version checks from the phantom-x64 branch to ensure ppl start moving over
- Increased debian package dependency for mono to 5.18
- Now actually doing something with the `update_required` file that was created by the debian package to force an early update check. (necessary to avoid database schema downgrade issues)

Mono 6 patch, updated framework checks to 4.7.2/mono 5.18 and post-install update check

---

frontend/src/Components/Filter/Builder/FilterBuilderRowValue.js
frontend/src/Components/Form/TagInput.js
frontend/src/Settings/Profiles/Release/EditReleaseProfileModalContent.js

NO
While in QWERTY `keyCode` for comma is 188, in Cyrillic layout
same `keyCode` represents regular letter. It's better idea to look
for a `key` instead, which is consistent between keyboard layouts

Fixed: Tag inputs respect non-QWERTY layouts

---

frontend/src/Episode/SceneInfo.js
src/NzbDrone.Core.Test/DecisionEngineTests/Search/SingleEpisodeSearchMatchSpecificationTests/StandardEpisodeSearch.cs
src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/GetEpisodesFixture.cs
src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/MapFixture.cs
src/NzbDrone.Core/DataAugmentation/Scene/SceneMappingService.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs
src/NzbDrone.Core/DecisionEngine/Specifications/Search/SeasonMatchSpecification.cs
src/NzbDrone.Core/DecisionEngine/Specifications/Search/SingleEpisodeSearchMatchSpecification.cs
src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs
src/NzbDrone.Core/IndexerSearch/NzbSearchService.cs
src/NzbDrone.Core/Indexers/IndexerPageableRequestChain.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
src/NzbDrone.Core/Parser/ParsingService.cs

NO
Mixed a few changes together
- nzedb can return a newznab api error result when downloading .nzb, detect that and produce readable error
- Newznab/Torznab will now _also_ search by title and mapped season number for SceneMappings where both SeasonNumber and SceneSeasonNumber is specified. Examples are Spartacus and Cosmos.
Parser will no longer produce Wrong season in that scenario either
This means that such episodes are now also searchable, rather than only parseable on rss
- Display the SceneSeasonNumber on the UI when specified
- Bonus feature for Jackett: If they specify `title` as supported query parameter, we'll use that instead of `q` for single/season/daily searches with the original series title (or scene title), rather than the newznab cleaned one. I didn't discuss this with …

Phantom search improvements

---

frontend/src/Settings/MediaManagement/Naming/Naming.js

NO
The prior help text made it seem like the setting would be required to both replace or remove illegal characters; however, it seems to be specifically meant for replacing those characters. If unchecked, then will Sonarr removes those characters rather than replacing them. I tried to clarify it in the help text, though if there's clearer language, that would be even better.
The current language is very confusing and misleading though.
*

Fixed: Indicate unchecking Replace Illegal Characters will remove them

---

src/NzbDrone.Core/Jobs/TaskManager.cs
src/NzbDrone.Core/Update/Commands/ApplicationUpdateCheckCommand.cs
src/NzbDrone.Core/Update/InstallUpdateService.cs

NO
Splits the update command to ApplicationUpdate and ApplicationUpdateCheck. This will prevent the command queue from being locked down due to the isExclusive ApplicationUpdateCommand if the update command is awaiting something else to finish... especially for cases when we skip updates anyway.

Fixed: Don't lock command queue if updating is disabled

---

distribution/debian/rules
src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs
src/NzbDrone.Console/ConsoleApp.cs
src/NzbDrone.Console/Sonarr.Console.csproj
src/Sonarr.RuntimePatches/Mono/BoringTLSVerifyFlagsPatch.cs
src/Sonarr.RuntimePatches/Mono/DeflateStreamAsyncPatch.cs
src/Sonarr.RuntimePatches/MonoRuntimePatchBase.cs
src/Sonarr.RuntimePatches/RuntimePatchBase.cs
src/Sonarr.RuntimePatches/RuntimePatchExtensions.cs
src/Sonarr.RuntimePatches/RuntimePatcher.cs
src/Sonarr.RuntimePatches/Sonarr.RuntimePatches.csproj
src/Sonarr.sln

NO
I wrote the Monkey Patch logic for DeflateStream somewhere last year but never merged it in.
It uses the Harmony library which can be used to patch any library/runtime function.
I'm still not sure whether monkey patching is a good idea, but it'd allow us to deal with more mono internal issues selectively.
The entire logic can be disabled via a `DISABLE_RUNTIMEPATCHES=1` environment variable, just to be safe so we can give the user a mechanism to disable it if it goes awry. Even though there are a ton of validation logic embedded in the patches.
The specific patch for certificate validation is to inject an updated VerifyParam flags to enable openssl/boringssl trust-first option.
The only alternative i can think of is dealing with it in `X509CertificateValidationService`, but that …

Monkey Patch mono to fix certificate validation flags

---

frontend/gulp/build.js
frontend/gulp/copy.js
frontend/gulp/webpack.js
frontend/jsconfig.json
frontend/src/index.html
frontend/src/index.js
src/NzbDrone.Api/Indexers/ReleasePushModule.cs
src/NzbDrone.Api/Profiles/LegacyProfileModule.cs
src/NzbDrone.Api/Wanted/LegacyMissingModule.cs
src/NzbDrone.Common/Composition/ContainerBuilderBase.cs
src/NzbDrone.Common/Reflection/ReflectionExtensions.cs
src/NzbDrone.Core/Datastore/DbFactory.cs
src/Sonarr.Api.V3/Indexers/ReleasePushModule.cs

NO
Cherrypicked some of the monaco-editor stuff that I'd like out of the way.
- Import polyfills in index.js so it gets bundled by webpack and doesn't need to be loaded separately in index.html. So no more unbundled js files.
- Enabled inline webworker again, it seems to work with fuse.worker.
- jsconfig file for some intellisense in VSCode.
- Tweaked our Inversion of Control auto registration logic to avoid it loading dependent assemblies unnecessarily. This helps mostly with the Roslyn assemblies in the separate diagnostic-script pr.
@ta264 The inline webworker seems to work with fuse, but lemme know if you see any problems with this PR.

Phantom webpack bundling

---

src/NzbDrone.Common.Test/DiskTests/DiskTransferServiceFixture.cs
src/NzbDrone.Common/Cache/CacheManager.cs
src/NzbDrone.Common/Cache/Cached.cs
src/NzbDrone.Common/Disk/DiskProviderBase.cs
src/NzbDrone.Common/Disk/DiskTransferService.cs
src/NzbDrone.Common/Disk/IDiskProvider.cs
src/NzbDrone.Core.Test/ParserTests/SeasonParserFixture.cs
src/NzbDrone.Core.Test/ProviderTests/RecycleBinProviderTests/DeleteDirectoryFixture.cs
src/NzbDrone.Core.Test/ProviderTests/RecycleBinProviderTests/DeleteFileFixture.cs
src/NzbDrone.Core.Test/TvTests/MoveSeriesServiceFixture.cs
src/NzbDrone.Core.Test/UpdateTests/UpdateServiceFixture.cs
src/NzbDrone.Core/Extras/Files/ExtraFileManager.cs
src/NzbDrone.Core/MediaFiles/Events/RenameCompletedEvent.cs
src/NzbDrone.Core/MediaFiles/RenameEpisodeFileService.cs
src/NzbDrone.Core/Notifications/INotification.cs
src/NzbDrone.Core/Notifications/NotificationBase.cs
src/NzbDrone.Core/Notifications/NotificationService.cs
src/NzbDrone.Core/Notifications/Plex/Server/PlexServer.cs
src/NzbDrone.Core/Notifications/Plex/Server/PlexServerService.cs
src/NzbDrone.Core/Parser/Parser.cs
src/NzbDrone.Core/Update/InstallUpdateService.cs
src/NzbDrone.Mono.Test/DiskProviderTests/SymlinkResolverFixture.cs
src/NzbDrone.Mono/Disk/DiskProvider.cs
src/NzbDrone.Mono/Disk/FindDriveType.cs
src/NzbDrone.Mono/Disk/RefLinkCreator.cs
src/NzbDrone.Mono/Disk/SymbolicLinkResolver.cs
src/NzbDrone.Mono/Interop/NativeMethods.cs
src/NzbDrone.Mono/Interop/SafeUnixHandle.cs

NO
Plex Library Update request are put in a queue and a later async event triggers processing that queue.
I think we should make the queue more generic and have a timeout, but that isn't necessary yet.
Also added a Rolling Expiry to Cached to keep track of the queue object.
The whole Cached implementation wasn't actually threadsafe, so I kinda rewrote it to be entirely threadsafe.
There's not that much benefit from refreshing multiple series at once, except that it saves on the sections query.
Ideally we should determine the mapping between series folder and plex, then we can identify the section the series is in more efficiently by simply comparing section/locations.
Perhaps using the series location.
But for now the async behavior (and deduplication) should give sufficient performance …

Fixed: Refreshing Plex Server series in high volume systems

---

frontend/src/Settings/UI/UISettings.js

NO
In the Calendar Options dialog, fix a small typo in one of the date examples in the `Week Column Header`.

Fixed: Typo in the Week Column Header example

---

frontend/src/App/ConnectionLostModal.js

Modal header had too many n's in Connection Lost
NO
Fixing a typo that I noticed today

Fixed: Typo in Lost Connection modal

---

src/NzbDrone.Core.Test/ImportListTests/ImportListSyncServiceFixture.cs
src/NzbDrone.Core/ImportLists/ImportListSyncService.cs
src/NzbDrone.Core/Tv/AddSeriesService.cs

NO
Prevents a single validation error from killing the entire list import. 
- Fixes #3959

Fixed: Prevent bulk add failure on single validation error for Lists

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Fix: Add various DTS- audio formats to exclusion so parser does not detect it as a group
Fix: Add Blu-Ray to exclusion so parser does not detect it as a group
* #3984 
Regex is the bane of my existence, but I think I did this right...testing indicates it did not pick up the -HD of DTS-HD as expected.
It may make sense to split the audio into it's own group?

Fix Parser False Positive Group Matches

---

src/NzbDrone.Core.Test/DiskSpace/DiskSpaceServiceFixture.cs
src/NzbDrone.Core.Test/HealthCheck/Checks/RootFolderCheckFixture.cs
src/NzbDrone.Core.Test/RootFolderTests/RootFolderServiceFixture.cs
src/NzbDrone.Core/DiskSpace/DiskSpaceService.cs
src/NzbDrone.Core/HealthCheck/Checks/MountCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/RootFolderCheck.cs
src/NzbDrone.Core/RootFolders/RootFolderService.cs
src/NzbDrone.Core/Tv/SeriesRepository.cs
src/NzbDrone.Core/Tv/SeriesService.cs
src/NzbDrone.Core/Validation/Paths/SeriesAncestorValidator.cs

NO
- Add `AllSeriesPaths` Method
- Use `AllSeriesPaths` in lieu of `All()` in HealthChecks, Diskspace, RootFolderService
- Only call All() (AllSeriesPaths) once for `AllWithUnmappedFolders` instead of for each folder

Improve use of All() and speedup Unmapped Folder matching

---

src/NzbDrone.Core/Notifications/Discord/Discord.cs

NO
Updated Discord.OnDownload to use Success Colour (green)
#4036 
*

FIX: Updated Import for Discord Notifications to use 'Success' Colour

---

src/NzbDrone.Core/Notifications/Discord/DiscordColors.cs

NO
Made the upgrade notification colour to be more clear than the grey that blends in with Discord's background
* #4044

New: Discord notification upgrade colour

---

src/NzbDrone.Core.Test/Download/CompletedDownloadServiceTests/ImportFixture.cs
src/NzbDrone.Core.Test/Download/CompletedDownloadServiceTests/ProcessFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV1.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentTorrent.cs
src/NzbDrone.Core/Download/CompletedDownloadService.cs
src/NzbDrone.Core/Download/DownloadClientBase.cs
src/NzbDrone.Core/Download/DownloadClientItem.cs
src/NzbDrone.Core/Download/IDownloadClient.cs
src/NzbDrone.Core/Download/PrepareImportService.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownload.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs

NO
Previously we were assuming that the output filename was the category
output dir + the torrent name.  This isn't true if the torrent has
been renamed or sanitised.
- Fixes #3968

Fixed: Get actual file names from QBittorrent API

---

src/NzbDrone.Core/Indexers/Nyaa/NyaaSettings.cs

NO
There is an error on version 2.0.0.5344 with nyaa indexers
The current settings cause an error 400 bad request like so : 
`20-11-14 10:12:50.3|Warn|HttpClient|HTTP Error - Res: [GET] https://nyaa.si/?page=rss&cats=1_37&filter=1&term=One+Piece+379: 400.BadRequest
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
20-11-14 10:12:50.6|Warn|Nyaa|Nyaa HTTP request failed: [400:BadRequest] [GET] at [https://nyaa.si/?page=rss&cats=1_37&filter=1&term=One+Piece+379]
`
https://nyaa.si/?f=1&c=1_37&term=jujutsu
Updating it to category : 1_0 fix the problem
https://nyaa.si/?f=1&c=1_0&term=jujutsu
*

Update indexer category parameters for the other nyaa

---

frontend/src/Components/Form/EnhancedSelectInput.css
frontend/src/Components/Form/EnhancedSelectInput.js
frontend/src/Components/Form/FormInputGroup.js
frontend/src/Components/Form/UMaskInput.css
frontend/src/Components/Form/UMaskInput.js
frontend/src/Helpers/Props/inputTypes.js
frontend/src/Settings/MediaManagement/MediaManagement.js
src/NzbDrone.Api/Config/MediaManagementConfigModule.cs
src/NzbDrone.Api/Config/MediaManagementConfigResource.cs
src/NzbDrone.Common/Disk/DiskProviderBase.cs
src/NzbDrone.Common/Disk/IDiskProvider.cs
src/NzbDrone.Core/Configuration/ConfigService.cs
src/NzbDrone.Core/Configuration/IConfigService.cs
src/NzbDrone.Core/Datastore/Migration/147_swap_filechmod_for_folderchmod.cs
src/NzbDrone.Core/MediaFiles/DiskScanService.cs
src/NzbDrone.Core/MediaFiles/MediaFileAttributeService.cs
src/NzbDrone.Core/Validation/FileChmodValidator.cs
src/NzbDrone.Mono.Test/DiskProviderTests/DiskProviderFixture.cs
src/NzbDrone.Mono/Disk/DiskProvider.cs
src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs
src/NzbDrone.Windows/Disk/DiskProvider.cs
src/Sonarr.Api.V3/Config/MediaManagementConfigModule.cs
src/Sonarr.Api.V3/Config/MediaManagementConfigResource.cs

**YES** = 145
1. Swapped the file-based permissions (644) with folder-based permissions (755). It's technically exactly the same but it was confusing for people.
2. Also extended EnhancedSelectInput with a editable mode, allowing uses to type in whatever they want but still have a dropdown with common presets.
I'm not entirely happy with it, I think that maybe duplicating the dropdown code to a PresetTextInput might be better. So let me know what you think.
3. Added preview of umask, folder and file permissions including drwxr-xr-x notation.
4. Readded chgrp, there was an usecase when wanting to secure Sonarr db vs the media library.
5. Fixed bug that erroneously removed existing setgid flags when applying permissions.
*

Displaying folder-based permissions in UI rather than file-based

---

frontend/src/Components/Link/Link.js
frontend/src/Components/Page/Header/PageHeader.js

NO
Currently if the URL base matches the root path of an existing Sonarr page this causes issues in with opening said page (reported about series assumed for all other similar root paths). 
I have tested each link on each page manually and this appears to be working - the API has not been tested from outside of the Sonarr webpage however this should not cause any issues due to the webpage working. 
The logo in the Page Header was the only link that seemed to cause an issue; in testing setting the "to" value to be '/' still works as expected. 
* #4148

Fixed: '/series' URL Base breaking UI navigation

---

frontend/src/Series/Index/Menus/SeriesIndexSortMenu.js
frontend/src/Store/Actions/seriesEditorActions.js
frontend/src/Store/Actions/seriesIndexActions.js

NO
Enable sorting by Language Profile and Tags within the Mass editor page
This looks like this when sorted:
No Tags comes first
No Tags comes last
* #3854

New: Sorting Series List/Mass Editor by Language Profile and Tags

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

NO
Fixes a missed case for parsing a series' language when spaces are present in the torrent name. My case was `The Spanish Princess` where the torrent name was `The Spanish Princess S02E02 Flodden 720p AMZN WEB-DL DDP5 1 H 264-NTb`
I added the relevant test cases where needed and all appear to pass. However, I'm not sure the greater impact of testing with an or for periods or spaces, but this still works exactly the same.
**Before**
**After**
Happy to review as needed.
* Closes #4056

Fixed: Language parsing with space-delimited releases

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

NO
Title
- Wiki Updates-N/A
N/A
Reference: https://www.reddit.com/r/sonarr/comments/kvsr4n/sonarr_think_uhd_release_is_fhd/

Fixed: Parse standalone UHD as 4K if no other resolution info is present

---

src/NzbDrone.Core/Notifications/Email/EmailService.cs
src/NzbDrone.Core/Notifications/Email/EmailSettings.cs
src/NzbDrone.Core/Sonarr.Core.csproj

NO
Replaces obsolete SmtpClient implementation with Mailkit which correctly handles all modern protocols. Client is setup to use the default `MailKit.Security.SecureSocketOptions.Auto` options. This means if 465 port is specified SSL is used automatically, otherwise mailkit will use StartTLS if available. Tested with both cases on Radarr side. 
Picked from https://github.com/Radarr/Radarr/pull/4638/commits/f69cf134d158cc1ec4ce17daf802823b4792cd54
* Fixes #4213

New: Replace SmtpClient with Mailkit

---

frontend/src/Settings/Quality/Definition/QualityDefinition.js

NO
Name of max component shouldn't be same as min component.

Fix name of max NumberInput in QualityDefinition.js

---

src/NzbDrone.Core/MediaFiles/RecycleBinProvider.cs

NO
Improve error handling around broken recycle bin paths; currently unclear what the error is when looking at the logs
* #4163

Fixed: Error handling when cannot create folder in Recycling Bin

---

frontend/src/Settings/Profiles/Release/EditReleaseProfileModalContent.js
frontend/src/Settings/Profiles/Release/ReleaseProfile.css
frontend/src/Settings/Profiles/Release/ReleaseProfile.js
src/NzbDrone.Core/Datastore/Migration/154_add_name_release_profile.cs
src/NzbDrone.Core/Profiles/Releases/ReleaseProfile.cs
src/Sonarr.Api.V3/Profiles/Release/ReleaseProfileResource.cs

This adds a new, non-functional field to release profiles for a friendly
name. This name may be used, for example, by scripts invoking the API to
look for specifically named profiles in order to find their ID, which is
required to perform further operations on it. Additionally it adds an
additional organization tool for users to manage their release profiles.
YES
See above

New: Add name field to release profiles

---

src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatVideoDynamicRangeFixture.cs
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/VideoFileInfoReaderFixture.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoModel.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs

NO
This PR is to address issue #4276 where Dolby Vision HDR was not being picked up by sonarr in the media info formatting for VideoDynamicRange
I updated mediainfo library windows and mac to 20.09 and added `VideoHdrFormat` and `VideoHdrFormatCompatibility` properties to the `MediaInfoModel`.
Adjusted `MediaInfoFormatter.FormatVideoDynamicRange` to return HDR if the VideoHdrFormat field is not empty.
This should handle older media info schemas by defaulting the properties to empty, and the formatter will just assume SDR
#4276

Detect Dolby Vision as HDR and MediaInfo Update

---

frontend/src/Components/Tooltip/Tooltip.css
frontend/src/Series/Details/SeriesDetails.css
frontend/src/Series/Details/SeriesDetails.js

NO
Adds a box on series info to show the number of files
* #4203

New: Show number of files as tooltip over size on disk

---

frontend/src/AddSeries/AddNewSeries/AddNewSeriesModalContent.js
frontend/src/AddSeries/AddNewSeries/AddNewSeriesModalContentConnector.js
frontend/src/Store/Actions/addSeriesActions.js

NO
Persist `searchForCutoffUnmetEpisodes` and `searchForMissingEpisodes` setting values in local cache.
* #4245

New: Persist search settings in add new series

---

src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DiskStationProxyBase.cs

NO
Addresses the issue described in #3943 by incrementing the `SYNO.API.Auth`. I've tested the download-import workflow without any added issues related to API changes made by Synology in DSM 7. This change does not raise any significant incompatibility issues as previously detailed in [my comment](https://github.com/Sonarr/Sonarr/issues/3943#issuecomment-774460487).
* #3943

Fix DownloadStation integration in DSM 7

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
Cleanse the keys before/after `announce/` and `/announce`
- Wiki Updates-N/A
- Fixes #4341

Fixed: Cleanse Tracker Announce Keys from logs

---

src/NzbDrone.Common/Http/HttpResponse.cs

NO
Update `HttpResponse` to recognize 303 (SeeOther) and 307 (Temporary Redirect) as valid redirects. This will allow Sonarr to follow these when `AllowAutoRedirect` is set to true in `HttpRequest` and ensure they are properly reported as redirects in `response.HasHttpRedirect`
I can add further `HttpClient` tests using httpbin `redirect-to/` endpoint which allows specifying of a redirect code if wanted.

Handle 303 and 307 redirects in Http Requests

---

src/NzbDrone.Core/Indexers/RssParser.cs

NO
Given that [XElement.Attribute()](https://docs.microsoft.com/en-us/dotnet/api/system.xml.linq.xelement.attribute?view=net-5.0) will return a null value when it cannot find the attribute, defensive programing is required.
Given that [XAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.xml.linq.xattribute?view=net-5.0) is a class that has nothing to do with long/Int64, the Value property should be accessed and parsed instead of using a cast.
* https://github.com/lidarr/Lidarr/issues/1730

Fixed: Parsing RSS with null values

---

src/Sonarr.Api.V3/EpisodeFiles/EpisodeFileListResource.cs
src/Sonarr.Api.V3/EpisodeFiles/EpisodeFileModule.cs
src/Sonarr.Api.V3/EpisodeFiles/EpisodeFileResource.cs

Include releasegroup in the API output
allow sceneName and releaseGroup to be modified via PUT request
NO
Allow releaseGroup to be read via episodeFile API request similar to how movieFile functions on Radarr
Allow both releaseGroup and sceneName to be modified by the API
Uses here would be primarily for post processing scripts to include this information if its lost or missing from Sonarr. My primary use case is that I have a script that rewraps MKV files in and MP4 container. After this file extension change the information about the sceneName and releaseGroup is lost and it makes finding subtitles and other release specific things more difficult. This would allow that information to be restored after a rescan is completed.
I have created a similar pull request for Radarr for sceneName …

New: Setting SceneName and ReleaseGroup for EpisodeFiles via API

---

src/NzbDrone.Core.Test/HealthCheck/Checks/DownloadClientRootFolderCheckFixture.cs
src/NzbDrone.Core.Test/HealthCheck/Checks/HealthCheckFixtureExtensions.cs
src/NzbDrone.Core/HealthCheck/Checks/DownloadClientRootFolderCheck.cs

already implemented within Radarr
(cherry picked from commit 88780f33a4c5032aaa151aaae7090371beb42f33)
NO
Health check to highlight that Sonarr is downloading to the root folder
* #4402

New: Health Check for Downloads to Root Folder

---

src/NzbDrone.Core/Datastore/Migration/158_cdh_per_downloadclient.cs
src/NzbDrone.Core/Download/Clients/Flood/Flood.cs
src/NzbDrone.Core/Download/Clients/Flood/Types/Torrent.cs

This change implements the new DownloadSeedConfigProvider for Flood.
See 411be4d0116f0739bb9c71235312d0c5a26dd3a2 and #3632.

Flood: allow to remove downloads when seeding criteria have been met

---

src/NzbDrone.Core/Download/Clients/Flood/Flood.cs

This is still somehow required even with `properties.DateFinished != null`. 
Fixes:
Sonarr\src\NzbDrone.Core\Download\Clients\Flood\Flood.cs(166,90,166,113):
error CS1503: Argument 1: cannot convert from 'long?' to 'long'

Flood: explicitly cast DateFinished long? to long

---

frontend/src/Settings/Profiles/Delay/EditDelayProfileModalContent.js
src/NzbDrone.Core.Test/TvTests/EpisodeServiceTests/HandleEpisodeFileDeletedFixture.cs
src/NzbDrone.Core/Datastore/BasicRepository.cs
src/NzbDrone.Core/Datastore/Events/ModelEvent.cs
src/NzbDrone.Core/Datastore/Extensions/MappingExtensions.cs
src/NzbDrone.Core/Tv/EpisodeRepository.cs
src/NzbDrone.Core/Tv/EpisodeService.cs
src/Sonarr.Api.V3/Episodes/EpisodeModule.cs
src/Sonarr.Api.V3/Episodes/EpisodeModuleWithSignalR.cs
src/Sonarr.Http/SonarrRestModuleWithSignalR.cs

NO
Changing monitored flags for episodes don't result in a signalr message.
This means that second browser tabs won't update, but also third-party apps using signalr won't get notified (Bazarr specifically).
note that I could do this in EpisodeModule handling the SetMonitored api calls and send broadcasts. However this means we wouldn't send updates for monitored flag changes triggered internally.
Some concerns:
- Added `GetResourceByIdForBroadcast` since I didn't want the series to be included in the notification. I have to check if that causes problems in the UI.
- It sends out 4 notifications for the calendar, episode, cutoff, missing endpoints. Which is a bit excessive.
- I do wonder what other things lack notifications to the UI.

Send signalr message for episode monitored flag changes

---

src/NzbDrone.Core/Download/DownloadClientInfo.cs

NO
Fixes null reference error caused by RuTorrent not providing DownloadClientInfo
PR already opened in Radarr/Lidarr/Readarr
* https://github.com/Radarr/Radarr/pull/6345
* https://github.com/lidarr/Lidarr/pull/2266
* https://github.com/Readarr/Readarr/pull/1051

Fixed: Root Folder Downloads check giving errors when RuTorrent is used

---

frontend/src/login.html

NO
I found that on mobile, it autocapitalizes the first character of the username in the HTTP authentication form.
I changed the input property to turn this off.
If this was intentional, feel free to deny this PR.

Fixed: autoCapitalization on mobile viewport

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/TorrentDownloadStationFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/UsenetDownloadStationFixture.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/DiskStationApi.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/DownloadStation2Task.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DiskStationProxyBase.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxySelector.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxyV1.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxyV2.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Responses/DiskStationError.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Responses/DownloadStation2TaskInfoResponse.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs

NO
Added compatibility with the new Download Station API 'SYNO.DownloadStation2.Task'.
This will resolve the compatibility issue with the new version of Synology Download Stations 3.8.16-3566.
If the new 'SYNO.DownloadStation2.Task' API is available, use it, otherwise use the old 'SYNO.DownloadStation.Task'.
* Fixes #4388

Fixed: Compatibility with the new Download Station API

---

frontend/src/InteractiveImport/Interactive/InteractiveImportModalContent.js

NO
Manual interactive imports can be time consuming because there's no ability to sort on the reject column. Now the user can click on that column and shift deselect based on that.

New: Manual Import rejection column is sortable

---

frontend/src/Store/Actions/queueActions.js

NO
Changes the `Timeleft` column to `Time Left`, as `Timeleft` is not a word.
* Related to #1010 but I assume that's no longer relevant. Was changed in 95da301 but appears to not have made it.

New: Activity Queue: Rename Timeleft column to Time Left

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
RePACKPOST  should not be parsed as a group
- N/A Wiki Updates
*

Fixed: Incorrectly parsing RePACKPOST as Group

---

src/NzbDrone.Core.Test/ParserTests/UnicodeReleaseParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Some anime release title without brackets, but episode number is in brackets. This pull request add "?" mark in regex which allows title with or without brackets
* #2898

Fixed: Parsing of some Chinese anime releases without brackets

---

src/NzbDrone.Core/Download/Clients/Flood/Flood.cs

NO
While investigating an issue with Flood I discovered that the following lines seem to have been mistakenly duplicated in this commit [c669be3](https://github.com/Sonarr/Sonarr/commit/c669be317fffa252d59851e9a8ca9e56032a01fb#diff-94a0ab78c97ff8de1786cfd7d29d336550638b602775f1cab002591a59ba7948L205-R206), This PR simply removes the duplicate call.
https://github.com/Sonarr/Sonarr/blob/4659a8366d8a1565890d3b72442bd35c6eb8176e/src/NzbDrone.Core/Download/Clients/Flood/Flood.cs#L229-L233

Flood Fix: Remove duplicate call to DeleteTorrent

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
- No longer Parse [PublicHD] as a group
- Cleanse the title of suffixes before parsing group
-  Wiki Updates
*

Fixed: Incorrectly Parsing [PublicHD] as Release Group

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

The `title` key is optional, but must not be empty if specified.
NO
This fixes the issue templates, which were broken by https://github.com/Sonarr/Sonarr/commit/3fb5f65f0889e5bf84338a7fa92680a9ccb135e2.

Fix issue templates

---

frontend/src/Settings/Quality/Definition/QualityDefinitionsConnector.js

NO
Avoid a double fetch of quality definitions on line 41 and 49
None

Fixed: Don't fetch quality definitions twice

---

frontend/src/Styles/Variables/colors.js

NO 
I found it hard to see the highlighted `today` block in the calendar, so I adjusted the color for more contrast.
This is the smallest of changes, but it makes a big difference in visibility.
Let me know if there are any problems in regards to text contrast for accessibility.

New: Change Today color in calendar for better visibility

---

frontend/src/Settings/General/HostSettings.js

YES | NO
In order to overcome a chance that the port field is automatically filled by a browser when viewing the general settings, and saved accidently, I propose to disable autocomplete on this field.
*

New: Disable autocomplete of port number

---

src/NzbDrone.Core/MediaFiles/EpisodeFile.cs

NO
Submitting the proposed fix for 4675, where GetSceneOrFileName no longer returns the extension
https://github.com/Sonarr/Sonarr/issues/4675

New: Use filename without extension if SceneName is unavailable for preferred words

---

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs

fixes bug reported in #4686
Single line fix, adding the missing call for the customscript in the OnEpisodeFileDeleted hook.

Fixed: On Delete events for Custom Scripts not being executed

---

frontend/src/Store/Actions/systemActions.js
frontend/src/System/Events/LogsTableRow.js

NO
Moves the time column to be after the event type as this is more typical for logging. This was cherry-picked from Radarr (and has gone downstream to all others) https://github.com/Radarr/Radarr/commit/c14ef7bee7477ad5d29498f1cba94267eb11daf0

New: Time column is first column on events page

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

(cherry picked from radarr commit 9a2cee3104b1e8d32f2df68d3ca75967aba41868)
NO
treat missingfiles as a warning rather than unknown state
- Wiki Updates
*

New: Handle missingFiles status from qBit

---

frontend/src/Settings/MediaManagement/Naming/NamingModal.js

NO
currently the modal examples implies that ! is removed from all  naming formats except {Series Title}.
Including it now in the examples to avoid confusion as a simple fix until the issue #2028 gets further attention
*

New: Updated naming examples

---

src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatVideoDynamicRangeFixture.cs
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoModelExtensionsFixture.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/HdrFormat.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoModelExtensions.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

NO
This is based off the work done by @Matty666 in #4278 and #2950
With the multiple hdr formats and some shows getting released as both DolbyVision and HDR10, Sonarr was renaming then all HDR. It is possible to use Preferred Words renaming to keep the extra metadata when it exists in the release name, but it's not always included (e.g. I believe Scene standards say it's optional if the HDR version was released first).
I added a new token instead of changing the logic of the original one. It adds a token that could be considered a dupe, but also means that existing users won't start seeing new stuff they're not expecting in their names.
The new token attempts to parse what type of HDR the media is based on the existing metadata pulls (so a rescan isn't needed and the model version doesn't …

New: Add {MediaInfo VideoDynamicRangeType} token for renaming

---

src/NzbDrone.Core/Sonarr.Core.csproj
src/NzbDrone.Test.Common/Sonarr.Test.Common.csproj

NO
This pull addresses CVE-2021-27293 in RestSharp by updating the dependency to 106.15.0. All tests passed locally with no issues.
* Resolves use of vulnerable version of RestSharp

Update RestSharp to 106.15.0 to address vulnerability

---

src/Marr.Data/QGen/WhereBuilder.cs
src/NzbDrone.Common/EnsureThat/ExpressionExtensions.cs
src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs
src/NzbDrone.Common/TinyIoC.cs
src/NzbDrone.Core.Test/Framework/MigrationTest.cs
src/NzbDrone.Core/Datastore/Migration/147_swap_filechmod_for_folderchmod.cs
src/NzbDrone.Core/Download/DownloadService.cs
src/NzbDrone.Test.Common/AutoMoq/AutoMoqer.cs
src/Sonarr.Http/Validation/EmptyCollectionValidator.cs

NO
This pull request is _very simple_ and aims to reduce the technical debt. It specifically targets the "Convert 'as' expression type check and the following null check into pattern matching" [rule](https://www.jetbrains.com/help/resharper/UsePatternMatching.html) reported by ReSharper.

Use pattern matching instead of as expression type checking

---

.github/ISSUE_TEMPLATE/bug_report.yml

git
skip ci is for downstream easier bot pulls; aware it does nothing here.

Clarify Trace logs in bug reports

---

frontend/src/Activity/History/Details/HistoryDetails.js

NO
Due to the confusing message, users frequently incorrectly believe Sonarr deleted the file when it simply could no longer be seen.
-  Tests
-  Wiki Updates
https://forums.sonarr.tv/t/unable-to-find-file-on-disk-so-it-was-deleted/29282

Fixed: Improved messaging when episode file was detected as deleted from disk

---

frontend/src/Store/Actions/releaseActions.js

NO
Adds ability to use "Season Pack" filter in Custom Filters
* #4780

New: Added "Season Pack" to Interactive Search custom filters

---

frontend/src/InteractiveSearch/InteractiveSearchRow.js

NO
The tooltip should show "download queue" rather than "downloaded queue" as "downloaded" implies it has already been downloaded.

Fixed: Grammar in tooltip of download button

---

src/NzbDrone.Core.Test/Datastore/SqliteSchemaDumperTests/SqliteSchemaDumperFixture.cs

NO
This adds a check to the SqliteSchemaDumperFixture to ensure identity is not lost on the Id column during migration. While not a problem with Sonarr thus far, this will ensure we catch issues for any future schemas in the testing suite. 
Reference Radarr issue solved by pulling Sonarr code 
https://github.com/Radarr/Radarr/commit/ec86de78d21dd05479379ef539686b2052504046
https://github.com/Sonarr/Sonarr/commit/34faa417c1d7c48d86236ed8f29bd44518322373
*

Add test to ensure Identity is maintained on Id column during migration

---

src/NzbDrone.Core/Download/Clients/Flood/Flood.cs
src/NzbDrone.Core/Download/Clients/Flood/FloodProxy.cs
src/NzbDrone.Core/Download/Clients/Flood/Types/FloodClientSettings.cs

(cherry picked from Radarr commit 7a859f340be3d0e82909e0f0d7260fb97409b4ee)
Authored by Qstick <qstick@gmail.com>
NO
Solves issue where Flood download client was not passing in designated directory, causing a health warning.
* Fixes #4825

Fixed: Avoid download path check false positives for Flood

---

src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
There is logic to handle parsing when series year is included in release name by matching against `CleanTitle` and `Year` in `Series` table. This logic previously failed to find a match for numeric series name due to extraneous whitespace. Therefore, this PR is simply trimming numeric series names to prevent extraneous whitespace from preventing query match. See the issue description and comments for a much more in-depth explanation/rationale.
* #4850

Fixed: Parsing of numeric only titles that include a year

---

frontend/src/Settings/Indexers/Indexers/EditIndexerModalContent.js

NO
Currently many users commonly are mislead by the existing helptext that implies indexer priority will change how indexers are searched or any other possibilities other than simply being a tiebreaker.
This clarifies the currently confusing helptext
-  Tests
- Wiki Updates - Already done `(Advanced Option) Indexer Priority - Priority of this indexer to prefer one indexer over another in release tiebreaker scenarios. 1 is highest priority and 50 is lowest priority.`
*

Fixed: Clarify Indexer Priority Helptext

---

frontend/src/Components/Page/PageContentFooter.css

NO
By reacting to breakpointExtraLarge we allow the `flex-wrap: wrap` to come in at a larger screen width ensuring the delete button is always visible. This is needed due to the amount of buttons present on the mass editor.
This does not impact negatively the other places where PageContentFooter is implemented (series import and season pass)
* #4860

Fixed: Mass Editor Footer on Smaller Screens

---

frontend/src/Components/Form/DownloadClientSelectInputConnector.js
frontend/src/Components/Form/FormInputGroup.js
frontend/src/Helpers/Props/inputTypes.js
frontend/src/Settings/Indexers/Indexers/EditIndexerModalContent.js
src/NzbDrone.Core.Test/Download/DownloadClientProviderFixture.cs
src/NzbDrone.Core.Test/Download/DownloadServiceFixture.cs
src/NzbDrone.Core/Datastore/Migration/164_download_client_per_indexer.cs
src/NzbDrone.Core/Download/DownloadClientProvider.cs
src/NzbDrone.Core/Download/DownloadService.cs
src/NzbDrone.Core/Indexers/IndexerDefinition.cs
src/NzbDrone.Core/ThingiProvider/IProviderFactory.cs
src/NzbDrone.Core/ThingiProvider/ProviderFactory.cs
src/Sonarr.Api.V3/Indexers/IndexerResource.cs

YES - 164 (DownloadClientId on Indexers)
Allow user to specify a particular client for an indexer
Basically copied from this radarr change: 
https://github.com/Radarr/Radarr/pull/6858
Closes [#1215](https://github.com/Sonarr/Sonarr/issues/1215)

New: Link indexer to specific download client

---

src/NzbDrone.Common/Disk/LongPathSupport.cs

NO
I changed the crafted string so it meets the segment limitations be still exceeded the old 255 character maximum.
#4877

Fix: Windows Long Path Support - Paths not allowed to be greater than 259 characters

---

src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs

NO
Updated helptext for option to add ruTorrent torrents in a stopped state.
*

Fixed: Updated ruTorrent stopped state helptext

---

src/NzbDrone.Core/Download/Clients/Deluge/DelugeSettings.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/DownloadStationSettings.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexSettings.cs
src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs
src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdSettings.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionSettings.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentSettings.cs

NO
title
- don't mention optional for download client categories (see also enabling show unknown as default)
- add forced warning for qbit
- Tests
*

Fixed: Improve help text for download client Category

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentSettings.cs

NO
This PR adds two settings to the download client qBittorrent: download in sequential order and prioritise first and last pieces.
Those settings were introduced in the qBittorrent API in 4.0.0 but until api v2 (4.1.0) they only work if the form is submitted as a `form-data` and not as a `x-www-form-urlencoded` (couldn't find the reason why but their doc says to use `form-data` after qBittorrent 3.3.1 and the tests I did showed this). As earlier versions of the qBittorrent API are only compatible with `x-www-form-urlencoded` and as I don't want to introduce changes to the HttpRequestBuilder to change the ContentType, this is only available for qBittorrent 4.1.0+.

New: Add qBittorrent sequential order and first and last piece priority options

---

frontend/src/Series/Index/Table/SeriesIndexHeader.css
frontend/src/Series/Index/Table/SeriesIndexRow.css
frontend/src/Series/Index/Table/SeriesIndexRow.js
frontend/src/Store/Actions/seriesActions.js
frontend/src/Store/Actions/seriesIndexActions.js
src/NzbDrone.Core/SeriesStats/SeasonStatistics.cs
src/NzbDrone.Core/SeriesStats/SeriesStatistics.cs
src/NzbDrone.Core/SeriesStats/SeriesStatisticsRepository.cs
src/NzbDrone.Core/SeriesStats/SeriesStatisticsService.cs
src/Sonarr.Api.V3/Series/SeasonStatisticsResource.cs
src/Sonarr.Api.V3/Series/SeriesResource.cs
src/Sonarr.Api.V3/Series/SeriesStatisticsResource.cs

NO
- Add Release Groups for Seasons and Series to Statistics entities.
- Include Release Groups column in Index Page (Table).
- Include Release Groups filter in Index Page (Table).

New: Option to show release group column on series list

---

src/NzbDrone.Core.Test/Extras/ExtraServiceFixture.cs
src/NzbDrone.Core.Test/Extras/Others/OtherExtraServiceFixture.cs
src/NzbDrone.Core.Test/Extras/Subtitles/SubtitleServiceFixture.cs
src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Extras/ExtraService.cs
src/NzbDrone.Core/Extras/Files/ExtraFileManager.cs
src/NzbDrone.Core/Extras/Metadata/MetadataService.cs
src/NzbDrone.Core/Extras/Others/OtherExtraService.cs
src/NzbDrone.Core/Extras/Subtitles/SubtitleService.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

NO
Improve extra files import by searching for filename match and season/episode match.
For subtitles, if no match is found and the folder contains only one episode, use any subtitle file available.
For subtitle filename parsing, ignore case for iso code search, fix language search and add support for common tags (full, forced, foreign, default, cc, psdh, sdh).
Add partial test coverage for extras.
Related to #2513

New: Import subtitles from sub folders

---

frontend/src/Activity/History/HistoryRow.js
frontend/src/Store/Actions/historyActions.js

NO
I've had it a few times that a show has bulk imported, and due to mismatches between scene and TVDB they don't quite get matched up properly to an episode in Sonarr.
What I like to do here is then look at the history page and see if the releases somewhat match up with the episodes. An example here is RuPauls Drag Race Untucked. The show didn't have a season 1 (as it began as a sideshow to season 2 of the main show). Some groups released it back then as season 1 and some release it now as season 2. It can often be determined from the release title if it was the correct one as epiosde title is in there.
Looking down the history list it'd be nice to see also the release name at a glance without having to go to details. Hence this PR. Hope you find it OK.
- [NA] Tests
- [NA] Wiki Updates
*

New: Add optional Source Title column to history

---

src/NzbDrone.Core/Download/Clients/DownloadStation/Responses/DiskStationError.cs

NO
Try to authenticate on the next request when sid not found is received.

Properly handle 119 Errorcode on Diskstation client

---

src/NzbDrone.Core/Sonarr.Core.csproj

Monotorrent v2.0.5 addresses an issue causing certain torrents created by rutorrent to not load, see https://github.com/alanmcgovern/monotorrent/issues/517
NO
This fixes an issue with monotorrent parsing code that resulted in Sonarr being unable to load certain torrents created by rutorrent (and possibly others) containing absolute paths. Absolute paths are now gracefully transformed into relative paths.

New: Update Monotorrent

---

frontend/src/App/ConnectionLostModal.js

Was incorrectly using 'it's' instead of 'its'
NO
Minor typo in 'ConnectionLostModal.js'

Fixed: Typo in Connection Lost modal

---

src/NzbDrone.Api/Calendar/CalendarFeedModule.cs
src/NzbDrone.Api/Sonarr.Api.csproj
src/Sonarr.Api.V3/Calendar/CalendarFeedModule.cs
src/Sonarr.Api.V3/Sonarr.Api.V3.csproj

NO
There is currently a bug with the current version of Ical.Net where the tentative status string is "Tentative" instead of "TENTATIVE" [reported here.](https://github.com/rianjs/ical.net/issues/318)
This is causing issues with google calendar as [reported here.](https://old.reddit.com/r/sonarr/comments/ubl6wd/google_calendar_link_not_updating/)
This version bump and fix resolves the issue.
*

Fixed: iCal status values

---

src/NzbDrone.Core.Test/ParserTests/SeasonParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
This commit adds 576p as a valid resolution when parsing the title of a release. It fixes the following case that failed to parse before:
Twin.Peaks.S01.576p.BluRay.DD5.1.x264-HiSD
By recognising 576p as a quality identifier, the release is now correctly parsed.
* https://github.com/Sonarr/Sonarr/issues/5006

Fix 576p release parsing

---

src/NzbDrone.Core/Validation/Paths/StartupFolderValidator.cs

NO
Currently startup folder validation on checks if folder settings is child, this change also checks to make sure it's not equal. This change is related to root folder and recycle bin settings.

Fixed: Validate if equals or child for startup folder

---

frontend/src/App/App.js
frontend/src/Components/Page/PageContent.js
frontend/src/Settings/General/GeneralSettings.js
frontend/src/Settings/General/HostSettings.js
src/NzbDrone.Common/Sonarr.Common.csproj
src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
src/NzbDrone.Core/Instrumentation/ReconfigureLogging.cs
src/NzbDrone.Core/Validation/RuleBuilderExtensions.cs
src/Sonarr.Api.V3/Config/HostConfigModule.cs
src/Sonarr.Api.V3/Config/HostConfigResource.cs
src/Sonarr.Api.V3/System/SystemModule.cs
src/Sonarr.Http/Frontend/InitializeJsModule.cs

NO
Allows for UDP Syslogging and adds instance name so you can see what logs come from which instance when running multiple instances. Instance name is used in both syslog and within the tab; and requires Sonarr to be in the instance name somewhere
This is already in Radarr, Readarr, Lidarr, Prowlarr and Whisparr; commits have been loosely cherry-picked from there (sonarr-ified where required and updated to make a bit more logical sense)
Syslog is a config file only parameter set.
* #4778

New: UDP Syslog support and Instance Name

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/UpgradeSpecification.cs

NO
useful for instances where the queue file quality (from the client) doesn't match the on-disk rejected file e.g. quality mismatch
- Tests
- Wiki Updates
*

New: Improve messaging for rejected quality upgrades

---

frontend/src/Settings/General/HostSettings.js
src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
src/NzbDrone.Core/Configuration/ConfigService.cs
src/NzbDrone.Core/Configuration/IConfigService.cs
src/Sonarr.Api.V3/Config/HostConfigResource.cs

Signed-off-by: Devin Buhl <devin@buhl.casa>
NO
Add external Application URL to Host settings, I poked around a little and didn't see a way to easily do validation on this URL, it could easily be any of the following:
- http(s)://sonarr.domain.tld
- http(s)://domain.tld/sonarr
- http(s)://sonarr:8989
- http(s)://192.168.1.100:8989
Please let me know if there's a need for validation and any existing examples would be helpful <3
After this is merged I will create other PRs implementing the use of this in notification services for pushover, custom script and webhook.
* https://github.com/Sonarr/Sonarr/issues/5060

New: Add application URL to host configuration settings

---

src/NzbDrone.Core/Tv/MoveSeriesService.cs

NO
Just fixes a log message.
Message I got when renaming a series folder:
```
2022-08-06 09:08:01.0|Info|MoveSeriesService|Moving 12 Monkeys from '/tv/12 Monkeys' to '/tv/12 Monkeys (2015)'
2022-08-06 09:08:01.1|Info|MoveSeriesService|12 Monkeys moved successfully to /tv/12 Monkeys
```
*

Fixed: Logging when series folder is moved successfully

---

src/NzbDrone.Core/Indexers/Nyaa/NyaaRequestGenerator.cs

NO
`NyaaRequestGenerator::GetSearchRequest` attempts to prepend `&term=` to the title being searched, even though `GetPagedRequests` already does this in constructing the search URL. I noticed this during inspection.

Fixed: Nyaa episode title search

---

src/NzbDrone.Core/Extras/Subtitles/SubtitleFile.cs

NO
#4924 Adds nullable DB field LanguageTags. This sets default value in SubtitleFile constructor to empty list, preventing null errors when accessed.

Fixed: Fix NullRef in Subtitle Service due to #4924

---

src/Sonarr.Api.V3/CustomFormats/CustomFormatResource.cs

NO
Previously, if the spec was not found, you'd get a
`NullReferenceException` back in the API response because the code always
assumed the `SingleOrDefault()` method would return non-null. This change
introduces a safety check for `null` and throws `ArgumentException` with
a more helpful error message that makes the issue more apparent to
clients of the API.
The use case for this is custom format import via API (and might also
apply to import on the frontend too, although I did not test this). If
you take a CF meant for Radarr and import it into Sonarr, you get this
issue.

Fixed: Better error messaging if you try to import an invalid Custom Format

---

src/NzbDrone.Core/Indexers/SeedCriteriaSettings.cs

NO
Making seed ratio a non-advanced option on indexer settings. Allows functionality of completed download removal to work without enabling advanced settings.
*

New: Torrent Seed Ratio no longer advance settings

---

src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs

NO
Minor adjustments to the HelpText fields for the rTorrent download client. Currently, ruTorrent is referenced instead of rTorrent.
*

Update help text for rTorrent download client options

---

src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs

NO
based on some discussion in discord, added note to clarify that torrents don't get paused when meeting seeding criteria, instead sonarr removes them once the criteria are met and remove completed is enabled
*

Fixed: updated rTorrent download client note

---

src/NzbDrone.Core/Indexers/Rarbg/RarbgParser.cs

backport of various response code updates in jackett, prowlarr, radarr
NO
Handle Rarbg error codes
ref from jackett
```
case 5: // Too many requests per second. Maximum requests allowed are 1req/2sec Please try again later!
case 8: // imdb not found, see issue #12466
case 9: // imdb not found, see Radarr #1845
case 10: // imdb not found, see issue #1486
case 14: // tmdb not found, see Radarr #7625
case 20: // no results found
```
- Tests
- Wiki Updates
*

Fixed: Improve RarBG Error Handling

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
This removes webhook ID and token from logging when using discord webhooks.
- [ X ] Tests
* #5169

Fixed: Cleanse Discord Webhook URLs

---

src/NzbDrone.Core/Download/DownloadService.cs

NO
This was to add the indexer name that was responsible for download. We logged the client, this is another piece of that information.
I didn't see the need for a change to add logging.
None, this was mainly for my own personal needs that I think people would benefit from having when trying to debug a configuration issue.

Add indexer name to the download report log

---

src/NzbDrone.Core/Notifications/Notifiarr/Notifiarr.cs
src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrException.cs
src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrProxy.cs
src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrSettings.cs

NO
- Implements native Notifiarr support to be used in lieu of existing webhook functionality
- Over a dozen other apps provide native Notifiarr support and do not require a webhook
- Autobrr
- Lidarr
- Plex Meta Manager
- Polinatarr
- Prowlarr
- Qbit Manage 
- MDBList
- Radarr
- Readarr
- Reciperr
- Unpackerr
- Whispar
- CrossSeed
- Previous concerns regarding confusion with Discord are now moot
- Allows customization of fields specific to notifiarr without modifying webhooks
- Allows easier and simpler configuration by users
- Tests
* Related to #3985
* Related to #3819

New: Add Notifiarr connection

---

src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs

NO
Custom formats for size weren't working because size would default to 0 since the reported size wasn't being passed in 'parsedEpisodeInfo'.
- Tests
- Wiki Updates
*

Fixed: File Size in Custom Formats

---

src/Sonarr.Http/ApiInfoController.cs
src/Sonarr.Http/ApiInfoResource.cs

NO
Adds authorized generic non-versioned endpoint for third party tools to grab latest API root and see API version status of all versions. 
**Endpoint**
```
192.168.1.1:8989/api
```
**Response**
```
{
"latest": "/api/v3",
"v2": "removed",
"v3": "current"
}
```

New: Base API info endpoint

---

src/NzbDrone.Core.Test/ImportListTests/ImportListSyncServiceFixture.cs
src/NzbDrone.Core.Test/MetadataSource/SkyHook/SkyHookProxySearchFixture.cs
src/NzbDrone.Core/ImportLists/FetchAndParseImportListService.cs
src/NzbDrone.Core/ImportLists/HttpImportListBase.cs
src/NzbDrone.Core/ImportLists/Imdb/ImdbListImport.cs
src/NzbDrone.Core/ImportLists/Imdb/ImdbListParser.cs
src/NzbDrone.Core/ImportLists/Imdb/ImdbListRequestGenerator.cs
src/NzbDrone.Core/ImportLists/Imdb/ImdbListSettings.cs
src/NzbDrone.Core/ImportLists/ImportListSyncService.cs
src/NzbDrone.Core/ImportLists/Plex/PlexListRequestGenerator.cs
src/NzbDrone.Core/MetadataSource/ISearchForNewSeries.cs
src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs
src/NzbDrone.Core/Parser/Parser.cs
src/NzbDrone.Core/Tv/SeriesRepository.cs
src/NzbDrone.Core/Tv/SeriesService.cs

NO
This PR adds IMDB LS Lists as an option for import list. As well this significantly speeds up ImportListSync due to eliminating 2 DB calls per result and instead making the 2 per batch of results. 
This needs to go in before #5235 or be reworked after that's merged
* Fixes #276

Imdb lists

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
The release group HONE does not adhere to the `-RlsGrp` group naming convention, as is the case with some other groups. This PR adds HONE to the existing list of groups that do not adhere to this convention.
Issue 5243: https://github.com/Sonarr/Sonarr/issues/5243
*

Add HONE to list of -RlsGrp exceptions

---

src/NzbDrone.Common/Instrumentation/Sentry/SentryCleanser.cs
src/NzbDrone.Common/Instrumentation/Sentry/SentryTarget.cs
src/NzbDrone.Common/Sonarr.Common.csproj

No
The current Sentry SDK used is 2 years old. Since then, a lost of improvements and fixes were made.
This PR updates the Sentry SDK to the latest with minimal refactoring changes (only removed some options that were assigning default values) and one potential bug fix (a cast).
SDK Diff:
https://github.com/getsentry/sentry-dotnet/compare/2.1.8...3.23.1
Changelog:
https://github.com/getsentry/sentry-dotnet/blob/main/CHANGELOG.md#3231
* Discuss follow ups: Can we add additional Sentry features such as performance monitoring, release health, attachments', etc?
* Would a PR adding [Sentry.NLog](https://www.nuget.org/packages/Sentry.NLog) be beneficial/accepted?
* Didn't open an issue to discuss it since it was a quick change.

Sentry SDK v3.23.1

---

src/NzbDrone.Core/Parser/Parser.cs

The previous PR #5244 can result in false positives if the release contains Hone at the end of any word in its release name. Reference to these posts on discord: https://discord.com/channels/383686866005917708/383687854057979906/1046188758787170387
It should be added to the release groups ending in `)` regex. I've moved it with this PR.
NO
Fix the previous PR
* #5243

Prevent false positives with HONE releases

---

frontend/src/Settings/CustomFormats/CustomFormats/Specifications/EditSpecificationModalContent.js
src/NzbDrone.Core.Test/DecisionEngineTests/QueueSpecificationFixture.cs
src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/Specifications/UpgradeSpecificationFixture.cs
src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs
src/NzbDrone.Core/DecisionEngine/Specifications/QueueSpecification.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs

NO
Make sure CustomFormatCalculationService is always aware of original language for ParsedEpisode scenarios. 
* Fixes #5240

Fixed: Original Language failures on Custom Format parsing

---

src/Sonarr.Api.V3/Episodes/EpisodeController.cs
src/Sonarr.Http/REST/RestController.cs

NO
When accepting a PUT API request, if no Id is passed in the body then the request fails due to resource Id validation. This PR uses the Id from the route in those cases to supplement. The current code requires that an Id always be set in the body resource even though it's set in the route (slightly different behavior than v3). 
Example is episode PUT for monitor toggle with the following payload:
`http://localhost:8989\api\v3\episode\1234`
```
{
monitored: true
}
```
* Fixes #5254

Fixed: Use route Id for PUT requests if not passed in body

---

frontend/src/Episode/Summary/EpisodeFileRow.js
src/Sonarr.Api.V3/Calendar/CalendarController.cs
src/Sonarr.Api.V3/EpisodeFiles/EpisodeFileController.cs
src/Sonarr.Api.V3/EpisodeFiles/EpisodeFileResource.cs
src/Sonarr.Api.V3/Episodes/EpisodeController.cs
src/Sonarr.Api.V3/Episodes/EpisodeControllerWithSignalR.cs
src/Sonarr.Api.V3/Wanted/CutoffController.cs
src/Sonarr.Api.V3/Wanted/MissingController.cs

NO
This change ensures formats are always returned with episode files. Additionally, uses `EpisodeFormats` component in UI for EpisodeSummary which properly handles when formats property is null. 
* Fixes #5268

Fixed: Error on EpisodeFile summary modal if CF is null

---

frontend/src/Settings/UI/UISettings.js
frontend/src/Styles/Themes/index.js
src/NzbDrone.Core/Configuration/ConfigFileProvider.cs

Update Make Auto Theme Default
Co-Authored-By: Qstick <qstick@gmail.com>
NO
Adds support for `prefers-color-scheme` to use the OS preferred theme (light or dark) and also makes it default with the option for the user to force the theme that they want in UI Settings
- N/A
* N/A

New: Auto theme option to match OS theme

---

frontend/src/Settings/ImportLists/ImportLists/EditImportListModalContent.css
frontend/src/Settings/ImportLists/ImportLists/EditImportListModalContent.js
frontend/src/Settings/ImportLists/ImportLists/ImportList.js
frontend/src/Utilities/Date/formatShortTimeSpan.js
src/NzbDrone.Core/Datastore/Migration/178_list_sync_time.cs
src/NzbDrone.Core/Datastore/TableMapping.cs
src/NzbDrone.Core/ImportLists/Custom/CustomImport.cs
src/NzbDrone.Core/ImportLists/FetchAndParseImportListService.cs
src/NzbDrone.Core/ImportLists/IImportList.cs
src/NzbDrone.Core/ImportLists/Imdb/ImdbListImport.cs
src/NzbDrone.Core/ImportLists/ImportListBase.cs
src/NzbDrone.Core/ImportLists/ImportListDefinition.cs
src/NzbDrone.Core/ImportLists/ImportListFactory.cs
src/NzbDrone.Core/ImportLists/ImportListStatus.cs
src/NzbDrone.Core/ImportLists/ImportListStatusService.cs
src/NzbDrone.Core/ImportLists/Plex/PlexImport.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrImport.cs
src/NzbDrone.Core/ImportLists/Trakt/TraktImportBase.cs
src/NzbDrone.Core/Jobs/TaskManager.cs
src/Sonarr.Api.V3/ImportLists/ImportListResource.cs

YES `(178 - Add LastSync Column to List Status Table)`
This makes a few changes to move list sync interval from global to by list implementation, allowing ListTypes which are user controlled (Sonarr Instances) to be minimal, while lists like Trakt and Plex remain more conservative. 
Currently Min Intervals by type are setup like so:
```
Sonarr - 5 mins
Plex - 6 hours (we can adjust this based on teams thoughts)
Trakt - 12 hours
IMDb - 12 hours
Custom - 6 hours
```
I choose not to make list interval user adjustable, but that's an easy add if we think that's useful in addition (this comes down to if we think users want something greater than the min intervals)
* Fixes #5011

New: Rework List sync interval logic

---

frontend/src/InteractiveImport/Interactive/InteractiveImportModalContent.js
frontend/src/InteractiveImport/Interactive/InteractiveImportRow.css
frontend/src/InteractiveImport/Interactive/InteractiveImportRow.js
src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportItem.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs
src/Sonarr.Api.V3/ManualImport/ManualImportResource.cs

NO
Builds on top of the custom work refactoring/changes in `episode-titles-with-language` to add custom formats to Manual Import / Manage Episodes
* Closes #5241

Custom formats in Manual Import / Manage Episodes

---

.github/ISSUE_TEMPLATE/bug_report.yml

NO
field was over 200 chars and apparently not valid! Causes bug report template to not show on the new issues page.

Fix bug_report.yml description field

---

src/Sonarr.Api.V3/Blocklist/BlocklistResource.cs
src/Sonarr.Api.V3/CustomFormats/CustomFormatController.cs
src/Sonarr.Api.V3/CustomFormats/CustomFormatResource.cs
src/Sonarr.Api.V3/EpisodeFiles/EpisodeFileResource.cs
src/Sonarr.Api.V3/History/HistoryResource.cs
src/Sonarr.Api.V3/Indexers/ReleaseResource.cs
src/Sonarr.Api.V3/ManualImport/ManualImportResource.cs
src/Sonarr.Api.V3/Queue/QueueResource.cs

NO
As discussed on Discord this reduces the size of responses that include Custom Formats outside of `CustomFormatController` responses that need the full information.

New: Reduce size of Custom Formats in responses for most endpoints

---

src/NzbDrone.Core.Test/MediaFiles/DownloadedEpisodesImportServiceFixture.cs
src/NzbDrone.Core/Download/CompletedDownloadService.cs
src/NzbDrone.Core/MediaFiles/DownloadedEpisodesImportService.cs
src/NzbDrone.Core/MediaFiles/FileExtensions.cs

NO
Show warning in queue if download contains executable or archive file and no video file was detected, instead of a generic message that no video files were found.
* Closes #5101

Improve handling of releases without video files

---

frontend/src/Components/ProgressBar.css
frontend/src/Styles/Themes/dark.js
frontend/src/Styles/Themes/light.js

NO
Buggered up my local git so continuation of this [PR 5293](https://github.com/Sonarr/Sonarr/pull/5293)
Fixed the progress bar text colors so that they are white regardless of the background, for some reason there was a weird bug causing different parts of the episode progress text to be different colors as the bar moved along as shown in the image
Moved the text to be a variable so can be changed depending on theme
- 
*

Fixed: Progress bar text colour in Dark theme

---

src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs

NO
currently for episodes with multiple subs, only one subtitle element is created as follows:
```
<subtitle>
<language>engengengaracatczedangergergergrespaspabaqfinfilfreglghebhrvhuninditajpnkormaynobdutpolporporrumrusswethaturukrviechichi</language>
</subtitle>
```
as per https://kodi.wiki/view/NFO_files/Movies multiple subtitle elements are allowed, where https://github.com/xbmc/xbmc/blob/master/xbmc/video/VideoInfoTag.cpp iterates through them.
This PR creates a seperate subtitle element for each langugae

Fixed: Kodi Metadata Subtitle Language

---

src/NzbDrone.Core.Test/DecisionEngineTests/UpgradeAllowedSpecificationFixture .cs
src/NzbDrone.Core/DecisionEngine/Specifications/QueueSpecification.cs
src/NzbDrone.Core/DecisionEngine/Specifications/UpgradableSpecification.cs
src/NzbDrone.Core/DecisionEngine/Specifications/UpgradeAllowedSpecification.cs

NO
Fixes custom format upgrades when the quality profile doesn't allow upgrading.
* Closes #5330

Fixed: Custom Formats upgrading even when profile doesn't allow upgrades

---

src/NzbDrone.Core.Test/Housekeeping/Housekeepers/CleanupQualityProfileFormatItemsFixture.cs
src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupQualityProfileFormatItems.cs
src/NzbDrone.Core/Profiles/Qualities/QualityProfileRepository.cs
src/NzbDrone.Core/Profiles/Qualities/QualityProfileService.cs

NO
Two different fixes for Quality profiles that contain invalid items, one to make sure we can still return profiles despite them being wrong and the other to actually clean them up.
I first looked to move from the events to update CFs in profiles, but the dependencies there were pretty messy to resolve and could lead to different issues trying to untangle.
* Closes #5323

Fixed: Unable to load UI if Quality Profiles contain removed Custom Format items

---

src/NzbDrone.Core.Test/ParserTests/UnicodeReleaseParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Some Chinese release group (Lilith-Raws && LoliHouse) are using Season number + Episode Number in  `Sxx - xx` format, which leads the Parser using Absolute Episode Number instead of Episode Number causing import errors.
`[Lilith-Raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka S04 - 12 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4`
`[Lilith-Raws][ Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka S04][12][Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4`
This patch will normerlize it to SxxExx Format only for these two release groups
`[Lilith-Raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka S04E12 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4`
```
2023-01-08 14:40:43.0|Debug|Parser|Parsing string '[Lilith-Raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru …
```

Fixed: Chinese releases with season and absolute episode numbers

---

frontend/src/Settings/Profiles/Delay/EditDelayProfileModalContent.js
src/NzbDrone.Core.Test/DecisionEngineTests/RssSync/DelaySpecificationFixture.cs
src/NzbDrone.Core/Datastore/Migration/182_add_bypass_to_delay_profile.cs
src/NzbDrone.Core/DecisionEngine/Specifications/RssSync/DelaySpecification.cs
src/NzbDrone.Core/Profiles/Delay/DelayProfile.cs
src/Sonarr.Api.V3/Profiles/Delay/DelayProfileResource.cs

YES - 182
Adds two more options to Delay Profiles which will bypass the delay profile if a minimum CF score is reached.
A few things:
- This operates independently from the quality bypass
- The minimum value is based on a second property in the delay profile, alternatively it could use the minimum score or cutoff from the profile instead, which would make it less related to the profile's scoring
- If we want to switch this to requiring both quality and score if configured it'd be possible with some changes (and potentially could be another value for the delay profile)
* Closes #4711

New: Add bypass if above Custom Format Score to Delay Profile

---

frontend/src/Activity/History/HistoryRow.js
frontend/src/Episode/History/EpisodeHistoryRow.js
src/NzbDrone.Core/History/HistoryService.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs
src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/DownloadMessage.cs
src/NzbDrone.Core/Notifications/Notifiarr/Notifiarr.cs
src/NzbDrone.Core/Notifications/NotificationService.cs
src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookCustomFormat.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookCustomFormatInfo.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookGrabPayload.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookImportPayload.cs
src/NzbDrone.Core/Parser/Model/LocalEpisode.cs
src/Sonarr.Api.V3/History/HistoryResource.cs

NO
This now stores CF score when importing episodes to align with grabs, but other events would still be lacking this score so it feels a bit janky, but not sure we want to store it for others or at all. Given CF is recalculated for everything else should the score be as well? Should we have some sort of caching for CF to allow quicker look ups when given the same information over and over?
* Closes #5291

Fixed: Store Custom Format score during import

---

src/NzbDrone.Core/Sonarr.Core.csproj

NO
TVDB Image conversions when uploading PNGs seem to be just changing the file extension, thus many images are PNG saved as JPG. There is an old bug in ImageSharp when handling these. 
Pulls in this https://github.com/SixLabors/ImageSharp/issues/1704

Bump ImageSharp to 2.1.3

---

frontend/src/Calendar/Events/CalendarEventGroup.css

NO
Fixes incorrect series title color in calendar event groups that have been collapsed
- N/A
* #5353

Fixed: Calendar Grouped Series Title

---

frontend/src/Settings/MediaManagement/Naming/NamingModal.js
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/CleanTitleWithoutYearFixture.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/TitleTheWithoutYearFixture.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/TitleWithoutYearFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs
src/NzbDrone.Core/Organizer/FileNameValidation.cs

NO
adds the naming tokens: 
* `{Series TitleWithoutYear}`
* `{Series TitleTheWithoutYear}`
* `{Series CleanTitleWithoutYear}`
* fixes #5369

New: Added new series title rename tokens without year

---

src/NzbDrone.Core/Tv/EpisodeCutoffService.cs

NO
If the cutoff quality on every profile is the lowest quality, `qualitiesBelowCutoff` will be empty in EpisodeCutoffService. This results in SQLite error when query is run on the DB due to the Where clause calculating to `AND ()`. This fix returns empty list before going into Repo.
```
System.Data.SQLite.SQLiteException: 'SQL logic error
near ")": syntax error'
```
Ref: https://github.com/Readarr/Readarr/issues/1911

Fixed: Avoid Sqlite Error when all profiles have lowest quality cutoff

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs

NO
Logs at warn that parse is being skipped; previously this was not clearer to the user
- Tests
- Wiki Updates
* https://forums.sonarr.tv/t/sonarr-v4-interactive-manual-import-not-detecting-series/31336

New: Improve Manual Import logging when not parsing files

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

NO
release names containing REPACK2 (etc) don't get parsed as a repack
* fixes #5383

Fixed: Enable parsing of repacks with revision

---

src/NzbDrone.Core.Test/ParserTests/UnicodeReleaseParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Updated: 2013/01/18
This fix is a continuation to https://github.com/Sonarr/Sonarr/pull/5356
After the patch https://github.com/Sonarr/Sonarr/pull/5356
Sonarr can correctly grab
`[Lilith-Raws] 致不灭的你 / Anime-Series Title S02 - 12 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4]`
as `Season 2`. 
But when importing them from download clients, sonarr still imported it to `Season 1`
The root cause of this type of bug:
1. Sonarr will parse 2 different names when downloading series.
One is release name, in this case: `[Lilith-Raws] 致不灭的你 / Anime-Series Title S02 - 12 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4]`.
The other one is downloaded file name, in this case: `[Lilith-Raws] Anime-Series Title S02 - 11 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4`.
2. XEM normaly doesn't have `S02` alias.
3. The …

Fixed: Chinese Anime releases that include a season number

---

src/NzbDrone.Common/EnvironmentInfo/IRuntimeInfo.cs
src/NzbDrone.Common/EnvironmentInfo/RuntimeInfo.cs
src/NzbDrone.Host/AppLifetime.cs
src/NzbDrone.Host/Startup.cs
src/Sonarr.Http/Middleware/StartingUpMiddleware.cs

NO
Returns a 503 response as plain text or JSON when Sonarr hasn't finished starting up, but the web server is online. In the future we could look at running migrations after the web server starts to provide feedback.
* Closes #5402

New: Return static response to requests while app is starting

---

frontend/src/SeasonPass/SeasonPassSeason.css

NO
the readability of complete seasons on season pass is not great. changed from light gray to dark gray:
to 
*

Fixed: text color of complete seasons dark mode

---

src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabFixture.cs
src/NzbDrone.Core.Test/IndexerTests/TorznabTests/TorznabFixture.cs
src/NzbDrone.Core/Indexers/Newznab/Newznab.cs
src/NzbDrone.Core/Indexers/Torznab/Torznab.cs

Max of Default or Max and no more than 100
NO
Change Newznab/Torznab logic to to use the largest page size of DefaultPageSize or MaxPageSize with a hardcoded max cap of 100
- Wiki Updates
* Fixes: #5373

New: Use better page size for Newznab/Torznab (up to 100) when supported by the indexer

---

frontend/src/Series/History/SeriesHistoryRow.js

NO
@markus101 updated episode history to show freshly calculated custom format score (rather than the one stored at time of import) in #5292. However, series and season history still show the stored value. This PR updates series and season to display the freshly calculated score.
*

Fixed: Show calculated (rather than stored) custom format score on season and series history, to match episode history

---

frontend/src/Components/FileBrowser/FileBrowserModalContent.js

NO
fixes error with mono: "error  'ReactDOM' is defined but never used  no-unused-vars"

Remove unused ReactDOM import

---

src/NzbDrone.Core/Parser/ParsingService.cs

NO
mapping all titles
release: `Одни из нас (The Last of Us) S1E1-7 (2023)`
it is parsed as two title:
- `Одни из нас`
- `The Last of Us`
error: `Release Rejected: Unknown Series`
mapped

Fixed: Mapping of parsed titles when one doesn't have an alias

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/TransmissionTests/TransmissionFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/VuzeTests/VuzeFixture.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionTorrent.cs

NO? (I don't think so but please double check)
fixes #5444
[The transmission API spec](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md) defines where the [Eta field is declared](https://github.com/transmission/transmission/blob/9d310b3a4d4a3fb119993e65f07ac5e80dde662a/libtransmission/transmission.h#L1439) and it derives from t_time [which can be int32 or int64](https://stackoverflow.com/questions/471248/what-is-time-t-ultimately-a-typedef-to).
My guess is that during their v4 upgrade, the upgraded underlying libs which moved to int64 to anticipate the 2038 limit on unix timestamps.
This PR changes the field on the client side from int to int64 (long) to address the overflow issue
*

Fixed: Processing very long ETA from Transmission 

---

src/NzbDrone.Core.Test/ParserTests/SeasonParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Adds matching of a multi-season pack if there is only a space between the two season numbers.
Also strips the text "Complete Series" from a potential title match in multi-season packs/
*

Fixed: Parsing of multi season packs with only space between the season numbers

---

src/NzbDrone.Core/Notifications/Discord/Discord.cs
src/NzbDrone.Core/Notifications/Discord/DiscordFieldType.cs

NO
When the OnGrab Discord notification is triggered it can now display the Indexer's name from the grab.
- [-] Tests: [no tests](https://github.com/lodu/Sonarr/tree/discord-notification-grab-indexer/src/NzbDrone.Core.Test/NotificationTests)
- [-] Wiki Updates: [no wiki entry for fields](https://wiki.servarr.com/sonarr/supported#notifications)

New: Add indexer option for Discord on grab notifications

---

src/NzbDrone.Common/Composition/AssemblyLoader.cs
src/NzbDrone.Common/OAuth/WebParameterCollection.cs
src/NzbDrone.Core/DataAugmentation/DailySeries/DailySeriesDataProxy.cs
src/NzbDrone.Core/Datastore/BasicRepository.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxyV1.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationTaskProxyV2.cs
src/NzbDrone.Core/Extras/Metadata/MetadataService.cs
src/NzbDrone.Core/ImportLists/Simkl/SimklImportBase.cs
src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
src/NzbDrone.Core/Indexers/RssParser.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs
src/NzbDrone.Core/Tv/RefreshEpisodeService.cs
src/Sonarr.Api.V3/ProviderControllerBase.cs
src/Sonarr.Http/REST/RestController.cs

NO
This PR fixes just a few multiple enumerations and reduces number of allocations by using Array.Empty

Use Array.Empty and fix a few multiple enumerations

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

NO
- simplifes regex for quality parser per [IDE0090](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0090)
- don't parse remux 720p as1080p remux and let it fall back through to BR 720p
- for non-720p resolution, still assume unknown remux is 1080p remux
- fix incorrect AnimeRemux source logic - was incorrectly treating a sourceless remux as BR and not Remux
- Wiki Updates
* Fixes #5517

Quality Parser Improvements -

---

src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs

NO
Fixed matching of Release Title custom formats during import by populating empty `CustomFormatInput` properties from `LocalEpisode` that are relied on when `SceneName` is not parsed.
* A release may be grabbed by Sonarr as a custom format upgrade then blocked with warnings indicating that the file(s) are not custom format upgrades for existing episode file(s).

Fixed: Matching of custom formats during episode file import

---

src/NzbDrone.Common/Disk/DiskProviderBase.cs
src/NzbDrone.Core/Download/Pending/PendingReleaseService.cs
src/NzbDrone.Core/History/HistoryRepository.cs
src/NzbDrone.Core/RootFolders/RootFolderService.cs
src/NzbDrone.Core/SeriesStats/SeriesStatisticsService.cs
src/NzbDrone.Core/Tv/ShouldRefreshSeries.cs

NO
This PR replaces `OrderBy().First()` by less resource-intensive `MinBy` and `MaxBy`.
Very simple benchmark:
```
public class Bench
{
private IEnumerable<int> numbers = Enumerable.Range(0, 100).OrderBy(_ => Random.Shared.Next()).ToArray();
[Benchmark]
public void Order()
{
var max = numbers.OrderBy(_ => _).First();
}
[Benchmark]
public void Min()
{
var max = numbers.MinBy(_ => _);
}
}
```
```
| Method |     Mean |   Error |  StdDev |   Gen0 | Allocated |
|------- |---------:|--------:|--------:|-------:|----------:|
|  Order | 807.8 ns | 1.68 ns | 1.49 ns | 0.0010 |     128 B |
|    Min | 512.0 ns | 9.53 ns | 7.96 ns |      - |      32 B |
```

Use MinBy and MaxBy instead of OrderBy + First

---

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs

NO
After the correct functionality was fixed in 5326a102e23eacfc1132eb544a92af737a531df5, the values are now case sensitive. Should we support the old broken behavior with `ignoreCase: true`?

Fixed: Config file settings do not need to be case-sensitive

---

src/NzbDrone.Core/Indexers/Newznab/Newznab.cs

NO
https://github.com/Prowlarr/Prowlarr/commit/55788ac04dea7adfd3b678b6df9e4631abd037be
`https://api.drunkenslug.com/ gives a 301`
- Tests
- Wiki Updates
*

Fixed: DrunkenSlug Default URL

---

src/NzbDrone.Core.Test/MediaFiles/MediaInfo/MediaInfoFormatterTests/FormatVideoCodecFixture.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs

NO
There are many cases where the primary video stream on a file is an `mjpeg` or `png` codec and the secondary stream is the actual stream. This PR attempts to be a bit smarter in selecting the primary video stream by bypassing the motion image stream. 
Also, a few tweaks to the formatter for other codecs seen in Sentry
Example:
```json
[
{
"index":0,
"codec_name":"mjpeg",
"codec_long_name":"Motion JPEG",
"profile":"Progressive",
"codec_type":"video",
"codec_tag_string":"[0][0][0][0]",
"codec_tag":"0x0000",
"width":2000,
"height":3000,
"coded_width":2000,
"coded_height":3000,
"closed_captions":0,
"film_grain":0,
"has_b_frames":0,
"sample_aspect_ratio":"1:1",
"display_aspect_ratio":"2:3",
"pix_fmt":"yuvj420p",
"level":-99,
"color_range":"pc",
"color_space":"bt470bg", …
```

Mediainfo improvements

---

src/NzbDrone.Core/Backup/BackupService.cs

(cherry picked from commit 43fa4cb5b9dca1aed25acb169c63ddd9a8e2712b)
NO
Currently `CreateVersionInfo` doesn't seem to do anything, so I'm thinking of adding version and timestamp to the zip file.

New: Add version and timestamp to backup archive

---

frontend/src/InteractiveSearch/InteractiveSearchRow.css
frontend/src/InteractiveSearch/InteractiveSearchRow.tsx

NO
Fixed: Spacing between manual download and override download buttons
*

Fixed: Spacing between manual download and override download buttons

---

frontend/src/Styles/Themes/dark.js

a number of colour definitions for border hovers had semi-colons in them.
NO
Fixed: Border hover colors in dark theme
*

Fixed: Border hover colors in dark theme

---

src/NzbDrone.Core/ImportLists/Sonarr/SonarrAPIResource.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrImport.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrSettings.cs
src/NzbDrone.Core/ImportLists/Sonarr/SonarrV3Proxy.cs

NO
Adds the option to filter imports from other Sonarr instances by Root Folder. 
Also updates the helptexts for URL and API key to not specify Sonarr V3. 
* #4835

New: Filter Sonarr synchronization based on Root Folders

---

src/NzbDrone.Core.Test/IndexerTests/RarbgTests/RarbgFixture.cs
src/NzbDrone.Core/Indexers/Rarbg/Rarbg.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgParser.cs
src/NzbDrone.Core/Indexers/Rarbg/RarbgTokenProvider.cs

* Added app_id to captcha check to avoid 403 forbidden error
* Migrated app_id from hard coded to BuildInfo.AppName
NO
Previously the captcha check threw an exception in the logs since RARBG's API responds with 403 forbidden if `app_id` is skipped/overlooked in the query. I also took the opportunity to update `app_id` from hard coded to use the `BuildInfo.AppName` value instead.

Use BuildInfo.AppName for RARBG appId instead of hardcoded value

---

src/NzbDrone.Core/Extras/Subtitles/ExistingSubtitleImporter.cs
src/NzbDrone.Core/Extras/Subtitles/SubtitleService.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

When renaming episodes with associated subtitle files that weren't directly imported by Sonarr, subtitle tags like SDH, Forced, HI, would be lost. This affected setups like Bazarr or other ways of manually putting subtitle files in the series' folder. Files imported alongside video files in automatic or manual imports weren't affected.
Tags were already getting parsed, but weren't getting passed along to the records. 
* #5577

Fixed: Subtitle tags from existing subtitle files being lost during rename

---

frontend/build/webpack.config.js

NO
The jQuery npm package comes with a minified version of the library, by using this in the webpack build, we can decrease module size by a few hundred kilobytes.
```
OLD
modules by path ./node_modules/ 5.77 MiB 597 modules
NEW
modules by path ./node_modules/ 5.56 MiB 491 modules
```

Use minified jquery

---

package.json
yarn.lock

NO
This updates `core-js` to the latest version and switches the browserslist used to determine which features to polyfill to the default which is `> 0.5%, last 2 versions, Firefox ESR, not dead`. 
This leads to a reduction of bundle size of ~400kb
```
OLD
modules by path ./frontend/src/ 2.59 MiB
NEW
modules by path ./frontend/src/ 2.12 MiB
```
Here is a diff for what that means in terms of supported browsers:

New: Update core-js and use better polyfill defaults

---

src/NzbDrone.Core/Queue/QueueService.cs

NO
Queue doesn't use the augmented languages from RemoteEpisode. This fixes.

Fixed: Use augmented languages for queue items

---

frontend/src/Styles/Themes/dark.js

NO
This upgrades the border color for buttons and the calendar grid from very bright to a pleasant darker color.
I assume that these were never supposed to be that bright considering dark mode is still work in progress(?).
There is a consideration to use the same color as the calendar headers for the calendar borders (#2a2a2a) so the connections look a bit more natural but that is also very close to the background color, contrast wise, and almost makes them disappear. Please let me know if you'd prefer that.

New: Updated button and calendar outline colors for dark theme

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/Blackhole/TorrentBlackholeFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/Blackhole/UsenetBlackholeFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/DelugeTests/DelugeFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadClientFixtureBase.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/TorrentDownloadStationFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadStationTests/UsenetDownloadStationFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/FreeboxDownloadTests/TorrentFreeboxDownloadFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/HadoukenTests/HadoukenFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/NzbVortexTests/NzbVortexFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/NzbgetTests/NzbgetFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/PneumaticProviderFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/RTorrentTests/RTorrentFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/SabnzbdTests/SabnzbdFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/TransmissionTests/TransmissionFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/UTorrentTests/UTorrentFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/VuzeTests/VuzeFixture.cs
src/NzbDrone.Core.Test/Download/DownloadServiceFixture.cs
src/NzbDrone.Core/Download/Clients/Pneumatic/Pneumatic.cs
src/NzbDrone.Core/Download/DownloadClientBase.cs
src/NzbDrone.Core/Download/DownloadService.cs
src/NzbDrone.Core/Download/IDownloadClient.cs
src/NzbDrone.Core/Download/TorrentClientBase.cs
src/NzbDrone.Core/Download/UsenetClientBase.cs
src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
src/NzbDrone.Core/Indexers/IIndexer.cs
src/NzbDrone.Core/Indexers/IndexerBase.cs

NO
This allows building the HTTP request from the indexer implementation, eg. when custom headers like authorization are needed.
Example for RED in Lidarr, since this is how I discovered the inability for this:
```csharp
public override HttpRequest GetDownloadRequest(Uri link)
{
var request = new HttpRequestBuilder(link.AbsoluteUri)
.SetHeader("Authorization", Settings.ApiKey)
.Build();
return request;
}
```
Also fixing the redirect without host issue in `DownloadFromWebUrl`.

Build download requests from indexer implementation

---

frontend/.eslintrc.js

NO
Fix loading eslintrc by using relative path to itself.
```
Error: Cannot read config file: ~/Projects/Sonarr/frontend/.eslintrc.js
Error: ENOENT: no such file or directory, scandir 'frontend/src'
```

Fix loading eslintrc

---

src/NzbDrone.Core/Download/DownloadService.cs
src/NzbDrone.Core/Download/TorrentClientBase.cs
src/NzbDrone.Core/Download/UsenetClientBase.cs

NO
Changed the download request not to assume the indexer is always defined.
* Fixes #5606

Fix downloading releases without an indexer

---

src/NzbDrone.Host/Bootstrap.cs

NO
Cherry-picks from Prowlarr:
- Catch InvalidDataException during initial config to prevent boot loop
- Provide a nicer error message if the config file is invalid, and logging the exception so the user can see the stack trace to know exactly what was the issue with loading the XML file.

Catch and log errors when loading invalid config file

---

package.json
yarn.lock

NO
Not in use, eslint is using @babel/eslint-parser as parser now.
[babel-eslint is now @babel/eslint-parser](https://github.com/babel/babel-eslint)

Downgrade rimraf to v4

---

frontend/src/Calendar/iCal/CalendarLinkModalContent.js
frontend/src/Components/SignalRConnector.js
src/NzbDrone.Core/HealthCheck/Checks/ApiKeyValidationCheck.cs

NO
Allow usage of `#` in the API key.
Radarr/Radarr#8441

Fix usage of special characters in apikey

---

src/NzbDrone.Core/ThingiProvider/ProviderFactory.cs
src/NzbDrone.Core/ThingiProvider/ProviderRepository.cs

NO
Fix for `System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')` when a config contract is missing.
```
System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')
at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
at NzbDrone.Core.ThingiProvider.ProviderRepository`1.Query(SqlBuilder builder) in ~/RiderProjects/Radarr/src/NzbDrone.Core/ThingiProvider/ProviderRepository.cs:line 63
at NzbDrone.Core.Datastore.BasicRepository`1.All() in ~/RiderProjects/Radarr/src/NzbDrone.Core/Datastore/BasicRepository.cs:line 88
at NzbDrone.Core.ThingiProvider.ProviderFactory`2.All() in ~/RiderProjects/Radarr/src/NzbDrone.Core/ThingiProvider/ProviderFactory.cs:line 39
at …
```

Fixed: Prevent ProviderRepository to deserialize to a null config contract

---

src/NzbDrone.Mono/Disk/DiskProvider.cs

NO
A workaround in showing the mount point(s) that fail in errors like:
```
2023-05-16 17:05:35.9|Warn|DiskProvider|Unable to get drive mounts: Access to the path is denied.
[v4.5.1.7282] System.UnauthorizedAccessException: Access to the path is denied.
---> System.IO.IOException: Operation not permitted
--- End of inner exception stack trace ---
at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
at System.IO.DriveInfo.get_DriveFormat()
at NzbDrone.Mono.Disk.DiskProvider.<>c.<GetAllMounts>b__16_0(DriveInfo d) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 185
at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 …
```

Show name of mount points that fail in DiskProvider

---

src/Sonarr.Api.V3/ProviderControllerBase.cs

NO
I didn't add this in #5612 since I'm wary about this, but since it's something supported I'll leave it up to you to decide.

Add `forceSave` to the OpenAPI docs

---

src/NzbDrone.Core/Indexers/Newznab/NewznabRssParser.cs
src/NzbDrone.Core/Indexers/Torznab/TorznabRssParser.cs

NO
After complains from @bakerboy448 that `Unable to connect to indexer. Indexer API call resulted in an unexpected StatusCode [Forbidden]` is too generic, let's use the error message from the response body if the Content-Type contains `xml`.

Fixed: Use indexer errors from response if Content-Type is XML before processing response

---

src/NzbDrone.Core/Validation/FolderValidator.cs
src/NzbDrone.Core/Validation/NzbDroneValidationExtensions.cs
src/NzbDrone.Core/Validation/NzbDroneValidationFailure.cs
src/NzbDrone.Core/Validation/NzbDroneValidationResult.cs
src/NzbDrone.Core/Validation/Paths/FileExistsValidator.cs
src/NzbDrone.Core/Validation/Paths/FolderWritableValidator.cs
src/NzbDrone.Core/Validation/Paths/PathExistsValidator.cs
src/NzbDrone.Core/Validation/Paths/PathValidator.cs
src/NzbDrone.Core/Validation/Paths/RecycleBinValidator.cs
src/NzbDrone.Core/Validation/Paths/RootFolderAncestorValidator.cs
src/NzbDrone.Core/Validation/Paths/RootFolderValidator.cs
src/NzbDrone.Core/Validation/Paths/SeriesAncestorValidator.cs
src/NzbDrone.Core/Validation/Paths/SeriesPathValidator.cs
src/NzbDrone.Core/Validation/Paths/StartupFolderValidator.cs
src/NzbDrone.Core/Validation/Paths/SystemFolderValidator.cs
src/NzbDrone.Core/Validation/UrlValidator.cs
src/Sonarr.Api.V3/Series/SeriesFolderAsRootFolderValidator.cs

NO
This is redundant from the start when using the UI, but logs with `Path: Folder is not writable by user abc` or `RootFolderPath: Invalid Path` aren't helpful at all for support or the users.
Should I continue with the rest of them?

New: Improve validation messages

---

frontend/src/Series/Index/SeriesIndex.tsx
frontend/src/Series/Index/SeriesIndexRefreshSeriesButton.tsx
src/NzbDrone.Core.Test/TvTests/RefreshSeriesServiceFixture.cs
src/NzbDrone.Core/Tv/Commands/RefreshSeriesCommand.cs
src/NzbDrone.Core/Tv/RefreshSeriesService.cs
src/NzbDrone.Core/Tv/SeriesAddedHandler.cs
src/NzbDrone.Core/Tv/SeriesEditedService.cs
src/NzbDrone.Integration.Test/IntegrationTestBase.cs

NO
Brings in the functionality already present in Radarr to allow the update series button to only update the selected items or the filtered items.
* closes #5611

New: refresh only selected or filtered series

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
On a number of sites Vyndros releases are irregularly named, for example:
this PR adds them to the release group exception list
*

Capture Vyndros releases ending in a )

---

src/Directory.Build.props

(cherry picked from commit fb908e8e1969e633a50ca000c767a998427363b2)
NO
This just uses the project name as relative path in the exceptions, for example:
```
[v10.0.0.41853] System.Net.Http.HttpRequestException: Connection refused (localhost:8080)
---> System.Net.Sockets.SocketException (61): Connection refused
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at …
```

Use project name as relative path in builds

---

frontend/src/Store/Actions/releaseActions.js
src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs

NO
This is to fix sorting by empty languages in https://github.com/Sonarr/Sonarr/blob/f05405fe1ce4c78a8c75e27920c863c5b83686bd/frontend/src/Store/Actions/releaseActions.js#L47 which does the same as https://github.com/Sonarr/Sonarr/blob/f05405fe1ce4c78a8c75e27920c863c5b83686bd/src/NzbDrone.Core/Parser/ParsingService.cs#L194 for a successful parsing. 
Before
After

 Fix sorting search releases by language

---

.github/workflows/api_docs.yml

NO
Adds `ignore-downstream` as discussed to extended description of API doc commits

Ignore API doc commits downstream

---

frontend/src/Content/Images/Icons/manifest.json

NO
This patches the manifest.json file to use relative paths instead of absolute paths, allowing the webapp to be installable when using an alternative URL root without redirects set up.
So far I've only tested on one browser (Edge on Windows)
N/A
* Closes #5688

Fix: Use relative paths instead of absolute paths for webmanifest

---

src/Directory.Build.props
src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs
src/NzbDrone.Common/OAuth/OAuthRequest.cs
src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/Specifications/MatchesGrabSpecificationFixture.cs
src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssSettingsDetector.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Aggregation/Aggregators/AggregateReleaseInfo.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs
src/NzbDrone.Core/MediaFiles/ScriptImportDecider.cs
src/NzbDrone.Core/MediaFiles/UpgradeMediaFileService.cs
src/NzbDrone.Core/Notifications/NotificationService.cs
src/NzbDrone.Core/Notifications/Signal/SignalError.cs
src/NzbDrone.Core/Notifications/Signal/SignalProxy.cs
src/Sonarr.Api.V3/Episodes/EpisodeController.cs
src/Sonarr.Api.V3/Series/SeriesController.cs

NO
Since c6b543e0729bc20f15e37d074fbf31d8c76c187a apparently a few unused import already got in, thus let's add a Github Action to prevent this.
I noticed the build.sh is little different from downstream and if I'm assuming correctly that in TC it's used with `build.sh --all` and not step by step like `build.sh --lint`, then I think I can add `LintBackend` to run on `$LINT_BACKEND == "YES"`.

Enforce rule IDE0005 on build

---

frontend/src/Store/Actions/Creators/createSaveProviderHandler.js
src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs
src/NzbDrone.Core/Indexers/SeedCriteriaSettings.cs
src/NzbDrone.Core/Indexers/Torznab/TorznabSettings.cs
src/NzbDrone.Core/Validation/NzbDroneValidationExtensions.cs
src/Sonarr.Api.V3/ProviderControllerBase.cs

NO
~~Validation with `AsWarning()` doesn't work nice with arrs, and this might a regression from b95c4d37d7e1c2d699dbfd995b496a2fffde6705 allowing use of <= 0 values.~~
~~Since I fixed this in Prowlarr a while ago a few users [complained](https://github.com/Prowlarr/Prowlarr/issues/1692) that Prowlarr doesn't allow `0` and Sonarr/Radarr does.~~
~~Should we allow >= 0 or stick to `>0`?~~
Fix showing warnings in provider validation.

Fixed: Enforce validation warnings

---

src/NzbDrone.Core/Tags/TagService.cs
src/NzbDrone.Core/Tv/SeriesRepository.cs
src/NzbDrone.Core/Tv/SeriesService.cs

NO
Avoid `AllSeries` call on Tag UI page, particularly detrimental on large libraries. 
Pulled from Radarr

Faster tag view in UI for large libraries

---

frontend/src/Components/ProgressBar.css
frontend/src/Components/ProgressBar.js

NO
Going from #5705, I moved the styles for kinds to be more specific.
Also adding kind to Text Containers should allow us to modify front & back styles more easily depending on the kind:
```scss
.frontTextContainer {
z-index: 1;
color: var(--progressBarFrontTextColor);
&.success {
color: var(--black);
}
}
```

Use more specific styling for kinds in ProgressBar

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

NO
Fixes Unknown download state: checkingResumeData
- Tests
- Wiki Updates
*

Fixed: (Qbittorrent) Handle checkingResumeData

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
- Cleanse only the RSS subdomains for torrentleech
- Cleanse username in paths containing home directory for Mac users
Better viewed with `?w=1` since the indentation was off.

Update cleansing rules for RSS TL feed and homedir for Mac

---

src/NzbDrone.Core/HealthCheck/Checks/DownloadClientSortingCheck.cs

NO
If marked as failed already there's no need to check for the sorting mode anymore since it's expected to fail.

Check only clients not in failure status in DownloadClientSortingCheck

---

src/NzbDrone.Core/Notifications/Discord/Discord.cs

See https://discord.com/developers/docs/resources/channel#embed-object-embed-limits
NO
For long embed titles, Discord will reject the embed with a 400. This limits the embed title length to 256 characters max.
*

Limit Discord embed title length to 256 characters

---

src/Sonarr.Api.V3/Health/HealthController.cs
src/Sonarr.Api.V3/Indexers/ReleaseControllerBase.cs
src/Sonarr.Api.V3/Profiles/Languages/LanguageProfileSchemaController.cs
src/Sonarr.Api.V3/ProviderControllerBase.cs
src/Sonarr.Api.V3/Queue/QueueController.cs
src/Sonarr.Api.V3/Queue/QueueDetailsController.cs
src/Sonarr.Api.V3/Queue/QueueStatusController.cs
src/Sonarr.Api.V3/openapi.json
src/Sonarr.Http/REST/RestController.cs

NO
I noticed some endpoints aren't implemented but still present in the API docs. 
I can remove the openapi.json from the commit, but I pushed it only to see the differences along with the changes.

Remove not implemented endpoints from API docs

---

frontend/src/Series/Details/SeriesDetails.js

NO
Series with no fanart (eg. tvdb:423396) make an unnecessary request to `/series/undefined`.

Don't set background image to `undefined` when fanart is missing

---

src/NzbDrone.Common/Serializer/Newtonsoft.Json/Json.cs
src/NzbDrone.Core/Indexers/HDBits/HDBitsRequestGenerator.cs

NO
- Added overload for use with `x.ToJson(Formatting.None)` to prevent spamming the logs across multiple lines.
- As an example added ContentSummary for HDBits for easier debugging.

Create overload for `ToJson()` with Formatting param

---

src/NzbDrone.Core.Test/Datastore/Migration/192_import_exclusion_typeFixture.cs
src/NzbDrone.Core/Datastore/Migration/192_import_exclusion_type.cs

YES (192 Type Alteration for TvdbId on Import List Exclusions)
Change TvdbId column to correct type. Sqlite doesn't really care, but other DB types will

Fixed: Correct typing for ImportListExclusions tvdbid column

---

src/Sonarr.Api.V3/System/Backup/BackupController.cs

NO
Allow backup uploads up to 500MB for upload endpoint only. We can disable size completely, but this may result in allowing uploads up to 2GB (max int size) which I'm not quite sure we want to do. 
* Fixes #5725

Fixed: Allow restore to process backups up to ~500MB

---

src/NzbDrone.Core/Validation/Paths/SeriesExistsValidator.cs
src/NzbDrone.Core/Validation/Paths/SeriesPathValidator.cs

NO
GetAllSeries is expensive due to deserialization of multiple json objects. Use GetAllSeriesPaths in SeriesPathValidator instead to speed up Series adds.

New: Speed up Series Add by reworking SeriesPathValidator

---

src/NzbDrone.Core/Notifications/Discord/Discord.cs
src/NzbDrone.Core/Notifications/Discord/DiscordFieldType.cs
src/NzbDrone.Core/Notifications/Discord/DiscordSettings.cs

Similar to Radarr, adds the ability to include parsed custom formats and CF score in the Discord webhook notification.
Are there even more options that could be included here?
Database Migration
NO
Description
See https://github.com/Sonarr/Sonarr/issues/5769.
Similar in nature to PR https://github.com/Sonarr/Sonarr/pull/5493
Todos
Tests (How?)
Wiki Updates (None, except all the possible field types listed somewhere would be nice. Might open a PR for the wiki at some point)
Issues Fixed or Closed by this PR
Closes https://github.com/Sonarr/Sonarr/issues/5769

New: Add CustomFormat field types to Discord OnGrab Notification

---

src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadataSettings.cs

NO
According to the [Jellyfin docs](https://jellyfin.org/docs/general/server/metadata/nfo/#image-paths-and-urls-in-nfo-files), .nfo file thumb image tags are prioritized over local images. However Sonarr always adds the thumb image tags, meaning Jellyfin attempts to grab the images from the internet rather than using those that are available locally. This PR simply removes the tags if episode images are enabled.

No thumb tags with local images in .nfo

---

frontend/src/Series/Details/EpisodeRow.css
frontend/src/Series/Details/EpisodeRow.css.d.ts
frontend/src/Series/Details/EpisodeRow.js
frontend/src/Series/Details/EpisodeRowConnector.js
frontend/src/Store/Actions/episodeActions.js
src/NzbDrone.Core/Localization/Core/en.json
src/Sonarr.Api.V3/EpisodeFiles/EpisodeFileResource.cs

NO
This commit adds the Custom Format column in the series episode row view. This is to be consistent with fields available in 
History, Queue, Search, etc.. This is something I wanted for my personal use at least
Disclaimer: I am not a React Developer and am hacking this together from existing code. If there is a better way to integrate all table views with consistent column view options, I am completely open to redesigning.
*

New: Show CF Score in episode row

---

frontend/src/Components/Form/QualityProfileSelectInputConnector.js

NO
As described on #development channel, allowing `noChange` as value for quality profile select.
```
Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a string.
select
SelectInput@webpack-internal:///10453:13:5
```

Fixed: Allow `noChange` as value in QualityProfileSelect

---

frontend/src/InteractiveImport/Interactive/InteractiveImportModalContent.tsx
frontend/src/InteractiveImport/Interactive/InteractiveImportRow.tsx
frontend/src/Store/Actions/interactiveImportActions.js
src/Sonarr.Api.V3/ManualImport/ManualImportResource.cs

NO
This PR adds custom format score information in the Manual Import modal and consequenctly manage series episodes modal.
This is part of my ongong effort to include CF Score data where-ever custom formats are shown/returned by the API
I am more than open to alternative approaches.
I think the UI on this one could use some tweaking. Perhaps keeping the icon next to the score number.
I also couldn't get sorting by CF column working. I think it should sort by the score value. 
*

New: Add CF Score to import modal

---

frontend/build/webpack.config.js

NO
Seems like the CSS files need a cache busting too. On iOS without clear all cache I can't make it see the new style.

Cache busting for CSS files

---

src/NzbDrone.Core/ImportLists/Simkl/SimklAPI.cs
src/NzbDrone.Core/ImportLists/Simkl/SimklParser.cs
src/NzbDrone.Core/ImportLists/Simkl/User/SimklUserRequestGenerator.cs
src/NzbDrone.Core/ImportLists/Simkl/User/SimklUserSettings.cs
src/NzbDrone.Core/ImportLists/Simkl/User/SimklUserShowType.cs
src/NzbDrone.Core/Parser/Model/ImportListItemInfo.cs

NO
This is our progress with issue 5635 so far. We added a button when going to "Settings→Import Lists→Add List→Simkl List" that allows the user to add an anime list where the button is called "Simkl Anime Watchlist". We also renamed the other button to "Simkl Shows Watchlist". 
When creating the new list for Simkl Anime Watchlist, we are able to create it in the same manner as Simkl Shows Watchlist. On the initial import, the code was able to import most of the anime shows into the Series tab with no issue. For a couple anime shows, it would import the wrong show. Some anime shows don't have a IMDB id when fetched from the Simkl API (it also does not list an IMDB link on Simkl's website). The issue is happening in ImportListServices.cs on line 99 where it is trying to search for the show …

Simkl Anime List integration

---

src/Sonarr.Http/ClientSchema/SchemaBuilder.cs

NO
Adding support for deprecated enums in SelectOptions with the attribute Obsolete by not displaying them in values anymore while maintaining BC.

Add support for deprecated values in field select options

---

src/NzbDrone.Core/Notifications/Discord/Discord.cs
src/NzbDrone.Core/Notifications/Discord/DiscordSettings.cs

NO
Opening this now to start a discussion about the discord notifications.  
I began working to add proper embeds and more info for Series Added/Deleted and Episode Deleted events.  
The fact is the `NzbDrone.Core.Notifications.Discord.Discord` class has some pretty redundant sections and code smell.  
I am wondering what the best way to go about setting defaults for the embeds,
Ideas I have for the potential future:
- All notifications are in embeds with Author+Title+Description+relevant fields
- Series link to the sonarr series page instead of TVDB. Links to external services are handled in the "links" field
- Similar to how the generic webhook notification sends ApplicationURL field
- Is it worth it to have complete control over all event type fields in the UI? Or is this unnecessary …

Improve Discord Add/Delete embeds

---

src/NzbDrone.Core/IndexerSearch/ReleaseSearchService.cs
src/NzbDrone.Core/Indexers/IndexerDefinition.cs

NO
This comes handy when you're using two instances of the same indexer (eg. one freeleech and the other normal), and would rather show the FL releases first based on the indexer priority.

Fixed: Add dedupe releases rule based on indexer priority

---

frontend/src/Components/Markdown/InlineMarkdown.js

NO
I wanted to make use of this during translations to properly present translation strings that contain codeblocks
Initally I used it for one code block found [here](https://github.com/stevietv/Sonarr/blob/80850ac976a3841be28fae3132240251893c5b93/frontend/src/Settings/MediaManagement/Naming/NamingModal.js#L511)
To translate this string and present it properly:
```
"MediaInfoFootNote": "MediaInfo Full/AudioLanguages/SubtitleLanguages support a `:EN+DE` suffix allowing you to filter the languages included in the filename. Use `-DE` to exclude specific languages. Appending `+` (eg `:EN+`) will output `[EN]`/`[EN+--]`/`[--]` depending on excluded languages. For example `{MediaInfo Full:EN+DE}`.",
```
There are two cases to handle during the split, one if the code passed to it begins with a ` …

extend InlineMarkdown to handle code blocks in backticks

---

frontend/src/Activity/History/Details/HistoryDetails.js
frontend/src/Activity/History/HistoryRow.js
frontend/src/Activity/Queue/QueueRow.js
frontend/src/Episode/History/EpisodeHistoryRow.js
frontend/src/InteractiveImport/Interactive/InteractiveImportRow.tsx
frontend/src/InteractiveSearch/InteractiveSearchRow.tsx
frontend/src/Series/Details/EpisodeRow.js
frontend/src/Series/History/SeriesHistoryRow.js
frontend/src/Utilities/Number/formatCustomFormatScore.ts
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportItem.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs
src/Sonarr.Api.V3/ManualImport/ManualImportController.cs
src/Sonarr.Api.V3/ManualImport/ManualImportReprocessResource.cs

NO
- Sadly 972e1408993fc4656196087c6646f23d222e41f5 didn't consider that the resource can be reprocessed on changes of rls grp, quality, etc.
- Renamed `formatPreferredWordScore` to `formatCustomFormatScore`

Fixed: Recalculate Custom Format Score in Manual Import

---

src/NzbDrone.Core/Indexers/IndexerFactory.cs
src/NzbDrone.Core/Indexers/Newznab/Newznab.cs
src/NzbDrone.Core/Indexers/Torznab/Torznab.cs

NO
I was playing with force sync indexers in Prowlarr and I noticed that `Test all indexers` in Sonarr doesn't do anything to show in the UI the API key failures.

Fixed: Ensure indexers are marked as failed on Test All

---

src/NzbDrone.Core/Qualities/QualityDefinitionService.cs

NO
When resetting the quality definitions to their default value using the "Reset Definitions" button
None

Include preferred size in quality definition reset

---

src/NzbDrone.Core/ImportLists/Simkl/SimklAPI.cs
src/NzbDrone.Core/ImportLists/Simkl/SimklParser.cs
src/NzbDrone.Core/ImportLists/TolerantEnumConverter.cs

NO
Users were getting error messages when trying to import their anime watchlist if they had the any OVAs, ONAs, Special, or Music Video anime types included in their watchlist. Added enum entries in simkl API, as well as tweaked the import warning message to fix this issue.
Fixes https://github.com/Sonarr/Sonarr/issues/5839

Importing additional Anime Types from Simkl

---

frontend/src/Episode/EpisodeDetailsModalContentConnector.js
frontend/src/Series/Search/SeasonInteractiveSearchModalConnector.js

NO
When using the browser's back button after searching for a season in one series and going to another, we would see the results for the previous series in the new series season search.

Fixed: Clear pending season releases to prevent stale results

---

src/NzbDrone/WindowsApp.cs

NO
Currently in certain cases MessageBox.Show fails with below. Likely from users trying to run tray app as a service. This will avoid tossing error on message box if environment is not UserInteractive
```
System.InvalidOperationException: Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application.
?, in MB MessageBox.GetMessageBoxStyle(IWin32Window owner, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, bool showHelp)
?, in DialogResult MessageBox.ShowCore(IWin32Window owner, string text, string caption, MessageBoxButtons buttons, MessageBoxIcon icon, …
```

Fixed: Error trying to notify user when process not UserInteractive

---

src/NzbDrone.Host/Startup.cs

NO
Expand the description on the swagger UI page to state that the API docs are for API v3 for the v4 frontend

Update API docs page to clarify v3/v4 independence

---

src/NzbDrone.Core/Download/DownloadClientFactory.cs
src/NzbDrone.Core/ImportLists/ImportListFactory.cs

NO
Similar to b407eba61284d5fb855df6a2868805853aa6f448, this seems to affect all providers.

Fixed: Ensure failing providers are marked as failed when testing all

---

frontend/src/InteractiveSearch/InteractiveSearchRow.tsx

New: Show successful grabs in Interactive Search with different color

---

src/NzbDrone.Core.Test/IndexerSearchTests/ReleaseSearchServiceFixture.cs
src/NzbDrone.Core.Test/IndexerTests/FanzubTests/FanzubRequestGeneratorFixture.cs
src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabRequestGeneratorFixture.cs
src/NzbDrone.Core.Test/IndexerTests/NyaaTests/NyaaRequestGeneratorFixture.cs
src/NzbDrone.Core/IndexerSearch/Definitions/AnimeEpisodeSearchCriteria.cs
src/NzbDrone.Core/IndexerSearch/Definitions/AnimeSeasonSearchCriteria.cs
src/NzbDrone.Core/IndexerSearch/ReleaseSearchService.cs
src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetRequestGenerator.cs
src/NzbDrone.Core/Indexers/Fanzub/FanzubRequestGenerator.cs
src/NzbDrone.Core/Indexers/FileList/FileListRequestGenerator.cs
src/NzbDrone.Core/Indexers/HDBits/HDBitsRequestGenerator.cs
src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
src/NzbDrone.Core/Indexers/IIndexer.cs
src/NzbDrone.Core/Indexers/IIndexerRequestGenerator.cs
src/NzbDrone.Core/Indexers/IPTorrents/IPTorrentsRequestGenerator.cs
src/NzbDrone.Core/Indexers/IndexerBase.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs
src/NzbDrone.Core/Indexers/Nyaa/NyaaRequestGenerator.cs
src/NzbDrone.Core/Indexers/RssIndexerRequestGenerator.cs
src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssIndexerRequestGenerator.cs
src/NzbDrone.Core/Indexers/Torrentleech/TorrentleechRequestGenerator.cs

NO
Implemented the new search criteria object, `AnimeSeasonSearchCriteria`, and applied it where it might be needed throughout the codebase. Generally paired with wherever `AnimeEpisodeSearchCriteria` is referenced. Added some minor tests that are similar to the already existing tests. Now, when the `AnimeStandardFormatSearch` option is enabled in the indexer settings, season packs will also be found in addition to its original function.
* https://github.com/Sonarr/Sonarr/issues/5616

AnimeStandardFormatSearch option also looks for season packs

---

src/NzbDrone.Core.Test/ThingiProviderTests/ProviderStatusServiceFixture.cs
src/NzbDrone.Core/ThingiProvider/Status/EscalationBackOff.cs
src/NzbDrone.Core/ThingiProvider/Status/ProviderStatusServiceBase.cs

NO
In [Prowlarr](https://github.com/Prowlarr/Prowlarr/commit/5cc044aa8fbc7ba62d9c32442d8125b9b347d28a) we had to add an additional back-off level of one minute to deal with a few indexers rate limiting per minute. Adding an additional one minute back-off level should help with not having the indexers marked as failed for too long than it's needed.

New: Additional one minute back-off level

---

frontend/src/Activity/Queue/QueueStatus.js

NO
revert translations on defaultProps for QueueStatus.js
This wasn't required
*

revert translations on defaultProps for QueueStatus.js

---

src/NzbDrone.Common/EnvironmentInfo/OsInfo.cs

`/proc/1/mountinfo` doesn't seem a reliable source of truth.

Fixed: Replace docker detection for cgroup v2

---

src/NzbDrone.Core/MediaFiles/EpisodeFileMovingService.cs

NO
Minor oversight for custom import scripts. When requesting a rename that is not required, an error is thrown because the file would be moved to the location it is already in. In that case we can simply catch the error and ignore it.
*

No error uneccessary custom import rename

---

src/NzbDrone.Core/Notifications/NotificationFactory.cs

If you disable a blocked connection by status it won't disappear from the health status because there's no filter for enabled notifications only.

Prevent health checks warnings for disabled notifications

---

frontend/src/System/Status/Health/Health.js
src/NzbDrone.Core/Localization/Core/en.json

NO
Adds an info box under the health messages when there are health checks reminding users to:
* check the wiki link on the message row 
* check their logs
* or come to support for help
* closes #5958

Add info box under health messages

---

frontend/src/Settings/UI/UISettings.js
src/NzbDrone.Core/Localization/Core/en.json
src/NzbDrone.Core/Localization/LocalizationService.cs
src/Sonarr.Api.V3/Config/UiConfigController.cs

NO
We saw on Discord that it was possible for someone to have -2 as an original language, which resulted in translations failing.
This falls back to English if an invalid Language is returned during evaluating what language the UI should be in.
*

Fix: Fallback to English translations if invalid UI language in config

---

frontend/src/Activity/History/Details/HistoryDetails.js
frontend/src/Activity/History/Details/HistoryDetailsModal.js
frontend/src/Activity/History/HistoryRow.js
frontend/src/Episode/History/EpisodeHistoryRow.js
frontend/src/Series/History/SeriesHistoryRow.js

NO
`DownloadId` has a separate column, not a part of data.

Fix showing Grab ID in history details modal

---

frontend/src/Store/Actions/Settings/autoTaggingSpecifications.js
frontend/src/Store/Actions/Settings/autoTaggings.js
frontend/src/Store/Actions/Settings/customFormatSpecifications.js
frontend/src/Store/Actions/Settings/customFormats.js
frontend/src/Store/Actions/Settings/indexers.js
frontend/src/Store/Actions/Settings/qualityProfiles.js
src/NzbDrone.Core/Localization/Core/en.json

NO
Translate Frontend Store
only additions that were needed were to the default names of copied profiles or specs within a profile.
*

Translate Frontend Store (default name for copied specs or profiles)

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentTorrent.cs

NO
https://github.com/Radarr/Radarr/issues/9126
Ignoring the mistakes from the API docs, `seeding_time` seems to be seconds while `seeding_time_limit` and `max_seeding_time` in minutes.

Fixed: Calculate reached seeding time in seconds for qBittorrent

---

src/NzbDrone.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs

NO
Currently CapabilitiesProvider doesn't throw on APIKey error, thus default categories are returned resulting in confusing messaging to the user. This change catches and throws the ApiKeyException that is generated instead of handling it with other exceptions

Fixed: Show correct error on unauthorized caps call

---

frontend/src/Store/Actions/seriesActions.js

NO
Adds the option to create a custom filter based on year show began airing
*

New: Year custom filter in Series Index

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

NO
don't raise RemovesCompletedDownloads health check if qBittorrent removes torrents after 14 days seeding.
Health Check is popped when:
```
downloads are set to remove or remove+delete, and
1) ratio box is checked, or
2) seeding time box is checked and is set to less than 14d
```
*

Fixed: qBittorent history retention to allow at least 14 days seeding

---

src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/SeriesTitleFirstCharacterFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

NO
This returns '#' as the first character to use in the `{Series TitleFirstCharacter}` token when that character is not alphanumeric
* fixes #6055 6055

Fix: return '#' as first character for non alphanumeric

---

src/NzbDrone.Core.Test/ParserTests/SingleEpisodeParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Aparantly spanish indexers aren't using the `Temporada #` part of their release title anymore, this was brough to attention on discord, and the regex is updated with this PR
Thanks to Ivory: https://discord.com/channels/383686866005917708/383688189941907459/1154205181270044772
*

Fix: update Spanish release episode parser

---

src/NzbDrone.Core/MediaCover/MediaCoverProxy.cs

NO
Noticed in Radarr, but it seems like when people mess around with downgrading and upgrading it can lead to issues with null values for RemoteUrl in Media Covers.
```
[v5.0.3.8107] System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
at System.Text.Encoding.GetBytes(String s)
at NzbDrone.Core.Hashing.SHA256Hash(String input) in ./Radarr.Core/Hashing.cs:line 14
at NzbDrone.Core.MediaCover.MediaCoverProxy.RegisterUrl(String url) in ./Radarr.Core/MediaCover/MediaCoverProxy.cs:line 34
at NzbDrone.Core.MediaCover.MediaCoverService.ConvertToLocalUrls(Int32 movieId, IEnumerable`1 covers, Dictionary`2 fileInfos) in ./Radarr.Core/MediaCover/MediaCoverService.cs:line 96
at NzbDrone.Core.MediaCover.MediaCoverService.ConvertToLocalUrls(IEnumerable`1 …
```

Prevent NullRef for cases when media covers have nullable urls

---

frontend/src/Settings/MediaManagement/Naming/NamingModal.js
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/CleanTitleTheFixture.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/CleanTitleTheWithoutYearFixture.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/CleanTitleTheYearFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

NO
Adds the remaining CleanTitle naming tokens and tests to cover them.
Also took the opportunity to reorder them so normal and clean line up properly in the with each other:
Question: Do we want the `,` the be prepended with `The` in Clean filenames? I.e. should it be `Series Name, The` or `Series Name The`
* Fixes #6066

New: Add remaining CleanTitle tokens and re-order options

---

src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs

NO
Add support for Jellyfin's "enddate" tag when generating the xbmc metadata nfo file. When the series has ended, enddate tag will be added to the nfo file.
*

New: Add support for Jellyfin's "enddate" tag when generating the xbmc metadata nfo file.

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
Update the announce URL cleanse regex for trackers that use generated hashes with upper case chars in the passkeys.

Fixed: Ignore case when cleansing announce URLs

---

frontend/src/Store/Actions/seriesActions.js

NO
The current hasMissingSeason filter returns all shows with missing seasons no matter what the filter is set to.
This enables the filter to be used as a boolean so that it can also be used for shows that don't have a full missing season.
*

Fix: hasMissingSeason filter function

---

frontend/src/Series/Details/SeriesDetails.css

NO
To avoid long titles taking up a lot of screen real estate, title font size is reduced for smaller screens
* Closes #6087

Fix: reduce Series Title on SeriesDetails when on small screen

---

src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularParser.cs
src/NzbDrone.Core/ImportLists/Trakt/TraktAPI.cs
src/NzbDrone.Core/ImportLists/Trakt/TraktParser.cs
src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserImport.cs
src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserParser.cs
src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserRequestGenerator.cs
src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserSettings.cs
src/NzbDrone.Core/ImportLists/Trakt/User/TraktUserWatchedListType.cs

NO
In Sonarr there is no way to import those series that are in progress on Trakt.
- Watchlist only brings you those that you have not started to see.
- Watched brings you both the ones you have in progress and the ones you have finished.
From the Trakt API they warn that there is no specific endpoint to bring you this information and you have to do calculations locally. After much asking and searching, we have agreed that the easiest way is to compare the total number of episodes in a series and the number of episodes seen without counting the rewatches.
I have included a selector in the import list configuration to be able to select if you want to bring Everything, In Progress, Completed.
*

New: Add Watched filter type to Trakt User Import List

---

src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/SeriesTitleFirstCharacterFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs
src/NzbDrone.Core/Sonarr.Core.csproj

NO
Use [Diacritical.Net ](https://www.nuget.org/packages/Diacritical.Net)library when determining the TitleFirstCharacter token for simpler sorting
*

Use Diacritical.Net library for TitleFirstCharacter token

---

src/NzbDrone.Core.Test/Profiles/QualityProfileServiceFixture.cs
src/NzbDrone.Core/Profiles/Qualities/QualityProfileRepository.cs
src/NzbDrone.Core/Profiles/Qualities/QualityProfileService.cs
src/NzbDrone.Core/Validation/DownloadClientExistsValidator.cs
src/NzbDrone.Core/Validation/QualityProfileExistsValidator.cs
src/NzbDrone.Integration.Test/ApiTests/SeriesEditorFixture.cs
src/NzbDrone.Integration.Test/ApiTests/WantedTests/CutoffUnmetFixture.cs
src/NzbDrone.Integration.Test/IntegrationTestBase.cs
src/Sonarr.Api.V3/ImportLists/ImportListController.cs
src/Sonarr.Api.V3/Indexers/IndexerController.cs
src/Sonarr.Api.V3/Series/SeriesController.cs

NO
- Renamed a few instances of Profile to QualityProfile
- Added Download Client validation for indexers
- Fixed validation logic in QualityProfileExistsValidator to allow 0 as valid choice for optional fields. For mandatory `ValidId` is to be used too.

New: Add Download Client validation for indexers

---

src/NzbDrone.Core/Datastore/ConnectionStringFactory.cs

NO
Adding a busy timeout in order to avoid db locks. I used 100 for more than week and 0 db locks since. 
https://www.sqlite.org/c3ref/busy_timeout.html

Set busy timeout for SQLite

---

frontend/src/InteractiveImport/InteractiveImportModal.tsx
frontend/src/Store/Actions/interactiveImportActions.js

NO
sets the default sort order of manual imports to ascending relative path, so the episodes (most likely) appear in order.
*

New: set relative path as Initial Sort order on Manual Import

---

src/NzbDrone.Core/Localization/Core/en.json

NO
remove unnecessary $1 from en translation

fix: remove unnecessary $1 from en translation

---

src/Sonarr.Api.V3/Indexers/ReleasePushController.cs
src/Sonarr.Api.V3/Indexers/ReleaseResource.cs

NO
Let's make it easier to override the download client for pushed release.

New: Resolve download client by name using 'downloadClient' for pushed releases

---

src/NzbDrone.Core/Notifications/Webhook/WebhookEpisode.cs

No
Add an Episode's TVDb ID (`TvdbId`) to the Webhook payload.
N/A

Add TvdbId to Webhook Episode payload

---

src/NzbDrone.Core.Test/ParserTests/AbsoluteEpisodeNumberParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

NO
Some Turkish release groups like TURG and turkseed like to localize episode names and add air dates to titles which sometimes confuses Sonarr, making detection flaky because it can't make up its mind between daily show vs absolute episodes.
The regex for this is specifically placed before this one:
```js
/^(?<title>.+?)?\W*(?<airmonth>[0-1][0-9])[-_. ]+(?<airday>[0-3][0-9])[-_. ]+(?<airyear>\d{4})(?!\d+)/
```
since that's what made parsing flaky in the first place.
I didn't include the air dates in the pattern because release titles are often very inconsistent. I don't think that's going to cause false positives though.
*

New: Parser for Turkish releases

---

frontend/src/App/State/QueueAppState.ts
frontend/src/Series/Index/createSeriesQueueDetailsSelector.ts
frontend/src/typings/Queue.ts

NO
Avoid already imported episodes to be shown as downloading in the SeriesIndexProgressBar component.
https://github.com/Radarr/Radarr/issues/9367

Fixed: Showing already imported episodes as downloading in Series index

---

frontend/src/Utilities/String/translate.ts

NO
when there tokens are passed to translate function appName is not added to the list, thus is skipped in multiple translation strings.
translate() function now defaults to it (when no tokens are passed) and adds it when tokens are passed.
* #6155

Fix: translate for empty appName token

---

src/Sonarr.Api.V3/ProviderControllerBase.cs

NO
Currently it seems like the warnings from `TestConnection` are shown only using the test endpoint, and I think it would better to show them on create/update as well.

Fixed: Enforce validation warnings when testing providers

---

src/NzbDrone.Core/Blocklisting/BlocklistService.cs
src/NzbDrone.Core/Download/Clients/Aria2/Aria2.cs
src/NzbDrone.Core/Download/Clients/Blackhole/TorrentBlackhole.cs
src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs
src/NzbDrone.Core/Download/Clients/Flood/Flood.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/TorrentFreeboxDownload.cs
src/NzbDrone.Core/Download/Clients/Hadouken/Hadouken.cs
src/NzbDrone.Core/Download/Clients/NzbVortex/NzbVortexProxy.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/Transmission/Transmission.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs
src/NzbDrone.Core/Download/Clients/Vuze/Vuze.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs
src/NzbDrone.Core/Download/DownloadService.cs
src/NzbDrone.Core/Download/FailedDownloadService.cs
src/NzbDrone.Core/Download/TorrentClientBase.cs
src/NzbDrone.Core/Exceptions/ReleaseBlockedException.cs
src/NzbDrone.Core/History/HistoryService.cs
src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetSettings.cs
src/NzbDrone.Core/Indexers/FileList/FileListSettings.cs
src/NzbDrone.Core/Indexers/HDBits/HDBitsSettings.cs
src/NzbDrone.Core/Indexers/IPTorrents/IPTorrentsSettings.cs
src/NzbDrone.Core/Indexers/ITorrentIndexerSettings.cs
src/NzbDrone.Core/Indexers/Nyaa/NyaaSettings.cs
src/NzbDrone.Core/Indexers/TorrentRss/TorrentRssIndexerSettings.cs
src/NzbDrone.Core/Indexers/Torrentleech/TorrentleechSettings.cs
src/NzbDrone.Core/Indexers/Torznab/TorznabSettings.cs

NO
A lot of low end indexers accessed through torznab don't provide hashes during parsing and we're forced to get it from the torrent/magnet link, which currently means it's not stored in history and not available for blocklisting.
This PR adds/fixes a few things:
- Blocklisting the last grabbed history item instead of the first (which would use the wrong title/indexer combination if the same release was re-grabbed from a different indexer)
- The hash from the torrent/magnet to the release so it's stored in history and used when blocklisting
- An option on indexers that is used after grabbing the torrent, but before sending it to the client to allow *arr to reject it
* Closes #6108

Fixed: Blocklisting torrents from indexers that do not provide torrent hash

---

src/NzbDrone.Core.Test/MediaFiles/DiskScanServiceTests/ScanFixture.cs
src/NzbDrone.Core.Test/MediaFiles/MediaInfo/UpdateMediaInfoServiceFixture.cs
src/NzbDrone.Core/Extras/ExistingExtraFileService.cs
src/NzbDrone.Core/Extras/ExtraService.cs
src/NzbDrone.Core/MediaFiles/DiskScanService.cs
src/NzbDrone.Core/MediaFiles/EpisodeFileMovingService.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs
src/NzbDrone.Core/MediaFiles/Events/SeriesScannedEvent.cs
src/NzbDrone.Core/MediaFiles/ScriptImportDecider.cs
src/NzbDrone.Core/MediaFiles/ScriptImportInfo.cs
src/NzbDrone.Core/Parser/Model/LocalEpisode.cs

NO
There are a few cases that were not handled for custom import scripts yet:
* Custom import scripts that generate additional extra files to be imported.
* Custom import scripts that remux the original media file to a different container, such that its extension must change
* Wanting to import extra files via a custom import script(as deferred to a later date in the original #5538)
All of these use cases are addressed as follows: A custom import script can now communicate back to Sonarr by means of a temporary file, the path to which is passed as an environment variable. This avoids parsing a potentially polluted stdout, however I am open to changes in this respect. This communication is used in order to inform Sonarr of: The potentially changed name of the media file, and which extras …

New: communication back from custom import script

---

src/NzbDrone.Core/Datastore/DbFactory.cs
src/NzbDrone.Core/Datastore/Migration/Framework/MigrationController.cs

NO
Use the database type from connection string factory for migration to prevent issues when postgres host contains ".db"
* Fixes #6225

Fixed: Correctly handle Migration when PG Host has ".db"

---

src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

NO
Needed to properly detect DV HDR10+ for already imported files.

Fixed: Bump media info revision for DV HDR10Plus

---

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs

Sometimes people have SSL enabled from before, but a hash was not set which results in the config not being fixed automatically.

Fixed: Disable SSL on start if certificate path is not set

---

src/NzbDrone.Core.Test/TvTests/EpisodeMonitoredServiceTests/SetEpisodeMontitoredFixture.cs
src/NzbDrone.Core/Tv/EpisodeMonitoredService.cs

NO
Fix for last season monitored with no future episodes when applying monitor future episodes.

Fixed: Monitor last season only if there's at least one future monitored episode

---

distribution/debian/install.sh
version.sh

NO
Instead of changing how the script is downloaded we can read user input from `/dev/tty`.
Found this solution on https://unix.stackexchange.com/questions/121231/how-to-read-user-input-from-a-pipe and https://unix.stackexchange.com/questions/166853/how-to-read-user-input-when-using-script-in-pipe
* Closes #6291

install.sh: Use /dev/tty for user input

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

NO
This is an upstream port of https://github.com/Radarr/Radarr/pull/9512
Correctly parses German DL and ML tags
- The DL tag (Dual Language) is quite like the `Multi` tag, but for the German Scene, it specifies that the release contains the German and the original language.
- The ML tag (Multi Language) contains the following languages: `German`, `Original`, `English` or more ([examples on xrel.to](https://www.xrel.to/p2p/releases.html?search_results=v6anRHibr9167592559&query=german+ml+s01&maxed_out=1))
*

Correctly parse German DL and ML tags in releases

---

distribution/debian/install.sh

Exit the install script with a warning when trying to run it from the planned install directory.

Exit Debian Install Script when running from install dir

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

NO
Added proper support for Latvian with test cases I have encountered in the wild and fixed a case where Russian is not recognized (RU instead of RUS).
- N/A Wiki Updates

Fixed: Latvian and Russian language parsing

---

src/NzbDrone.Core/Indexers/Nyaa/Nyaa.cs
src/NzbDrone.Core/Indexers/Nyaa/NyaaRequestGenerator.cs

NO
Nyaa's RSS feed doesn't support pagination (confirmed on IRC).
Tested as working, but feel free to tidy/change whatever is needed.
*

Fixed: Remove unsupported pagination for Nyaa

---

.github/actions/test/action.yml
.github/workflows/publish-test-results.yml

This should address PRs from forks failing with `Resource not accessible by integration` per https://github.com/phoenix-actions/test-reporting#recommended-setup-for-public-repositories

Separate publishing of test results for PRs from forks

---

.editorconfig
.github/actions/test/action.yml
.github/workflows/build.yml
.github/workflows/publish-test-results.yml
src/NzbDrone.Mono.Test/EnvironmentInfo/VersionAdapters/MacOsVersionAdapterFixture.cs

The separate workflow doesn't work correctly with upload-artifact@v4, which can be worked around, but a separate check with the results isn't really necessary.
https://github.com/marketplace/actions/publish-test-results looks like a possibly better solution as check publishing can be disabled and has the option for PR comments, but disabled them for now to avoid the need for special permissions.

Better Test Result Publishing

---

frontend/src/InteractiveImport/Interactive/InteractiveImportModalContent.tsx
src/Sonarr.Api.V3/ManualImport/ManualImportController.cs

Fixes a backend issue when reprocessing items with multiple languages and prevents mass selection of season if series isn't selected and episode when season isn't yet selected.
* Closes #6354

Fixed: Reprocessing multi-language file in Manual Import

---

src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

Instead of using the first frame for any video stream, read only frames associated with the primary video stream we've chosen. This prevents false matches for HDR if the first frame doesn't belong to the correct stream. 
https://github.com/Radarr/Radarr/pull/9618

Fixed: Only use frames for Primary video stream for analysis

---

src/NzbDrone.Common.Test/Http/HttpClientFixture.cs
src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs

NO
Currently when request is made and our timeout is exceeded (100s or request.RequestTimeout) HttpClient throws `ThreadCanceledException` with inner `SocketException` from the Socket Handler. This PR catches that in `ManageHttpDispatcher` and throws appropriate `WebException` with Timeout WebExceptionStatus. Also adds test to ensure correct handling of timeouts from HttpClient.
There is some argument to throw System.TimeoutException instead, however it's not currently handled anywhere either whereas WebException is. This can be discussed.

Improved http timeout handling

---

src/NzbDrone.Core/Parser/IsoLanguages.cs

add zhtw and yue as alternative codes for Chinese language.
order of check rearranged in `Find`in `IsoLanguages.cs` - otherwise the dictionary of AlternativeIsoCodeMappings is never used for three character codes.
* Closes #6363

add zhtw and yue as Chinese language

---

src/NzbDrone.Core/History/HistoryRepository.cs
src/Sonarr.Api.V3/History/HistoryController.cs

NO
Change to use all query params named `eventType`, not just the first one.
https://github.com/Radarr/Radarr/issues/9553

Fixed: Filter history by multiple event types

---

src/NzbDrone.Core/Datastore/Migration/188_postgres_update_timestamp_columns_to_with_timezone.cs

Avoid a common migration error:
```[Error] FluentMigrator.Runner.MigrationRunner: database disk image is malformed
database disk image is malformed
While Processing:
"INSERT INTO "Commands_temp" ("Id", "Name", "Body", "Priority", "Status", "QueuedAt", "StartedAt", "EndedAt", "Duration", "Exception", "Trigger", "Result") SELECT "Id", "Name", "Body", "Priority", "Status", "QueuedAt", "StartedAt", "EndedAt", "Duration", "Exception", "Trigger", "Result" FROM "Commands""
```
YES - 188 (existing)

Drop commands table content before altering tables

---

src/NzbDrone.Core/ImportLists/Rss/Plex/PlexRssImportParser.cs

It may happen that some items to have the GUID missing and would break the whole import.

Fixed: Importing Plex RSS lists with invalid items

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

qBittorrent rounds of its ratio when deciding to pause a torrent, but then provides in its API response a full double which we store as float. 
When a paused torrent is then Global Max ratio it can be under the ratio (`0.99999 < 1`) which results in a paused torrent not being removed even though it is presented in qbit ui as Paused with a ratio of 1.0
By rounding off the seeded ratio when checking for removal candidates we can avoid these edge cases hanging in qbit.

Fix: Removal of paused Qbittorrent torrents with global max ratio

---

src/Sonarr.Api.V3/Series/SeriesController.cs

Iterating list of stats for every series is costly, this significantly improves response time for All Series call for large libraries by converting stats object to a dictionary for value search prior to linking. 
The effects of this are exponential, an extreme example from Radarr testing is below:
Library - 263,000 Items
Current Code - 26 Min to link
Proposed Code - 22 Sec to link
Due to the double iteration it's not near as substantial on a smaller library, but can have some impact.

New: Improve All Series call by using dictionary for stats iteration

---

frontend/src/Calendar/Events/CalendarEvent.css
frontend/src/Calendar/Events/CalendarEvent.js
frontend/src/Calendar/Events/CalendarEventGroup.css
frontend/src/Calendar/Events/CalendarEventGroup.css.d.ts
frontend/src/Calendar/Events/CalendarEventGroup.js
frontend/src/Calendar/Legend/Legend.js
frontend/src/Calendar/Legend/LegendIconItem.css
frontend/src/Calendar/Legend/LegendIconItem.js
frontend/src/Components/Icon.css
frontend/src/Components/Icon.js
frontend/src/Helpers/Props/icons.js
frontend/src/Styles/Themes/dark.js
frontend/src/Styles/Themes/light.js
frontend/src/typings/UiSettings.ts

Full color events were only showing gray for most icons or no attempt to fix them was done (warnings and download status). This PR adds color changing via CSS `filter()` which applies to all elements within the container: https://developer.mozilla.org/en-US/docs/Web/CSS/filter
This allows us to change the result depending on the theme and keep minimal conflicting colors. The results aren't perfect, but significantly better than the previous behaviour.
Light Theme:
Dark Theme:
* Closes #6331

Fixed: Icons on full color calendar events

---

frontend/src/Store/Actions/Settings/indexers.js

No longer clone `********` as the indexer API key, instead clear it out.
* Closes #6265

Fixed: Don't clone indexer API Key

---

frontend/src/Series/Index/Posters/SeriesIndexPosters.tsx

Don't update `size` as quickly as the CPU will let us when the value hasn't chaged.
* Closes #6387

Fixed: Series poster view on mobile devices

---

src/NzbDrone.Core/Update/InstallUpdateService.cs

With the fact that `/tmp` can change rather quickly, I don't see a lot of value in a health check for this, but checking just before updating that there is 1GB free space (which is more than Sonarr needs) and logging a warning if it's lower will improve the current behaviour.
* Closes #6385

New: Log warning if less than 1 GB free space during update

---

src/NzbDrone.Core.Test/Datastore/Migration/198_parse_titles_from_existing_subtitle_filesFixture.cs
src/NzbDrone.Core/Datastore/Migration/198_parse_titles_from_existing_subtitle_files.cs

Fixes migration 198 when the Original File Path is null.

Fixed: Subtitle title migration when original title is null

---

src/NzbDrone.Core.Test/ParserTests/AbsoluteEpisodeNumberParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

A number only hash getting substituted during pre-parsing replacement.

Fixed: Number only hashes getting substituted incorrectly

---

src/NzbDrone.Core.Test/Datastore/Migration/198_parse_titles_from_existing_subtitle_filesFixture.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

The Regex that extracted the `copy` was very greedy and when it ran into a hash or string with a very large number it could easily exceed the maximum value for a integer, it's now capped at 1-3 digits and won't be extracted from a string of numbers longer than that.
* Closes #6409

Fixed: Migrating subtitle files with unexpectedly large number at end

---

src/NzbDrone.Core.Test/ParserTests/AbsoluteEpisodeNumberParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Hungarian anime triggers the website prefix regex because it uses `Naruto-Kun.Hu` as the release group, this changes the regex to to ignore `Naruto-Kun` as the domain.
* Closes #6275

Fixed: Parsing Hungarian anime releases

---

frontend/src/Calendar/Events/CalendarEventGroup.css
frontend/src/Calendar/Events/CalendarEventGroup.js

Uses a non-breaking space before/after the expand icon to change the row height and centers the icon vertically, this results in the height being the same for grouped and ungrouped events without needing to hardcode a height.
* Closes #6395

New: Added some extra pixels to grouped calendar events

---

frontend/src/Series/Details/SeriesDetailsSeason.js

Expand by default seasons where the episodes, usually TBA, have the air date missing. 
Should make it easier to not get scared that you missed a whole season, when it's actually TBA. 😄

New: Expand seasons with all episodes having missing air dates

---

frontend/src/Store/Actions/Settings/downloadClients.js
frontend/src/Store/Actions/Settings/indexers.js

I don't think sorting by name DESCENDING was intentional.

Fixed: Sorting by name in Manage Indexer and Download Client modals

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/SabnzbdTests/SabnzbdFixture.cs
src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs

Newsbin fakes the SAB API, but doesn't return `history_retention`, treating null/empty retaining is safe for SAB's current behaviour.
> -1 is do not keep, 0 keep all. then n/d is for max number or max days.

Fixed: History retention for Newsbin

---

src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/UsenetDownloadStation.cs

Currently the validation of a downloadstation client fails if no `default_dir` is set in downloadstation, however it should pass if a user has set an alternative download path in the settings.
By adjusting the call we will gather the download path that the client would use during operation and validate against that.
* Closes #6421

Fix: validation logic of DownloadStation output path ref #6421

---

src/NzbDrone.Common.Test/DiskTests/DiskProviderFixtureBase.cs
src/NzbDrone.Common/Disk/DiskProviderBase.cs

cherry picked from commit 96384521c59233dab5bd8289e7c84043f75b84a2
bring in change from Radarr to potentially fix cifs mounts in unix.
* Closes #6425

Fixed: FolderWritable check for CIFS shares mounted in Unix

---

src/NzbDrone.Common.Test/ExtensionTests/StringExtensionTests/ReverseFixture.cs
src/NzbDrone.Common/Extensions/StringExtensions.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/TruncatedReleaseGroupFixture.cs
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/TruncatedSeriesTitleFixture.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/Proxies/DownloadStationInfoProxy.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

Adds `:##` to the end of series title, episode title and release group renaming tokens to allow truncation. Episode title truncation will behave as it does to truncate for file system limitations (middle truncating if including first/last). Series Title and Release Group truncation will allow truncation from the beginning: `My Series...` or the end `...Series Title`.
* Closes #6416

Add max token length (including ellipsis) for some tokens

---

frontend/src/Calendar/Events/CalendarEventGroupConnector.js

`episode` no longer exists with the request we're making so we need to use `episodeId` instead of `episode.id`.
* Closes #6441

Fixed: Grouped calendar events not correctly showing as downloading

---

src/NzbDrone.Core.Test/MediaFiles/DiskScanServiceTests/ScanFixture.cs
src/NzbDrone.Core/MediaFiles/DiskScanService.cs

Add Other to the list of subdirectories ignored during disk scan using ExcludeExtrasSubFolderRegex
* Closes #6437

New: ignore Other subfolder when scanning disk

---

frontend/src/Settings/PendingChangesModal.js

This seems to be executed as well when using Enter in a `ConfirmModal` and throws an undefined for `nextLocation`.
https://github.com/Sonarr/Sonarr/blob/70807a9dcf0fbbd39768779ec8b416c78e6804f8/frontend/src/Settings/SettingsToolbarConnector.js#L86

Bind shortcut for pending changes confirmation only when it's shown

---

src/NzbDrone.Core/Download/CompletedDownloadService.cs

Trigger notification on other manual interaction types.
* Closes #6448

Add additional On Manual Interaction Required notifications

---

src/Sonarr.Http/Authentication/AuthenticationController.cs

We weren't correctly returning to the return URL and also noticed that redirecting when URL base is set, but URL base is not included in the original URL results in failed redirects.
* Closes #6454

Fixed: Redirecting after login

---

src/NzbDrone.Core/Organizer/FileNameBuilder.cs

I only included the supported values.

Fixed: Naming validation when using max token length

---

src/NzbDrone.Core/Datastore/Migration/000_database_engine_version_check.cs
src/NzbDrone.Core/Datastore/Migration/Framework/MigrationController.cs

Some users are running OAF versions of SQLite that don't work for all migrations, this will give us a little more information when troubleshooting those issues.
The DB engine version will be logged once for each database being migrated on every startup.
Console logs look like this:
```
[Info] DatabaseEngineversionCheck: SQLite 3.36.0
[Info] DatabaseEngineversionCheck: Postgres 14.8
````
Not really, it's a "maintenance" migration that doesn't change the DB and runs every time Sonarr starts up

New: Log database engine version on startup

---

frontend/src/Series/Details/SeriesDetails.js

This allows you to triple click on the series details page to select the path for instance, similar to the details page in radarr.
NO

Wrapped fields on series details page in div

---

src/NzbDrone.Core/Update/InstallUpdateService.cs

Use the "temp" folder directly, not the sub folder we use for the update.
* Closes #6478

Fixed: Don't use sub folder to check for free disk space for update

---

src/NzbDrone.Core.Test/ParserTests/MultiEpisodeParserFixture.cs
src/NzbDrone.Core.Test/ParserTests/ParserFixture.cs
src/NzbDrone.Core.Test/ParserTests/SingleEpisodeParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

This PR adds support for the following title formats:
```
Title1 / Title2 / ... / Title / S1E1
Title1 / Title2 / ... / Title / S1E1-2
Title1 / Title2 / ... / Title / S1E1-2 of 10
Title1 / Title2 / ... / Title / (S1E1)
Title1 / Title2 / ... / Title / (S1E1-2)
Title1 / Title2 / ... / Title / (S1E1-2 of 10)
```
Example of problematic title fixed by this PR: `Настоящий детектив / True Detective / S4E1-2 of 6 (Исса Лопес) [2024, США, детектив, криминал, триллер, WEB-DL 2160p, HDR10, Dolby Vision] [Hybrid] 5x + 2x + Original (Eng)`
NO

New: Parsing for titles with multiple translated titles separated by '/' and the season at the end

---

src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs

Don't use Ep/Season parameters if the indexer doesn't support it (MOE)

Fixed: Prevent anime search with ep/season if not supported

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs

```
System.InvalidOperationException: Sequence contains more than one element
at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.ReprocessItem(String path, String downloadId, Int32 seriesId, Nullable`1 seasonNumber, List`1 episodeIds, String releaseGroup, QualityModel quality, List`1 languages) in ./Sonarr.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs:line 170
```

Fixed reprocessing file in Manage Episodes

---

.github/workflows/build.yml

`paths` cannot only contain paths to exclude, at least one path to include must be present or you need to use `paths-ignore`
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths

Use 'paths-ignore' instead of 'path' with only negative matches

---

frontend/src/Components/Form/TextTagInputConnector.js

This changes all text tags to allow space within them, which is what tag fields from the backend utilize.
* Closes #6488

Fixed: Multi-word genres in Auto Tags

---

src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/MapFixture.cs
src/NzbDrone.Core/Parser/ParsingService.cs

Skip TV Rage ID lookup when release has TVDB ID.
* Closes #6517

Fixed: Only match via TV Rage ID if TheTVDB ID is not available

---

.github/workflows/build.yml

Branch names with slashes cause issues with builds so replace them with dashes.

Clean branch name to remove slashes

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

Allow for additional separators other than period between ISO language and additional subtitle information.
* Closes #6494

Fixed: Parsing of subtitle languages separated by dash

---

src/NzbDrone.Core.Test/ParserTests/NormalizeEpisodeTitleFixture.cs
src/NzbDrone.Core.Test/ParserTests/NormalizeSeriesTitleFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Split episode titles weren't properly getting normalized which allowed for languages in the split title to be treated as the audio language.

New: Ignore language in split episode title

---

src/NzbDrone.Core/Datastore/TableMapping.cs

Seasons should have been ignored because we don't store other monitoring info and now store information about each item in the DB.
* Closes #6555

Fixed: Don't store seasons from import list items in database

---

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/ManualInteractionRequiredMessage.cs
src/NzbDrone.Core/Notifications/NotificationService.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs

Cherry pick from Radarr for the same issue.
* Closes #6558

Fixed: Handle DownloadClientInfo as nullable in ManualInteractionRequiredMessage

---

src/NzbDrone.Core/Tv/EpisodeRefreshedService.cs
src/NzbDrone.Core/Tv/Events/EpisodeInfoRefreshedEvent.cs

Actually include updated episodes in `EpisodeInfoRefreshedEvent`...
* Closes #6560

Fixed: Processing updated episodes in series after refresh

---

src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs
src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdProxy.cs

SABnzbd is adding a history archive, so deletions will end up in the archive instead of deleted permanently. For failed downloads we want to skip the archiving and allow Sonarr to find a replacement without dupe checking getting in the way.

New: Bypass archived history for failed downloads in SABnzbd

---

src/NzbDrone.Core.Test/Datastore/Migration/203_release_typeFixture.cs
src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/ImportApprovedEpisodesFixture.cs
src/NzbDrone.Core/Blocklisting/Blocklist.cs
src/NzbDrone.Core/Blocklisting/BlocklistService.cs
src/NzbDrone.Core/CustomFormats/CustomFormatCalculationService.cs
src/NzbDrone.Core/CustomFormats/CustomFormatInput.cs
src/NzbDrone.Core/CustomFormats/Specifications/IndexerFlagSpecification.cs
src/NzbDrone.Core/CustomFormats/Specifications/SeasonPackSpecification.cs
src/NzbDrone.Core/Datastore/Migration/203_release_type.cs
src/NzbDrone.Core/Datastore/Migration/Framework/MigrationController.cs
src/NzbDrone.Core/History/HistoryService.cs
src/NzbDrone.Core/Localization/Core/en.json
src/NzbDrone.Core/MediaFiles/EpisodeFile.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportFile.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportItem.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs
src/NzbDrone.Core/Parser/Model/LocalEpisode.cs
src/NzbDrone.Core/Parser/Model/ParsedEpisodeInfo.cs
src/NzbDrone.Core/Parser/Model/ReleaseType.cs
src/Sonarr.Api.V3/EpisodeFiles/EpisodeFileController.cs
src/Sonarr.Api.V3/EpisodeFiles/EpisodeFileResource.cs
src/Sonarr.Api.V3/ManualImport/ManualImportResource.cs

Adds a new CF type of `Release Type` which can be used to prefer or avoid releases based on whether they are single episode, multi-episode or season packs. The value of the release type is stored in history, blocklist and with the final episode file to prevent download loops that previously existed with release title regex matching alone.
In a roundabout way it closes #3562 by embracing the lose of season/multi-episode preference that currently exists, but also adds some changes towards #5598.
YES - 203
* Closes #3562

New: Release Type (Single/Multi episode and Season Pack) for Custom Formats

---

src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs

Adds function HasRoutableIPv4Address consulted when ipv6 failure has happened.
NO
* Closes #6545

Fixed: Add patch verifying ipv4 connectivity on disabling ipv6

---

src/NzbDrone.Core/Tv/AddSeriesService.cs

Improve UX
```none
2024-02-29 10:09:49.0|Error|AddSeriesService|TVDB ID 0 was not found, it may have been removed from TheTVDB.  Path:
```
no way to debug from the error without finding the addseries line
```none
2024-02-29 10:09:45.0|Info|AddSeriesService|Adding Series [0][Masters of the Air] Root Folder Path: [/data/media/media/tv]
```

Improve AddSeries Messaging and Logging

---

frontend/src/typings/pending.ts

Will stop GHA from writing the warnings as annotations in the summary.

Properly type validation errors/warnings

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

`ImE` was overly aggressive because `Showtime` would trigger it, now requires a valid separator for all matches.
* Closes #6591

Fixed: Overly aggressive exception release group parsing

---

frontend/src/App/State/AppSectionState.ts
frontend/src/Settings/ImportLists/ImportListExclusions/ImportListExclusions.tsx

Fixes a problem with the import list exclusion props declaring `useCurrentPage` and `totalRecords` but not actually being passed them. This removes those props and makes it so `totalRecords` is selected from the app state, and `useCurrentPage` is calculated from the `useHistory()` hook.

Fix import list exclusion props

---

frontend/src/index.ejs
frontend/src/login.html

New iPhones need different meta tags to see an app as a web-app. This should address those missing tags on index.ejs, namely Status Bar.

Apple WebApp

---

frontend/src/InteractiveImport/InteractiveImport.ts
frontend/src/InteractiveImport/ReleaseType.ts
frontend/src/Store/Actions/interactiveImportActions.js
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs
src/Sonarr.Api.V3/ManualImport/ManualImportController.cs
src/Sonarr.Api.V3/ManualImport/ManualImportReprocessResource.cs

Reuse `releaseType` when reprocessing items in manual import.

Fixed: Reprocessing release type for items in Manual Import

---

src/NzbDrone.Core/Notifications/NotificationService.cs

Another case where Manual Interaction Required throws an exception because the series is null.

Fixed: Error sending Manual Interaction Required notification

---

frontend/src/Settings/MediaManagement/Naming/NamingModal.js
src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/CustomFormatsFixture.cs
src/NzbDrone.Core/CustomFormats/CustomFormat.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

Implementing the `{Custom Format:Format}` rename token to allow position of Custom Formats when renaming.
This re-implements #4453 for Custom Formats, and would satisfy [Radarr/Radarr#6801](https://github.com/Radarr/Radarr/issues/6801) if it gets cherry-picked to over there.
It is a smaller change because it's really just allowing exact placement of the Format Name instead of the old Preferred Words implementation that replaced with the matched values.
NO
* #6431 - It doesn't close this issue, but is related.

`{Custom Format:Format}` Rename Token

---

src/NzbDrone.Common/Sonarr.Common.csproj
src/NzbDrone.Core/Sonarr.Core.csproj
src/NzbDrone.Host/Sonarr.Host.csproj
src/NzbDrone.Update/Sonarr.Update.csproj

Security bump for `SixLabors.ImageSharp`: [CVE-2024-27929](https://devhub.checkmarx.com/cve-details/CVE-2024-27929/)

Bump ImageSharp, Polly, DryIoc, STJson, WindowsServices

---

src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/CustomFormatsFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

Adds include/exclude logic similar to the `{MediaInfo}` languages tokens.
The delimiter is `,` instead however because I thought `,` would be less used in Custom Format names than the `-`. e.g. `{Custom Formats:-Name1,Name2}` instead of `{Custom Formats:-WEB-DL}`
NO
* Closes #6615

Add include/exclude logic for `{Custom Formats}` renaming token

---

frontend/src/Components/Form/MonitorEpisodesSelectInput.js
frontend/src/Components/Form/MonitorNewItemsSelectInput.js
frontend/src/Components/Form/QualityProfileSelectInputConnector.js
frontend/src/Components/Form/SeriesTypeSelectInput.tsx
frontend/src/Series/Index/Select/Edit/EditSeriesModalContent.tsx
frontend/src/Settings/DownloadClients/DownloadClients/Manage/Edit/ManageDownloadClientsEditModalContent.tsx
frontend/src/Settings/ImportLists/ImportLists/Manage/Edit/ManageImportListsEditModalContent.tsx
frontend/src/Settings/Indexers/Indexers/Manage/Edit/ManageIndexersEditModalContent.tsx

Came up on Discord today, `disabled != isDisabled` for `EnhancedSelectInput`, also converted a couple `SelectInput` usages in to `EnhancedSelectInput` for consistency in forms.

Fixed: Disabled select option still selectable

---

src/Sonarr.Api.V3/Indexers/ReleasePushController.cs

Allows `MagnetUrl` without `DownloadUrl` and vice versa.
* Closes #6622

Fixed: Release push with only Magnet URL

---

src/NzbDrone.Core/IndexerSearch/ReleaseSearchService.cs
src/NzbDrone.Core/Indexers/RssSyncCommand.cs
src/NzbDrone.Core/Messaging/Commands/Command.cs
src/NzbDrone.Core/ProgressMessaging/ProgressMessageContext.cs
src/NzbDrone.Core/Tv/Commands/RefreshSeriesCommand.cs
src/NzbDrone.Core/Update/Commands/ApplicationUpdateCommand.cs

Async tasks lack the `ThreadStatic` context, using `AsyncLocal` adds that context back. Also changed the default completion message to be the last received message.
* Closes #6632

Fixed: Task progress messages in the UI

---

src/NzbDrone.Core.Test/ParserTests/MultiEpisodeParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Parse 2-3 episode numbers in multi-episode release/file names.
* Closes #6631

New: Parsing multi-episode file with two and three digit episode numbers

---

src/NzbDrone.Core/Notifications/Plex/PlexTv/PlexTvService.cs

The subdomain has changed, but more importantly the query param to get the GUIDs has changed.

Fixed: Plex Watchlist import list

---

src/NzbDrone.Core.Test/ParserTests/PathParserFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs
src/NzbDrone.Core/Organizer/FileNameValidation.cs
src/NzbDrone.Core/Organizer/FileNameValidationService.cs
src/NzbDrone.Core/Parser/Parser.cs

If the season folder is parsable and the file name starts with a simple episode number (`E01` or `01` for example) Sonarr will import or rename to that format.
* Closes #903

New: Support parsing season number from season folder when importing

---

src/NzbDrone.Core.Test/ImportListTests/ImportListSyncServiceFixture.cs
src/NzbDrone.Core/ImportLists/ImportListSyncService.cs
src/NzbDrone.Core/ImportLists/Plex/PlexParser.cs

Plex Watchlist isn't returning any IDs, but series with TVDB ID of 0 were attempting to be added.

Fixed: Don't add series from import list with no matched TVDB ID

---

frontend/src/Store/Selectors/createMultiSeriesSelector.ts

Tasks without a matching series would get undefined and fail, the selector will now skip unknown series.

Fixed: Task with removed series causing error

---

src/NzbDrone.Core/MediaFiles/EpisodeFileMovingService.cs

CFs used during import for comparing weren't being used for the import and matching of the download name was failing because it contains `_` and `/b` doesn't match like `.` or spaces does.
https://forums.sonarr.tv/t/including-custom-formats-as-part-of-filename-format/33605

Fixed: Use custom formats from import during rename

---

frontend/src/Settings/DownloadClients/DownloadClients/EditDownloadClientModalContent.js
frontend/src/Settings/DownloadClients/DownloadClients/EditDownloadClientModalContentConnector.js
frontend/src/Settings/ImportLists/ImportLists/EditImportListModalContent.js
frontend/src/Settings/ImportLists/ImportLists/EditImportListModalContentConnector.js
frontend/src/Settings/Notifications/Notifications/EditNotificationModalContent.js
frontend/src/Settings/Notifications/Notifications/EditNotificationModalContentConnector.js

Mostly to avoid new comers redoing their settings because they forgot to enable show advanced beforehand. 
I added for import lists too, but ATM only Trakt has an advanced field.

New: Advanced settings toggle in import list, notification and download client modals

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

The validation added on #6050 was not included in the code for the connection Test between Sonarr and the qBittorrent client. This means that even with a correctly configured client, sonarr would complain that torrents could be deleted before they were imported. This PR fixes this issue by including the same validation on the Test function

Fix bug in which Minimum retention was not being considered for qBittorrent client test

---

src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs

Prevents the exiting of torrent processing due to a single torrent having a relative path.
Now warns user and processes remaining torrents

Adjust reporting of torrents with relative path in rTorrent

---

src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookDownloadStatusMessage.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookManualInteractionPayload.cs

The current status and messages for the tracked download is important context needed to handle "Interaction Required" notifications.
- Add `WebhookDownloadStatusMessage` class
- Add `DownloadStatus` and `DownloadStatusMessages` fields to `WebhookManualInteractionPayload`
- Update `BuildManualInteractionRequiredPayload` with new fields

Add DownloadStatus and DownloadStatusMessages to WebhookManualInteractionPayload

---

src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs
src/NzbDrone.Core.Test/Framework/CoreTest.cs

Wrap NetworkInterface.GetAllNetworkInterfaces in try catch to solve race condition on aarch64
NO
* Closes #
https://github.com/Prowlarr/Prowlarr/issues/2076

Fix: Wrap routeableipv4 in try catch

---

src/NzbDrone.Core.Test/ParserTests/PathParserFixture.cs
src/NzbDrone.Core/Parser/Model/ParsedEpisodeInfo.cs
src/NzbDrone.Core/Parser/Parser.cs

A file with a series title that starts with a number could be treated as the episode number and result in mis-parsing.

Fixed: Path parsing incorrectly treating series title as episode number

---

src/NzbDrone.Core/MediaFiles/DiskScanService.cs
src/NzbDrone.Core/MediaFiles/MediaFileDeletionService.cs

Series folders were being deleted mid-processing when they were empty, which resulted in the extra files scan failing and the unmonitoring of deleted files not being triggered.
* Closes #6678

Fixed: Deleted episodes not being unmonitored when series folder has been deleted

---

src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/Aggregation/Aggregators/AggregateSubtitleInfoFixture.cs
src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Extras/ExistingExtraFileService.cs
src/NzbDrone.Core/Extras/IImportExistingExtraFiles.cs
src/NzbDrone.Core/Extras/ImportExistingExtraFilesBase.cs
src/NzbDrone.Core/Extras/Metadata/ExistingMetadataImporter.cs
src/NzbDrone.Core/Extras/Others/ExistingOtherExtraImporter.cs
src/NzbDrone.Core/Extras/Subtitles/ExistingSubtitleImporter.cs
src/NzbDrone.Core/MediaFiles/EpisodeFileMovingService.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Aggregation/Aggregators/AggregateSubtitleInfo.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs
src/NzbDrone.Core/Parser/LanguageParser.cs
src/NzbDrone.Core/Parser/Model/LocalEpisode.cs

Previously, subtitle titles such as `test 1` would incorrectly be parsed as having no title with index `1`, despite the correct format for a title with copy being `test - 1`. This is fixed.
Quite literally a single character change.
NO
*

Fix incorrect subtitle copy regex and extra file script import

---

frontend/src/Content/Images/Icons/manifest.json

With the changes from #6231 by changing `display` to `minimal-ui` it broke Progressive Web App behavior on iOS.
Instead of opening the *arr application as a standalone (PWA) instance it opens a new tab in Safari.
By looking at [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/Manifest/display#browser_compatibility) of `display` in **manifest.json**, you can see that `minimal-ui` is not supported on iOS.
Reverting these changes made to **manifest.json** the *arr application will properly open a standalone (PWA) instance on iOS.
In this video you can see the difference between current (4.0.2.1183) and fixed behavior on iOS.
https://github.com/Sonarr/Sonarr/assets/2996147/273b7c4c-049a-496a-867e-23e0f80edbcd
NO

Specify widely supported display mode for PWA

---

frontend/src/Settings/CustomFormats/CustomFormats/EditCustomFormatModalContent.js
src/NzbDrone.Core/Localization/Core/en.json

Add a small info box to the custom formats modal, clarifying how CFs are applied when multiple specs are chosen.

Add info box to custom formats modal

---

src/NzbDrone.Core/Notifications/Ntfy/NtfyProxy.cs

Switched to query string params instead of headers for ntfy.sh parameters which handles unicode characters properly.
* Closes #6679

Fixed: Sending ntfy.sh notifications with unicode characters

---

src/NzbDrone.Core/Localization/Core/en.json
src/NzbDrone.Core/Notifications/Telegram/Telegram.cs
src/NzbDrone.Core/Notifications/Telegram/TelegramProxy.cs
src/NzbDrone.Core/Notifications/Telegram/TelegramSettings.cs

Added an option so users can choose to add the app name to Telegram messages.

New: Option to prefix app name on Telegram notification titles

---

.devcontainer/devcontainer.json
.github/dependabot.yml
.gitignore
.vscode/extensions.json
.vscode/launch.json
.vscode/tasks.json
src/Directory.Build.props

This makes it possible to develop Sonarr in a DevContainer with VSCode (which is useful for running this easily on a Mac).
On an M1/M2 Mac, I found that the default linux-x64 runtime identifier
is not valid for the aarch64 docker image that will be used by default.
So instead of hardcoding the runtime identifier, I've added a check to
set the architecture based on the current process architecture.
Tested working on an M2 Mac with Docker Desktop not using Rosetta.
1. Install docker desktop (or your preferred flavor of docker)
2. Open the repo in VSCode and accept the suggestion to reload into the DevContainer
3. Run the npm: install and npm: build tasks 
4. Run | Run without Debugging
5. Click button to load in browser
The existing code specifies `linux-x64` for the architecture, and it's …

Add DevContainer and VSCode config

---

src/NzbDrone.Core/MediaFiles/EpisodeFileMovingService.cs

Fixes a regression introduced in #6640 where localEpisode can be null when using Organize & Rename under a series.
- Fixes #6704

Fixed: Renaming episodes for a series

---

src/NzbDrone.Core/Organizer/FileNameBuilder.cs

Minor change to prevent possible multiple enumerations for the `{Custom Formats}` token.

Prevent multiple enumerations in Custom Formats token

---

src/Sonarr.Api.V3/EpisodeFiles/EpisodeFileResource.cs

Manual Import works around values of type string for release types.
* Closes #6706

Fixed: Changing Release Type in Manage Episodes

---

src/NzbDrone.Core/Localization/Core/es.json
src/NzbDrone.Core/Localization/Core/pt_BR.json
src/NzbDrone.Core/Localization/Core/zh_CN.json

Translations update from [Servarr Weblate](https://translate.servarr.com) for [Servarr/Sonarr](https://translate.servarr.com/projects/servarr/sonarr/).
Current translation status:

Translations update from Servarr Weblate

---

.github/workflows/build.yml
.github/workflows/deploy.yml

For all main releases release notes will be generated off the previous main release, instead of off of develop, this will provide a much more accurate list of actual changes in these releases. For develop releases the releases will be built off the previous develop release (though the impact this is much lower).

Improve release notes for main releases

---

.github/workflows/conflict_labeler.yml

Added a merge conflict labeler workflow for all the PR when a merge conflict is detected so people can resolve it when commit on develop branch is made
`merge-conflict` label need to be made before merging this PR
Update action version to remove the warning and adapt parameters on labeler

Update action and add merge conflict labeler

---

frontend/src/Store/Actions/Creators/createTestProviderHandler.js
src/Sonarr.Api.V3/ProviderControllerBase.cs

Same as with force saving, re-testing will exclude warnings.

Fixed: Re-testing edited providers will forcibly test them

---

.github/workflows/build.yml

`macos-latest` now runs on M1/arm64 machines instead of x64 machines, test artifacts and steps need to be updated to match.

macOS tests now run on arm64

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentPreferences.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentTorrent.cs

Related to #6266 
qBitorrent supports a new share limit based on how long the torrent has been inactive. This causes Sonarr to not remove completed torrents since it's checking to see if the share limits are met before removing.
This PR adds logic to check if torrents are using inactive time as the share limit and remove them appropriately.

Fix removing completed qBitorrent torrents that use inactive seeding time

---

src/NzbDrone.Windows/Disk/DiskProvider.cs

On Discord we had a user with a source path of more than 256 characters silently failing to hardlink, this is due to kernel32.dll silently failing (no exception thrown in Sonarr). We can't control the source path, but prepending the path with `\\?\` allows the file to be hardlinked properly as verified by `fsutils` via the command line.

Fixed: Improve paths longer than 256 on Windows failing to hardlink

---

src/NzbDrone.Common.Test/PathExtensionFixture.cs
src/NzbDrone.Common/Extensions/PathExtensions.cs
src/Sonarr.Api.V3/Series/SeriesController.cs

Validates that paths being saved don't contain a folder that starts or ends with a space. Also removes a duplicate validator for PUT requests for series.
* Closes #6709

New: Validate that folders in paths don't start or end with a space

---

src/NzbDrone.Common.Test/ConfigFileProviderTest.cs
src/NzbDrone.Common.Test/ServiceFactoryFixture.cs
src/NzbDrone.Common/Options/AppOptions.cs
src/NzbDrone.Common/Options/AuthOptions.cs
src/NzbDrone.Common/Options/HttpOptions.cs
src/NzbDrone.Common/Options/LogOptions.cs
src/NzbDrone.Common/Options/ServerOptions.cs
src/NzbDrone.Common/Options/UpdateOptions.cs
src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
src/NzbDrone.Host.Test/ContainerFixture.cs
src/NzbDrone.Host/Bootstrap.cs

Adds environment variable support for all options in config.xml. Using the IOptions pattern this will allow users to override config with the following environment variables
The environment variables will take precedence over config.xml for populated values. This change is not breaking and will still default to config.xml for anything not set as an environment variable.
<details>
<summary>New environment variables</summary>
SONARR__APP__INSTANCENAME
SONARR__APP__THEME
SONARR__APP__LAUNCHBROWSER
SONARR__AUTH__APIKEY
SONARR__AUTH__ENABLED
SONARR__AUTH__METHOD
SONARR__AUTH__REQUIRED
SONARR__SERVER__URLBASE
SONARR__SERVER__BINDADDRESS
SONARR__SERVER__PORT
SONARR__SERVER__ENABLESSL
SONARR__SERVER__SSLPORT
SONARR__SERVER__SSLCERTPATH
SONARR__SERVER__SSLCERTPASSWORD
SONARR__LOG__LEVEL …

New: added environment variable support for all options in config.xml

---

src/NzbDrone.Core/Datastore/CorruptDatabaseException.cs

Doesn't change much expect for prepending `Sonarr failed to start` to the message, but fits better as a startup exception due to it's nature.

Treat CorruptDatabaseException as a startup failure

---

src/NzbDrone.Core/Download/DownloadClientBase.cs

Adding another use case for when the HTTP errors are not suppressed and we should treat the exception instead. First case remains valid for `request.SuppressHttpError = true;`
* Closes #6752

Fixed: Retrying download on not suppressed HTTP errors

---

frontend/src/System/Tasks/Queued/QueuedTaskRowNameCell.tsx

Limiting titles in task names to max 20 series since on big libraries you need to scroll a lot to get to the next tasks.

Fixed: Limit titles in task name to 10 series

---

src/NzbDrone.Core/Download/Clients/Transmission/TransmissionProxy.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionTorrent.cs

There is no such field `fileCount` in [Transmission RPC](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#33-torrent-accessor-torrent-get), however, there is one called `file-count`. The naming is inconsistent, so the mistake is understandable. Also, it doesn't help that Transmission will ignore any fields it doesn't recognize.
I stumbled upon this while testing Sonarr with a client I'm developing which aims to be Transmission RPC compatible. Only, my code throws an error when asked for invalid fields (oops).
You may verify by running these commands:
_(this returns the field)_
```
curl -H "X-Transmission-Session-Id: <session-id>" <host>/transmission/rpc --data-raw '{ "method": "torrent-get", "arguments": { "fields": ["file-count"] } }'
```
_(this does not return …

Fix wrongly named field in TransmissionProxy

---

src/Sonarr.Api.V3/Indexers/ReleaseResource.cs

Allows the use of indexer flags for torrent release pushes by apps like autobrr, etc.

Fixed: Use of indexer flags for torrent release pushes

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

In qBittorrent 5.0, pausedUP and pausedDL have been renamed to stoppedUP and stoppedDL.
This adds support for the new states while keeping compatibility with the old ones.
Tests have been adapted to check that both states are working as intended.
NO

qBittorrent: support stoppedUP and stoppedDL states

---

src/NzbDrone.Host/Bootstrap.cs
src/NzbDrone.Host/Startup.cs

Fix to call `AppFolderFactory.MigrateAppDataFolder` before the database migrations.

Fixed: Initialize databases after app folder migrations

---

src/NzbDrone.Core/SeriesStats/SeasonStatistics.cs
src/NzbDrone.Core/SeriesStats/SeriesStatistics.cs
src/NzbDrone.Core/SeriesStats/SeriesStatisticsService.cs

~~When a model has type string apparently Npgsql is doing a DateTime.ToString() that loses the timezone information.~~
The previous fix worked fine under PG but with SQLite would still return a string even when mapped to `DateTime`. Reverted to to using AssumeUniversal.
* Closes #6790

Fixed: Timezone issue with next/previous/last air dates

---

frontend/src/Store/Actions/seriesActions.js
src/NzbDrone.Core/Localization/Core/en.json

I forget whether this was brought up on the forums or reddit, but this adds a filter for series to find series with an unmonitored season so you can quickly find series and not need to blindly set episode monitoring to all episodes.

New: Has Unmonitored Season filter for Series

---

src/NzbDrone.Core/Notifications/NotificationDefinition.cs

As per title, consider notifications with only `On Renamed` as enabled.

Fixed: Notifications with only On Rename enabled

---

frontend/src/Components/Table/Cells/RelativeDateCell.js
frontend/src/Episode/History/EpisodeHistoryRow.js
frontend/src/Series/History/SeriesHistoryModal.js
frontend/src/Series/History/SeriesHistoryRow.js
frontend/src/Utilities/Date/getRelativeDate.js
src/NzbDrone.Core/Localization/Core/en.json

A follow up to https://github.com/Sonarr/Sonarr/pull/6767 that adds time stamps to relative dates including seconds for episode/season/series history.

New: Include time for episode/season/series history

---

.github/workflows/build.yml
.github/workflows/labeler.yml
.github/workflows/lock.yml
src/NzbDrone.Core/Configuration/ConfigFileProvider.cs

The slashes aren't trimmed from UrlBase when set by an env variable. 
Plus fix for branch name which only replaces the first occurrence of `/` and disable some workflows on forks.

Fixed: Trimming slashes from UrlBase when using environment variable

---

frontend/src/Utilities/Date/getRelativeDate.tsx

Time was only being formatted when `includeTime` was enabled, but `timeForToday` is also valid, updated to correct those.

Fixed: Time for episodes airing today being blank

---

src/NzbDrone.Core.Test/MediaFiles/MediaInfo/VideoFileInfoReaderFixture.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

This relates to an issue I opened for Radarr, but I thought it might be better to apply the fix to Sonarr first seeing as it seems to be present there too. Radarr issue: https://github.com/Radarr/Radarr/issues/9890
SDR files are being parsed as HLG owing to `bt2020-10` being a match in `HlgTransferFunctions`. It is only the `arib-std-b67` transfer function that indicates a file is using HLG: https://en.wikipedia.org/wiki/Hybrid_log–gamma
I am not hugely familiar with the whole application code, so it may be that there are other areas that would need to be addressed too.

Fix SDR Files Being Parsed As HLG

---

src/NzbDrone.Core.Test/IndexerSearchTests/ReleaseSearchServiceFixture.cs
src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs
src/NzbDrone.Core/IndexerSearch/ReleaseSearchService.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs

Long thread on the [forums](https://forums.sonarr.tv/t/wrong-series-titles-used-with-no-results-from-indexer-greys-anatomy-and-chicago-p-d/33988) which resulted in two different fixes.
1. Make sure we include the raw series title in the search terms instead of only including it if mapping doesn't have the same clean title
2. When raw searching is enabled on newznab/torznab indexers search for both raw and clean titles to ensure we maximize results, deduping titles to avoid duplicate requests.

Fixed: Include full series title in episode search

---

src/NzbDrone.Core/Notifications/NotificationService.cs

Prevent a NullRef when the notification is sent due to an invalid series title
https://github.com/Radarr/Radarr/issues/10053

Fixed: Manual Interaction Required with possible null series

---

src/Sonarr.Api.V3/Indexers/ReleasePushController.cs
src/Sonarr.Api.V3/ProviderControllerBase.cs

Personally I think it would be better if provider existence by name is case insensitive to prevent any providers by the same name, and also to do the same regarding the case when resolving the indexer in release/push.

Fixed: Ignore case for name validation in providers

---

src/NzbDrone.Core/Tv/MoveSeriesService.cs
src/NzbDrone.Core/Validation/Paths/RootFolderValidator.cs
src/NzbDrone.Core/Validation/Paths/SeriesPathValidator.cs

This currently prevents people from fixing invalid paths for a series, but we don't need to validate the existing stored series paths as they are validated elsewhere.

Fixed: Skip invalid series paths during validation

---

docs.sh
src/NzbDrone.Host/Sonarr.Host.csproj
src/Sonarr.Api.V3/Episodes/EpisodeResource.cs
src/Sonarr.Api.V3/Sonarr.Api.V3.csproj
src/Sonarr.Api.V3/openapi.json

Since fields with JsonIgnore using `JsonIgnoreCondition.WhenWritingDefault` are not ignored from the swagger gen, bumping Swashbuckle to a version that supports `SwaggerIgnore` attribute.
* Closes #6868

Ignore `Grabbed` from API docs

---

src/NzbDrone.Common/Disk/DiskProviderBase.cs
src/NzbDrone.Core.Test/UpdateTests/UpdatePackageProviderFixture.cs

Pretty much based on e5aa8584100d96a2077c57f74ae5b2ceab63de19 and d493f8762fcb1684b44e182753c21d7a493db787 to skip inaccessible folders that breaks manual import if the selected folder contains such folders.
https://github.com/Radarr/Radarr/issues/10085

New: Ignore inaccessible folders with getting folders

---

src/NzbDrone.Core.Test/ParserTests/SeasonParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

More anime releases, more regex for parsing, this time for season packs with trailing numbers in the title.
* Closes #6883

New: Parse anime seasons with trailing number in title

---

frontend/src/Activity/Queue/QueueStatus.js
src/NzbDrone.Core.Test/Download/CompletedDownloadServiceTests/ImportFixture.cs
src/NzbDrone.Core/Download/CompletedDownloadService.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownload.cs
src/NzbDrone.Core/Localization/Core/en.json

Adds a new `ImportBlocked` state when manual interaction is required along with improved messaging in the UI. If a title is added then Sonarr will still try to automatically process the release.
* Closes #6873

New: Improve UI status when downloads cannot be imported automatically

---

src/NzbDrone.Core/Indexers/Newznab/NewznabRssParser.cs
src/NzbDrone.Core/Indexers/RssParser.cs
src/NzbDrone.Core/Indexers/Torznab/TorznabRssParser.cs

I didn't find an easy way of adding a ValidationFailure without overriding and duplicating some code from `TestConnection`, so I think we should just ignore the releases so it triggers a validation error in
https://github.com/Sonarr/Sonarr/blob/d15c116f13c79153c1b1f0ee2e2a2c48eed904a2/src/NzbDrone.Core/Indexers/HttpIndexerBase.cs#L385-L388

Fixed: Exclude invalid releases from Newznab and Torznab parsers

---

src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs

Apparently when Deluge crashes it can lead to torrents without names being returned to Sonarr, we'll now just ignore those items, same as we do for torrents without hashes.
I opted not to add logging because it could get very noisy and we're just guarding against Deluge sending us junk.
* Closes #6885

New: Ignore Deluge torrents without a title

---

src/NzbDrone.Core.Test/ParserTests/CrapParserFixture.cs
src/NzbDrone.Core.Test/ParserTests/UrlFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Strips out `(website.com)` from start of release title before parsing, prevents non-numerical numbers from breaking during parsing and uses the correct release title when getting release tokens.

Fixed: Prevent errors parsing releases in unexpected formats

---

src/NzbDrone.Core/Download/FailedDownloadService.cs
src/NzbDrone.Core/Download/TrackedDownloads/DownloadMonitoringService.cs

A follow up to https://github.com/Sonarr/Sonarr/pull/6889 because blocked items weren't being reprocessed after the underlying reason they were blocked was resolved.

Fixed: Reprocessing items that were previously blocked during importing

---

src/NzbDrone.Core/Parser/Parser.cs

Using the simplified title is too aggressive and loses too much. There is a good chance that `ReleaseTokens` is wrong in a lot of cases, but not an easily solved problem, nor a new one.

Fixed: Don't use cleaned up release title for release title

---

src/NzbDrone.Core.Test/QueueTests/QueueServiceFixture.cs
src/NzbDrone.Core/Queue/QueueService.cs

This behavior was present before, but after ea54ade9bfcb51809797edf940b04d23b3c2eeb0 is now shown on series add which is a little annoying to see your queue displaying already imported downloads for a minute till the refresh downloads command kicks in.
This seems to be due `GetTrackedDownloads` returning everything, including non-trackable download.
https://github.com/Sonarr/Sonarr/blob/143ccb1e2a18c63cf246368a717c8a9e7732ed8f/src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs#L200-L203

Fixed: Use only trackable downloads in queue

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs

Necessary to calculate the correct scoring post-manual import for those custom formats that are dependent on other attributes like for example the quality.
Fixes filename renaming issues where CFs like [Hybrid](https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf/hybrid.json) that rely on quality.

Fixed: Calculate custom formats after setting user-chosen attributes in manual import

---

frontend/src/Series/Index/Select/Delete/DeleteSeriesModalContent.tsx

Seems to be possible to have missing statistics on series in some weird cases, which breaks the bulk delete series modal.
Change to fallback to `{}` if that's the case.
* Closes #6933

Fixed destructuring null statistics for bulk delete series modal

---

src/NzbDrone.Core.Test/TvTests/SeriesServiceTests/UpdateMultipleSeriesFixture.cs
src/NzbDrone.Core.Test/TvTests/SeriesServiceTests/UpdateSeriesFixture.cs
src/NzbDrone.Core/Tv/RefreshSeriesService.cs
src/NzbDrone.Core/Tv/SeriesService.cs

Applies updated tags during series update in addition to series metadata refresh. This will immediately remove tags that are no longer relevant instead of the next refresh.
* Closes #6783

New: Update AutoTags on series update

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

This PR improves the SourceRegex in QualityParser.cs to also account for non-numeric codec tags such as AVC or HEVC  
which would previously cause the QualityParser to fallback to HDTV, due to the regex not accounting for those tags.
ref https://discord.com/channels/383686866005917708/383688189941907459/1259748157345107978

Fixed: add non-numeric codec tags to SourceRegex in QualityParser

---

src/NzbDrone.Core/Download/CompletedDownloadService.cs

Fixes the debug logging about not finding all episode files in the DB when a download is only partially imported.

Fixed: Import queue not processing after incomplete import

---

frontend/src/App/State/SeriesAppState.ts
frontend/src/Series/Index/Overview/Options/SeriesIndexOverviewOptionsModalContent.tsx
frontend/src/Series/Index/Overview/SeriesIndexOverview.css
frontend/src/Series/Index/Overview/SeriesIndexOverview.css.d.ts
frontend/src/Series/Index/Overview/SeriesIndexOverview.tsx
frontend/src/Series/Index/Posters/Options/SeriesIndexPosterOptionsModalContent.tsx
frontend/src/Series/Index/Posters/SeriesIndexPoster.css
frontend/src/Series/Index/Posters/SeriesIndexPoster.css.d.ts
frontend/src/Series/Index/Posters/SeriesIndexPoster.tsx
frontend/src/Series/Index/Posters/SeriesIndexPosters.tsx
frontend/src/Store/Actions/seriesIndexActions.js
src/NzbDrone.Core/Localization/Core/en.json

For posters tags are centered and truncated. For overview tags will show under the overview, instead of with the additional info where there is limited room.
Overview
Poster
* Closes #6946

New: Add option to show tags on series Poster and Overview

---

frontend/src/Components/Filter/Builder/FilterBuilderRow.js
frontend/src/Components/Filter/Builder/FilterBuilderRowValueConnector.js
frontend/src/Components/Filter/Builder/SeriesFilterBuilderRowValue.tsx
frontend/src/Components/Filter/CustomFilters/CustomFiltersModalContent.js
frontend/src/Components/Form/DownloadClientSelectInputConnector.js
frontend/src/Components/Form/IndexerSelectInputConnector.js
frontend/src/Components/Form/QualityProfileSelectInputConnector.js
frontend/src/Components/Menu/FilterMenuContent.js
frontend/src/Components/TagList.js
frontend/src/InteractiveImport/Series/SelectSeriesModalContent.tsx
frontend/src/Series/Details/SeriesTagsConnector.js
frontend/src/Settings/CustomFormats/CustomFormats/CustomFormatsConnector.js
frontend/src/Settings/DownloadClients/DownloadClients/DownloadClientsConnector.js
frontend/src/Settings/ImportLists/ImportLists/ImportListsConnector.js
frontend/src/Settings/Indexers/Indexers/IndexersConnector.js
frontend/src/Settings/Metadata/Metadata/MetadatasConnector.js
frontend/src/Settings/Notifications/Notifications/NotificationsConnector.js
frontend/src/Settings/Profiles/Quality/QualityProfileFormatItems.js
frontend/src/Settings/Profiles/Quality/QualityProfilesConnector.js
frontend/src/Settings/Tags/AutoTagging/AutoTaggings.js
frontend/src/Store/Actions/releaseActions.js
frontend/src/Store/Actions/seriesActions.js
frontend/src/Store/Selectors/createEnabledDownloadClientsSelector.ts
frontend/src/Store/Selectors/createRootFoldersSelector.ts
frontend/src/Store/Selectors/createSortedSectionSelector.ts
frontend/src/System/Tasks/Queued/QueuedTaskRowNameCell.tsx
frontend/src/Utilities/Array/sortByName.js
frontend/src/Utilities/Array/sortByProp.ts
frontend/src/typings/Helpers/KeysMatching.ts

Improves sorting of items with numeric values so `test-10` is sorted after `test-2` in a list using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#numeric_sorting
* Closes #6955

New: Use natural sorting for lists of items in the UI

---

src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/CleanTitleFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

Updating the regex for removing characters to the proposed allows episode titles to be more thoroughly cleaned.
When using {Episode CleanTitle}, add the backtick and apostrophe to the regex for contraction cleaning when they are used instead of a single quote. As they are now, both the backtick and the apostrophe are being used in the filename, even though {Episode CleanTitle} option is set.
When using {Episode CleanTitle} only quotes from contractions that end in s or m (i.e. world's > worlds, i'm > im, etc.) are being cleaned. This adds contractions that end in t, ve, re, ll or d (i.e. don't > dont, i've > ive, they're > theyre, i'll > ill, i'd > id, etc.).

Fixed: {Episode CleanTitle} Does Not Remove Apostrophe, Backtick and Most Contractions

---

frontend/src/Settings/CustomFormats/CustomFormats/EditCustomFormatModalContent.css
frontend/src/Settings/CustomFormats/CustomFormats/EditCustomFormatModalContent.css.d.ts
frontend/src/Settings/Tags/AutoTagging/EditAutoTaggingModalContent.css
frontend/src/Settings/Tags/AutoTagging/EditAutoTaggingModalContent.css.d.ts

wraps specifications in the modals for custom formats and autotagging. helpful in large custom formats
from this:
to:

New: Wrap specification blocks in modals

---

src/Sonarr.Api.V3/Config/NamingExampleResource.cs

Prevents clients that aren't sending this value as null from have an issue saving to the DB to maintain backwards compatibility, eventually we'll probably want to update the API docs to correctly indicate that some fields are not nullable.
https://stackoverflow.com/a/70365325

Set default value for CustomColonReplacementFormat if not provided

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

For category paths qbit returns UNC paths with forward slashes instead of back slashes, this will convert those to backslashes so they can be handled properly by Sonarr. Anyone that incorrectly puts `//` at the start of their *nix path will need to fix them and should feel shame.
* Closes Radarr/Radarr#10162

Fixed: Assume category path from qBittorent starting with '//' is a Windows path

---

frontend/src/Series/Index/Overview/SeriesIndexOverviewInfo.tsx
frontend/src/Series/Index/Posters/SeriesIndexPoster.tsx
frontend/src/Series/Index/Posters/SeriesIndexPosterInfo.css
frontend/src/Series/Index/Posters/SeriesIndexPosterInfo.css.d.ts
frontend/src/Series/Index/Posters/SeriesIndexPosterInfo.tsx
frontend/src/Series/Index/Posters/SeriesIndexPosters.tsx
src/NzbDrone.Core/Localization/Core/en.json

As per title, and moving tag list after next airing.

Fixed: Display tag list when sort by tags on series Posters

---

src/NzbDrone.Core/Datastore/Migration/Framework/SqliteSchemaDumper.cs

Ignoring tables created by Litestream to be excluded from being managed by FluentMigrator seems to enough to prevent errors on start-up.
Ref https://github.com/Prowlarr/Prowlarr/issues/2178 https://github.com/Radarr/Radarr/issues/7930

New: Litestream compatibility for SQLite

---

frontend/src/InteractiveImport/Series/SelectSeriesModalContent.tsx

When filtering, sorting is executed on every keyword change. This got noticeable after the switch to numeric sorting.

Fixed: Improve filtering performance in Select Series Modal

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

Currently, when downloading metadata the status is "queued" and the message is `DownloadClientQbittorrentTorrentStateMetadata`
When the download is forced, though, the status is "downloading" and the isn't a message. 
I think that is inconsitent, and in both cases the status and he message should be `queued` / `DownloadClientQbittorrentTorrentStateMetadata`

Making status messages for meta downloading consistent 

---

src/NzbDrone.Common.Test/PathExtensionFixture.cs
src/NzbDrone.Common/Disk/OsPath.cs
src/NzbDrone.Common/Extensions/PathExtensions.cs
src/NzbDrone.Core/Parser/Parser.cs
src/NzbDrone.Core/Tv/SeriesPathBuilder.cs

.net on non-Windows machines mangles Windows paths preventing Sonarr from finding relative paths, this improves support for that as well as falling back if things fail instead of failing the request completely.
* Closes #6953

Fixed: Updating series path from different OS paths

---

src/NzbDrone.Core.Test/DiskSpace/DiskSpaceServiceFixture.cs
src/NzbDrone.Core/DiskSpace/DiskSpaceService.cs
src/NzbDrone.Core/RootFolders/RootFolderService.cs

Caching root folders for each series path will speed up the places where they're necessary and we can also use them for determining the path root instead of doing it once per series.
* Closes #6076

Cache root folders and improve getting disk space for series path roots

---

src/NzbDrone.Core/Sonarr.Core.csproj

Security update.
https://github.com/advisories/GHSA-63p8-c4ww-9cg7

Bump ImageSharp to 3.1.5

---

frontend/src/Components/Form/TagInputTag.css

Fixes the height so it doesn't fill all vertical space.

Fix height of tags in tag inputs

---

frontend/build/webpack.config.js
frontend/src/InteractiveImport/Interactive/InteractiveImportModalContent.css

Extending https://github.com/Sonarr/Sonarr/pull/7016 so the dropdowns aren't limited to 50% of the width on mobile.
* Closes #7015

Fixed: Interactive Import dropdown width on mobile

---

src/NzbDrone.Common.Test/PathExtensionFixture.cs
src/NzbDrone.Common/Extensions/PathExtensions.cs

Allows leading/trailing spaces in folder/file names on Linux/Mac/everything else.
* Closes #6971

Fixed: Allow leading/trailing spaces on non-Windows

---

src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/ImportApprovedEpisodesFixture.cs
src/NzbDrone.Core/Download/DownloadClientItem.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs

After I got moved a bunch of files from qbit resulting in missing files that need to be redownloaded, this option is nothing less than destructive. If the download client has Remove Completed Downloads disabled, we should not touch the files no matter if the seeding goals are reached.

Fixed: Import with copy from download clients with remove completed disabled

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs

Ref https://github.com/Radarr/Radarr/issues/10237#issuecomment-2259635395
Mostly reverting 217611d7165e2f24068697e4996f0dcfc54f786c since automatic imports are affected as well, and moving the indexer flags assignment to `ImportDecisionMaker` which I tried to avoid in my previous commit, but `DownloadedEpisodesImportService` and `ManualImportService` both are using this method call.

Fixed: Persist indexer flags for automatic imports

---

src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/ImportApprovedEpisodesFixture.cs
src/NzbDrone.Core/Download/Clients/Aria2/Aria2.cs
src/NzbDrone.Core/Download/Clients/Blackhole/TorrentBlackhole.cs
src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs
src/NzbDrone.Core/Download/Clients/DownloadStation/TorrentDownloadStation.cs
src/NzbDrone.Core/Download/Clients/Flood/Flood.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/TorrentFreeboxDownload.cs
src/NzbDrone.Core/Download/Clients/Hadouken/Hadouken.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs
src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs

Moving the `RemoveCompletedDownloads` check to the download clients.
* Closes #7043

Fixed: Moving files on import for usenet clients

---

src/NzbDrone.Core.Test/IndexerSearchTests/SearchDefinitionFixture.cs
src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs

Removes special character ’ from series & episode titles when searching.

Add special character to search criteria

---

src/NzbDrone.Core.Test/DecisionEngineTests/DownloadDecisionMakerFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/DownloadClientFixtureBase.cs
src/NzbDrone.Core.Test/Download/TrackedDownloads/TrackedDownloadServiceFixture.cs
src/NzbDrone.Core.Test/MediaFiles/EpisodeImport/Specifications/MatchesFolderSpecificationFixture.cs
src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/GetEpisodesFixture.cs
src/NzbDrone.Core.Test/ParserTests/ParsingServiceTests/MapFixture.cs
src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs
src/NzbDrone.Core/History/HistoryService.cs
src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetParser.cs
src/NzbDrone.Core/Indexers/FileList/FileListParser.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabRssParser.cs
src/NzbDrone.Core/Indexers/Torznab/TorznabRssParser.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications/MatchesFolderSpecification.cs
src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs
src/NzbDrone.Core/Parser/ParsingService.cs
src/NzbDrone.Core/Tv/SeriesRepository.cs
src/NzbDrone.Core/Tv/SeriesService.cs
src/Sonarr.Api.V3/Indexers/ReleaseResource.cs
src/Sonarr.Api.V3/Parse/ParseController.cs

Since Sonarr doesn't have support for `AKA` titles, some results are rejected due to unknown series. Noticed this mostly with anime titles, but seem to have IMDb IDs so I thought we should match them like we do for tvdb and tvrage.

New: Match search releases using IMDb ID

---

frontend/src/RootFolder/RootFolderRow.tsx
frontend/src/Series/Details/SeasonInfo.tsx
frontend/src/Series/Details/SeriesDetails.js
frontend/src/Series/Index/Overview/SeriesIndexOverviewInfo.tsx
frontend/src/Series/Index/Posters/SeriesIndexPosterInfo.tsx
frontend/src/Utilities/Number/formatBytes.ts

Reverting a regression introduced in d46f4b215483e3a902454aa706336f3869328b3e where 0 is not displayed anymore making the UI inconsistent.

Fixed: Formatting empty size on disk values

---

src/NzbDrone.Core.Test/Download/Aggregation/Aggregators/AggregateLanguagesFixture.cs
src/NzbDrone.Core/Download/Aggregation/Aggregators/AggregateLanguages.cs
src/NzbDrone.Core/Indexers/IndexerBase.cs
src/NzbDrone.Core/Parser/Parser.cs

Use the indexer default languages configuration for multi-languages when a release with `MULTI` is pushed using the API `/release/push`.
The Interactive search and RSS sync seems to be already correct.
I had to change `IndexerBase.cs` to put the regex expression for MULTI in `FileNameBuilder.cs`, not quite sure if it's the right place.
Note : this is my first PR for Sonarr, I tried to look around at the function, tests naming convention to use it. If something is not good enough for a merge, feel free to say it I and will change it.
* Closes #7059

Fix indexer multi-languages for release/push

---

src/NzbDrone.Core/DataAugmentation/Scene/SceneMappingService.cs
src/NzbDrone.Core/IndexerSearch/ReleaseSearchService.cs

Dedupe scene titles to avoid any similar searches, like `BLEACH` and `Bleach` as seen in these [logs](https://pastebin.com/raw/2Pq0K59S).

Fixed: Dedupe titles to avoid similar search requests

---

frontend/src/Store/Actions/Creators/createRemoveItemHandler.js

Seems not to be possible to overwrite queryParams, like for example in https://github.com/Sonarr/Sonarr/blob/c9b5a1258ade0dbf45132aae5c1df8730c4c0fe3/frontend/src/Store/Actions/seriesActions.js#L501-L504

Fixed: Overwriting query params for remove item handler

---

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/Discord/Discord.cs
src/NzbDrone.Core/Notifications/Slack/Slack.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs

Affecting Discord/Slack/Webhooks/CustomScript
Logs from Radarr, but same applies to Sonarr.
```
2024-07-18 20:48:45.6|Error|NotificationService|Unable to send OnManualInteractionRequired notification to probleme detecte
[v5.7.0.8882] System.NullReferenceException: Object reference not set to an instance of an object.
at NzbDrone.Core.Notifications.Discord.Discord.OnManualInteractionRequired(ManualInteractionRequiredMessage message) in ./Radarr.Core/Notifications/Discord/Discord.cs:line 444
at NzbDrone.Core.Notifications.NotificationService.Handle(ManualInteractionRequiredEvent message) in ./Radarr.Core/Notifications/NotificationService.cs:line 296
```

Fixed: Sending Manual Interaction Required notifications for unknown series

---

frontend/src/Activity/History/HistoryRow.tsx
frontend/src/Episode/EpisodeLanguages.tsx

Don't display multiple languages when actually are no languages.

Fixed: Avoid displaying multi-languages for episodes parsed without languages

---

frontend/src/Components/SignalRConnector.js
frontend/src/Series/Details/SeriesDetailsConnector.js
frontend/src/Wanted/CutoffUnmet/CutoffUnmetConnector.js

If you change the quality profile for a series it's necessary to either reload the page or go back and forward for the custom formats to reflect the new scores.

Fixed: Stale custom formats after changing quality profile for series 

---

src/NzbDrone.Core/Notifications/Discord/Discord.cs

Switching to series ratings since episode ratings aren't a thing anymore.

Fixed: Switch to series rating for Discord notifications

---

src/NzbDrone.Core/ThingiProvider/Status/ProviderStatusRepository.cs
src/NzbDrone.Core/ThingiProvider/Status/ProviderStatusServiceBase.cs

As noticed on support channels, some users report issues like `System.Data.DataException: Error parsing column 6 (LastRssSyncReleaseInfo={ ... } ---> System.FormatException: The DateTime represented by the string '10169-05-19T05:09:00Z' is not supported in calendar 'System.Globalization.ThaiBuddhistCalendar'.` where the only solution is to tell them to install another 3rd-party app and execute the query `UPDATE IndexerStatus SET LastRssSyncReleaseInfo = NULL;` to make it work again. 
Switching to deletion directly without loading the provider entity with Dapper would allow us to recommend the removal the indexer and to add once again to clear the issue.

Fixed: Removing invalid statuses on provider deletion

---

frontend/src/Settings/General/GeneralSettings.js
frontend/src/Settings/General/LoggingSettings.js
src/NzbDrone.Core/Localization/Core/en.json
src/Sonarr.Api.V3/Config/HostConfigController.cs
src/Sonarr.Api.V3/Config/HostConfigResource.cs
src/Sonarr.Api.V3/openapi.json

This PR exposes the newly added LogSizeLimit from this commit https://github.com/Sonarr/Sonarr/commit/813965e6a20edef2772d68eaa7646af33028425a to the API and the WebUI.
While fiddling this together i noticed that the log size limit has a hardcoded upper limit of 10 MB.
https://github.com/Sonarr/Sonarr/blob/cd3a1c18ab4f8b644ddea3e6358ec23eb3069526/src/NzbDrone.Core/Configuration/ConfigFileProvider.cs#L245
Is there a specific reason for that limit or could this be subject to change?

New: Expose log size limit to API and WebUI

---

src/NzbDrone.Core.Test/Download/Aggregation/Aggregators/AggregateLanguagesFixture.cs
src/NzbDrone.Core.Test/Download/TrackedDownloads/TrackedDownloadServiceFixture.cs
src/NzbDrone.Core.Test/Indexers/IndexerRepositoryFixture.cs
src/NzbDrone.Core/Download/Aggregation/Aggregators/AggregateLanguages.cs
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownloadService.cs
src/NzbDrone.Core/Indexers/IndexerFactory.cs
src/NzbDrone.Core/Indexers/IndexerRepository.cs

Related to PR https://github.com/Sonarr/Sonarr/pull/7066, the indexer was not set before the `_aggregationService.Augment(...)` for the tracked downloads. This cause incorrect custom format score.

Fix indexer multi-languages for tracked download

---

frontend/src/Content/manifest.json

Fix the URLs for images now that `manifest.json` doesn't live along side them.
* Closes #7125

Fixed: PWA Manifest images

---

src/NzbDrone.Core/Validation/Paths/RootFolderExistsValidator.cs
src/Sonarr.Api.V3/Series/SeriesController.cs

Directed to overseer/jellyseer users that forget to update the root folders in their instances after making changes in Sonarr/Radarr, resulting in broken items in queue due to the paths not existing.

Fixed: Validate root folder existence when adding series

---

src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookEpisodeFile.cs

Path seems to be empty and ignored in TableMapping.
- Fixes #7135

Fixed: Paths for renamed episode files in Custom Script and Webhook

---

frontend/src/Components/Link/Link.tsx

Fixes a regression due to passing `button` for all Links.
instead of

Fixed: Queue header

---

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs

```
System.NullReferenceException: Object reference not set to an instance of an object.
at NzbDrone.Core.Configuration.ConfigFileProvider.SetValue(String key, Object value) in ./Prowlarr.Core/Configuration/ConfigFileProvider.cs:line 335
at NzbDrone.Core.Configuration.ConfigFileProvider.<>c__DisplayClass89_0.<GetValue>b__0() in ./Prowlarr.Core/Configuration/ConfigFileProvider.cs:line 325
at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Prowlarr.Common/Cache/Cached.cs:line 98
at NzbDrone.Core.Configuration.ConfigFileProvider.GetValue(String key, Object defaultValue, Boolean persist) in ./Prowlarr.Core/Configuration/ConfigFileProvider.cs:line 308
at NzbDrone.Core.Configuration.ConfigFileProvider.MigrateConfigFile() in …
```

Don't persist value for SslCertHash when checking for existence

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportApprovedEpisodes.cs

Since adding a9b93dd9c686a11ee16e717ca4e8698629a44ef7 we're using the Series on the EpisodeFile but lazyloading doesn't seem to work with models just created but not fetched yet from the db. Worked fine with renamed files since they're fetched, but not with new imports.
CustomScript was not affected because it's using the series from the DownloadMessage.
* Fixes #7149

Fixed: Generating absolute episode file paths in webhooks

---

src/NzbDrone.Core.Test/MediaFiles/MediaInfo/UpdateMediaInfoServiceFixture.cs
src/NzbDrone.Core/MediaFiles/MediaInfo/UpdateMediaInfoService.cs

Sonarr seems to allow manual importing of ISO files just fine with renaming disabled, but with renaming enabled it fails to because `shouldUpdateMediaInfo` is true due to missing media info. Leading to this place where at this moment the `Path` is the source path of a not yet import file.
Reference https://github.com/Radarr/Radarr/issues/7828

Fixed: Importing files without media info available

---

frontend/src/Episode/Episode.ts
frontend/src/Store/Actions/wantedActions.js
frontend/src/Wanted/CutoffUnmet/CutoffUnmetConnector.js
frontend/src/Wanted/CutoffUnmet/CutoffUnmetRow.js
frontend/src/Wanted/Missing/MissingConnector.js
frontend/src/Wanted/Missing/MissingRow.js
src/NzbDrone.Core/Localization/Core/en.json
src/Sonarr.Api.V3/Episodes/EpisodeResource.cs

Adds ability to check when user has added/last searched for a given episode.
Reason to chose /episode over /episodeFile is because /episodeFile is not returned until the first file is available.
Since here we deal with items that are in process of being searched, chance is high that no file is there yet, hence /episode rather than /episodeFile

Add Last Search Time to /episode API and to the Frontend (Cut-off Unmet & Missing)

---

src/NzbDrone.Core.Test/CustomFormats/Specifications/LanguageSpecification/MultiLanguageFixture.cs
src/NzbDrone.Core.Test/CustomFormats/Specifications/LanguageSpecification/SingleLanguageFixture.cs
src/NzbDrone.Core/CustomFormats/Specifications/LanguageSpecification.cs
src/NzbDrone.Core/Localization/Core/en.json

Adds an Except Language option for Language CF that allows matching on languages other than the selected language. This will allow Except Original Language to match if a language other than the original language is present and negating that will allow matching if none of the other languages are present.
* Closes #7120

New: Except language option for Language Custom Formats

---

src/NzbDrone.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs

Moves the try up to catch getting the file size if that fails for some reason, like bad unicode encoding.
* Closes #7157

Fixed: Failing to import any file for series if one has bad encoding

---

src/NzbDrone.Core/ImportLists/Trakt/List/TraktListRequestGenerator.cs

Includes season and episode entities in Trakt lists. The whole series will still be added regardless of which entity is included.
* Closes #7137

New: Include seasons and episodes in Trakt import lists

---

.gitignore
src/NzbDrone.Api.Test/v3/Qualities/QualityDefinitionResourceValidatorTest.cs
src/NzbDrone.Core/Qualities/QualityDefinitionLimits.cs
src/NzbDrone.Core/Qualities/QualityDefinitionService.cs
src/Sonarr.Api.V3/Qualities/QualityDefinitionController.cs
src/Sonarr.Api.V3/Qualities/QualityDefinitionLimitsResource.cs
src/Sonarr.Api.V3/Qualities/QualityDefinitionResourceValidator.cs
src/Sonarr.Http/REST/RestController.cs

This update moves the minimum, maximum, and preferred quality limits to
the backend, accessible via the new `/qualitydefinition/limits`
endpoint. This change improves support for unofficial Sonarr API clients
and enables a more flexible frontend.
The Quality Definitions settings page has been significantly refactored
to allow for asynchronous and dynamic loading of these limits.
Additional changes:
* Add .idea directory to gitignore
For users of the Jetbrains IDEs, the `.idea` directory isn't strictly
necessary for version control. It's better to ignore it than tie a repo
to specific tooling.
* Add --output-pathinfo to start & watch scripts
The motivation for this change is to get React debugging working.

Shift quality definition limits management to the backend

---

.github/workflows/support-requests.yml

Allow automatic response and closing of issues when tagged with `support`

Chore: add workflow to close issue when labelled as support

---

frontend/src/Series/Index/Menus/SeriesIndexSortMenu.tsx

Description
Now that ratings are populated again, adding this option to the sorting dropdown in Series Overview. Sorting of ratings was already possible via table header in table view, can now also be done in the other views.

Add rating as option in sort dropdown

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Adds KCRT to the release group exception regex.
* closes #7214

Parse KCRT as release group

---

frontend/src/Settings/ImportLists/ImportListExclusions/ImportListExclusions.tsx
frontend/src/Store/Actions/systemActions.js
src/Sonarr.Api.V3/Blocklist/BlocklistController.cs
src/Sonarr.Api.V3/History/HistoryController.cs
src/Sonarr.Api.V3/ImportLists/ImportListExclusionController.cs
src/Sonarr.Api.V3/Logs/LogController.cs
src/Sonarr.Api.V3/Queue/QueueController.cs
src/Sonarr.Api.V3/Wanted/CutoffController.cs
src/Sonarr.Api.V3/Wanted/MissingController.cs
src/Sonarr.Http/PagingResource.cs

Prevent fatal exceptions due to bad sorting keys that require locale storage resetting to fix the issue.

New: Allowed sort keys for paginated resources

---

frontend/src/InteractiveSearch/InteractiveSearch.tsx

When the modal re-rendered while fetching results it'd try to refetch them again, resulting in multiple queries being sent to the backend and multiple requests sent to indexers. This compounded in the UI and would result in queries for different searches populating results because they weren't cancelled correctly.

Fixed: Interactive searches causing multiple requests to indexers

---

src/NzbDrone.Host/Startup.cs

I've stumbled upon [this line](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Host/Startup.cs#L138) the description of api key query parameter while looking at Available authorizations in [https://sonarr.tv/docs/api](https://sonarr.tv/docs/api).
**X-Api-Key (apiKey)**
_Apikey passed as header_
Name: `X-Api-Key`
In: `header`
**apikey (apiKey)**
_Apikey passed as header_
Name: `apikey`
In: `query`
I think it should be `Apikey passed as query parameter`, right?
hope this helps, please let me know if I am missing something obvious here.

fix: annotate passing apikey as query parameter consistently in description

---

src/NzbDrone.Core/ImportLists/Plex/PlexImport.cs
src/NzbDrone.Core/ImportLists/Plex/PlexListRequestGenerator.cs

Increasing PageSize to 100 to allow 1000 items to be fetched, and raising the RateLimit from to 5s.
Minor CS cleanup while at it.
Ref https://github.com/Radarr/Radarr/issues/10447

New: Fetch up to 1000 series from Plex Watchlist

---

src/Sonarr.Http/Authentication/AuthenticationBuilderExtensions.cs

Just strip out anything that may cause issues with setting the cookie name.
* Closes #7229

Fixed: Unable to login when instance name contained brackets

---

src/NzbDrone.Common/Extensions/DateTimeExtensions.cs
src/NzbDrone.Core/MediaFiles/UpdateEpisodeFileService.cs

Allows SnapRAID's sub-millisecond comparison to not be overwritten when series is refreshed and Sonarr sees the timestamp has changed.
* Closes #7228

Fixed: Don't set last write time on episode files if difference is within the same second

---

src/NzbDrone.Core/Notifications/Telegram/Telegram.cs

When no links are being sent an empty list will be passed in, instead of null.
* Closes #7240

New: Errors sending Telegram notifications when links aren't available

---

frontend/src/Series/SeriesImage.tsx

Safari doesn't execute `onLoad` callbacks if the same image has already been loaded, which also affected scrolling down the series list, which is the case for the placeholder base64 image and results in the series image never loading. This changes the default for `isLoaded` to true so the image will attempt to be loaded.
* Closes Radarr/Radarr#10474

Fixed: Loading series images after placeholder in Safari

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

Adding an exception for `Hybrid-Remux` since `-` is excluded due to conflict with some release groups as seen in the following testcase:
https://github.com/Sonarr/Sonarr/blob/6063d63c9e99b76220bdd631459727c73c3a9998/src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs#L154

Fixed: Parsing of Hybrid-Remux

---

src/NzbDrone.Core.Test/MediaFiles/DiskScanServiceTests/ScanFixture.cs
src/NzbDrone.Core/MediaFiles/DiskScanService.cs

Excluding these files from being scanned: 
- `.DS_Store` 
- `.unmanic`
- `.unmanic.part`
* Closes https://github.com/Radarr/Radarr/issues/10473

Fixed: Ignore '.DS_Store' and '.unmanic' when scanning for files

---

src/NzbDrone.Core.Test/DecisionEngineTests/UpgradeAllowedSpecificationFixture .cs
src/NzbDrone.Core/DecisionEngine/Specifications/UpgradableSpecification.cs

Don't block revision upgrades when the profile doesn't allow upgrades.

Fixed: Don't reject revision upgrades if profile doesn't allow upgrades

---

src/NzbDrone.Common/Extensions/PathExtensions.cs

Trailing spaces should be ignored on non-Windows systems.
* Closes #7251

Fixed: Ignore extra spaces in path when not running on Windows

---

src/NzbDrone.Common/Disk/DiskTransferService.cs

I'm encountering an issue where the file size right after a copy is reported as smaller than the original file size. I believe this is because the remote copy destination is over NFS which takes a moment to sync the most recent writes. This change adds `WaitForIO();` after the copy and move actions before the file size check to give time for the writes to sync. `WaitForIO()` will simply sleep for 3 seconds as is done in `RollbackMove` and `RollbackPartialMove` already:  https://github.com/Sonarr/Sonarr/blob/e196c1be69593b26c49e9844efd56d4322e3b334/src/NzbDrone.Common/Disk/DiskTransferService.cs#L466-L470

[DiskTransferService] WaitForIO after Copy/Move file

---

frontend/src/Components/Link/ClipboardButton.tsx
package.json
yarn.lock

99fc52039f44264c83d939e5f096d8e16d2f3355 is a regression IMO, so introducing`copy-to-clipboard` to add support for older browsers and non-HTTPS installations is needed.
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#security_considerations
https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts
TLDR: `navigator.clipboard` is only available on localhost and over TLS.

Fixed: Copy to clipboard in non-secure contexts

---

src/Sonarr.Api.V3/ProviderControllerBase.cs

Prevent NullRef when someone tries to update an non-existing provider.
While working on this I would the fact that `id` from the body is used, and not the one from the path.
I think we should switch to the id from route eventually.

Fixed: Use Id from route and check for existence on provider update

---

src/Sonarr.Api.V3/Series/SeriesController.cs

Added path validation for series update, and `Cascade(CascadeMode.Stop)` where possible.

Fixed: Validate path on series update

---

src/NzbDrone.Core.Test/MediaFiles/EpisodeFileMovingServiceTests/MoveEpisodeFileFixture.cs
src/NzbDrone.Core/MediaFiles/EpisodeFileMovingService.cs

Using `{Series TitleFirstCharacter}/{Series Title}` would break here since it thinks the root folder is the same as the parent folder which is not the case.

Fixed: Manual importing to nested series folders

---

src/NzbDrone.Common.Test/PathExtensionFixture.cs
src/NzbDrone.Common/Disk/OsPath.cs
src/NzbDrone.Common/Extensions/PathExtensions.cs

Prevent trailing slash trimming like:
- `/` => (empty string)
- `E:/` => `E:`

Fixed: Clean paths for top level root folders

---

src/NzbDrone.Core/DecisionEngine/Specifications/UpgradeDiskSpecification.cs

It's a little confusing when you have a WEB-DL but the message uses Bluray Remux in your cutoff met rejection.
before
after

Use the first allowed quality for cutoff met rejection message with disabled upgrades

---

src/Sonarr.Http/Middleware/UrlBaseMiddleware.cs

Using 307 redirects prevents the method from being dropped.
* Closes #7262

New: Use 307 redirect for requests missing URL Base

---

src/NzbDrone.Common/EnvironmentInfo/OsInfo.cs

The goal of  this PR is to simplify the logic in `OsInfo` by relying on the [OperatingSystem](https://learn.microsoft.com/en-us/dotnet/api/system.operatingsystem?view=net-8.0) class to detect the running OS instead of running `uname` and parsing its output.

Use `OperatingSystem` class to get OS information

---

frontend/src/Components/Page/Header/SeriesSearchResult.js
frontend/src/Components/Page/Header/fuse.worker.js

fuse.js seems to actually return `refIndex` now, not `arrayIndexer`.
Before
[before 1](https://github.com/user-attachments/assets/74f56d0a-8aa6-4a88-a3ea-7ab9e87bf665)
[before 2](https://github.com/user-attachments/assets/90d1c93f-1296-40d1-b8a4-ee1a589fd578)
After
[after 3](https://github.com/user-attachments/assets/4f99cc89-bff1-4ec3-9cd0-b4255a2f5475) 
[after 4](https://github.com/user-attachments/assets/89f57c5c-a5ee-4451-8b90-65a07d0ba2f7)

Fixed: Matched alternative titles and tags in header search results

---

src/NzbDrone.Core/Messaging/Commands/CommandQueueManager.cs
src/Sonarr.Api.V3/Commands/CommandController.cs
src/Sonarr.Api.V3/Series/SeriesController.cs

I had to debug why all `CommandQueueManager.Push` where having a `unspecified` command trigger while scheduled tasks had the right trigger, and it was because for scheduled tasks it was set [here](https://github.com/Sonarr/Sonarr/blob/86446a768627b98909389eac230720fcd00cb127/src/NzbDrone.Core/Messaging/Commands/CommandQueueManager.cs#L145). 
Same for the pushes via API due to this [part](https://github.com/Sonarr/Sonarr/blob/2f87d52a962df65d59fd5cafbfc144e78fd2e52f/src/Sonarr.Api.V3/Commands/CommandController.cs#L71).
We can set Trigger on pushed commands and would be fine, but like [this](https://github.com/Sonarr/Sonarr/blob/0e95ba2021b23cc65bce0a0620dd48e355250dab/src/NzbDrone.Core/Update/InstallUpdateService.cs#L283) the CommandTrigger is lost as we have access only to the Command …

Inherit trigger from pushed command models

---

src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV1.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentState.cs

In qBittorrent v5.0 `paused` was renamed to `stopped` in https://github.com/qbittorrent/qBittorrent/commit/5d1c2496063b41874e85af0145b153e006fc92d3.
Unused methods `PauseTorrent` and `ResumeTorrent` were removed.
* Closes https://github.com/Radarr/Radarr/issues/10551

Fixed: Stopped/Started as initial state for qBittorrent v5.0

---

src/NzbDrone.Common.Test/PathExtensionFixture.cs
src/NzbDrone.Common/Extensions/PathExtensions.cs

When migrating from Windows to Linux, changing the root folder for a series from `E:\Media\TV` to `/mnt/media/tv` without moving the files would use the relative path but due to difference between path separators would result into an invalid path `/mnt/media/tv/\Series Title`.

Fixed: Changing series to another root folder without moving files

---

src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

Allows `...` to be specified in file names and not be stripped out automatically.
* Closes #7290

New: Maintain '...' in naming format

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/DelugeTests/DelugeFixture.cs
src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs

If you use `DownloadDirectory` and `CompletedDirectory`, the DownloadClientRootFolderCheck fails to trigger a warning with the right paths for Deluge.

Fixed: Status output root folders for completed directories in Deluge

---

src/NzbDrone.Common/Sonarr.Common.csproj
src/NzbDrone.Core/Sonarr.Core.csproj

Package 'System.Text.Json' 6.0.9 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4
Update System.Text.Json dependency to 6.0.10.
Fixes CVE-2024-43485.
This PR fix the build using dotnet-sdk 8.x.

[CVE-2024-43485] Update System.Text.Json to version 6.0.10 / Fix the build using dotnet-sdk 8.x.

---

frontend/src/Content/manifest.json
src/Sonarr.Http/Frontend/Mappers/ManifestMapper.cs

Uses the `Instance Name` setting for the name in the PWA manifest.
* Closes #7315

New: Use instance name in PWA manifest

---

src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs
src/NzbDrone.Core/Parser/QualityParser.cs

Parse `v2` as anime version 2 when following resolution (720p, 1080p, etc).
* Closes #7302

Fixed: Parse version after quality in renamed files

---

frontend/src/Activity/History/HistoryRow.tsx
frontend/src/typings/History.ts

Changes from the implementation name (`SABnzbd`), to the assigned name (`SAB`),

Fixed: Use download client name for history column

---

src/NzbDrone.Core.Test/ParserTests/NormalizeSeriesTitleFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Properly normalize the French preposition `à` in order for `Something a Deux` and `Something à Deux` to generate the same clean title.

Fixed: Cleaning the French preposition 'à' from titles

---

src/NzbDrone.Core/Datastore/Extensions/BuilderExtensions.cs
src/NzbDrone.Core/Download/Pending/PendingReleaseRepository.cs
src/NzbDrone.Core/Download/Pending/PendingReleaseService.cs

While we have `CleanupOrphanedPendingReleases` and a clean up on SeriesDeletedEvent, we still get cases where we get pending releases with non-existing series ids.
We should load only the pending releases with existing series by using an INNER JOIN to prevent queue loading errors.
* Closes https://github.com/Radarr/Radarr/issues/10616

Fixed: Loading queue with pending releases for deleted series

---

src/NzbDrone.Core/Notifications/Telegram/Telegram.cs

Small fix to the links label on telegram notification so the label would match the link itself

Fixed: Telegram notification link text

---

frontend/src/Components/Form/Tag/TagInput.tsx

Since it can be multiple types, making `id` nullable would revert the previous supported behavior.
* Closes #7347

Fixed: New values for custom filters

---

src/NzbDrone.Core/HealthCheck/Checks/MountCheck.cs

Adding a series path as example for MountCheck to make it easier to debug if the path it's in /home. 
Should help support with recent Archlinux hardening with `ProtectHome=true`.

Show a series path as example in Mount Health Check

---

src/NzbDrone.Common/Extensions/IEnumerableExtensions.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/TransmissionTests/TransmissionFixture.cs
src/NzbDrone.Core.Test/Download/DownloadClientTests/TransmissionTests/TransmissionFixtureBase.cs
src/NzbDrone.Core/Download/Clients/Transmission/Transmission.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionProxy.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionSettings.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionTorrent.cs
src/NzbDrone.Core/Download/Clients/Vuze/Vuze.cs

Adding support for labels starting with Transmission v3.0.0 with some caveats:
- ~~v3.0.0 has torrent labels support only on `torrent-set`, labels support was added on `torrent-add` since v4.0.0 so for < v4.0.0 an extra request is mandatory.~~
- Adding support for `Post-Import Category`
- Changing the default value for `Category` to `tv-sonarr`.
- To maintain BC I didn't touched the destination directory logic so it would still create a sub-folder with the `Category`. I think it's best anyway to have a sub-folder anyway since the labels aren't like in Qbit with a save path.
* Closes #7300

New: Labels support for Transmission

---

src/NzbDrone.Common.Test/PathExtensionFixture.cs
src/NzbDrone.Common/Extensions/PathExtensions.cs
src/NzbDrone.Common/PathEqualityComparer.cs
src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs

Untested with the exact scenario on macOS, but ensures we're comparing paths with the same unicode normalization.
* Closes #6657

Fixed: Normalize unicode characters when comparing paths for equality

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

Parses `Original` or `Orig` from the release name as original language so it can be handled in augmentation.
* Closes #5805

New: Parse original from release name when specified

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/Blackhole/TorrentBlackholeFixture.cs
src/NzbDrone.Core/Download/Clients/Blackhole/TorrentBlackhole.cs
src/NzbDrone.Core/Download/Clients/Blackhole/UsenetBlackhole.cs

Torrent Blackhole will move files when read-only is disabled regardless of `Remove Completed Downloads` being enabled or not

Fixed: Allow files to be moved from Torrent Blackhole even when remove is disabled

---

src/NzbDrone.Common/Disk/DiskProviderBase.cs

Some of the videos in my library are symlinks because they are too large to store on the disk space I have, so I download it to the cloud and mount it using [rclone](https://rclone.org) instead.
The problem with using symlinks is that Sonarr does not follow symlinks when reading file sizes. So, the videos will report as being only a few hundred KBs.

fix: Allow `GetFileSize` to follow symlinks

---

src/NzbDrone.Core/Download/Pending/PendingReleaseService.cs
src/NzbDrone.Core/HealthCheck/Checks/SystemTimeCheck.cs
src/NzbDrone.Core/Queue/Queue.cs
src/NzbDrone.Core/Queue/QueueService.cs
src/Sonarr.Api.V3/Queue/QueueController.cs
src/Sonarr.Api.V3/Queue/QueueResource.cs

Adds `sizeLeft` and `timeLeft` properties, while marking `sizeleft` and `timeleft` obsolete for removal in a future API version.
Also fixed all health checks dying if internet is unavailable.
* Closes #7392

Rename SizeLeft and TimeLeft queue item properties

---

src/NzbDrone.Core/Extras/Metadata/Consumers/Kometa/KometaMetadata.cs
src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs

Guard against duplicate episodes files breaking the extra file process.
* Closes #7381

Fixed: Kometa and Kodi metadata failing with duplicate episode files

---

src/NzbDrone.Core.Test/Datastore/DatabaseVersionParserFixture.cs
src/NzbDrone.Core/Datastore/Database.cs
src/NzbDrone.Core/Datastore/DatabaseVersionParser.cs

Supports non-standard Postgres version information such as `16.3 - Percona Distribution` as well as official releases.

Support Postgres with non-standard version string

---

frontend/src/Store/Selectors/selectSettings.ts
frontend/src/typings/pending.ts
src/NzbDrone.Integration.Test/ApiTests/QueueFixture.cs
src/NzbDrone.Integration.Test/Client/QueueClient.cs
src/NzbDrone.Integration.Test/IntegrationTestBase.cs
src/Sonarr.Api.V3/Queue/QueueResource.cs

Reverts the resource changes in b51a49097941e5f306cae5785c63985b319784fd to avoid case-insensitive deserialization issues. Will still be considered obsolete and marked deprecated in the docs.
* Closes #7422

Fixed: Error loading queue

---

src/NzbDrone.Core/Download/Clients/Transmission/TransmissionSettings.cs

Reverting the default category that was introduced in 675e3cd38a14ea33c27f2d66a4be2bf802e17d88. Sadly while this was a regression due to the fact `TvCategory` was null for some configurations and using the new default value, at this point I can't imagine a solution to revert this without manual intervention on the user side.
* Closes #7424

Fixed: Avoid default category on existing Transmission configurations 

---

frontend/src/Series/Details/SeriesDetails.css

Tweak text-wrapping for title and overview
Tweak CSS to improve text wrapping by adding text-wrap: balance to series view
Before:
After:

Tweak text-wrapping for title and overview in series view

---

src/NzbDrone.Common.Test/ExtensionTests/IPAddressExtensionsFixture.cs
src/NzbDrone.Common/Extensions/IpAddressExtensions.cs
src/NzbDrone.Common/Options/AuthOptions.cs
src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
src/NzbDrone.Core/Configuration/ConfigService.cs
src/NzbDrone.Core/Configuration/IConfigService.cs
src/Sonarr.Api.V3/Config/HostConfigResource.cs
src/Sonarr.Http/Authentication/UiAuthorizationHandler.cs

Added support for CGNAT IP ranges (100.64.0.0/10) to be optionally recognized as trusted addresses, allowing authentication bypass when accessing Sonarr through CGNAT networks (like Tailscale), consistent with other local network behavior.
Changes include:
- Added CGNAT validation
- Made CGNAT support configurable via config or `SONARR__AUTH__TRUSTCGNATIPADDRESSES` environment variable
- Updated test cases
- Maintains existing behavior for local IP ranges
The CGNAT support is disabled by default and must be explicitly enabled through configuration or environment variable.
- None

New: Add opt-in CGNAT support for authentication bypass

---

src/NzbDrone.Common/Disk/DiskProviderBase.cs
src/Sonarr.Api.V3/Series/SeriesLookupController.cs

Catch IOExceptions trying to resolve symlinks so they can be logged, but not fail.
Adds the correct return type for the `series/lookup` endpoint.
* Closes #7431
* Closes #7438

Fixed: Don't fail import if symlink target can't be resolved

---

src/NzbDrone.Common/Extensions/IpAddressExtensions.cs

Optimizes the `IsLocalIPv4` check by removing heap allocations. Changes heavy non-static lambdas into simple local bool variables.

Remove unnecessary heap allocations in local IP check

---

frontend/src/Wanted/CutoffUnmet/CutoffUnmet.js
frontend/src/Wanted/CutoffUnmet/CutoffUnmetConnector.js
frontend/src/Wanted/Missing/Missing.js
frontend/src/Wanted/Missing/MissingConnector.js

makes the search button reactive to selections on the Wanted pages
wanted
Cutoff unmet
* Closes #7449

New: Reactive search button on Wanted pages

---

src/Sonarr.Api.V3/Calendar/CalendarFeedController.cs

Skipping entries in the ICS calendar when episodes return a non-existing series id.
* Closes #7467

Fixed: Fetching ICS calendar with missing series

---

src/NzbDrone.Common/Processes/ProcessProvider.cs

Prevents a process with a null `MainModule` from throwing when getting process info.
* Closes #7470

Fixed: Error getting processes in some cases

---

src/NzbDrone.Core.Test/Download/Aggregation/Aggregators/AggregateLanguagesFixture.cs
src/NzbDrone.Core/Download/Aggregation/Aggregators/AggregateLanguages.cs

Deleted indexers break look ups by the indexer's original ID, will now try to fall back to the name in case it was re-created.
* Closes #7476

Fixed: Augmenting languages from indexer for release with stale indexer ID

---

frontend/src/Calendar/Events/CalendarEvent.tsx
src/NzbDrone.Core/Download/DownloadClientProvider.cs

Swapping callbacks for calendar event clicks to open the episode info modal.
* Closes #7486

Fixed: Opening episode info modal on calendar event click

---

frontend/build/webpack.config.js

According to https://github.com/zloirock/core-js?tab=readme-ov-file#babelpolyfill it's recommended to specify the minor version if you want to use polyfills introduced in minor versions.

Set minor version for core-js in babel/preset-env

---

frontend/src/polyfills.js

Allows the calendar to load again in Firefox ESR 115

Fixed: Loading calendar on older browsers

---

frontend/src/Components/Form/Select/RootFolderSelectInput.tsx

Adding a new root folder from series edit modal doesn't function - no path is passed to the API endpoint
Fixes #7497

Fix: adding a new root folder from series edit modal

---

src/NzbDrone.Common/Sonarr.Common.csproj
src/NzbDrone.Core/Sonarr.Core.csproj
src/NzbDrone.Host/Sonarr.Host.csproj
src/NzbDrone.Test.Common/Sonarr.Test.Common.csproj
src/NzbDrone.Update/Sonarr.Update.csproj
src/NzbDrone.Windows/Sonarr.Windows.csproj
src/Sonarr.Api.V3/Sonarr.Api.V3.csproj
src/Sonarr.Http/Sonarr.Http.csproj
src/Sonarr.RuntimePatches/Sonarr.RuntimePatches.csproj

- Bumping MailKit to 4.8.0 (latest to support .NET 6) in order to bump it's MimeKit dependency due to https://github.com/advisories/GHSA-gmc6-fwg3-75m5
- Bumping Microsoft.Data.SqlClient to 2.1.7 due to https://github.com/advisories/GHSA-98g6-xh36-x2p7 , as it's a dependency of Servarr.FluentMigrator.Runner.SqlServer and implicitly installs 2.1.2.

Bump MailKit to 4.8.0 and Microsoft.Data.SqlClient to 2.1.7

---

src/NzbDrone.Core.Test/IndexerTests/SeedConfigProviderFixture.cs
src/NzbDrone.Core/Indexers/CachedIndexerSettingsProvider.cs

Prevent NullRef when fetching seed configuration with an invalid indexer ID, which may happen after an indexer gets removed as the ID would be used from grab history.
Also clearing the cache on indexer removal to avoid any stale settings.
* Closes #7508

Fixed: Prevent exception for seed configuration provider with invalid indexer ID

---

src/NzbDrone.Core/Tv/Events/SeriesBulkEditedEvent.cs
src/NzbDrone.Core/Tv/SeriesService.cs
src/Sonarr.Api.V3/Series/SeriesController.cs

Bulk editing of series doesn't result in the UI being updated, these changes will now be broadcast like other changes are so any active UI will be updated.
* Closes #7511

Fixed: Series updated during Import List Sync not reflected in the UI

---

frontend/src/Settings/Metadata/Metadata/EditMetadataModal.tsx
frontend/src/Settings/Metadata/Metadata/Metadata.tsx

Fixing a minor regression after c62fc9d05bb9e1fe51b454d78e80bd9250e31f89 where the advanced settings was always set to false.

Fixed: Advanced settings for Metadata consumers

---

src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs

#6844 attempted to fix this previously but it looks like it was only added to searches for Anime. This change extends that fix to episodes and seasons.

Raw search: Fix non-anime seasons and episodes not searching with clean titles

---

src/NzbDrone.Common/ArchiveService.cs
src/NzbDrone.Core/Backup/BackupService.cs

Adding a little more information about the backup folder and path on creating a new backup.
As reference https://github.com/Radarr/Radarr/issues/10792, the backup folder seems to be `/home/(removed)/.config/Radarr/Backups` but SharpZipLib is seeing a difference between in and out.

Check if backup folder is writable on backup

---

src/NzbDrone.Core.Test/Download/DownloadClientTests/QBittorrentTests/QBittorrentFixture.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs

Math.Round returns a double, which then causes some discrepancies in the comparison between a double and a float.
Instead allow a check with a low tolerance of 0.001f
applies the same check also to torrents that have their own ratio limit set, not only global torrents.
* Closes #7527

Fix: adjust qBittorrent ratio limit check accounting for float

---

src/NzbDrone.Core/Validation/IpValidation.cs
src/Sonarr.Api.V3/Config/HostConfigController.cs

removes the validation failure of ip `0.0.0.0` in the bind on host, allowing user to bind to only ipv4 addresses
* Closes #7526

remove `0.0.0.0` validation for bind host

---

src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs
src/NzbDrone.Core/DecisionEngine/Specifications/CustomFormatAllowedByProfileSpecification.cs

Currently CF score is only logged during download decisions when its below the minimum quality profile score.
This adds a couple of extra trace log entries that could help when providing support.

Additional logging for custom format score

---

src/NzbDrone.Core/Notifications/Discord/Discord.cs

I haven't spent any time debugging this, but the user who did seemed to identify an issue in Radarr with relative images making Discord simply returning `{"embeds": ["0"]}`.
Consistency too, as all use RemoteUrl.

Remote image links for Discord's manual interaction needed

---

src/NzbDrone.Common/Disk/DiskTransferService.cs

This allows for fast copy on ZFS volumes using the ZFS block cloning feature, aka reflink.
* Closes #6183

Add reflink support for ZFS

---

src/Sonarr.Api.V3/Series/SeriesController.cs

Fixing a regression after 1c30ecd66dd0fd1dafaf9ab0e41a11a54eaac132 due to no longer using just the response body to update the state but it's also updated via SignalR without skipping the images update like it was before in https://github.com/Sonarr/Sonarr/blob/acebe87dbabe0def975bd43b9e4a40287f50fb33/frontend/src/Store/Actions/seriesActions.js#L758-L764

Fixed: Map covers to local for Series Editor

---

frontend/src/index.ts

Bug reported by @thezoggy on [Discord](https://discord.com/channels/264387956343570434/264388019585286144/1331133420449042504) that occurs when one of the arguments might be for example null or integer among others as `includes` is only available for String and Array.

Prevent page crash on console.error being used with non-string values

---

src/NzbDrone.Core/IndexerSearch/ReleaseSearchService.cs

when the user triggers a search (non-interactive) for a season of specials, the monitored status is not respected in the episode title search
* Closes #7589

Fix: respect MonitoredOnly for search for specials by title

---

src/NzbDrone.Core/Download/RejectedImportService.cs
src/NzbDrone.Core/MediaFiles/DownloadedEpisodesImportService.cs

It seems that the failed download handling per indexer doesn't actually fail the download and retry, for two reasons as far as I can see:
* the filetype is checked against a list of acceptable filetypes before the checks for dangerous or executable types is done. The download is already rejected on basis of filetype then and never reaches the empty results check.
* the RejectedImport service seems to return false when localEpisode != null - I assume we should be returning out this method only when localEpisode is null (i.e. can't be matched and therefore can't be re-searched)

Fix: Fail downloads for dangerous or exe

---

frontend/src/Components/Form/Select/EnhancedSelectInput.tsx

Prevents drop downs from flickering when repositioned by popper and overflowing that happens when it's too large to be positioned under/above (such as UI Language in UI Settings).
* Closes #7608

Fixed: Drop downs flickering in some cases

---

frontend/src/Episode/Summary/MediaInfo.tsx
frontend/src/Utilities/Number/formatBitrate.ts
src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs

Fixing the value for video bitrate by using the tag `BPS`, and using filesize in base 10 to properly format both bitrates in a human readable output.
* Closes #7585

Fixed: Format bitrate for primary streams in media info

---

frontend/src/Settings/MediaManagement/Naming/NamingModal.css
frontend/src/Settings/MediaManagement/Naming/NamingModal.css.d.ts
frontend/src/Settings/MediaManagement/Naming/NamingModal.tsx
frontend/src/Settings/MediaManagement/Naming/NamingOption.css
frontend/src/Settings/MediaManagement/Naming/NamingOption.css.d.ts
frontend/src/Settings/MediaManagement/Naming/NamingOption.tsx
src/NzbDrone.Core/Localization/Core/en.json

Adds `MediaInfo AudioLanguagesAll` token to the Naming modal and uses superscript instead of icon so multiple footnotes can be provided.
* Closes #7587

Add MediaInfo AudioLanguagesAll and update styling

---

src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs

A minor change to give newer usenet releases that are older than 7 days a minor bump while still allowing sorting by preferred sizes a chance by rounding log10(ageDays).
* Closes #6057

Prefer newer Usenet releases

---

src/NzbDrone.Core.Test/HealthCheck/Checks/DownloadClientRootFolderCheckFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/DownloadClientRootFolderCheck.cs

Check if the root folder is parent to the downloads folder to display the downloading to root warning.
Example of such setup:
* root folder: `/datasets/music`
* download folder: `/datasets/music/download`
* Closes https://github.com/Lidarr/Lidarr/issues/5384

Fixed: Health warning for downloading inside root folders

---

src/NzbDrone.Core/DecisionEngine/Specifications/RssSync/DeletedEpisodeFileSpecification.cs

Fixing a minor typo since `AutoUnmonitorPreviouslyDownloadedEpisodes` will unmonitor the episode on next disk scan, and not the series.

Fix typo in Deleted Episode File Specification

---

src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs

sorting mode based on new sabnzbd sorting response only gets check when adding, but is not refreshed on a status update, thus never throwing a health check.
This fix ensures that SortingMode is set when enabled ensuring the health check is raised.

Fix: set sorting mode for new sabnzbd sorting on update status

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Parser/LanguageParser.cs
src/NzbDrone.Core/Parser/Parser.cs

Fix parsing for German language to correctly detect "GER" and "DE" 
Update test for GER/DE language parsing.
* Closes #7635

Fixed: Parse GER/DE releases as German language

---

src/NzbDrone.Core/Notifications/Discord/Discord.cs

Discord notifications use the MachineName when no Author is defined, despite the tooltip stating it falls back to Instance Name.
Use InstanceName instead for the notification Author if no Author is defined in the connections settings

Fix: Discord Notification - Fallback to Instance Name for Author

---

frontend/src/Settings/Metadata/Metadata/EditMetadataModalContent.tsx

Minor regression since c62fc9d05bb9e1fe51b454d78e80bd9250e31f89 where the settings modal stopped being closed on successful saving.

Fixed: Close Metadata settings modal on saving

---

src/NzbDrone.Core/Indexers/FileList/FileListParser.cs

We're trimming the spaces in the request generator, but not in the parser where it generates the download links.

Fix download links for FileList when passkey contains spaces

---

src/NzbDrone.Common/Instrumentation/CleansingClefLogLayout.cs
src/NzbDrone.Common/Instrumentation/CleansingConsoleLogLayout.cs
src/NzbDrone.Common/Instrumentation/CleansingFileTarget.cs
src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs
src/NzbDrone.Core/Instrumentation/ReconfigureLogging.cs

It's annoy that we need to reimplement this everywhere we want to cleanse logs, but makes sense to cleanse console logs as well, especially with CLEF and other tooling capturing logs.
I tried a few different ways to achieve this, but everything was a little clunky. I'm not a fan of clearing the value in the string builder like it's doing, but it solves the problem without too much pain.
* Closes #7632

Cleanse console log messages

---

src/NzbDrone.Core/ImportLists/Trakt/Popular/TraktPopularSettings.cs
src/NzbDrone.Core/ImportLists/Trakt/TraktSettingsBase.cs

`Additional Parameters` only works on Trakt Popular lists, so it's removed from the base settings.
* Closes #7575

Fixed: Only show Additional Parameters on Trakt Popular list

---

src/NzbDrone.Core/Download/RejectedImportService.cs

RejectedImportService throws a nulref exception when no release or indexerID is available. This can happen for pushed releases or manually added torrents.
Break out when the RemoteEpisode has no release associated with it, and on only check for FailDownloads settings if the IndexerId is not 0.

Fix: Rejected Imports with no associated release or indexer

---

src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
src/NzbDrone.Core/Parser/Parser.cs

Fixing cases where `8-Bit-ZR-` is being parsed as `Bit-ZR` instead of `ZR`.

Fixed: Exclude 8/10/24-bit from being parsed as release group

---

src/NzbDrone.Core/Download/RejectedImportService.cs

Due to the corrections in the logic for handling rejected downloads, warnings are now correctly constructed in the RejectedImportService.
The download warnings are currently being constructed with the message in the title field. Instead of TrackedDownloadStatusMessage directly in the service, instead we can make use of the trackedDownload.Warm(message) function to create TrackedDownloadStatusMessage properly.
* Closes #7663

Fix: Don't return warning in title field for rejected downloads

---

src/NzbDrone.Core/DecisionEngine/Specifications/FreeSpaceSpecification.cs

It ain't much, but there should be quite an improvement avoiding to check for free space if the episode/season pack is not even eligible to be grabbed anyway.
https://github.com/Sonarr/Sonarr/blob/3c8268c428688cc703af76b648c9b3385858274f/src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs#L201

Fixed: Avoid checking for free space if other specifications fail first

---

src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
src/NzbDrone.Core/Languages/Language.cs
src/NzbDrone.Core/Parser/IsoLanguages.cs
src/NzbDrone.Core/Parser/LanguageParser.cs

Adds Azerbaijani, Uzbek and Malay languages. Malay will only be used for translations/metadata (in the future).
* Closes #6285
* Closes #7560

New: Add Azerbaijani, Uzbek and Malay languages

---

src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/CleanTitleFixture.cs
src/NzbDrone.Core/Organizer/FileNameBuilder.cs

Replacing diacritics for clean title naming tokens to provide cleaner paths.
* Closes https://github.com/Radarr/Radarr/issues/10911
* Closes #454

Fixed: Replace diacritics in Clean Title naming tokens

---

frontend/src/Settings/DownloadClients/Options/DownloadClientOptions.tsx
src/NzbDrone.Core/Localization/Core/en.json

This info box can be removed in v5, no longer relevant two versions later.

remove the info box about Remove settings on completed download handling

---

frontend/src/Components/Page/Sidebar/PageSidebarItem.css
frontend/src/Components/Page/Sidebar/PageSidebarItem.css.d.ts
frontend/src/Components/Page/Sidebar/PageSidebarItem.tsx
frontend/src/Components/Page/Toolbar/PageToolbarButton.css
frontend/src/Components/Page/Toolbar/PageToolbarButton.tsx

Truncates toolbar button text to a maximum width and lines, translations may need to be changed to correctly fit in that spacing, but using the search button example on Calendar that should fit if `Search Missing` was used as the reference.
The sidebar wraps text correctly when too long to fit on one row, those it wasn't forced to wrap for me.
* Closes #7691

Truncate Button Text / Better Sidebar Text Wrapping

---

frontend/src/Settings/DownloadClients/DownloadClients/EditDownloadClientModalContent.tsx
src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownload.cs

The first change enables torrents failed for potentially dangerous or executable files to be removed from the client instead of seeding forever.
The second change is for the UI to show the `Remove Failed` option for torrent clients.
Back porting the backend change to v4 makes sense.

Fixed: Downloads failed for file contents will be removed from client

---

src/NzbDrone.Core.Test/Sonarr.Core.Test.csproj
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs
src/NzbDrone.Core/Sonarr.Core.csproj

Package 'SixLabors.ImageSharp' 3.1.6 has a known high severity vulnerability, https://github.com/advisories/GHSA-2cmq-823j-5qj8

Bump SixLabors.ImageSharp, Dapper, MailKit, Polly and Npgsql

---

src/NzbDrone.Common/Processes/ProcessProvider.cs
src/NzbDrone.Core/Datastore/ExpressionVisitor.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/Responses/FreeboxDownloadTask.cs
src/NzbDrone.Core/Download/Clients/FreeboxDownload/TorrentFreeboxDownload.cs
src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs

Fixes some user-facing and non-user-facing typos.  
Found via `codespell -q 3 -S "./yarn.lock,./pnpm-lock.yaml,./src/NzbDrone.Core.Test,./src/NzbDrone.Core/Localization,./src/NzbDrone.Core/Parser/IsoLanguages.cs" -L abd,ect`
n/a
n/a
n/a

Fix various typos

---

frontend/src/Activity/History/Details/HistoryDetails.tsx
frontend/src/typings/History.ts
src/NzbDrone.Core/History/EpisodeHistory.cs
src/NzbDrone.Core/History/HistoryService.cs

When using marked as failed from history, we're losing the indexer name/size/release group information.
Since `Data` is available in FailedDownloadService, let's inherit the fields from here.
https://github.com/Sonarr/Sonarr/blob/c9027359271690f7d374d1330fa39776e2b8ec40/src/NzbDrone.Core/Download/FailedDownloadService.cs#L136

Fixed: Inherit indexer, size and release group for marked as failed history

---

frontend/src/Series/Details/SeriesDetails.tsx

`toggleSeriesMonitored` sets `isSaving` at item level, so let's make icon spin again.

Fixed: Spinning icon on toggling series monitoring

---

src/NzbDrone.Core.Test/Files/Indexers/Newznab/newznab_indexerflags.xml
src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabFixture.cs
src/NzbDrone.Core/Indexers/Newznab/NewznabRssParser.cs

If the `subs` attribute is present the `Subtitles` indexer flag will be enabled and usable in 
* Closes #7625

New: Subtitles indexer flag to indicate releases with subtitles

---

src/NuGet.Config
src/NzbDrone.Common/Sonarr.Common.csproj
src/NzbDrone.Core.Test/Sonarr.Core.Test.csproj
src/NzbDrone.Core/Sonarr.Core.csproj

Removing the dependency on a custom build of System.Data.SQLite by using the official 2.x package.
> It is no longer necessary to update System.Data.SQLite itself just to update to a new version of SQLite.
Bump sqlite3 to 3.50.4 using [SourceGear.sqlite3](https://www.nuget.org/packages/SourceGear.sqlite3), which provides support for much more platforms than the custom build.

Bump System.Data.SQLite to official 2.0

---

src/NzbDrone.Core/Localization/Core/en.json

AddNewSeriesHelpText in En had one word "of" missing. I just added that in. No other changes.
NO - ###

Fix grammar in En translation of AddNewSeriesHelpText

---

frontend/src/Components/Modal/Modal.css

Add a max width to the base modal CSS class. This prevents the fixed-width modals from being too large on some screen sizes.
No
* Closes #8085

Fix modal widths on some screen sizes

---

src/Directory.Build.props
src/NuGet.Config
src/coverlet.runsettings

Switch from custom build.
- https://github.com/OpenCover/opencover is not a thing anymore.
- Avoid changing file paths with project names.

Bump coverlet.collector to official 6.0.4

---

frontend/src/Series/Details/SeriesDetails.css

My FF 143.0.1 was mostly happy with things as it was before, but was showing a scroller when text had descenders.
A few things here:
1. The line height/maximum height didn't account for descenders, which wasn't a problem for Silo, but was for other things, it needs to be around 58px.
2. `line-clamp` support in FF exists, but only with the `-webkit` prefix, so I've included that
3. The alternate titles anchor needed to be adjusted up, it was a little low at 50px line height, but really low at 60px.

Adjust series details title line height to account for descenders

---

frontend/src/Series/Index/Overview/SeriesIndexOverview.tsx
frontend/src/Series/Index/Posters/SeriesIndexPoster.tsx
frontend/src/Series/Index/Select/SeriesIndexPosterSelect.css
frontend/src/Series/Index/Select/SeriesIndexPosterSelect.tsx

Mainly removing duplicated logic, with a fix to use the urlbase to avoid relying on the redirect from `/`.

Remove redundant code in selecting with click on poster
